class AirportRunner{

public static void main(String[] airportinfo){


Airport airport1 = new Airport();

System.out.println("Airport name: "+airport1.name);
System.out.println("Airport location: "+airport1.location);
System.out.println("Airport city: "+airport1.city);
System.out.println("Airport state: "+airport1.state);
System.out.println("Airport country: "+airport1.country);
System.out.println("Airport code: "+airport1.airportCode);
System.out.println("Airport terminals: "+airport1.numberOfTerminals);
System.out.println("Airport runways: "+airport1.numberOfRunways);
System.out.println("Airport daily flights: "+airport1.dailyFlights);
System.out.println("Airport daily passengers: "+airport1.dailyPassengers);
System.out.println("International flights: "+airport1.internationalFlights);
System.out.println("Domestic flights: "+airport1.domesticFlights);
System.out.println("Cargo service: "+airport1.cargoService);
System.out.println("Parking available: "+airport1.parkingAvailable);
System.out.println("Wifi available: "+airport1.wifiAvailable);
System.out.println("Lounge available: "+airport1.loungeAvailable);
System.out.println("Shopping area: "+airport1.shoppingArea);
System.out.println("Restaurants: "+airport1.restaurants);
System.out.println("Taxi service: "+airport1.taxiService);
System.out.println("Metro connectivity: "+airport1.metroConnectivity);
System.out.println("Security system: "+airport1.securitySystem);
System.out.println("Baggage service: "+airport1.baggageService);
System.out.println("Opening time: "+airport1.openingTime);
System.out.println("Closing time: "+airport1.closingTime);
System.out.println("Entry fee: "+airport1.entryFee);

airport1.name="Kempegowda International Airport";
airport1.location="Devanahalli";
airport1.city="Bangalore";
airport1.state="Karnataka";
airport1.country="India";
airport1.airportCode="BLR";
airport1.numberOfTerminals=2;
airport1.numberOfRunways=2;
airport1.dailyFlights=650;
airport1.dailyPassengers=90000;
airport1.internationalFlights=true;
airport1.domesticFlights=true;
airport1.cargoService=true;
airport1.parkingAvailable=true;
airport1.wifiAvailable=true;
airport1.loungeAvailable=true;
airport1.shoppingArea=true;
airport1.restaurants=true;
airport1.taxiService=true;
airport1.metroConnectivity=false;
airport1.securitySystem=true;
airport1.baggageService=true;
airport1.openingTime="24 Hours";
airport1.closingTime="24 Hours";
airport1.entryFee=150;


System.out.println("Airport name: "+airport1.name);
System.out.println("Airport location: "+airport1.location);
System.out.println("Airport city: "+airport1.city);
System.out.println("Airport state: "+airport1.state);
System.out.println("Airport country: "+airport1.country);
System.out.println("Airport code: "+airport1.airportCode);
System.out.println("Airport terminals: "+airport1.numberOfTerminals);
System.out.println("Airport runways: "+airport1.numberOfRunways);
System.out.println("Airport daily flights: "+airport1.dailyFlights);
System.out.println("Airport daily passengers: "+airport1.dailyPassengers);
System.out.println("International flights: "+airport1.internationalFlights);
System.out.println("Domestic flights: "+airport1.domesticFlights);
System.out.println("Cargo service: "+airport1.cargoService);
System.out.println("Parking available: "+airport1.parkingAvailable);
System.out.println("Wifi available: "+airport1.wifiAvailable);
System.out.println("Lounge available: "+airport1.loungeAvailable);
System.out.println("Shopping area: "+airport1.shoppingArea);
System.out.println("Restaurants: "+airport1.restaurants);
System.out.println("Taxi service: "+airport1.taxiService);
System.out.println("Metro connectivity: "+airport1.metroConnectivity);
System.out.println("Security system: "+airport1.securitySystem);
System.out.println("Baggage service: "+airport1.baggageService);
System.out.println("Opening time: "+airport1.openingTime);
System.out.println("Closing time: "+airport1.closingTime);
System.out.println("Entry fee: "+airport1.entryFee);

Airport airport2 = new Airport();

System.out.println("Airport name: "+airport2.name);
System.out.println("Airport location: "+airport2.location);
System.out.println("Airport city: "+airport2.city);
System.out.println("Airport state: "+airport2.state);
System.out.println("Airport country: "+airport2.country);
System.out.println("Airport code: "+airport2.airportCode);
System.out.println("Airport terminals: "+airport2.numberOfTerminals);
System.out.println("Airport runways: "+airport2.numberOfRunways);
System.out.println("Airport daily flights: "+airport2.dailyFlights);
System.out.println("Airport daily passengers: "+airport2.dailyPassengers);
System.out.println("International flights: "+airport2.internationalFlights);
System.out.println("Domestic flights: "+airport2.domesticFlights);
System.out.println("Cargo service: "+airport2.cargoService);
System.out.println("Parking available: "+airport2.parkingAvailable);
System.out.println("Wifi available: "+airport2.wifiAvailable);
System.out.println("Lounge available: "+airport2.loungeAvailable);
System.out.println("Shopping area: "+airport2.shoppingArea);
System.out.println("Restaurants: "+airport2.restaurants);
System.out.println("Taxi service: "+airport2.taxiService);
System.out.println("Metro connectivity: "+airport2.metroConnectivity);
System.out.println("Security system: "+airport2.securitySystem);
System.out.println("Baggage service: "+airport2.baggageService);
System.out.println("Opening time: "+airport2.openingTime);
System.out.println("Closing time: "+airport2.closingTime);
System.out.println("Entry fee: "+airport2.entryFee);

airport2.name="Indira Gandhi International Airport";
airport2.location="Delhi";
airport2.city="New Delhi";
airport2.state="Delhi";
airport2.country="India";
airport2.airportCode="DEL";
airport2.numberOfTerminals=3;
airport2.numberOfRunways=3;
airport2.dailyFlights=900;
airport2.dailyPassengers=120000;
airport2.internationalFlights=true;
airport2.domesticFlights=true;
airport2.cargoService=true;
airport2.parkingAvailable=true;
airport2.wifiAvailable=true;
airport2.loungeAvailable=true;
airport2.shoppingArea=true;
airport2.restaurants=true;
airport2.taxiService=true;
airport2.metroConnectivity=true;
airport2.securitySystem=true;
airport2.baggageService=true;
airport2.openingTime="24 Hours";
airport2.closingTime="24 Hours";
airport2.entryFee=120;

System.out.println("Airport name: "+airport2.name);
System.out.println("Airport location: "+airport2.location);
System.out.println("Airport city: "+airport2.city);
System.out.println("Airport state: "+airport2.state);
System.out.println("Airport country: "+airport2.country);
System.out.println("Airport code: "+airport2.airportCode);
System.out.println("Airport terminals: "+airport2.numberOfTerminals);
System.out.println("Airport runways: "+airport2.numberOfRunways);
System.out.println("Airport daily flights: "+airport2.dailyFlights);
System.out.println("Airport daily passengers: "+airport2.dailyPassengers);
System.out.println("International flights: "+airport2.internationalFlights);
System.out.println("Domestic flights: "+airport2.domesticFlights);
System.out.println("Cargo service: "+airport2.cargoService);
System.out.println("Parking available: "+airport2.parkingAvailable);
System.out.println("Wifi available: "+airport2.wifiAvailable);
System.out.println("Lounge available: "+airport2.loungeAvailable);
System.out.println("Shopping area: "+airport2.shoppingArea);
System.out.println("Restaurants: "+airport2.restaurants);
System.out.println("Taxi service: "+airport2.taxiService);
System.out.println("Metro connectivity: "+airport2.metroConnectivity);
System.out.println("Security system: "+airport2.securitySystem);
System.out.println("Baggage service: "+airport2.baggageService);
System.out.println("Opening time: "+airport2.openingTime);
System.out.println("Closing time: "+airport2.closingTime);
System.out.println("Entry fee: "+airport2.entryFee);

Airport airport3 = new Airport();

System.out.println("Airport name: "+airport3.name);
System.out.println("Airport location: "+airport3.location);
System.out.println("Airport city: "+airport3.city);
System.out.println("Airport state: "+airport3.state);
System.out.println("Airport country: "+airport3.country);
System.out.println("Airport code: "+airport3.airportCode);
System.out.println("Airport terminals: "+airport3.numberOfTerminals);
System.out.println("Airport runways: "+airport3.numberOfRunways);
System.out.println("Airport daily flights: "+airport3.dailyFlights);
System.out.println("Airport daily passengers: "+airport3.dailyPassengers);
System.out.println("International flights: "+airport3.internationalFlights);
System.out.println("Domestic flights: "+airport3.domesticFlights);
System.out.println("Cargo service: "+airport3.cargoService);
System.out.println("Parking available: "+airport3.parkingAvailable);
System.out.println("Wifi available: "+airport3.wifiAvailable);
System.out.println("Lounge available: "+airport3.loungeAvailable);
System.out.println("Shopping area: "+airport3.shoppingArea);
System.out.println("Restaurants: "+airport3.restaurants);
System.out.println("Taxi service: "+airport3.taxiService);
System.out.println("Metro connectivity: "+airport3.metroConnectivity);
System.out.println("Security system: "+airport3.securitySystem);
System.out.println("Baggage service: "+airport3.baggageService);
System.out.println("Opening time: "+airport3.openingTime);
System.out.println("Closing time: "+airport3.closingTime);
System.out.println("Entry fee: "+airport3.entryFee);

airport3.name="Chhatrapati Shivaji Maharaj International Airport";
airport3.location="Santacruz";
airport3.city="Mumbai";
airport3.state="Maharashtra";
airport3.country="India";
airport3.airportCode="BOM";
airport3.numberOfTerminals=2;
airport3.numberOfRunways=2;
airport3.dailyFlights=750;
airport3.dailyPassengers=100000;
airport3.internationalFlights=true;
airport3.domesticFlights=true;
airport3.cargoService=true;
airport3.parkingAvailable=true;
airport3.wifiAvailable=true;
airport3.loungeAvailable=true;
airport3.shoppingArea=true;
airport3.restaurants=true;
airport3.taxiService=true;
airport3.metroConnectivity=true;
airport3.securitySystem=true;
airport3.baggageService=true;
airport3.openingTime="24 Hours";
airport3.closingTime="24 Hours";
airport3.entryFee=120;

System.out.println("Airport name: "+airport3.name);
System.out.println("Airport location: "+airport3.location);
System.out.println("Airport city: "+airport3.city);
System.out.println("Airport state: "+airport3.state);
System.out.println("Airport country: "+airport3.country);
System.out.println("Airport code: "+airport3.airportCode);
System.out.println("Airport terminals: "+airport3.numberOfTerminals);
System.out.println("Airport runways: "+airport3.numberOfRunways);
System.out.println("Airport daily flights: "+airport3.dailyFlights);
System.out.println("Airport daily passengers: "+airport3.dailyPassengers);
System.out.println("International flights: "+airport3.internationalFlights);
System.out.println("Domestic flights: "+airport3.domesticFlights);
System.out.println("Cargo service: "+airport3.cargoService);
System.out.println("Parking available: "+airport3.parkingAvailable);
System.out.println("Wifi available: "+airport3.wifiAvailable);
System.out.println("Lounge available: "+airport3.loungeAvailable);
System.out.println("Shopping area: "+airport3.shoppingArea);
System.out.println("Restaurants: "+airport3.restaurants);
System.out.println("Taxi service: "+airport3.taxiService);
System.out.println("Metro connectivity: "+airport3.metroConnectivity);
System.out.println("Security system: "+airport3.securitySystem);
System.out.println("Baggage service: "+airport3.baggageService);
System.out.println("Opening time: "+airport3.openingTime);
System.out.println("Closing time: "+airport3.closingTime);
System.out.println("Entry fee: "+airport3.entryFee);

Airport airport4 = new Airport();

System.out.println("Airport name: "+airport4.name);
System.out.println("Airport location: "+airport4.location);
System.out.println("Airport city: "+airport4.city);
System.out.println("Airport state: "+airport4.state);
System.out.println("Airport country: "+airport4.country);
System.out.println("Airport code: "+airport4.airportCode);
System.out.println("Airport terminals: "+airport4.numberOfTerminals);
System.out.println("Airport runways: "+airport4.numberOfRunways);
System.out.println("Airport daily flights: "+airport4.dailyFlights);
System.out.println("Airport daily passengers: "+airport4.dailyPassengers);
System.out.println("International flights: "+airport4.internationalFlights);
System.out.println("Domestic flights: "+airport4.domesticFlights);
System.out.println("Cargo service: "+airport4.cargoService);
System.out.println("Parking available: "+airport4.parkingAvailable);
System.out.println("Wifi available: "+airport4.wifiAvailable);
System.out.println("Lounge available: "+airport4.loungeAvailable);
System.out.println("Shopping area: "+airport4.shoppingArea);
System.out.println("Restaurants: "+airport4.restaurants);
System.out.println("Taxi service: "+airport4.taxiService);
System.out.println("Metro connectivity: "+airport4.metroConnectivity);
System.out.println("Security system: "+airport4.securitySystem);
System.out.println("Baggage service: "+airport4.baggageService);
System.out.println("Opening time: "+airport4.openingTime);
System.out.println("Closing time: "+airport4.closingTime);
System.out.println("Entry fee: "+airport4.entryFee);

airport4.name="Chennai International Airport";
airport4.location="Meenambakkam";
airport4.city="Chennai";
airport4.state="Tamil Nadu";
airport4.country="India";
airport4.airportCode="MAA";
airport4.numberOfTerminals=2;
airport4.numberOfRunways=2;
airport4.dailyFlights=500;
airport4.dailyPassengers=70000;
airport4.internationalFlights=true;
airport4.domesticFlights=true;
airport4.cargoService=true;
airport4.parkingAvailable=true;
airport4.wifiAvailable=true;
airport4.loungeAvailable=true;
airport4.shoppingArea=true;
airport4.restaurants=true;
airport4.taxiService=true;
airport4.metroConnectivity=true;
airport4.securitySystem=true;
airport4.baggageService=true;
airport4.openingTime="24 Hours";
airport4.closingTime="24 Hours";
airport4.entryFee=100;

System.out.println("Airport name: "+airport4.name);
System.out.println("Airport location: "+airport4.location);
System.out.println("Airport city: "+airport4.city);
System.out.println("Airport state: "+airport4.state);
System.out.println("Airport country: "+airport4.country);
System.out.println("Airport code: "+airport4.airportCode);
System.out.println("Airport terminals: "+airport4.numberOfTerminals);
System.out.println("Airport runways: "+airport4.numberOfRunways);
System.out.println("Airport daily flights: "+airport4.dailyFlights);
System.out.println("Airport daily passengers: "+airport4.dailyPassengers);
System.out.println("International flights: "+airport4.internationalFlights);
System.out.println("Domestic flights: "+airport4.domesticFlights);
System.out.println("Cargo service: "+airport4.cargoService);
System.out.println("Parking available: "+airport4.parkingAvailable);
System.out.println("Wifi available: "+airport4.wifiAvailable);
System.out.println("Lounge available: "+airport4.loungeAvailable);
System.out.println("Shopping area: "+airport4.shoppingArea);
System.out.println("Restaurants: "+airport4.restaurants);
System.out.println("Taxi service: "+airport4.taxiService);
System.out.println("Metro connectivity: "+airport4.metroConnectivity);
System.out.println("Security system: "+airport4.securitySystem);
System.out.println("Baggage service: "+airport4.baggageService);
System.out.println("Opening time: "+airport4.openingTime);
System.out.println("Closing time: "+airport4.closingTime);
System.out.println("Entry fee: "+airport4.entryFee);

Airport airport5 = new Airport();

System.out.println("Airport name: "+airport5.name);
System.out.println("Airport location: "+airport5.location);
System.out.println("Airport city: "+airport5.city);
System.out.println("Airport state: "+airport5.state);
System.out.println("Airport country: "+airport5.country);
System.out.println("Airport code: "+airport5.airportCode);
System.out.println("Airport terminals: "+airport5.numberOfTerminals);
System.out.println("Airport runways: "+airport5.numberOfRunways);
System.out.println("Airport daily flights: "+airport5.dailyFlights);
System.out.println("Airport daily passengers: "+airport5.dailyPassengers);
System.out.println("International flights: "+airport5.internationalFlights);
System.out.println("Domestic flights: "+airport5.domesticFlights);
System.out.println("Cargo service: "+airport5.cargoService);
System.out.println("Parking available: "+airport5.parkingAvailable);
System.out.println("Wifi available: "+airport5.wifiAvailable);
System.out.println("Lounge available: "+airport5.loungeAvailable);
System.out.println("Shopping area: "+airport5.shoppingArea);
System.out.println("Restaurants: "+airport5.restaurants);
System.out.println("Taxi service: "+airport5.taxiService);
System.out.println("Metro connectivity: "+airport5.metroConnectivity);
System.out.println("Security system: "+airport5.securitySystem);
System.out.println("Baggage service: "+airport5.baggageService);
System.out.println("Opening time: "+airport5.openingTime);
System.out.println("Closing time: "+airport5.closingTime);
System.out.println("Entry fee: "+airport5.entryFee);

airport5.name="Rajiv Gandhi International Airport";
airport5.location="Shamshabad";
airport5.city="Hyderabad";
airport5.state="Telangana";
airport5.country="India";
airport5.airportCode="HYD";
airport5.numberOfTerminals=1;
airport5.numberOfRunways=2;
airport5.dailyFlights=450;
airport5.dailyPassengers=60000;
airport5.internationalFlights=true;
airport5.domesticFlights=true;
airport5.cargoService=true;
airport5.parkingAvailable=true;
airport5.wifiAvailable=true;
airport5.loungeAvailable=true;
airport5.shoppingArea=true;
airport5.restaurants=true;
airport5.taxiService=true;
airport5.metroConnectivity=false;
airport5.securitySystem=true;
airport5.baggageService=true;
airport5.openingTime="24 Hours";
airport5.closingTime="24 Hours";
airport5.entryFee=100;

System.out.println("Airport name: "+airport5.name);
System.out.println("Airport location: "+airport5.location);
System.out.println("Airport city: "+airport5.city);
System.out.println("Airport state: "+airport5.state);
System.out.println("Airport country: "+airport5.country);
System.out.println("Airport code: "+airport5.airportCode);
System.out.println("Airport terminals: "+airport5.numberOfTerminals);
System.out.println("Airport runways: "+airport5.numberOfRunways);
System.out.println("Airport daily flights: "+airport5.dailyFlights);
System.out.println("Airport daily passengers: "+airport5.dailyPassengers);
System.out.println("International flights: "+airport5.internationalFlights);
System.out.println("Domestic flights: "+airport5.domesticFlights);
System.out.println("Cargo service: "+airport5.cargoService);
System.out.println("Parking available: "+airport5.parkingAvailable);
System.out.println("Wifi available: "+airport5.wifiAvailable);
System.out.println("Lounge available: "+airport5.loungeAvailable);
System.out.println("Shopping area: "+airport5.shoppingArea);
System.out.println("Restaurants: "+airport5.restaurants);
System.out.println("Taxi service: "+airport5.taxiService);
System.out.println("Metro connectivity: "+airport5.metroConnectivity);
System.out.println("Security system: "+airport5.securitySystem);
System.out.println("Baggage service: "+airport5.baggageService);
System.out.println("Opening time: "+airport5.openingTime);
System.out.println("Closing time: "+airport5.closingTime);
System.out.println("Entry fee: "+airport5.entryFee);

Airport airport6 = new Airport();

System.out.println("Airport name: "+airport6.name);
System.out.println("Airport location: "+airport6.location);
System.out.println("Airport city: "+airport6.city);
System.out.println("Airport state: "+airport6.state);
System.out.println("Airport country: "+airport6.country);
System.out.println("Airport code: "+airport6.airportCode);
System.out.println("Airport terminals: "+airport6.numberOfTerminals);
System.out.println("Airport runways: "+airport6.numberOfRunways);
System.out.println("Airport daily flights: "+airport6.dailyFlights);
System.out.println("Airport daily passengers: "+airport6.dailyPassengers);
System.out.println("International flights: "+airport6.internationalFlights);
System.out.println("Domestic flights: "+airport6.domesticFlights);
System.out.println("Cargo service: "+airport6.cargoService);
System.out.println("Parking available: "+airport6.parkingAvailable);
System.out.println("Wifi available: "+airport6.wifiAvailable);
System.out.println("Lounge available: "+airport6.loungeAvailable);
System.out.println("Shopping area: "+airport6.shoppingArea);
System.out.println("Restaurants: "+airport6.restaurants);
System.out.println("Taxi service: "+airport6.taxiService);
System.out.println("Metro connectivity: "+airport6.metroConnectivity);
System.out.println("Security system: "+airport6.securitySystem);
System.out.println("Baggage service: "+airport6.baggageService);
System.out.println("Opening time: "+airport6.openingTime);
System.out.println("Closing time: "+airport6.closingTime);
System.out.println("Entry fee: "+airport6.entryFee);

airport6.name="Netaji Subhas Chandra Bose International Airport";
airport6.location="Dum Dum";
airport6.city="Kolkata";
airport6.state="West Bengal";
airport6.country="India";
airport6.airportCode="CCU";
airport6.numberOfTerminals=2;
airport6.numberOfRunways=2;
airport6.dailyFlights=420;
airport6.dailyPassengers=55000;
airport6.internationalFlights=true;
airport6.domesticFlights=true;
airport6.cargoService=true;
airport6.parkingAvailable=true;
airport6.wifiAvailable=true;
airport6.loungeAvailable=true;
airport6.shoppingArea=true;
airport6.restaurants=true;
airport6.taxiService=true;
airport6.metroConnectivity=true;
airport6.securitySystem=true;
airport6.baggageService=true;
airport6.openingTime="24 Hours";
airport6.closingTime="24 Hours";
airport6.entryFee=100;

System.out.println("Airport name: "+airport6.name);
System.out.println("Airport location: "+airport6.location);
System.out.println("Airport city: "+airport6.city);
System.out.println("Airport state: "+airport6.state);
System.out.println("Airport country: "+airport6.country);
System.out.println("Airport code: "+airport6.airportCode);
System.out.println("Airport terminals: "+airport6.numberOfTerminals);
System.out.println("Airport runways: "+airport6.numberOfRunways);
System.out.println("Airport daily flights: "+airport6.dailyFlights);
System.out.println("Airport daily passengers: "+airport6.dailyPassengers);
System.out.println("International flights: "+airport6.internationalFlights);
System.out.println("Domestic flights: "+airport6.domesticFlights);
System.out.println("Cargo service: "+airport6.cargoService);
System.out.println("Parking available: "+airport6.parkingAvailable);
System.out.println("Wifi available: "+airport6.wifiAvailable);
System.out.println("Lounge available: "+airport6.loungeAvailable);
System.out.println("Shopping area: "+airport6.shoppingArea);
System.out.println("Restaurants: "+airport6.restaurants);
System.out.println("Taxi service: "+airport6.taxiService);
System.out.println("Metro connectivity: "+airport6.metroConnectivity);
System.out.println("Security system: "+airport6.securitySystem);
System.out.println("Baggage service: "+airport6.baggageService);
System.out.println("Opening time: "+airport6.openingTime);
System.out.println("Closing time: "+airport6.closingTime);
System.out.println("Entry fee: "+airport6.entryFee);

Airport airport7 = new Airport();

System.out.println("Airport name: "+airport7.name);
System.out.println("Airport location: "+airport7.location);
System.out.println("Airport city: "+airport7.city);
System.out.println("Airport state: "+airport7.state);
System.out.println("Airport country: "+airport7.country);
System.out.println("Airport code: "+airport7.airportCode);
System.out.println("Airport terminals: "+airport7.numberOfTerminals);
System.out.println("Airport runways: "+airport7.numberOfRunways);
System.out.println("Airport daily flights: "+airport7.dailyFlights);
System.out.println("Airport daily passengers: "+airport7.dailyPassengers);
System.out.println("International flights: "+airport7.internationalFlights);
System.out.println("Domestic flights: "+airport7.domesticFlights);
System.out.println("Cargo service: "+airport7.cargoService);
System.out.println("Parking available: "+airport7.parkingAvailable);
System.out.println("Wifi available: "+airport7.wifiAvailable);
System.out.println("Lounge available: "+airport7.loungeAvailable);
System.out.println("Shopping area: "+airport7.shoppingArea);
System.out.println("Restaurants: "+airport7.restaurants);
System.out.println("Taxi service: "+airport7.taxiService);
System.out.println("Metro connectivity: "+airport7.metroConnectivity);
System.out.println("Security system: "+airport7.securitySystem);
System.out.println("Baggage service: "+airport7.baggageService);
System.out.println("Opening time: "+airport7.openingTime);
System.out.println("Closing time: "+airport7.closingTime);
System.out.println("Entry fee: "+airport7.entryFee);

airport7.name="Kempegowda International Airport";
airport7.location="Devanahalli";
airport7.city="Bangalore";
airport7.state="Karnataka";
airport7.country="India";
airport7.airportCode="BLR";
airport7.numberOfTerminals=2;
airport7.numberOfRunways=2;
airport7.dailyFlights=650;
airport7.dailyPassengers=90000;
airport7.internationalFlights=true;
airport7.domesticFlights=true;
airport7.cargoService=true;
airport7.parkingAvailable=true;
airport7.wifiAvailable=true;
airport7.loungeAvailable=true;
airport7.shoppingArea=true;
airport7.restaurants=true;
airport7.taxiService=true;
airport7.metroConnectivity=false;
airport7.securitySystem=true;
airport7.baggageService=true;
airport7.openingTime="24 Hours";
airport7.closingTime="24 Hours";
airport7.entryFee=120;

System.out.println("Airport name: "+airport7.name);
System.out.println("Airport location: "+airport7.location);
System.out.println("Airport city: "+airport7.city);
System.out.println("Airport state: "+airport7.state);
System.out.println("Airport country: "+airport7.country);
System.out.println("Airport code: "+airport7.airportCode);
System.out.println("Airport terminals: "+airport7.numberOfTerminals);
System.out.println("Airport runways: "+airport7.numberOfRunways);
System.out.println("Airport daily flights: "+airport7.dailyFlights);
System.out.println("Airport daily passengers: "+airport7.dailyPassengers);
System.out.println("International flights: "+airport7.internationalFlights);
System.out.println("Domestic flights: "+airport7.domesticFlights);
System.out.println("Cargo service: "+airport7.cargoService);
System.out.println("Parking available: "+airport7.parkingAvailable);
System.out.println("Wifi available: "+airport7.wifiAvailable);
System.out.println("Lounge available: "+airport7.loungeAvailable);
System.out.println("Shopping area: "+airport7.shoppingArea);
System.out.println("Restaurants: "+airport7.restaurants);
System.out.println("Taxi service: "+airport7.taxiService);
System.out.println("Metro connectivity: "+airport7.metroConnectivity);
System.out.println("Security system: "+airport7.securitySystem);
System.out.println("Baggage service: "+airport7.baggageService);
System.out.println("Opening time: "+airport7.openingTime);
System.out.println("Closing time: "+airport7.closingTime);
System.out.println("Entry fee: "+airport7.entryFee);

Airport airport8 = new Airport();

System.out.println("Airport name: "+airport8.name);
System.out.println("Airport location: "+airport8.location);
System.out.println("Airport city: "+airport8.city);
System.out.println("Airport state: "+airport8.state);
System.out.println("Airport country: "+airport8.country);
System.out.println("Airport code: "+airport8.airportCode);
System.out.println("Airport terminals: "+airport8.numberOfTerminals);
System.out.println("Airport runways: "+airport8.numberOfRunways);
System.out.println("Airport daily flights: "+airport8.dailyFlights);
System.out.println("Airport daily passengers: "+airport8.dailyPassengers);
System.out.println("International flights: "+airport8.internationalFlights);
System.out.println("Domestic flights: "+airport8.domesticFlights);
System.out.println("Cargo service: "+airport8.cargoService);
System.out.println("Parking available: "+airport8.parkingAvailable);
System.out.println("Wifi available: "+airport8.wifiAvailable);
System.out.println("Lounge available: "+airport8.loungeAvailable);
System.out.println("Shopping area: "+airport8.shoppingArea);
System.out.println("Restaurants: "+airport8.restaurants);
System.out.println("Taxi service: "+airport8.taxiService);
System.out.println("Metro connectivity: "+airport8.metroConnectivity);
System.out.println("Security system: "+airport8.securitySystem);
System.out.println("Baggage service: "+airport8.baggageService);
System.out.println("Opening time: "+airport8.openingTime);
System.out.println("Closing time: "+airport8.closingTime);
System.out.println("Entry fee: "+airport8.entryFee);

airport8.name="Sardar Vallabhbhai Patel International Airport";
airport8.location="Hansol";
airport8.city="Ahmedabad";
airport8.state="Gujarat";
airport8.country="India";
airport8.airportCode="AMD";
airport8.numberOfTerminals=2;
airport8.numberOfRunways=1;
airport8.dailyFlights=300;
airport8.dailyPassengers=40000;
airport8.internationalFlights=true;
airport8.domesticFlights=true;
airport8.cargoService=true;
airport8.parkingAvailable=true;
airport8.wifiAvailable=true;
airport8.loungeAvailable=true;
airport8.shoppingArea=true;
airport8.restaurants=true;
airport8.taxiService=true;
airport8.metroConnectivity=false;
airport8.securitySystem=true;
airport8.baggageService=true;
airport8.openingTime="24 Hours";
airport8.closingTime="24 Hours";
airport8.entryFee=80;

System.out.println("Airport name: "+airport8.name);
System.out.println("Airport location: "+airport8.location);
System.out.println("Airport city: "+airport8.city);
System.out.println("Airport state: "+airport8.state);
System.out.println("Airport country: "+airport8.country);
System.out.println("Airport code: "+airport8.airportCode);
System.out.println("Airport terminals: "+airport8.numberOfTerminals);
System.out.println("Airport runways: "+airport8.numberOfRunways);
System.out.println("Airport daily flights: "+airport8.dailyFlights);
System.out.println("Airport daily passengers: "+airport8.dailyPassengers);
System.out.println("International flights: "+airport8.internationalFlights);
System.out.println("Domestic flights: "+airport8.domesticFlights);
System.out.println("Cargo service: "+airport8.cargoService);
System.out.println("Parking available: "+airport8.parkingAvailable);
System.out.println("Wifi available: "+airport8.wifiAvailable);
System.out.println("Lounge available: "+airport8.loungeAvailable);
System.out.println("Shopping area: "+airport8.shoppingArea);
System.out.println("Restaurants: "+airport8.restaurants);
System.out.println("Taxi service: "+airport8.taxiService);
System.out.println("Metro connectivity: "+airport8.metroConnectivity);
System.out.println("Security system: "+airport8.securitySystem);
System.out.println("Baggage service: "+airport8.baggageService);
System.out.println("Opening time: "+airport8.openingTime);
System.out.println("Closing time: "+airport8.closingTime);
System.out.println("Entry fee: "+airport8.entryFee);


Airport airport9 = new Airport();

System.out.println("Airport name: "+airport9.name);
System.out.println("Airport location: "+airport9.location);
System.out.println("Airport city: "+airport9.city);
System.out.println("Airport state: "+airport9.state);
System.out.println("Airport country: "+airport9.country);
System.out.println("Airport code: "+airport9.airportCode);
System.out.println("Airport terminals: "+airport9.numberOfTerminals);
System.out.println("Airport runways: "+airport9.numberOfRunways);
System.out.println("Airport daily flights: "+airport9.dailyFlights);
System.out.println("Airport daily passengers: "+airport9.dailyPassengers);
System.out.println("International flights: "+airport9.internationalFlights);
System.out.println("Domestic flights: "+airport9.domesticFlights);
System.out.println("Cargo service: "+airport9.cargoService);
System.out.println("Parking available: "+airport9.parkingAvailable);
System.out.println("Wifi available: "+airport9.wifiAvailable);
System.out.println("Lounge available: "+airport9.loungeAvailable);
System.out.println("Shopping area: "+airport9.shoppingArea);
System.out.println("Restaurants: "+airport9.restaurants);
System.out.println("Taxi service: "+airport9.taxiService);
System.out.println("Metro connectivity: "+airport9.metroConnectivity);
System.out.println("Security system: "+airport9.securitySystem);
System.out.println("Baggage service: "+airport9.baggageService);
System.out.println("Opening time: "+airport9.openingTime);
System.out.println("Closing time: "+airport9.closingTime);
System.out.println("Entry fee: "+airport9.entryFee);

airport9.name="Cochin International Airport";
airport9.location="Nedumbassery";
airport9.city="Kochi";
airport9.state="Kerala";
airport9.country="India";
airport9.airportCode="COK";
airport9.numberOfTerminals=3;
airport9.numberOfRunways=1;
airport9.dailyFlights=350;
airport9.dailyPassengers=45000;
airport9.internationalFlights=true;
airport9.domesticFlights=true;
airport9.cargoService=true;
airport9.parkingAvailable=true;
airport9.wifiAvailable=true;
airport9.loungeAvailable=true;
airport9.shoppingArea=true;
airport9.restaurants=true;
airport9.taxiService=true;
airport9.metroConnectivity=false;
airport9.securitySystem=true;
airport9.baggageService=true;
airport9.openingTime="24 Hours";
airport9.closingTime="24 Hours";
airport9.entryFee=90;

System.out.println("Airport name: "+airport9.name);
System.out.println("Airport location: "+airport9.location);
System.out.println("Airport city: "+airport9.city);
System.out.println("Airport state: "+airport9.state);
System.out.println("Airport country: "+airport9.country);
System.out.println("Airport code: "+airport9.airportCode);
System.out.println("Airport terminals: "+airport9.numberOfTerminals);
System.out.println("Airport runways: "+airport9.numberOfRunways);
System.out.println("Airport daily flights: "+airport9.dailyFlights);
System.out.println("Airport daily passengers: "+airport9.dailyPassengers);
System.out.println("International flights: "+airport9.internationalFlights);
System.out.println("Domestic flights: "+airport9.domesticFlights);
System.out.println("Cargo service: "+airport9.cargoService);
System.out.println("Parking available: "+airport9.parkingAvailable);
System.out.println("Wifi available: "+airport9.wifiAvailable);
System.out.println("Lounge available: "+airport9.loungeAvailable);
System.out.println("Shopping area: "+airport9.shoppingArea);
System.out.println("Restaurants: "+airport9.restaurants);
System.out.println("Taxi service: "+airport9.taxiService);
System.out.println("Metro connectivity: "+airport9.metroConnectivity);
System.out.println("Security system: "+airport9.securitySystem);
System.out.println("Baggage service: "+airport9.baggageService);
System.out.println("Opening time: "+airport9.openingTime);
System.out.println("Closing time: "+airport9.closingTime);
System.out.println("Entry fee: "+airport9.entryFee);

Airport airport10 = new Airport();

System.out.println("Airport name: "+airport10.name);
System.out.println("Airport location: "+airport10.location);
System.out.println("Airport city: "+airport10.city);
System.out.println("Airport state: "+airport10.state);
System.out.println("Airport country: "+airport10.country);
System.out.println("Airport code: "+airport10.airportCode);
System.out.println("Airport terminals: "+airport10.numberOfTerminals);
System.out.println("Airport runways: "+airport10.numberOfRunways);
System.out.println("Airport daily flights: "+airport10.dailyFlights);
System.out.println("Airport daily passengers: "+airport10.dailyPassengers);
System.out.println("International flights: "+airport10.internationalFlights);
System.out.println("Domestic flights: "+airport10.domesticFlights);
System.out.println("Cargo service: "+airport10.cargoService);
System.out.println("Parking available: "+airport10.parkingAvailable);
System.out.println("Wifi available: "+airport10.wifiAvailable);
System.out.println("Lounge available: "+airport10.loungeAvailable);
System.out.println("Shopping area: "+airport10.shoppingArea);
System.out.println("Restaurants: "+airport10.restaurants);
System.out.println("Taxi service: "+airport10.taxiService);
System.out.println("Metro connectivity: "+airport10.metroConnectivity);
System.out.println("Security system: "+airport10.securitySystem);
System.out.println("Baggage service: "+airport10.baggageService);
System.out.println("Opening time: "+airport10.openingTime);
System.out.println("Closing time: "+airport10.closingTime);
System.out.println("Entry fee: "+airport10.entryFee);

airport10.name="Pune International Airport";
airport10.location="Lohegaon";
airport10.city="Pune";
airport10.state="Maharashtra";
airport10.country="India";
airport10.airportCode="PNQ";
airport10.numberOfTerminals=1;
airport10.numberOfRunways=1;
airport10.dailyFlights=250;
airport10.dailyPassengers=30000;
airport10.internationalFlights=true;
airport10.domesticFlights=true;
airport10.cargoService=true;
airport10.parkingAvailable=true;
airport10.wifiAvailable=true;
airport10.loungeAvailable=true;
airport10.shoppingArea=true;
airport10.restaurants=true;
airport10.taxiService=true;
airport10.metroConnectivity=false;
airport10.securitySystem=true;
airport10.baggageService=true;
airport10.openingTime="24 Hours";
airport10.closingTime="24 Hours";
airport10.entryFee=70;

System.out.println("Airport name: "+airport10.name);
System.out.println("Airport location: "+airport10.location);
System.out.println("Airport city: "+airport10.city);
System.out.println("Airport state: "+airport10.state);
System.out.println("Airport country: "+airport10.country);
System.out.println("Airport code: "+airport10.airportCode);
System.out.println("Airport terminals: "+airport10.numberOfTerminals);
System.out.println("Airport runways: "+airport10.numberOfRunways);
System.out.println("Airport daily flights: "+airport10.dailyFlights);
System.out.println("Airport daily passengers: "+airport10.dailyPassengers);
System.out.println("International flights: "+airport10.internationalFlights);
System.out.println("Domestic flights: "+airport10.domesticFlights);
System.out.println("Cargo service: "+airport10.cargoService);
System.out.println("Parking available: "+airport10.parkingAvailable);
System.out.println("Wifi available: "+airport10.wifiAvailable);
System.out.println("Lounge available: "+airport10.loungeAvailable);
System.out.println("Shopping area: "+airport10.shoppingArea);
System.out.println("Restaurants: "+airport10.restaurants);
System.out.println("Taxi service: "+airport10.taxiService);
System.out.println("Metro connectivity: "+airport10.metroConnectivity);
System.out.println("Security system: "+airport10.securitySystem);
System.out.println("Baggage service: "+airport10.baggageService);
System.out.println("Opening time: "+airport10.openingTime);
System.out.println("Closing time: "+airport10.closingTime);
System.out.println("Entry fee: "+airport10.entryFee);


}


}