class BeachRunner{

public static void main(String[] beachinfo){

Beach beach=new Beach();
System.out.println("Before initialization : ");
System.out.println("The name of the beach is "+beach.beachName);
System.out.println("Beach location "+beach.location);
System.out.println("Beach located country name : "+beach.country);
System.out.println("Beach located state name: "+beach.state);
System.out.println("Beach sand type: "+beach.sandType);
System.out.println("Beach water color: "+beach.waterColor);
System.out.println("Beach beach length: "+beach.beachLength);
System.out.println("Beach width : "+beach.beachWidth);
System.out.println("Beach temperature: "+beach.temperature);
System.out.println("Beach water Temperature: "+beach.waterTemperature);
System.out.println("Beach wave height: "+ beach.waveHeight);
System.out.println("Beach tide Level: "+beach.tideLevel);
System.out.println("Beach wind speed: "+beach.windSpeed);
System.out.println("Beach humidity: "+beach.humidity);
System.out.println("Beach cleanlinessRating: "+beach.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach.crowdLevel);
System.out.println("Beach sunrise Time: "+beach.sunriseTime);
System.out.println("Beach sunset time: "+beach.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach.numberOfShops);
System.out.println("Beach parking Available: "+beach.parkingAvailable);
System.out.println("Beach restroom Available: "+beach.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach.entryFee);

beach.beachName="Gokarna";
beach.location="udupi";
beach.country="India";
beach.state="Karnataka";
beach.sandType="Sand";
beach.waterColor="Blue";
beach.beachLength=582.36;
beach.beachWidth=52.28;
beach.temperature=15.02F;
beach.waterTemperature=25.52F;
beach.waveHeight=500.00;
beach.tideLevel="high";
beach.windSpeed=15.00;
beach.humidity=20.00;
beach.cleanlinessRating=4;
beach.crowdLevel=200;
beach.sunriseTime="5:00";
beach.sunsetTime="6:00";
beach.numberOfLifeguards=20;
beach.numberOfShops=10;
beach.parkingAvailable=true;
beach.restroomAvailable=true;
beach.foodStallsAvailable=true;
beach.waterSportsAvailable=true;
beach.entryFee=100.00;

System.out.println("After initialization : ");
System.out.println("The name of the beach is "+beach.beachName);
System.out.println("Beach location "+beach.location);
System.out.println("Beach located country name : "+beach.country);
System.out.println("Beach located state name: "+beach.state);
System.out.println("Beach sand type: "+beach.sandType);
System.out.println("Beach water color: "+beach.waterColor);
System.out.println("Beach beach length: "+beach.beachLength);
System.out.println("Beach width : "+beach.beachWidth);
System.out.println("Beach temperature: "+beach.temperature);
System.out.println("Beach water Temperature: "+beach.waterTemperature);
System.out.println("Beach wave height: "+ beach.waveHeight);
System.out.println("Beach tide Level: "+beach.tideLevel);
System.out.println("Beach wind speed: "+beach.windSpeed);
System.out.println("Beach humidity: "+beach.humidity);
System.out.println("Beach cleanlinessRating: "+beach.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach.crowdLevel);
System.out.println("Beach sunrise Time: "+beach.sunriseTime);
System.out.println("Beach sunset time: "+beach.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach.numberOfShops);
System.out.println("Beach parking Available: "+beach.parkingAvailable);
System.out.println("Beach restroom Available: "+beach.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach.entryFee);

Beach beach1=new Beach();
System.out.println("Before initialization : ");
System.out.println("The name of the beach is "+beach1.beachName);
System.out.println("Beach location "+beach1.location);
System.out.println("Beach located country name : "+beach1.country);
System.out.println("Beach located state name: "+beach1.state);
System.out.println("Beach sand type: "+beach1.sandType);
System.out.println("Beach water color: "+beach1.waterColor);
System.out.println("Beach beach length: "+beach1.beachLength);
System.out.println("Beach width : "+beach1.beachWidth);
System.out.println("Beach temperature: "+beach1.temperature);
System.out.println("Beach water Temperature: "+beach1.waterTemperature);
System.out.println("Beach wave height: "+ beach1.waveHeight);
System.out.println("Beach tide Level: "+beach1.tideLevel);
System.out.println("Beach wind speed: "+beach1.windSpeed);
System.out.println("Beach humidity: "+beach1.humidity);
System.out.println("Beach cleanlinessRating: "+beach1.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach1.crowdLevel);
System.out.println("Beach sunrise Time: "+beach1.sunriseTime);
System.out.println("Beach sunset time: "+beach1.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach1.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach1.numberOfShops);
System.out.println("Beach parking Available: "+beach1.parkingAvailable);
System.out.println("Beach restroom Available: "+beach1.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach1.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach1.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach1.entryFee);

beach1.beachName="Gokarna";
beach1.location="Udupi";
beach1.country="India";
beach1.state="Karnataka";
beach1.sandType="Sand";
beach1.waterColor="Blue";
beach1.beachLength=582.36;
beach1.beachWidth=52.28;
beach1.temperature=15.02F;
beach1.waterTemperature=25.52F;
beach1.waveHeight=500.00;
beach1.tideLevel="High";
beach1.windSpeed=15.00;
beach1.humidity=20.00;
beach1.cleanlinessRating=4;
beach1.crowdLevel=200;
beach1.sunriseTime="5:00";
beach1.sunsetTime="6:00";
beach1.numberOfLifeguards=20;
beach1.numberOfShops=10;
beach1.parkingAvailable=true;
beach1.restroomAvailable=true;
beach1.foodStallsAvailable=true;
beach1.waterSportsAvailable=true;
beach1.entryFee=100.00;

System.out.println("After initialization : ");
System.out.println("The name of the beach is "+beach1.beachName);
System.out.println("Beach location "+beach1.location);
System.out.println("Beach located country name : "+beach1.country);
System.out.println("Beach located state name: "+beach1.state);
System.out.println("Beach sand type: "+beach1.sandType);
System.out.println("Beach water color: "+beach1.waterColor);
System.out.println("Beach beach length: "+beach1.beachLength);
System.out.println("Beach width : "+beach1.beachWidth);
System.out.println("Beach temperature: "+beach1.temperature);
System.out.println("Beach water Temperature: "+beach1.waterTemperature);
System.out.println("Beach wave height: "+ beach1.waveHeight);
System.out.println("Beach tide Level: "+beach1.tideLevel);
System.out.println("Beach wind speed: "+beach1.windSpeed);
System.out.println("Beach humidity: "+beach1.humidity);
System.out.println("Beach cleanlinessRating: "+beach1.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach1.crowdLevel);
System.out.println("Beach sunrise Time: "+beach1.sunriseTime);
System.out.println("Beach sunset time: "+beach1.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach1.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach1.numberOfShops);
System.out.println("Beach parking Available: "+beach1.parkingAvailable);
System.out.println("Beach restroom Available: "+beach1.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach1.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach1.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach1.entryFee);


Beach beach2=new Beach();
System.out.println("Before initialization : ");
System.out.println("The name of the beach is "+beach2.beachName);
System.out.println("Beach location "+beach2.location);
System.out.println("Beach located country name : "+beach2.country);
System.out.println("Beach located state name: "+beach2.state);
System.out.println("Beach sand type: "+beach2.sandType);
System.out.println("Beach water color: "+beach2.waterColor);
System.out.println("Beach beach length: "+beach2.beachLength);
System.out.println("Beach width : "+beach2.beachWidth);
System.out.println("Beach temperature: "+beach2.temperature);
System.out.println("Beach water Temperature: "+beach2.waterTemperature);
System.out.println("Beach wave height: "+ beach2.waveHeight);
System.out.println("Beach tide Level: "+beach2.tideLevel);
System.out.println("Beach wind speed: "+beach2.windSpeed);
System.out.println("Beach humidity: "+beach2.humidity);
System.out.println("Beach cleanlinessRating: "+beach2.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach2.crowdLevel);
System.out.println("Beach sunrise Time: "+beach2.sunriseTime);
System.out.println("Beach sunset time: "+beach2.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach2.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach2.numberOfShops);
System.out.println("Beach parking Available: "+beach2.parkingAvailable);
System.out.println("Beach restroom Available: "+beach2.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach2.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach2.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach2.entryFee);

beach2.beachName="Malpe";
beach2.location="Udupi";
beach2.country="India";
beach2.state="Karnataka";
beach2.sandType="White Sand";
beach2.waterColor="Light Blue";
beach2.beachLength=600.50;
beach2.beachWidth=60.00;
beach2.temperature=16.50F;
beach2.waterTemperature=26.00F;
beach2.waveHeight=450.00;
beach2.tideLevel="Medium";
beach2.windSpeed=12.00;
beach2.humidity=25.00;
beach2.cleanlinessRating=5;
beach2.crowdLevel=150;
beach2.sunriseTime="5:45";
beach2.sunsetTime="6:20";
beach2.numberOfLifeguards=15;
beach2.numberOfShops=12;
beach2.parkingAvailable=true;
beach2.restroomAvailable=true;
beach2.foodStallsAvailable=true;
beach2.waterSportsAvailable=true;
beach2.entryFee=50.00;

System.out.println("After initialization : ");
System.out.println("The name of the beach is "+beach2.beachName);
System.out.println("Beach location "+beach2.location);
System.out.println("Beach located country name : "+beach2.country);
System.out.println("Beach located state name: "+beach2.state);
System.out.println("Beach sand type: "+beach2.sandType);
System.out.println("Beach water color: "+beach2.waterColor);
System.out.println("Beach beach length: "+beach2.beachLength);
System.out.println("Beach width : "+beach2.beachWidth);
System.out.println("Beach temperature: "+beach2.temperature);
System.out.println("Beach water Temperature: "+beach2.waterTemperature);
System.out.println("Beach wave height: "+ beach2.waveHeight);
System.out.println("Beach tide Level: "+beach2.tideLevel);
System.out.println("Beach wind speed: "+beach2.windSpeed);
System.out.println("Beach humidity: "+beach2.humidity);
System.out.println("Beach cleanlinessRating: "+beach2.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach2.crowdLevel);
System.out.println("Beach sunrise Time: "+beach2.sunriseTime);
System.out.println("Beach sunset time: "+beach2.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach2.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach2.numberOfShops);
System.out.println("Beach parking Available: "+beach2.parkingAvailable);
System.out.println("Beach restroom Available: "+beach2.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach2.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach2.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach2.entryFee);
System.out.println();

Beach beach3=new Beach();
System.out.println("Before initialization : ");
System.out.println("The name of the beach is "+beach3.beachName);
System.out.println("Beach location "+beach3.location);
System.out.println("Beach located country name : "+beach3.country);
System.out.println("Beach located state name: "+beach3.state);
System.out.println("Beach sand type: "+beach3.sandType);
System.out.println("Beach water color: "+beach3.waterColor);
System.out.println("Beach beach length: "+beach3.beachLength);
System.out.println("Beach width : "+beach3.beachWidth);
System.out.println("Beach temperature: "+beach3.temperature);
System.out.println("Beach water Temperature: "+beach3.waterTemperature);
System.out.println("Beach wave height: "+ beach3.waveHeight);
System.out.println("Beach tide Level: "+beach3.tideLevel);
System.out.println("Beach wind speed: "+beach3.windSpeed);
System.out.println("Beach humidity: "+beach3.humidity);
System.out.println("Beach cleanlinessRating: "+beach3.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach3.crowdLevel);
System.out.println("Beach sunrise Time: "+beach3.sunriseTime);
System.out.println("Beach sunset time: "+beach3.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach3.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach3.numberOfShops);
System.out.println("Beach parking Available: "+beach3.parkingAvailable);
System.out.println("Beach restroom Available: "+beach3.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach3.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach3.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach3.entryFee);

beach3.beachName="Om Beach";
beach3.location="Gokarna";
beach3.country="India";
beach3.state="Karnataka";
beach3.sandType="Golden Sand";
beach3.waterColor="Blue";
beach3.beachLength=450.00;
beach3.beachWidth=40.00;
beach3.temperature=28.5F;
beach3.waterTemperature=25.5F;
beach3.waveHeight=4.5;
beach3.tideLevel="Low";
beach3.windSpeed=10.0;
beach3.humidity=35.0;
beach3.cleanlinessRating=4;
beach3.crowdLevel=120;
beach3.sunriseTime="5:55";
beach3.sunsetTime="6:15";
beach3.numberOfLifeguards=10;
beach3.numberOfShops=6;
beach3.parkingAvailable=true;
beach3.restroomAvailable=true;
beach3.foodStallsAvailable=true;
beach3.waterSportsAvailable=false;
beach3.entryFee=30.00;

System.out.println("The name of the beach is "+beach3.beachName);
System.out.println("Beach location "+beach3.location);
System.out.println("Beach located country name : "+beach3.country);
System.out.println("Beach located state name: "+beach3.state);
System.out.println("Beach sand type: "+beach3.sandType);
System.out.println("Beach water color: "+beach3.waterColor);
System.out.println("Beach beach length: "+beach3.beachLength);
System.out.println("Beach width : "+beach3.beachWidth);
System.out.println("Beach temperature: "+beach3.temperature);
System.out.println("Beach water Temperature: "+beach3.waterTemperature);
System.out.println("Beach wave height: "+ beach3.waveHeight);
System.out.println("Beach tide Level: "+beach3.tideLevel);
System.out.println("Beach wind speed: "+beach3.windSpeed);
System.out.println("Beach humidity: "+beach3.humidity);
System.out.println("Beach cleanlinessRating: "+beach3.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach3.crowdLevel);
System.out.println("Beach sunrise Time: "+beach3.sunriseTime);
System.out.println("Beach sunset time: "+beach3.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach3.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach3.numberOfShops);
System.out.println("Beach parking Available: "+beach3.parkingAvailable);
System.out.println("Beach restroom Available: "+beach3.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach3.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach3.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach3.entryFee);


Beach beach4=new Beach();
System.out.println("Before initialization");
System.out.println("The name of the beach is "+beach4.beachName);
System.out.println("Beach location "+beach4.location);
System.out.println("Beach located country name : "+beach4.country);
System.out.println("Beach located state name: "+beach4.state);
System.out.println("Beach sand type: "+beach4.sandType);
System.out.println("Beach water color: "+beach4.waterColor);
System.out.println("Beach beach length: "+beach4.beachLength);
System.out.println("Beach width : "+beach4.beachWidth);
System.out.println("Beach temperature: "+beach4.temperature);
System.out.println("Beach water Temperature: "+beach4.waterTemperature);
System.out.println("Beach wave height: "+ beach4.waveHeight);
System.out.println("Beach tide Level: "+beach4.tideLevel);
System.out.println("Beach wind speed: "+beach4.windSpeed);
System.out.println("Beach humidity: "+beach4.humidity);
System.out.println("Beach cleanlinessRating: "+beach4.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach4.crowdLevel);
System.out.println("Beach sunrise Time: "+beach4.sunriseTime);
System.out.println("Beach sunset time: "+beach4.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach4.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach4.numberOfShops);
System.out.println("Beach parking Available: "+beach4.parkingAvailable);
System.out.println("Beach restroom Available: "+beach4.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach4.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach4.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach4.entryFee);




beach4.beachName="Kaup";
beach4.location="Udupi";
beach4.country="India";
beach4.state="Karnataka";
beach4.sandType="Brown Sand";
beach4.waterColor="Dark Blue";
beach4.beachLength=520.00;
beach4.beachWidth=55.00;
beach4.temperature=31.0F;
beach4.waterTemperature=26.0F;
beach4.waveHeight=5.0;
beach4.tideLevel="High";
beach4.windSpeed=14.0;
beach4.humidity=28.0;
beach4.cleanlinessRating=3;
beach4.crowdLevel=180;
beach4.sunriseTime="5:48";
beach4.sunsetTime="6:23";
beach4.numberOfLifeguards=12;
beach4.numberOfShops=7;
beach4.parkingAvailable=true;
beach4.restroomAvailable=true;
beach4.foodStallsAvailable=true;
beach4.waterSportsAvailable=false;
beach4.entryFee=20.00;

System.out.println("After initialization");
System.out.println("The name of the beach is "+beach4.beachName);
System.out.println("Beach location "+beach4.location);
System.out.println("Beach located country name : "+beach4.country);
System.out.println("Beach located state name: "+beach4.state);
System.out.println("Beach sand type: "+beach4.sandType);
System.out.println("Beach water color: "+beach4.waterColor);
System.out.println("Beach beach length: "+beach4.beachLength);
System.out.println("Beach width : "+beach4.beachWidth);
System.out.println("Beach temperature: "+beach4.temperature);
System.out.println("Beach water Temperature: "+beach4.waterTemperature);
System.out.println("Beach wave height: "+ beach4.waveHeight);
System.out.println("Beach tide Level: "+beach4.tideLevel);
System.out.println("Beach wind speed: "+beach4.windSpeed);
System.out.println("Beach humidity: "+beach4.humidity);
System.out.println("Beach cleanlinessRating: "+beach4.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach4.crowdLevel);
System.out.println("Beach sunrise Time: "+beach4.sunriseTime);
System.out.println("Beach sunset time: "+beach4.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach4.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach4.numberOfShops);
System.out.println("Beach parking Available: "+beach4.parkingAvailable);
System.out.println("Beach restroom Available: "+beach4.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach4.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach4.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach4.entryFee);

Beach beach5=new Beach();
System.out.println("The name of the beach is "+beach5.beachName);
System.out.println("Beach location "+beach5.location);
System.out.println("Beach located country name : "+beach5.country);
System.out.println("Beach located state name: "+beach5.state);
System.out.println("Beach sand type: "+beach5.sandType);
System.out.println("Beach water color: "+beach5.waterColor);
System.out.println("Beach beach length: "+beach5.beachLength);
System.out.println("Beach width : "+beach5.beachWidth);
System.out.println("Beach temperature: "+beach5.temperature);
System.out.println("Beach water Temperature: "+beach5.waterTemperature);
System.out.println("Beach wave height: "+ beach5.waveHeight);
System.out.println("Beach tide Level: "+beach5.tideLevel);
System.out.println("Beach wind speed: "+beach5.windSpeed);
System.out.println("Beach humidity: "+beach5.humidity);
System.out.println("Beach cleanlinessRating: "+beach5.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach5.crowdLevel);
System.out.println("Beach sunrise Time: "+beach5.sunriseTime);
System.out.println("Beach sunset time: "+beach5.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach5.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach5.numberOfShops);
System.out.println("Beach parking Available: "+beach5.parkingAvailable);
System.out.println("Beach restroom Available: "+beach5.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach5.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach5.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach5.entryFee);

beach5.beachName="Marina";
beach5.location="Chennai";
beach5.country="India";
beach5.state="Tamil Nadu";
beach5.sandType="Golden Sand";
beach5.waterColor="Blue";
beach5.beachLength=1300.00;
beach5.beachWidth=80.00;
beach5.temperature=32.0F;
beach5.waterTemperature=27.0F;
beach5.waveHeight=4.5;
beach5.tideLevel="High";
beach5.windSpeed=18.0;
beach5.humidity=40.0;
beach5.cleanlinessRating=3;
beach5.crowdLevel=500;
beach5.sunriseTime="5:40";
beach5.sunsetTime="6:30";
beach5.numberOfLifeguards=30;
beach5.numberOfShops=20;
beach5.parkingAvailable=true;
beach5.restroomAvailable=true;
beach5.foodStallsAvailable=true;
beach5.waterSportsAvailable=false;
beach5.entryFee=0.00;
System.out.println("The name of the beach is "+beach5.beachName);
System.out.println("Beach location "+beach5.location);
System.out.println("Beach located country name : "+beach5.country);
System.out.println("Beach located state name: "+beach5.state);
System.out.println("Beach sand type: "+beach5.sandType);
System.out.println("Beach water color: "+beach5.waterColor);
System.out.println("Beach beach length: "+beach5.beachLength);
System.out.println("Beach width : "+beach5.beachWidth);
System.out.println("Beach temperature: "+beach5.temperature);
System.out.println("Beach water Temperature: "+beach5.waterTemperature);
System.out.println("Beach wave height: "+ beach5.waveHeight);
System.out.println("Beach tide Level: "+beach5.tideLevel);
System.out.println("Beach wind speed: "+beach5.windSpeed);
System.out.println("Beach humidity: "+beach5.humidity);
System.out.println("Beach cleanlinessRating: "+beach5.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach5.crowdLevel);
System.out.println("Beach sunrise Time: "+beach5.sunriseTime);
System.out.println("Beach sunset time: "+beach5.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach5.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach5.numberOfShops);
System.out.println("Beach parking Available: "+beach5.parkingAvailable);
System.out.println("Beach restroom Available: "+beach5.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach5.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach5.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach5.entryFee);


Beach beach6=new Beach();
System.out.println("The name of the beach is "+beach6.beachName);
System.out.println("Beach location "+beach6.location);
System.out.println("Beach located country name : "+beach6.country);
System.out.println("Beach located state name: "+beach6.state);
System.out.println("Beach sand type: "+beach6.sandType);
System.out.println("Beach water color: "+beach6.waterColor);
System.out.println("Beach beach length: "+beach6.beachLength);
System.out.println("Beach width : "+beach6.beachWidth);
System.out.println("Beach temperature: "+beach6.temperature);
System.out.println("Beach water Temperature: "+beach6.waterTemperature);
System.out.println("Beach wave height: "+ beach6.waveHeight);
System.out.println("Beach tide Level: "+beach6.tideLevel);
System.out.println("Beach wind speed: "+beach6.windSpeed);
System.out.println("Beach humidity: "+beach6.humidity);
System.out.println("Beach cleanlinessRating: "+beach6.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach6.crowdLevel);
System.out.println("Beach sunrise Time: "+beach6.sunriseTime);
System.out.println("Beach sunset time: "+beach6.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach6.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach6.numberOfShops);
System.out.println("Beach parking Available: "+beach6.parkingAvailable);
System.out.println("Beach restroom Available: "+beach6.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach6.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach6.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach6.entryFee);
beach6.beachName="Baga";
beach6.location="Goa";
beach6.country="India";
beach6.state="Goa";
beach6.sandType="White Sand";
beach6.waterColor="Light Blue";
beach6.beachLength=900.00;
beach6.beachWidth=70.00;
beach6.temperature=30.5F;
beach6.waterTemperature=26.0F;
beach6.waveHeight=5.0;
beach6.tideLevel="Medium";
beach6.windSpeed=16.0;
beach6.humidity=45.0;
beach6.cleanlinessRating=4;
beach6.crowdLevel=350;
beach6.sunriseTime="5:50";
beach6.sunsetTime="6:35";
beach6.numberOfLifeguards=25;
beach6.numberOfShops=18;
beach6.parkingAvailable=true;
beach6.restroomAvailable=true;
beach6.foodStallsAvailable=true;
beach6.waterSportsAvailable=true;
beach6.entryFee=50.00;

System.out.println("The name of the beach is "+beach6.beachName);
System.out.println("Beach location "+beach6.location);
System.out.println("Beach located country name : "+beach6.country);
System.out.println("Beach located state name: "+beach6.state);
System.out.println("Beach sand type: "+beach6.sandType);
System.out.println("Beach water color: "+beach6.waterColor);
System.out.println("Beach beach length: "+beach6.beachLength);
System.out.println("Beach width : "+beach6.beachWidth);
System.out.println("Beach temperature: "+beach6.temperature);
System.out.println("Beach water Temperature: "+beach6.waterTemperature);
System.out.println("Beach wave height: "+ beach6.waveHeight);
System.out.println("Beach tide Level: "+beach6.tideLevel);
System.out.println("Beach wind speed: "+beach6.windSpeed);
System.out.println("Beach humidity: "+beach6.humidity);
System.out.println("Beach cleanlinessRating: "+beach6.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach6.crowdLevel);
System.out.println("Beach sunrise Time: "+beach6.sunriseTime);
System.out.println("Beach sunset time: "+beach6.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach6.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach6.numberOfShops);
System.out.println("Beach parking Available: "+beach6.parkingAvailable);
System.out.println("Beach restroom Available: "+beach6.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach6.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach6.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach6.entryFee);

Beach beach7=new Beach();
System.out.println("The name of the beach is "+beach7.beachName);
System.out.println("Beach location "+beach7.location);
System.out.println("Beach located country name : "+beach7.country);
System.out.println("Beach located state name: "+beach7.state);
System.out.println("Beach sand type: "+beach7.sandType);
System.out.println("Beach water color: "+beach7.waterColor);
System.out.println("Beach beach length: "+beach7.beachLength);
System.out.println("Beach width : "+beach7.beachWidth);
System.out.println("Beach temperature: "+beach7.temperature);
System.out.println("Beach water Temperature: "+beach7.waterTemperature);
System.out.println("Beach wave height: "+ beach7.waveHeight);
System.out.println("Beach tide Level: "+beach7.tideLevel);
System.out.println("Beach wind speed: "+beach7.windSpeed);
System.out.println("Beach humidity: "+beach7.humidity);
System.out.println("Beach cleanlinessRating: "+beach7.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach7.crowdLevel);
System.out.println("Beach sunrise Time: "+beach7.sunriseTime);
System.out.println("Beach sunset time: "+beach7.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach7.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach7.numberOfShops);
System.out.println("Beach parking Available: "+beach7.parkingAvailable);
System.out.println("Beach restroom Available: "+beach7.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach7.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach7.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach7.entryFee);

beach7.beachName="Calangute";
beach7.location="Goa";
beach7.country="India";
beach7.state="Goa";
beach7.sandType="Golden Sand";
beach7.waterColor="Blue";
beach7.beachLength=1000.00;
beach7.beachWidth=75.00;
beach7.temperature=31.0F;
beach7.waterTemperature=27.0F;
beach7.waveHeight=4.8;
beach7.tideLevel="High";
beach7.windSpeed=17.0;
beach7.humidity=42.0;
beach7.cleanlinessRating=4;
beach7.crowdLevel=400;
beach7.sunriseTime="5:48";
beach7.sunsetTime="6:33";
beach7.numberOfLifeguards=22;
beach7.numberOfShops=15;
beach7.parkingAvailable=true;
beach7.restroomAvailable=true;
beach7.foodStallsAvailable=true;
beach7.waterSportsAvailable=true;
beach7.entryFee=40.00;


System.out.println("The name of the beach is "+beach7.beachName);
System.out.println("Beach location "+beach7.location);
System.out.println("Beach located country name : "+beach7.country);
System.out.println("Beach located state name: "+beach7.state);
System.out.println("Beach sand type: "+beach7.sandType);
System.out.println("Beach water color: "+beach7.waterColor);
System.out.println("Beach beach length: "+beach7.beachLength);
System.out.println("Beach width : "+beach7.beachWidth);
System.out.println("Beach temperature: "+beach7.temperature);
System.out.println("Beach water Temperature: "+beach7.waterTemperature);
System.out.println("Beach wave height: "+ beach7.waveHeight);
System.out.println("Beach tide Level: "+beach7.tideLevel);
System.out.println("Beach wind speed: "+beach7.windSpeed);
System.out.println("Beach humidity: "+beach7.humidity);
System.out.println("Beach cleanlinessRating: "+beach7.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach7.crowdLevel);
System.out.println("Beach sunrise Time: "+beach7.sunriseTime);
System.out.println("Beach sunset time: "+beach7.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach7.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach7.numberOfShops);
System.out.println("Beach parking Available: "+beach7.parkingAvailable);
System.out.println("Beach restroom Available: "+beach7.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach7.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach7.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach7.entryFee);


Beach beach8=new Beach();
System.out.println("The name of the beach is "+beach8.beachName);
System.out.println("Beach location "+beach8.location);
System.out.println("Beach located country name : "+beach8.country);
System.out.println("Beach located state name: "+beach8.state);
System.out.println("Beach sand type: "+beach8.sandType);
System.out.println("Beach water color: "+beach8.waterColor);
System.out.println("Beach beach length: "+beach8.beachLength);
System.out.println("Beach width : "+beach8.beachWidth);
System.out.println("Beach temperature: "+beach8.temperature);
System.out.println("Beach water Temperature: "+beach8.waterTemperature);
System.out.println("Beach wave height: "+ beach8.waveHeight);
System.out.println("Beach tide Level: "+beach8.tideLevel);
System.out.println("Beach wind speed: "+beach8.windSpeed);
System.out.println("Beach humidity: "+beach8.humidity);
System.out.println("Beach cleanlinessRating: "+beach8.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach8.crowdLevel);
System.out.println("Beach sunrise Time: "+beach8.sunriseTime);
System.out.println("Beach sunset time: "+beach8.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach8.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach8.numberOfShops);
System.out.println("Beach parking Available: "+beach8.parkingAvailable);
System.out.println("Beach restroom Available: "+beach8.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach8.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach8.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach8.entryFee);

beach8.beachName="Kovalam";
beach8.location="Trivandrum";
beach8.country="India";
beach8.state="Kerala";
beach8.sandType="Brown Sand";
beach8.waterColor="Blue";
beach8.beachLength=750.00;
beach8.beachWidth=65.00;
beach8.temperature=29.5F;
beach8.waterTemperature=26.5F;
beach8.waveHeight=4.0;
beach8.tideLevel="Medium";
beach8.windSpeed=14.0;
beach8.humidity=50.0;
beach8.cleanlinessRating=5;
beach8.crowdLevel=250;
beach8.sunriseTime="5:55";
beach8.sunsetTime="6:20";
beach8.numberOfLifeguards=18;
beach8.numberOfShops=12;
beach8.parkingAvailable=true;
beach8.restroomAvailable=true;
beach8.foodStallsAvailable=true;
beach8.waterSportsAvailable=true;
beach8.entryFee=30.00;
System.out.println("The name of the beach is "+beach8.beachName);
System.out.println("Beach location "+beach8.location);
System.out.println("Beach located country name : "+beach8.country);
System.out.println("Beach located state name: "+beach8.state);
System.out.println("Beach sand type: "+beach8.sandType);
System.out.println("Beach water color: "+beach8.waterColor);
System.out.println("Beach beach length: "+beach8.beachLength);
System.out.println("Beach width : "+beach8.beachWidth);
System.out.println("Beach temperature: "+beach8.temperature);
System.out.println("Beach water Temperature: "+beach8.waterTemperature);
System.out.println("Beach wave height: "+ beach8.waveHeight);
System.out.println("Beach tide Level: "+beach8.tideLevel);
System.out.println("Beach wind speed: "+beach8.windSpeed);
System.out.println("Beach humidity: "+beach8.humidity);
System.out.println("Beach cleanlinessRating: "+beach8.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach8.crowdLevel);
System.out.println("Beach sunrise Time: "+beach8.sunriseTime);
System.out.println("Beach sunset time: "+beach8.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach8.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach8.numberOfShops);
System.out.println("Beach parking Available: "+beach8.parkingAvailable);
System.out.println("Beach restroom Available: "+beach8.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach8.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach8.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach8.entryFee);


Beach beach9=new Beach();

System.out.println("The name of the beach is "+beach9.beachName);
System.out.println("Beach location "+beach9.location);
System.out.println("Beach located country name : "+beach9.country);
System.out.println("Beach located state name: "+beach9.state);
System.out.println("Beach sand type: "+beach9.sandType);
System.out.println("Beach water color: "+beach9.waterColor);
System.out.println("Beach beach length: "+beach9.beachLength);
System.out.println("Beach width : "+beach9.beachWidth);
System.out.println("Beach temperature: "+beach9.temperature);
System.out.println("Beach water Temperature: "+beach9.waterTemperature);
System.out.println("Beach wave height: "+ beach9.waveHeight);
System.out.println("Beach tide Level: "+beach9.tideLevel);
System.out.println("Beach wind speed: "+beach9.windSpeed);
System.out.println("Beach humidity: "+beach9.humidity);
System.out.println("Beach cleanlinessRating: "+beach9.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach9.crowdLevel);
System.out.println("Beach sunrise Time: "+beach9.sunriseTime);
System.out.println("Beach sunset time: "+beach9.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach9.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach9.numberOfShops);
System.out.println("Beach parking Available: "+beach9.parkingAvailable);
System.out.println("Beach restroom Available: "+beach9.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach9.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach9.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach9.entryFee);

beach9.beachName="Varkala";
beach9.location="Kerala";
beach9.country="India";
beach9.state="Kerala";
beach9.sandType="Red Sand";
beach9.waterColor="Blue";
beach9.beachLength=700.00;
beach9.beachWidth=60.00;
beach9.temperature=29.0F;
beach9.waterTemperature=26.0F;
beach9.waveHeight=4.2;
beach9.tideLevel="Low";
beach9.windSpeed=13.0;
beach9.humidity=48.0;
beach9.cleanlinessRating=5;
beach9.crowdLevel=200;
beach9.sunriseTime="5:57";
beach9.sunsetTime="6:18";
beach9.numberOfLifeguards=16;
beach9.numberOfShops=10;
beach9.parkingAvailable=true;
beach9.restroomAvailable=true;
beach9.foodStallsAvailable=true;
beach9.waterSportsAvailable=false;
beach9.entryFee=20.00;

System.out.println("The name of the beach is "+beach9.beachName);
System.out.println("Beach location "+beach9.location);
System.out.println("Beach located country name : "+beach9.country);
System.out.println("Beach located state name: "+beach9.state);
System.out.println("Beach sand type: "+beach9.sandType);
System.out.println("Beach water color: "+beach9.waterColor);
System.out.println("Beach beach length: "+beach9.beachLength);
System.out.println("Beach width : "+beach9.beachWidth);
System.out.println("Beach temperature: "+beach9.temperature);
System.out.println("Beach water Temperature: "+beach9.waterTemperature);
System.out.println("Beach wave height: "+ beach9.waveHeight);
System.out.println("Beach tide Level: "+beach9.tideLevel);
System.out.println("Beach wind speed: "+beach9.windSpeed);
System.out.println("Beach humidity: "+beach9.humidity);
System.out.println("Beach cleanlinessRating: "+beach9.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach9.crowdLevel);
System.out.println("Beach sunrise Time: "+beach9.sunriseTime);
System.out.println("Beach sunset time: "+beach9.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach9.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach9.numberOfShops);
System.out.println("Beach parking Available: "+beach9.parkingAvailable);
System.out.println("Beach restroom Available: "+beach9.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach9.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach9.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach9.entryFee);



Beach beach10=new Beach();

System.out.println("The name of the beach is "+beach10.beachName);
System.out.println("Beach location "+beach10.location);
System.out.println("Beach located country name : "+beach10.country);
System.out.println("Beach located state name: "+beach10.state);
System.out.println("Beach sand type: "+beach10.sandType);
System.out.println("Beach water color: "+beach10.waterColor);
System.out.println("Beach beach length: "+beach10.beachLength);
System.out.println("Beach width : "+beach10.beachWidth);
System.out.println("Beach temperature: "+beach10.temperature);
System.out.println("Beach water Temperature: "+beach10.waterTemperature);
System.out.println("Beach wave height: "+ beach10.waveHeight);
System.out.println("Beach tide Level: "+beach10.tideLevel);
System.out.println("Beach wind speed: "+beach10.windSpeed);
System.out.println("Beach humidity: "+beach10.humidity);
System.out.println("Beach cleanlinessRating: "+beach10.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach10.crowdLevel);
System.out.println("Beach sunrise Time: "+beach10.sunriseTime);
System.out.println("Beach sunset time: "+beach10.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach10.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach10.numberOfShops);
System.out.println("Beach parking Available: "+beach10.parkingAvailable);
System.out.println("Beach restroom Available: "+beach10.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach10.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach10.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach10.entryFee);

beach10.beachName="Puri";
beach10.location="Odisha";
beach10.country="India";
beach10.state="Odisha";
beach10.sandType="Golden Sand";
beach10.waterColor="Blue";
beach10.beachLength=850.00;
beach10.beachWidth=70.00;
beach10.temperature=31.5F;
beach10.waterTemperature=27.0F;
beach10.waveHeight=5.0;
beach10.tideLevel="High";
beach10.windSpeed=19.0;
beach10.humidity=55.0;
beach10.cleanlinessRating=4;
beach10.crowdLevel=300;
beach10.sunriseTime="5:42";
beach10.sunsetTime="6:28";
beach10.numberOfLifeguards=20;
beach10.numberOfShops=14;
beach10.parkingAvailable=true;
beach10.restroomAvailable=true;
beach10.foodStallsAvailable=true;
beach10.waterSportsAvailable=true;
beach10.entryFee=25.00;

System.out.println("The name of the beach is "+beach10.beachName);
System.out.println("Beach location "+beach10.location);
System.out.println("Beach located country name : "+beach10.country);
System.out.println("Beach located state name: "+beach10.state);
System.out.println("Beach sand type: "+beach10.sandType);
System.out.println("Beach water color: "+beach10.waterColor);
System.out.println("Beach beach length: "+beach10.beachLength);
System.out.println("Beach width : "+beach10.beachWidth);
System.out.println("Beach temperature: "+beach10.temperature);
System.out.println("Beach water Temperature: "+beach10.waterTemperature);
System.out.println("Beach wave height: "+ beach10.waveHeight);
System.out.println("Beach tide Level: "+beach10.tideLevel);
System.out.println("Beach wind speed: "+beach10.windSpeed);
System.out.println("Beach humidity: "+beach10.humidity);
System.out.println("Beach cleanlinessRating: "+beach10.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach10.crowdLevel);
System.out.println("Beach sunrise Time: "+beach10.sunriseTime);
System.out.println("Beach sunset time: "+beach10.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach10.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach10.numberOfShops);
System.out.println("Beach parking Available: "+beach10.parkingAvailable);
System.out.println("Beach restroom Available: "+beach10.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach10.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach10.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach10.entryFee);


Beach beach11=new Beach();
System.out.println("The name of the beach is "+beach11.beachName);
System.out.println("Beach location "+beach11.location);
System.out.println("Beach located country name : "+beach11.country);
System.out.println("Beach located state name: "+beach11.state);
System.out.println("Beach sand type: "+beach11.sandType);
System.out.println("Beach water color: "+beach11.waterColor);
System.out.println("Beach beach length: "+beach11.beachLength);
System.out.println("Beach width : "+beach11.beachWidth);
System.out.println("Beach temperature: "+beach11.temperature);
System.out.println("Beach water Temperature: "+beach11.waterTemperature);
System.out.println("Beach wave height: "+ beach11.waveHeight);
System.out.println("Beach tide Level: "+beach11.tideLevel);
System.out.println("Beach wind speed: "+beach11.windSpeed);
System.out.println("Beach humidity: "+beach11.humidity);
System.out.println("Beach cleanlinessRating: "+beach11.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach11.crowdLevel);
System.out.println("Beach sunrise Time: "+beach11.sunriseTime);
System.out.println("Beach sunset time: "+beach11.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach11.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach11.numberOfShops);
System.out.println("Beach parking Available: "+beach11.parkingAvailable);
System.out.println("Beach restroom Available: "+beach11.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach11.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach11.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach11.entryFee);

beach11.beachName="Juhu";
beach11.location="Mumbai";
beach11.country="India";
beach11.state="Maharashtra";
beach11.sandType="Brown Sand";
beach11.waterColor="Dark Blue";
beach11.beachLength=800.00;
beach11.beachWidth=70.00;
beach11.temperature=30.0F;
beach11.waterTemperature=26.0F;
beach11.waveHeight=4.5;
beach11.tideLevel="Medium";
beach11.windSpeed=15.0;
beach11.humidity=60.0;
beach11.cleanlinessRating=3;
beach11.crowdLevel=450;
beach11.sunriseTime="6:00";
beach11.sunsetTime="6:40";
beach11.numberOfLifeguards=20;
beach11.numberOfShops=18;
beach11.parkingAvailable=true;
beach11.restroomAvailable=true;
beach11.foodStallsAvailable=true;
beach11.waterSportsAvailable=false;
beach11.entryFee=0.00;

System.out.println("The name of the beach is "+beach11.beachName);
System.out.println("Beach location "+beach11.location);
System.out.println("Beach located country name : "+beach11.country);
System.out.println("Beach located state name: "+beach11.state);
System.out.println("Beach sand type: "+beach11.sandType);
System.out.println("Beach water color: "+beach11.waterColor);
System.out.println("Beach beach length: "+beach11.beachLength);
System.out.println("Beach width : "+beach11.beachWidth);
System.out.println("Beach temperature: "+beach11.temperature);
System.out.println("Beach water Temperature: "+beach11.waterTemperature);
System.out.println("Beach wave height: "+ beach11.waveHeight);
System.out.println("Beach tide Level: "+beach11.tideLevel);
System.out.println("Beach wind speed: "+beach11.windSpeed);
System.out.println("Beach humidity: "+beach11.humidity);
System.out.println("Beach cleanlinessRating: "+beach11.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach11.crowdLevel);
System.out.println("Beach sunrise Time: "+beach11.sunriseTime);
System.out.println("Beach sunset time: "+beach11.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach11.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach11.numberOfShops);
System.out.println("Beach parking Available: "+beach11.parkingAvailable);
System.out.println("Beach restroom Available: "+beach11.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach11.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach11.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach11.entryFee);


Beach beach12=new Beach();
System.out.println("The name of the beach is "+beach12.beachName);
System.out.println("Beach location "+beach12.location);
System.out.println("Beach located country name : "+beach12.country);
System.out.println("Beach located state name: "+beach12.state);
System.out.println("Beach sand type: "+beach12.sandType);
System.out.println("Beach water color: "+beach12.waterColor);
System.out.println("Beach beach length: "+beach12.beachLength);
System.out.println("Beach width : "+beach12.beachWidth);
System.out.println("Beach temperature: "+beach12.temperature);
System.out.println("Beach water Temperature: "+beach12.waterTemperature);
System.out.println("Beach wave height: "+ beach12.waveHeight);
System.out.println("Beach tide Level: "+beach12.tideLevel);
System.out.println("Beach wind speed: "+beach12.windSpeed);
System.out.println("Beach humidity: "+beach12.humidity);
System.out.println("Beach cleanlinessRating: "+beach12.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach12.crowdLevel);
System.out.println("Beach sunrise Time: "+beach12.sunriseTime);
System.out.println("Beach sunset time: "+beach12.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach12.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach12.numberOfShops);
System.out.println("Beach parking Available: "+beach12.parkingAvailable);
System.out.println("Beach restroom Available: "+beach12.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach12.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach12.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach12.entryFee);

beach12.beachName="Anjuna";
beach12.location="Goa";
beach12.country="India";
beach12.state="Goa";
beach12.sandType="Golden Sand";
beach12.waterColor="Blue";
beach12.beachLength=720.00;
beach12.beachWidth=65.00;
beach12.temperature=30.0F;
beach12.waterTemperature=26.5F;
beach12.waveHeight=4.3;
beach12.tideLevel="Medium";
beach12.windSpeed=14.0;
beach12.humidity=50.0;
beach12.cleanlinessRating=4;
beach12.crowdLevel=220;
beach12.sunriseTime="5:52";
beach12.sunsetTime="6:32";
beach12.numberOfLifeguards=14;
beach12.numberOfShops=9;
beach12.parkingAvailable=true;
beach12.restroomAvailable=true;
beach12.foodStallsAvailable=true;
beach12.waterSportsAvailable=true;
beach12.entryFee=30.00;
System.out.println("The name of the beach is "+beach12.beachName);
System.out.println("Beach location "+beach12.location);
System.out.println("Beach located country name : "+beach12.country);
System.out.println("Beach located state name: "+beach12.state);
System.out.println("Beach sand type: "+beach12.sandType);
System.out.println("Beach water color: "+beach12.waterColor);
System.out.println("Beach beach length: "+beach12.beachLength);
System.out.println("Beach width : "+beach12.beachWidth);
System.out.println("Beach temperature: "+beach12.temperature);
System.out.println("Beach water Temperature: "+beach12.waterTemperature);
System.out.println("Beach wave height: "+ beach12.waveHeight);
System.out.println("Beach tide Level: "+beach12.tideLevel);
System.out.println("Beach wind speed: "+beach12.windSpeed);
System.out.println("Beach humidity: "+beach12.humidity);
System.out.println("Beach cleanlinessRating: "+beach12.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach12.crowdLevel);
System.out.println("Beach sunrise Time: "+beach12.sunriseTime);
System.out.println("Beach sunset time: "+beach12.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach12.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach12.numberOfShops);
System.out.println("Beach parking Available: "+beach12.parkingAvailable);
System.out.println("Beach restroom Available: "+beach12.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach12.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach12.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach12.entryFee);


Beach beach13=new Beach();

System.out.println("The name of the beach is "+beach13.beachName);
System.out.println("Beach location "+beach13.location);
System.out.println("Beach located country name : "+beach13.country);
System.out.println("Beach located state name: "+beach13.state);
System.out.println("Beach sand type: "+beach13.sandType);
System.out.println("Beach water color: "+beach13.waterColor);
System.out.println("Beach beach length: "+beach13.beachLength);
System.out.println("Beach width : "+beach13.beachWidth);
System.out.println("Beach temperature: "+beach13.temperature);
System.out.println("Beach water Temperature: "+beach13.waterTemperature);
System.out.println("Beach wave height: "+ beach13.waveHeight);
System.out.println("Beach tide Level: "+beach13.tideLevel);
System.out.println("Beach wind speed: "+beach13.windSpeed);
System.out.println("Beach humidity: "+beach13.humidity);
System.out.println("Beach cleanlinessRating: "+beach13.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach13.crowdLevel);
System.out.println("Beach sunrise Time: "+beach13.sunriseTime);
System.out.println("Beach sunset time: "+beach13.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach13.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach13.numberOfShops);
System.out.println("Beach parking Available: "+beach13.parkingAvailable);
System.out.println("Beach restroom Available: "+beach13.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach13.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach13.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach13.entryFee);

beach13.beachName="Mandrem";
beach13.location="Goa";
beach13.country="India";
beach13.state="Goa";
beach13.sandType="White Sand";
beach13.waterColor="Light Blue";
beach13.beachLength=680.00;
beach13.beachWidth=60.00;
beach13.temperature=29.5F;
beach13.waterTemperature=26.0F;
beach13.waveHeight=3.8;
beach13.tideLevel="Low";
beach13.windSpeed=12.0;
beach13.humidity=48.0;
beach13.cleanlinessRating=5;
beach13.crowdLevel=140;
beach13.sunriseTime="5:55";
beach13.sunsetTime="6:30";
beach13.numberOfLifeguards=12;
beach13.numberOfShops=7;
beach13.parkingAvailable=true;
beach13.restroomAvailable=true;
beach13.foodStallsAvailable=true;
beach13.waterSportsAvailable=false;
beach13.entryFee=20.00;
System.out.println("The name of the beach is "+beach13.beachName);
System.out.println("Beach location "+beach13.location);
System.out.println("Beach located country name : "+beach13.country);
System.out.println("Beach located state name: "+beach13.state);
System.out.println("Beach sand type: "+beach13.sandType);
System.out.println("Beach water color: "+beach13.waterColor);
System.out.println("Beach beach length: "+beach13.beachLength);
System.out.println("Beach width : "+beach13.beachWidth);
System.out.println("Beach temperature: "+beach13.temperature);
System.out.println("Beach water Temperature: "+beach13.waterTemperature);
System.out.println("Beach wave height: "+ beach13.waveHeight);
System.out.println("Beach tide Level: "+beach13.tideLevel);
System.out.println("Beach wind speed: "+beach13.windSpeed);
System.out.println("Beach humidity: "+beach13.humidity);
System.out.println("Beach cleanlinessRating: "+beach13.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach13.crowdLevel);
System.out.println("Beach sunrise Time: "+beach13.sunriseTime);
System.out.println("Beach sunset time: "+beach13.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach13.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach13.numberOfShops);
System.out.println("Beach parking Available: "+beach13.parkingAvailable);
System.out.println("Beach restroom Available: "+beach13.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach13.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach13.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach13.entryFee);


Beach beach14=new Beach();

System.out.println("The name of the beach is "+beach14.beachName);
System.out.println("Beach location "+beach14.location);
System.out.println("Beach located country name : "+beach14.country);
System.out.println("Beach located state name: "+beach14.state);
System.out.println("Beach sand type: "+beach14.sandType);
System.out.println("Beach water color: "+beach14.waterColor);
System.out.println("Beach beach length: "+beach14.beachLength);
System.out.println("Beach width : "+beach14.beachWidth);
System.out.println("Beach temperature: "+beach14.temperature);
System.out.println("Beach water Temperature: "+beach14.waterTemperature);
System.out.println("Beach wave height: "+ beach14.waveHeight);
System.out.println("Beach tide Level: "+beach14.tideLevel);
System.out.println("Beach wind speed: "+beach14.windSpeed);
System.out.println("Beach humidity: "+beach14.humidity);
System.out.println("Beach cleanlinessRating: "+beach14.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach14.crowdLevel);
System.out.println("Beach sunrise Time: "+beach14.sunriseTime);
System.out.println("Beach sunset time: "+beach14.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach14.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach14.numberOfShops);
System.out.println("Beach parking Available: "+beach14.parkingAvailable);
System.out.println("Beach restroom Available: "+beach14.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach14.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach14.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach14.entryFee);

beach14.beachName="Dhanushkodi";
beach14.location="Rameswaram";
beach14.country="India";
beach14.state="Tamil Nadu";
beach14.sandType="Golden Sand";
beach14.waterColor="Blue";
beach14.beachLength=900.00;
beach14.beachWidth=70.00;
beach14.temperature=31.0F;
beach14.waterTemperature=27.0F;
beach14.waveHeight=5.1;
beach14.tideLevel="High";
beach14.windSpeed=18.0;
beach14.humidity=52.0;
beach14.cleanlinessRating=4;
beach14.crowdLevel=180;
beach14.sunriseTime="5:45";
beach14.sunsetTime="6:25";
beach14.numberOfLifeguards=15;
beach14.numberOfShops=10;
beach14.parkingAvailable=true;
beach14.restroomAvailable=true;
beach14.foodStallsAvailable=true;
beach14.waterSportsAvailable=false;
beach14.entryFee=25.00;

System.out.println("The name of the beach is "+beach14.beachName);
System.out.println("Beach location "+beach14.location);
System.out.println("Beach located country name : "+beach14.country);
System.out.println("Beach located state name: "+beach14.state);
System.out.println("Beach sand type: "+beach14.sandType);
System.out.println("Beach water color: "+beach14.waterColor);
System.out.println("Beach beach length: "+beach14.beachLength);
System.out.println("Beach width : "+beach14.beachWidth);
System.out.println("Beach temperature: "+beach14.temperature);
System.out.println("Beach water Temperature: "+beach14.waterTemperature);
System.out.println("Beach wave height: "+ beach14.waveHeight);
System.out.println("Beach tide Level: "+beach14.tideLevel);
System.out.println("Beach wind speed: "+beach14.windSpeed);
System.out.println("Beach humidity: "+beach14.humidity);
System.out.println("Beach cleanlinessRating: "+beach14.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach14.crowdLevel);
System.out.println("Beach sunrise Time: "+beach14.sunriseTime);
System.out.println("Beach sunset time: "+beach14.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach14.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach14.numberOfShops);
System.out.println("Beach parking Available: "+beach14.parkingAvailable);
System.out.println("Beach restroom Available: "+beach14.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach14.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach14.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach14.entryFee);



Beach beach15=new Beach();

System.out.println("The name of the beach is "+beach15.beachName);
System.out.println("Beach location "+beach15.location);
System.out.println("Beach located country name : "+beach15.country);
System.out.println("Beach located state name: "+beach15.state);
System.out.println("Beach sand type: "+beach15.sandType);
System.out.println("Beach water color: "+beach15.waterColor);
System.out.println("Beach beach length: "+beach15.beachLength);
System.out.println("Beach width : "+beach15.beachWidth);
System.out.println("Beach temperature: "+beach15.temperature);
System.out.println("Beach water Temperature: "+beach15.waterTemperature);
System.out.println("Beach wave height: "+ beach15.waveHeight);
System.out.println("Beach tide Level: "+beach15.tideLevel);
System.out.println("Beach wind speed: "+beach15.windSpeed);
System.out.println("Beach humidity: "+beach15.humidity);
System.out.println("Beach cleanlinessRating: "+beach15.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach15.crowdLevel);
System.out.println("Beach sunrise Time: "+beach15.sunriseTime);
System.out.println("Beach sunset time: "+beach15.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach15.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach15.numberOfShops);
System.out.println("Beach parking Available: "+beach15.parkingAvailable);
System.out.println("Beach restroom Available: "+beach15.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach15.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach15.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach15.entryFee);

beach15.beachName="Cherai";
beach15.location="Kochi";
beach15.country="India";
beach15.state="Kerala";
beach15.sandType="White Sand";
beach15.waterColor="Blue";
beach15.beachLength=750.00;
beach15.beachWidth=68.00;
beach15.temperature=29.8F;
beach15.waterTemperature=26.2F;
beach15.waveHeight=4.0;
beach15.tideLevel="Medium";
beach15.windSpeed=13.0;
beach15.humidity=49.0;
beach15.cleanlinessRating=5;
beach15.crowdLevel=210;
beach15.sunriseTime="5:58";
beach15.sunsetTime="6:22";
beach15.numberOfLifeguards=16;
beach15.numberOfShops=11;
beach15.parkingAvailable=true;
beach15.restroomAvailable=true;
beach15.foodStallsAvailable=true;
beach15.waterSportsAvailable=true;
beach15.entryFee=35.00;
System.out.println("The name of the beach is "+beach15.beachName);
System.out.println("Beach location "+beach15.location);
System.out.println("Beach located country name : "+beach15.country);
System.out.println("Beach located state name: "+beach15.state);
System.out.println("Beach sand type: "+beach15.sandType);
System.out.println("Beach water color: "+beach15.waterColor);
System.out.println("Beach beach length: "+beach15.beachLength);
System.out.println("Beach width : "+beach15.beachWidth);
System.out.println("Beach temperature: "+beach15.temperature);
System.out.println("Beach water Temperature: "+beach15.waterTemperature);
System.out.println("Beach wave height: "+ beach15.waveHeight);
System.out.println("Beach tide Level: "+beach15.tideLevel);
System.out.println("Beach wind speed: "+beach15.windSpeed);
System.out.println("Beach humidity: "+beach15.humidity);
System.out.println("Beach cleanlinessRating: "+beach15.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach15.crowdLevel);
System.out.println("Beach sunrise Time: "+beach15.sunriseTime);
System.out.println("Beach sunset time: "+beach15.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach15.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach15.numberOfShops);
System.out.println("Beach parking Available: "+beach15.parkingAvailable);
System.out.println("Beach restroom Available: "+beach15.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach15.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach15.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach15.entryFee);

Beach beach16=new Beach();

System.out.println("The name of the beach is "+beach16.beachName);
System.out.println("Beach location "+beach16.location);
System.out.println("Beach located country name : "+beach16.country);
System.out.println("Beach located state name: "+beach16.state);
System.out.println("Beach sand type: "+beach16.sandType);
System.out.println("Beach water color: "+beach16.waterColor);
System.out.println("Beach beach length: "+beach16.beachLength);
System.out.println("Beach width : "+beach16.beachWidth);
System.out.println("Beach temperature: "+beach16.temperature);
System.out.println("Beach water Temperature: "+beach16.waterTemperature);
System.out.println("Beach wave height: "+ beach16.waveHeight);
System.out.println("Beach tide Level: "+beach16.tideLevel);
System.out.println("Beach wind speed: "+beach16.windSpeed);
System.out.println("Beach humidity: "+beach16.humidity);
System.out.println("Beach cleanlinessRating: "+beach16.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach16.crowdLevel);
System.out.println("Beach sunrise Time: "+beach16.sunriseTime);
System.out.println("Beach sunset time: "+beach16.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach16.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach16.numberOfShops);
System.out.println("Beach parking Available: "+beach16.parkingAvailable);
System.out.println("Beach restroom Available: "+beach16.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach16.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach16.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach16.entryFee);

beach16.beachName="Radhanagar";
beach16.location="Andaman";
beach16.country="India";
beach16.state="Andaman and Nicobar";
beach16.sandType="White Sand";
beach16.waterColor="Crystal Blue";
beach16.beachLength=1000.00;
beach16.beachWidth=85.00;
beach16.temperature=30.5F;
beach16.waterTemperature=27.5F;
beach16.waveHeight=4.7;
beach16.tideLevel="Medium";
beach16.windSpeed=16.0;
beach16.humidity=60.0;
beach16.cleanlinessRating=5;
beach16.crowdLevel=170;
beach16.sunriseTime="5:40";
beach16.sunsetTime="6:10";
beach16.numberOfLifeguards=18;
beach16.numberOfShops=8;
beach16.parkingAvailable=true;
beach16.restroomAvailable=true;
beach16.foodStallsAvailable=true;
beach16.waterSportsAvailable=true;
beach16.entryFee=100.00;
System.out.println("The name of the beach is "+beach16.beachName);
System.out.println("Beach location "+beach16.location);
System.out.println("Beach located country name : "+beach16.country);
System.out.println("Beach located state name: "+beach16.state);
System.out.println("Beach sand type: "+beach16.sandType);
System.out.println("Beach water color: "+beach16.waterColor);
System.out.println("Beach beach length: "+beach16.beachLength);
System.out.println("Beach width : "+beach16.beachWidth);
System.out.println("Beach temperature: "+beach16.temperature);
System.out.println("Beach water Temperature: "+beach16.waterTemperature);
System.out.println("Beach wave height: "+ beach16.waveHeight);
System.out.println("Beach tide Level: "+beach16.tideLevel);
System.out.println("Beach wind speed: "+beach16.windSpeed);
System.out.println("Beach humidity: "+beach16.humidity);
System.out.println("Beach cleanlinessRating: "+beach16.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach16.crowdLevel);
System.out.println("Beach sunrise Time: "+beach16.sunriseTime);
System.out.println("Beach sunset time: "+beach16.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach16.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach16.numberOfShops);
System.out.println("Beach parking Available: "+beach16.parkingAvailable);
System.out.println("Beach restroom Available: "+beach16.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach16.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach16.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach16.entryFee);

Beach beach17=new Beach();
System.out.println("The name of the beach is "+beach17.beachName);
System.out.println("Beach location "+beach17.location);
System.out.println("Beach located country name : "+beach17.country);
System.out.println("Beach located state name: "+beach17.state);
System.out.println("Beach sand type: "+beach17.sandType);
System.out.println("Beach water color: "+beach17.waterColor);
System.out.println("Beach beach length: "+beach17.beachLength);
System.out.println("Beach width : "+beach17.beachWidth);
System.out.println("Beach temperature: "+beach17.temperature);
System.out.println("Beach water Temperature: "+beach17.waterTemperature);
System.out.println("Beach wave height: "+ beach17.waveHeight);
System.out.println("Beach tide Level: "+beach17.tideLevel);
System.out.println("Beach wind speed: "+beach17.windSpeed);
System.out.println("Beach humidity: "+beach17.humidity);
System.out.println("Beach cleanlinessRating: "+beach17.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach17.crowdLevel);
System.out.println("Beach sunrise Time: "+beach17.sunriseTime);
System.out.println("Beach sunset time: "+beach17.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach17.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach17.numberOfShops);
System.out.println("Beach parking Available: "+beach17.parkingAvailable);
System.out.println("Beach restroom Available: "+beach17.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach17.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach17.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach17.entryFee);

beach17.beachName="Paradise";
beach17.location="Puducherry";
beach17.country="India";
beach17.state="Puducherry";
beach17.sandType="Golden Sand";
beach17.waterColor="Blue";
beach17.beachLength=820.00;
beach17.beachWidth=72.00;
beach17.temperature=30.2F;
beach17.waterTemperature=26.8F;
beach17.waveHeight=4.4;
beach17.tideLevel="Medium";
beach17.windSpeed=15.0;
beach17.humidity=47.0;
beach17.cleanlinessRating=4;
beach17.crowdLevel=190;
beach17.sunriseTime="5:47";
beach17.sunsetTime="6:27";
beach17.numberOfLifeguards=17;
beach17.numberOfShops=9;
beach17.parkingAvailable=true;
beach17.restroomAvailable=true;
beach17.foodStallsAvailable=true;
beach17.waterSportsAvailable=true;
beach17.entryFee=40.00;
System.out.println("The name of the beach is "+beach17.beachName);
System.out.println("Beach location "+beach17.location);
System.out.println("Beach located country name : "+beach17.country);
System.out.println("Beach located state name: "+beach17.state);
System.out.println("Beach sand type: "+beach17.sandType);
System.out.println("Beach water color: "+beach17.waterColor);
System.out.println("Beach beach length: "+beach17.beachLength);
System.out.println("Beach width : "+beach17.beachWidth);
System.out.println("Beach temperature: "+beach17.temperature);
System.out.println("Beach water Temperature: "+beach17.waterTemperature);
System.out.println("Beach wave height: "+ beach17.waveHeight);
System.out.println("Beach tide Level: "+beach17.tideLevel);
System.out.println("Beach wind speed: "+beach17.windSpeed);
System.out.println("Beach humidity: "+beach17.humidity);
System.out.println("Beach cleanlinessRating: "+beach17.cleanlinessRating);
System.out.println("Beach crowdlevel: "+beach17.crowdLevel);
System.out.println("Beach sunrise Time: "+beach17.sunriseTime);
System.out.println("Beach sunset time: "+beach17.sunsetTime);
System.out.println("Beach number Of Lifeguards: "+beach17.numberOfLifeguards);
System.out.println("Beach number Of Shops: "+beach17.numberOfShops);
System.out.println("Beach parking Available: "+beach17.parkingAvailable);
System.out.println("Beach restroom Available: "+beach17.restroomAvailable);
System.out.println("Beach foodStalls Available: "+beach17.foodStallsAvailable);
System.out.println("Beach waterSports Available: "+beach17.waterSportsAvailable);
System.out.println("Beach entry Fee: "+beach17.entryFee);

}




}