class BlinkIt {
    public static double search(String foodName) {
        if(foodName.equals("WholeWheatBread")) return 45;
        else if(foodName.equals("MultigrainBread")) return 55;
        else if(foodName.equals("FullCreamMilk")) return 32;
        else if(foodName.equals("LowFatMilk")) return 30;
        else if(foodName.equals("OrganicEggs")) return 85;
        else if(foodName.equals("SaltedPeanuts")) return 40;
        else if(foodName.equals("MasalaPeanuts")) return 50;
        else if(foodName.equals("CheeseSlices")) return 140;
        else if(foodName.equals("ButterCookies")) return 90;
        else if(foodName.equals("CreamBiscuits")) return 25;
        else if(foodName.equals("ProteinBar")) return 60;
        else if(foodName.equals("GranolaBar")) return 50;
        else if(foodName.equals("TomatoSoupPacket")) return 30;
        else if(foodName.equals("SweetCornSoupPacket")) return 35;
        else if(foodName.equals("InstantOats")) return 100;
        else if(foodName.equals("DryFigs")) return 280;
        else if(foodName.equals("Walnuts")) return 350;
        else if(foodName.equals("PumpkinSeeds")) return 200;
        else if(foodName.equals("ChiaSeeds")) return 220;
        else if(foodName.equals("BakingPowder")) return 25;
        else if(foodName.equals("BakingSoda")) return 20;
        else if(foodName.equals("CocoaPowder")) return 150;
        else if(foodName.equals("VanillaEssence")) return 45;
        else if(foodName.equals("StrawberryJam")) return 110;
        else if(foodName.equals("MixedFruitJam")) return 100;
        else if(foodName.equals("Mayonnaise")) return 120;
        else if(foodName.equals("SchezwanSauce")) return 130;
        else if(foodName.equals("SoySauce")) return 60;
        else if(foodName.equals("VinegarBottle")) return 50;
        else if(foodName.equals("ReadyToEatRajma")) return 130;
        else if(foodName.equals("ReadyToEatPalakPaneer")) return 150;
        else if(foodName.equals("FrozenParatha")) return 90;
        else if(foodName.equals("FrozenPizzaBase")) return 80;
        else if(foodName.equals("ChickenSausages")) return 210;
        else if(foodName.equals("VegSausages")) return 170;
        else if(foodName.equals("ColdCoffeeBottle")) return 90;
        else if(foodName.equals("MangoJuiceBottle")) return 70;
        else if(foodName.equals("GuavaJuiceBottle")) return 75;
        else if(foodName.equals("AppleJuiceBottle")) return 85;
        else if(foodName.equals("OrangeJuiceBottle")) return 80;
        else if(foodName.equals("EnergyBar")) return 45;
        else if(foodName.equals("RoastedChana")) return 30;
        else if(foodName.equals("PohaPacket")) return 40;
        else if(foodName.equals("UpmaMix")) return 45;
        else if(foodName.equals("DhoklaMix")) return 60;
        else if(foodName.equals("IdliMix")) return 55;
        else if(foodName.equals("RavaPacket")) return 50;
        else if(foodName.equals("MaidaPacket")) return 45;
        else if(foodName.equals("BesanPacket")) return 60;
        else if(foodName.equals("SabudanaPacket")) return 70;
        else if(foodName.equals("PopcornKernels")) return 65;
        else if(foodName.equals("InstantCoffeeSachets")) return 120;
        else if(foodName.equals("HerbalGreenTea")) return 150;
        else if(foodName.equals("BlackTeaLeaves")) return 130;
        else if(foodName.equals("DigestiveBiscuits")) return 35;
        return 0;
    }
}
