class Dominos {
    public static double search(String foodName) {
        if(foodName.equals("ClassicMargherita")) return 199;
        else if(foodName.equals("DoubleCheeseMargherita")) return 249;
        else if(foodName.equals("MexicanGreenWave")) return 299;
        else if(foodName.equals("DeluxeVeggie")) return 329;
        else if(foodName.equals("VegExtravaganza")) return 359;
        else if(foodName.equals("PepperBarbecueChicken")) return 349;
        else if(foodName.equals("ChickenGoldenDelight")) return 369;
        else if(foodName.equals("NonVegSupreme")) return 399;
        else if(foodName.equals("IndiChickenTikka")) return 379;
        else if(foodName.equals("IndiTandooriPaneer")) return 349;
        else if(foodName.equals("CheeseBurstMargherita")) return 299;
        else if(foodName.equals("CheeseBurstFarmhouse")) return 399;
        else if(foodName.equals("PaneerMakhaniPizza")) return 369;
        else if(foodName.equals("VegParadise")) return 319;
        else if(foodName.equals("ChickenFiesta")) return 359;
        else if(foodName.equals("CapsicumPizza")) return 259;
        else if(foodName.equals("OnionPizza")) return 239;
        else if(foodName.equals("TomatoPizza")) return 229;
        else if(foodName.equals("CornCheesePizza")) return 289;
        else if(foodName.equals("MushroomPizza")) return 299;
        else if(foodName.equals("VegLoadedPizza")) return 389;
        else if(foodName.equals("ChickenLoadedPizza")) return 429;
        else if(foodName.equals("GarlicBreadsticks")) return 129;
        else if(foodName.equals("StuffedGarlicBread")) return 159;
        else if(foodName.equals("TacoMexicanaVeg")) return 169;
        else if(foodName.equals("TacoMexicanaNonVeg")) return 189;
        else if(foodName.equals("ChocoLavaDelight")) return 109;
        else if(foodName.equals("ButterscotchMousseCake")) return 149;
        else if(foodName.equals("RedVelvetLavaCake")) return 129;
        else if(foodName.equals("Pepsi")) return 60;
        else if(foodName.equals("7Up")) return 60;
        else if(foodName.equals("Mirinda")) return 60;
        else if(foodName.equals("LiptonIceTea")) return 70;
        else if(foodName.equals("WaterBottle")) return 20;
        else if(foodName.equals("CheeseDip")) return 30;
        else if(foodName.equals("JalapenoDip")) return 35;
        else if(foodName.equals("PizzaManiaVegLoaded")) return 149;
        else if(foodName.equals("PizzaManiaPaneer")) return 169;
        else if(foodName.equals("PizzaManiaChicken")) return 189;
        else if(foodName.equals("ChickenSausagePizza")) return 349;
        else if(foodName.equals("VeggieFeastPizza")) return 329;
        else if(foodName.equals("SpicyTripleChicken")) return 429;
        else if(foodName.equals("PaneerZingyParcel")) return 79;
        else if(foodName.equals("ChickenZingyParcel")) return 89;
        else if(foodName.equals("ClassicVegBurger")) return 119;
        else if(foodName.equals("ClassicChickenBurger")) return 139;
        else if(foodName.equals("VegSubSandwich")) return 129;
        else if(foodName.equals("ChickenSubSandwich")) return 149;
        else if(foodName.equals("ChocolateBrownieDelight")) return 119;
        else if(foodName.equals("VanillaMousse")) return 109;
        else if(foodName.equals("StrawberryMousse")) return 109;
        else if(foodName.equals("PaneerStuffedCrust")) return 399;
        else if(foodName.equals("ChickenStuffedCrust")) return 449;
        else if(foodName.equals("VegCheeseVolcano")) return 379;
        else if(foodName.equals("ChickenCheeseVolcano")) return 429;
        return 0;
    }
}
