class FoodPanda {
    public static double search(String foodName) {
        if(foodName.equals("ClassicChickenBiryani")) return 210;
        else if(foodName.equals("PaneerBiryani")) return 180;
        else if(foodName.equals("EggBiryani")) return 160;
        else if(foodName.equals("VegHyderabadiBiryani")) return 170;
        else if(foodName.equals("Chicken65")) return 190;
        else if(foodName.equals("Gobi65")) return 150;
        else if(foodName.equals("PepperChicken")) return 220;
        else if(foodName.equals("LemonChicken")) return 200;
        else if(foodName.equals("PaneerTikkaMasala")) return 190;
        else if(foodName.equals("KashmiriPulao")) return 160;
        else if(foodName.equals("CurdVada")) return 80;
        else if(foodName.equals("VegKorma")) return 170;
        else if(foodName.equals("ChickenMasala")) return 230;
        else if(foodName.equals("MuttonBiryaniSpecial")) return 260;
        else if(foodName.equals("FishBiryani")) return 240;
        else if(foodName.equals("PrawnBiryani")) return 280;
        else if(foodName.equals("VegFriedMoments")) return 120;
        else if(foodName.equals("ChickenMoments")) return 150;
        else if(foodName.equals("VegDimsum")) return 130;
        else if(foodName.equals("ChickenDimsum")) return 160;
        else if(foodName.equals("VegClearSoup")) return 90;
        else if(foodName.equals("ChickenClearSoup")) return 110;
        else if(foodName.equals("VegBurgerDelight")) return 100;
        else if(foodName.equals("ChickenBurgerDelight")) return 130;
        else if(foodName.equals("VegWrap")) return 110;
        else if(foodName.equals("ChickenWrap")) return 140;
        else if(foodName.equals("FalafelPlate")) return 150;
        else if(foodName.equals("ChickenKebabPlate")) return 200;
        else if(foodName.equals("MuttonSeekhKebab")) return 240;
        else if(foodName.equals("PaneerKathiRoll")) return 120;
        else if(foodName.equals("ChickenKathiRoll")) return 150;
        else if(foodName.equals("VegNuggets")) return 130;
        else if(foodName.equals("ChickenNuggets")) return 170;
        else if(foodName.equals("VegSizzler")) return 220;
        else if(foodName.equals("ChickenSizzler")) return 260;
        else if(foodName.equals("ChocolateShake")) return 120;
        else if(foodName.equals("VanillaShake")) return 100;
        else if(foodName.equals("ButterscotchShake")) return 110;
        else if(foodName.equals("FreshLimeWater")) return 60;
        else if(foodName.equals("MintCooler")) return 80;
        else if(foodName.equals("ColdCocoa")) return 90;
        else if(foodName.equals("IceTeaPeach")) return 85;
        else if(foodName.equals("IceTeaLemon")) return 80;
        else if(foodName.equals("FruitCustard")) return 100;
        else if(foodName.equals("CarrotHalwa")) return 120;
        else if(foodName.equals("MoongDalHalwa")) return 130;
        else if(foodName.equals("Rabdi")) return 140;
        else if(foodName.equals("KajuKatli")) return 200;
        else if(foodName.equals("MilkPeda")) return 150;
        else if(foodName.equals("DryFruitLaddu")) return 180;
        else if(foodName.equals("CoconutBarfi")) return 140;
        else if(foodName.equals("GheeMysorePak")) return 160;
        else if(foodName.equals("BadamHalwa")) return 170;
        else if(foodName.equals("Thandai")) return 100;
        else if(foodName.equals("ElaichiMilk")) return 90;
        return 0;
    }
}
