class HospitalRunner{

public static void main(String[] hospitaldetails){


Hospital hospital1 = new Hospital();
System.out.println("Hospital name: "+hospital1.name);
System.out.println("Hospital location: "+hospital1.location);
System.out.println("Hospital city: "+hospital1.city);
System.out.println("Hospital state: "+hospital1.state);
System.out.println("Hospital country: "+hospital1.country);
System.out.println("Number of doctors: "+hospital1.numberOfDoctors);
System.out.println("Number of nurses: "+hospital1.numberOfNurses);
System.out.println("Number of beds: "+hospital1.numberOfBeds);
System.out.println("Emergency service: "+hospital1.emergencyService);
System.out.println("Ambulance service: "+hospital1.ambulanceService);
System.out.println("ICU available: "+hospital1.icuAvailable);
System.out.println("Pharmacy available: "+hospital1.pharmacyAvailable);
System.out.println("Blood bank: "+hospital1.bloodBank);
System.out.println("Surgery facility: "+hospital1.surgeryFacility);
System.out.println("Online appointment: "+hospital1.onlineAppointment);
System.out.println("Insurance accepted: "+hospital1.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital1.cafeteriaAvailable);
System.out.println("Parking available: "+hospital1.parkingAvailable);
System.out.println("Wifi available: "+hospital1.wifiAvailable);
System.out.println("Lab services: "+hospital1.labServices);
System.out.println("Radiology department: "+hospital1.radiologyDepartment);
System.out.println("Daily patients: "+hospital1.dailyPatients);
System.out.println("Hospital type: "+hospital1.hospitalType);
System.out.println("Opening time: "+hospital1.openingTime);
System.out.println("Closing time: "+hospital1.closingTime);

hospital1.name="Apollo Hospital";
hospital1.location="Bannerghatta Road";
hospital1.city="Bangalore";
hospital1.state="Karnataka";
hospital1.country="India";
hospital1.numberOfDoctors=120;
hospital1.numberOfNurses=200;
hospital1.numberOfBeds=500;
hospital1.emergencyService=true;
hospital1.ambulanceService=true;
hospital1.icuAvailable=true;
hospital1.pharmacyAvailable=true;
hospital1.bloodBank=true;
hospital1.surgeryFacility=true;
hospital1.onlineAppointment=true;
hospital1.insuranceAccepted=true;
hospital1.cafeteriaAvailable=true;
hospital1.parkingAvailable=true;
hospital1.wifiAvailable=true;
hospital1.labServices=true;
hospital1.radiologyDepartment=true;
hospital1.dailyPatients=700;
hospital1.hospitalType="Private";
hospital1.openingTime="24 Hours";
hospital1.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital1.name);
System.out.println("Hospital location: "+hospital1.location);
System.out.println("Hospital city: "+hospital1.city);
System.out.println("Hospital state: "+hospital1.state);
System.out.println("Hospital country: "+hospital1.country);
System.out.println("Number of doctors: "+hospital1.numberOfDoctors);
System.out.println("Number of nurses: "+hospital1.numberOfNurses);
System.out.println("Number of beds: "+hospital1.numberOfBeds);
System.out.println("Emergency service: "+hospital1.emergencyService);
System.out.println("Ambulance service: "+hospital1.ambulanceService);
System.out.println("ICU available: "+hospital1.icuAvailable);
System.out.println("Pharmacy available: "+hospital1.pharmacyAvailable);
System.out.println("Blood bank: "+hospital1.bloodBank);
System.out.println("Surgery facility: "+hospital1.surgeryFacility);
System.out.println("Online appointment: "+hospital1.onlineAppointment);
System.out.println("Insurance accepted: "+hospital1.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital1.cafeteriaAvailable);
System.out.println("Parking available: "+hospital1.parkingAvailable);
System.out.println("Wifi available: "+hospital1.wifiAvailable);
System.out.println("Lab services: "+hospital1.labServices);
System.out.println("Radiology department: "+hospital1.radiologyDepartment);
System.out.println("Daily patients: "+hospital1.dailyPatients);
System.out.println("Hospital type: "+hospital1.hospitalType);
System.out.println("Opening time: "+hospital1.openingTime);
System.out.println("Closing time: "+hospital1.closingTime);

Hospital hospital2 = new Hospital();

System.out.println("Hospital name: "+hospital2.name);
System.out.println("Hospital location: "+hospital2.location);
System.out.println("Hospital city: "+hospital2.city);
System.out.println("Hospital state: "+hospital2.state);
System.out.println("Hospital country: "+hospital2.country);
System.out.println("Number of doctors: "+hospital2.numberOfDoctors);
System.out.println("Number of nurses: "+hospital2.numberOfNurses);
System.out.println("Number of beds: "+hospital2.numberOfBeds);
System.out.println("Emergency service: "+hospital2.emergencyService);
System.out.println("Ambulance service: "+hospital2.ambulanceService);
System.out.println("ICU available: "+hospital2.icuAvailable);
System.out.println("Pharmacy available: "+hospital2.pharmacyAvailable);
System.out.println("Blood bank: "+hospital2.bloodBank);
System.out.println("Surgery facility: "+hospital2.surgeryFacility);
System.out.println("Online appointment: "+hospital2.onlineAppointment);
System.out.println("Insurance accepted: "+hospital2.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital2.cafeteriaAvailable);
System.out.println("Parking available: "+hospital2.parkingAvailable);
System.out.println("Wifi available: "+hospital2.wifiAvailable);
System.out.println("Lab services: "+hospital2.labServices);
System.out.println("Radiology department: "+hospital2.radiologyDepartment);
System.out.println("Daily patients: "+hospital2.dailyPatients);
System.out.println("Hospital type: "+hospital2.hospitalType);
System.out.println("Opening time: "+hospital2.openingTime);
System.out.println("Closing time: "+hospital2.closingTime);

hospital2.name="Fortis Hospital";
hospital2.location="Rajajinagar";
hospital2.city="Bangalore";
hospital2.state="Karnataka";
hospital2.country="India";
hospital2.numberOfDoctors=100;
hospital2.numberOfNurses=150;
hospital2.numberOfBeds=400;
hospital2.emergencyService=true;
hospital2.ambulanceService=true;
hospital2.icuAvailable=true;
hospital2.pharmacyAvailable=true;
hospital2.bloodBank=true;
hospital2.surgeryFacility=true;
hospital2.onlineAppointment=true;
hospital2.insuranceAccepted=true;
hospital2.cafeteriaAvailable=true;
hospital2.parkingAvailable=true;
hospital2.wifiAvailable=true;
hospital2.labServices=true;
hospital2.radiologyDepartment=true;
hospital2.dailyPatients=600;
hospital2.hospitalType="Private";
hospital2.openingTime="24 Hours";
hospital2.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital2.name);
System.out.println("Hospital location: "+hospital2.location);
System.out.println("Hospital city: "+hospital2.city);
System.out.println("Hospital state: "+hospital2.state);
System.out.println("Hospital country: "+hospital2.country);
System.out.println("Number of doctors: "+hospital2.numberOfDoctors);
System.out.println("Number of nurses: "+hospital2.numberOfNurses);
System.out.println("Number of beds: "+hospital2.numberOfBeds);
System.out.println("Emergency service: "+hospital2.emergencyService);
System.out.println("Ambulance service: "+hospital2.ambulanceService);
System.out.println("ICU available: "+hospital2.icuAvailable);
System.out.println("Pharmacy available: "+hospital2.pharmacyAvailable);
System.out.println("Blood bank: "+hospital2.bloodBank);
System.out.println("Surgery facility: "+hospital2.surgeryFacility);
System.out.println("Online appointment: "+hospital2.onlineAppointment);
System.out.println("Insurance accepted: "+hospital2.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital2.cafeteriaAvailable);
System.out.println("Parking available: "+hospital2.parkingAvailable);
System.out.println("Wifi available: "+hospital2.wifiAvailable);
System.out.println("Lab services: "+hospital2.labServices);
System.out.println("Radiology department: "+hospital2.radiologyDepartment);
System.out.println("Daily patients: "+hospital2.dailyPatients);
System.out.println("Hospital type: "+hospital2.hospitalType);
System.out.println("Opening time: "+hospital2.openingTime);
System.out.println("Closing time: "+hospital2.closingTime);



Hospital hospital3 = new Hospital();

System.out.println("Hospital name: "+hospital3.name);
System.out.println("Hospital location: "+hospital3.location);
System.out.println("Hospital city: "+hospital3.city);
System.out.println("Hospital state: "+hospital3.state);
System.out.println("Hospital country: "+hospital3.country);
System.out.println("Number of doctors: "+hospital3.numberOfDoctors);
System.out.println("Number of nurses: "+hospital3.numberOfNurses);
System.out.println("Number of beds: "+hospital3.numberOfBeds);
System.out.println("Emergency service: "+hospital3.emergencyService);
System.out.println("Ambulance service: "+hospital3.ambulanceService);
System.out.println("ICU available: "+hospital3.icuAvailable);
System.out.println("Pharmacy available: "+hospital3.pharmacyAvailable);
System.out.println("Blood bank: "+hospital3.bloodBank);
System.out.println("Surgery facility: "+hospital3.surgeryFacility);
System.out.println("Online appointment: "+hospital3.onlineAppointment);
System.out.println("Insurance accepted: "+hospital3.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital3.cafeteriaAvailable);
System.out.println("Parking available: "+hospital3.parkingAvailable);
System.out.println("Wifi available: "+hospital3.wifiAvailable);
System.out.println("Lab services: "+hospital3.labServices);
System.out.println("Radiology department: "+hospital3.radiologyDepartment);
System.out.println("Daily patients: "+hospital3.dailyPatients);
System.out.println("Hospital type: "+hospital3.hospitalType);
System.out.println("Opening time: "+hospital3.openingTime);
System.out.println("Closing time: "+hospital3.closingTime);

hospital3.name="Victoria Hospital";
hospital3.location="KR Market";
hospital3.city="Bangalore";
hospital3.state="Karnataka";
hospital3.country="India";
hospital3.numberOfDoctors=80;
hospital3.numberOfNurses=120;
hospital3.numberOfBeds=350;
hospital3.emergencyService=true;
hospital3.ambulanceService=true;
hospital3.icuAvailable=true;
hospital3.pharmacyAvailable=true;
hospital3.bloodBank=true;
hospital3.surgeryFacility=true;
hospital3.onlineAppointment=false;
hospital3.insuranceAccepted=true;
hospital3.cafeteriaAvailable=true;
hospital3.parkingAvailable=true;
hospital3.wifiAvailable=false;
hospital3.labServices=true;
hospital3.radiologyDepartment=true;
hospital3.dailyPatients=500;
hospital3.hospitalType="Government";
hospital3.openingTime="24 Hours";
hospital3.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital3.name);
System.out.println("Hospital location: "+hospital3.location);
System.out.println("Hospital city: "+hospital3.city);
System.out.println("Hospital state: "+hospital3.state);
System.out.println("Hospital country: "+hospital3.country);
System.out.println("Number of doctors: "+hospital3.numberOfDoctors);
System.out.println("Number of nurses: "+hospital3.numberOfNurses);
System.out.println("Number of beds: "+hospital3.numberOfBeds);
System.out.println("Emergency service: "+hospital3.emergencyService);
System.out.println("Ambulance service: "+hospital3.ambulanceService);
System.out.println("ICU available: "+hospital3.icuAvailable);
System.out.println("Pharmacy available: "+hospital3.pharmacyAvailable);
System.out.println("Blood bank: "+hospital3.bloodBank);
System.out.println("Surgery facility: "+hospital3.surgeryFacility);
System.out.println("Online appointment: "+hospital3.onlineAppointment);
System.out.println("Insurance accepted: "+hospital3.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital3.cafeteriaAvailable);
System.out.println("Parking available: "+hospital3.parkingAvailable);
System.out.println("Wifi available: "+hospital3.wifiAvailable);
System.out.println("Lab services: "+hospital3.labServices);
System.out.println("Radiology department: "+hospital3.radiologyDepartment);
System.out.println("Daily patients: "+hospital3.dailyPatients);
System.out.println("Hospital type: "+hospital3.hospitalType);
System.out.println("Opening time: "+hospital3.openingTime);
System.out.println("Closing time: "+hospital3.closingTime);

Hospital hospital4 = new Hospital();

System.out.println("Hospital name: "+hospital4.name);
System.out.println("Hospital location: "+hospital4.location);
System.out.println("Hospital city: "+hospital4.city);
System.out.println("Hospital state: "+hospital4.state);
System.out.println("Hospital country: "+hospital4.country);
System.out.println("Number of doctors: "+hospital4.numberOfDoctors);
System.out.println("Number of nurses: "+hospital4.numberOfNurses);
System.out.println("Number of beds: "+hospital4.numberOfBeds);
System.out.println("Emergency service: "+hospital4.emergencyService);
System.out.println("Ambulance service: "+hospital4.ambulanceService);
System.out.println("ICU available: "+hospital4.icuAvailable);
System.out.println("Pharmacy available: "+hospital4.pharmacyAvailable);
System.out.println("Blood bank: "+hospital4.bloodBank);
System.out.println("Surgery facility: "+hospital4.surgeryFacility);
System.out.println("Online appointment: "+hospital4.onlineAppointment);
System.out.println("Insurance accepted: "+hospital4.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital4.cafeteriaAvailable);
System.out.println("Parking available: "+hospital4.parkingAvailable);
System.out.println("Wifi available: "+hospital4.wifiAvailable);
System.out.println("Lab services: "+hospital4.labServices);
System.out.println("Radiology department: "+hospital4.radiologyDepartment);
System.out.println("Daily patients: "+hospital4.dailyPatients);
System.out.println("Hospital type: "+hospital4.hospitalType);
System.out.println("Opening time: "+hospital4.openingTime);
System.out.println("Closing time: "+hospital4.closingTime);

hospital4.name="Manipal Hospital";
hospital4.location="Whitefield";
hospital4.city="Bangalore";
hospital4.state="Karnataka";
hospital4.country="India";
hospital4.numberOfDoctors=110;
hospital4.numberOfNurses=170;
hospital4.numberOfBeds=450;
hospital4.emergencyService=true;
hospital4.ambulanceService=true;
hospital4.icuAvailable=true;
hospital4.pharmacyAvailable=true;
hospital4.bloodBank=true;
hospital4.surgeryFacility=true;
hospital4.onlineAppointment=true;
hospital4.insuranceAccepted=true;
hospital4.cafeteriaAvailable=true;
hospital4.parkingAvailable=true;
hospital4.wifiAvailable=true;
hospital4.labServices=true;
hospital4.radiologyDepartment=true;
hospital4.dailyPatients=650;
hospital4.hospitalType="Private";
hospital4.openingTime="24 Hours";
hospital4.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital4.name);
System.out.println("Hospital location: "+hospital4.location);
System.out.println("Hospital city: "+hospital4.city);
System.out.println("Hospital state: "+hospital4.state);
System.out.println("Hospital country: "+hospital4.country);
System.out.println("Number of doctors: "+hospital4.numberOfDoctors);
System.out.println("Number of nurses: "+hospital4.numberOfNurses);
System.out.println("Number of beds: "+hospital4.numberOfBeds);
System.out.println("Emergency service: "+hospital4.emergencyService);
System.out.println("Ambulance service: "+hospital4.ambulanceService);
System.out.println("ICU available: "+hospital4.icuAvailable);
System.out.println("Pharmacy available: "+hospital4.pharmacyAvailable);
System.out.println("Blood bank: "+hospital4.bloodBank);
System.out.println("Surgery facility: "+hospital4.surgeryFacility);
System.out.println("Online appointment: "+hospital4.onlineAppointment);
System.out.println("Insurance accepted: "+hospital4.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital4.cafeteriaAvailable);
System.out.println("Parking available: "+hospital4.parkingAvailable);
System.out.println("Wifi available: "+hospital4.wifiAvailable);
System.out.println("Lab services: "+hospital4.labServices);
System.out.println("Radiology department: "+hospital4.radiologyDepartment);
System.out.println("Daily patients: "+hospital4.dailyPatients);
System.out.println("Hospital type: "+hospital4.hospitalType);
System.out.println("Opening time: "+hospital4.openingTime);
System.out.println("Closing time: "+hospital4.closingTime);

Hospital hospital5 = new Hospital();

System.out.println("Hospital name: "+hospital5.name);
System.out.println("Hospital location: "+hospital5.location);
System.out.println("Hospital city: "+hospital5.city);
System.out.println("Hospital state: "+hospital5.state);
System.out.println("Hospital country: "+hospital5.country);
System.out.println("Number of doctors: "+hospital5.numberOfDoctors);
System.out.println("Number of nurses: "+hospital5.numberOfNurses);
System.out.println("Number of beds: "+hospital5.numberOfBeds);
System.out.println("Emergency service: "+hospital5.emergencyService);
System.out.println("Ambulance service: "+hospital5.ambulanceService);
System.out.println("ICU available: "+hospital5.icuAvailable);
System.out.println("Pharmacy available: "+hospital5.pharmacyAvailable);
System.out.println("Blood bank: "+hospital5.bloodBank);
System.out.println("Surgery facility: "+hospital5.surgeryFacility);
System.out.println("Online appointment: "+hospital5.onlineAppointment);
System.out.println("Insurance accepted: "+hospital5.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital5.cafeteriaAvailable);
System.out.println("Parking available: "+hospital5.parkingAvailable);
System.out.println("Wifi available: "+hospital5.wifiAvailable);
System.out.println("Lab services: "+hospital5.labServices);
System.out.println("Radiology department: "+hospital5.radiologyDepartment);
System.out.println("Daily patients: "+hospital5.dailyPatients);
System.out.println("Hospital type: "+hospital5.hospitalType);
System.out.println("Opening time: "+hospital5.openingTime);
System.out.println("Closing time: "+hospital5.closingTime);

hospital5.name="Narayana Hospital";
hospital5.location="Electronic City";
hospital5.city="Bangalore";
hospital5.state="Karnataka";
hospital5.country="India";
hospital5.numberOfDoctors=90;
hospital5.numberOfNurses=140;
hospital5.numberOfBeds=380;
hospital5.emergencyService=true;
hospital5.ambulanceService=true;
hospital5.icuAvailable=true;
hospital5.pharmacyAvailable=true;
hospital5.bloodBank=true;
hospital5.surgeryFacility=true;
hospital5.onlineAppointment=true;
hospital5.insuranceAccepted=true;
hospital5.cafeteriaAvailable=true;
hospital5.parkingAvailable=true;
hospital5.wifiAvailable=true;
hospital5.labServices=true;
hospital5.radiologyDepartment=true;
hospital5.dailyPatients=550;
hospital5.hospitalType="Private";
hospital5.openingTime="24 Hours";
hospital5.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital5.name);
System.out.println("Hospital location: "+hospital5.location);
System.out.println("Hospital city: "+hospital5.city);
System.out.println("Hospital state: "+hospital5.state);
System.out.println("Hospital country: "+hospital5.country);
System.out.println("Number of doctors: "+hospital5.numberOfDoctors);
System.out.println("Number of nurses: "+hospital5.numberOfNurses);
System.out.println("Number of beds: "+hospital5.numberOfBeds);
System.out.println("Emergency service: "+hospital5.emergencyService);
System.out.println("Ambulance service: "+hospital5.ambulanceService);
System.out.println("ICU available: "+hospital5.icuAvailable);
System.out.println("Pharmacy available: "+hospital5.pharmacyAvailable);
System.out.println("Blood bank: "+hospital5.bloodBank);
System.out.println("Surgery facility: "+hospital5.surgeryFacility);
System.out.println("Online appointment: "+hospital5.onlineAppointment);
System.out.println("Insurance accepted: "+hospital5.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital5.cafeteriaAvailable);
System.out.println("Parking available: "+hospital5.parkingAvailable);
System.out.println("Wifi available: "+hospital5.wifiAvailable);
System.out.println("Lab services: "+hospital5.labServices);
System.out.println("Radiology department: "+hospital5.radiologyDepartment);
System.out.println("Daily patients: "+hospital5.dailyPatients);
System.out.println("Hospital type: "+hospital5.hospitalType);
System.out.println("Opening time: "+hospital5.openingTime);
System.out.println("Closing time: "+hospital5.closingTime);

Hospital hospital6 = new Hospital();

System.out.println("Hospital name: "+hospital6.name);
System.out.println("Hospital location: "+hospital6.location);
System.out.println("Hospital city: "+hospital6.city);
System.out.println("Hospital state: "+hospital6.state);
System.out.println("Hospital country: "+hospital6.country);
System.out.println("Number of doctors: "+hospital6.numberOfDoctors);
System.out.println("Number of nurses: "+hospital6.numberOfNurses);
System.out.println("Number of beds: "+hospital6.numberOfBeds);
System.out.println("Emergency service: "+hospital6.emergencyService);
System.out.println("Ambulance service: "+hospital6.ambulanceService);
System.out.println("ICU available: "+hospital6.icuAvailable);
System.out.println("Pharmacy available: "+hospital6.pharmacyAvailable);
System.out.println("Blood bank: "+hospital6.bloodBank);
System.out.println("Surgery facility: "+hospital6.surgeryFacility);
System.out.println("Online appointment: "+hospital6.onlineAppointment);
System.out.println("Insurance accepted: "+hospital6.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital6.cafeteriaAvailable);
System.out.println("Parking available: "+hospital6.parkingAvailable);
System.out.println("Wifi available: "+hospital6.wifiAvailable);
System.out.println("Lab services: "+hospital6.labServices);
System.out.println("Radiology department: "+hospital6.radiologyDepartment);
System.out.println("Daily patients: "+hospital6.dailyPatients);
System.out.println("Hospital type: "+hospital6.hospitalType);
System.out.println("Opening time: "+hospital6.openingTime);
System.out.println("Closing time: "+hospital6.closingTime);

hospital6.name="Columbia Asia";
hospital6.location="Hebbal";
hospital6.city="Bangalore";
hospital6.state="Karnataka";
hospital6.country="India";
hospital6.numberOfDoctors=85;
hospital6.numberOfNurses=130;
hospital6.numberOfBeds=300;
hospital6.emergencyService=true;
hospital6.ambulanceService=true;
hospital6.icuAvailable=true;
hospital6.pharmacyAvailable=true;
hospital6.bloodBank=true;
hospital6.surgeryFacility=true;
hospital6.onlineAppointment=true;
hospital6.insuranceAccepted=true;
hospital6.cafeteriaAvailable=true;
hospital6.parkingAvailable=true;
hospital6.wifiAvailable=true;
hospital6.labServices=true;
hospital6.radiologyDepartment=true;
hospital6.dailyPatients=450;
hospital6.hospitalType="Private";
hospital6.openingTime="24 Hours";
hospital6.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital6.name);
System.out.println("Hospital location: "+hospital6.location);
System.out.println("Hospital city: "+hospital6.city);
System.out.println("Hospital state: "+hospital6.state);
System.out.println("Hospital country: "+hospital6.country);
System.out.println("Number of doctors: "+hospital6.numberOfDoctors);
System.out.println("Number of nurses: "+hospital6.numberOfNurses);
System.out.println("Number of beds: "+hospital6.numberOfBeds);
System.out.println("Emergency service: "+hospital6.emergencyService);
System.out.println("Ambulance service: "+hospital6.ambulanceService);
System.out.println("ICU available: "+hospital6.icuAvailable);
System.out.println("Pharmacy available: "+hospital6.pharmacyAvailable);
System.out.println("Blood bank: "+hospital6.bloodBank);
System.out.println("Surgery facility: "+hospital6.surgeryFacility);
System.out.println("Online appointment: "+hospital6.onlineAppointment);
System.out.println("Insurance accepted: "+hospital6.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital6.cafeteriaAvailable);
System.out.println("Parking available: "+hospital6.parkingAvailable);
System.out.println("Wifi available: "+hospital6.wifiAvailable);
System.out.println("Lab services: "+hospital6.labServices);
System.out.println("Radiology department: "+hospital6.radiologyDepartment);
System.out.println("Daily patients: "+hospital6.dailyPatients);
System.out.println("Hospital type: "+hospital6.hospitalType);
System.out.println("Opening time: "+hospital6.openingTime);
System.out.println("Closing time: "+hospital6.closingTime);

Hospital hospital7 = new Hospital();

System.out.println("Hospital name: "+hospital7.name);
System.out.println("Hospital location: "+hospital7.location);
System.out.println("Hospital city: "+hospital7.city);
System.out.println("Hospital state: "+hospital7.state);
System.out.println("Hospital country: "+hospital7.country);
System.out.println("Number of doctors: "+hospital7.numberOfDoctors);
System.out.println("Number of nurses: "+hospital7.numberOfNurses);
System.out.println("Number of beds: "+hospital7.numberOfBeds);
System.out.println("Emergency service: "+hospital7.emergencyService);
System.out.println("Ambulance service: "+hospital7.ambulanceService);
System.out.println("ICU available: "+hospital7.icuAvailable);
System.out.println("Pharmacy available: "+hospital7.pharmacyAvailable);
System.out.println("Blood bank: "+hospital7.bloodBank);
System.out.println("Surgery facility: "+hospital7.surgeryFacility);
System.out.println("Online appointment: "+hospital7.onlineAppointment);
System.out.println("Insurance accepted: "+hospital7.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital7.cafeteriaAvailable);
System.out.println("Parking available: "+hospital7.parkingAvailable);
System.out.println("Wifi available: "+hospital7.wifiAvailable);
System.out.println("Lab services: "+hospital7.labServices);
System.out.println("Radiology department: "+hospital7.radiologyDepartment);
System.out.println("Daily patients: "+hospital7.dailyPatients);
System.out.println("Hospital type: "+hospital7.hospitalType);
System.out.println("Opening time: "+hospital7.openingTime);
System.out.println("Closing time: "+hospital7.closingTime);

hospital7.name="Aster Hospital";
hospital7.location="JP Nagar";
hospital7.city="Bangalore";
hospital7.state="Karnataka";
hospital7.country="India";
hospital7.numberOfDoctors=95;
hospital7.numberOfNurses=160;
hospital7.numberOfBeds=420;
hospital7.emergencyService=true;
hospital7.ambulanceService=true;
hospital7.icuAvailable=true;
hospital7.pharmacyAvailable=true;
hospital7.bloodBank=true;
hospital7.surgeryFacility=true;
hospital7.onlineAppointment=true;
hospital7.insuranceAccepted=true;
hospital7.cafeteriaAvailable=true;
hospital7.parkingAvailable=true;
hospital7.wifiAvailable=true;
hospital7.labServices=true;
hospital7.radiologyDepartment=true;
hospital7.dailyPatients=520;
hospital7.hospitalType="Private";
hospital7.openingTime="24 Hours";
hospital7.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital7.name);
System.out.println("Hospital location: "+hospital7.location);
System.out.println("Hospital city: "+hospital7.city);
System.out.println("Hospital state: "+hospital7.state);
System.out.println("Hospital country: "+hospital7.country);
System.out.println("Number of doctors: "+hospital7.numberOfDoctors);
System.out.println("Number of nurses: "+hospital7.numberOfNurses);
System.out.println("Number of beds: "+hospital7.numberOfBeds);
System.out.println("Emergency service: "+hospital7.emergencyService);
System.out.println("Ambulance service: "+hospital7.ambulanceService);
System.out.println("ICU available: "+hospital7.icuAvailable);
System.out.println("Pharmacy available: "+hospital7.pharmacyAvailable);
System.out.println("Blood bank: "+hospital7.bloodBank);
System.out.println("Surgery facility: "+hospital7.surgeryFacility);
System.out.println("Online appointment: "+hospital7.onlineAppointment);
System.out.println("Insurance accepted: "+hospital7.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital7.cafeteriaAvailable);
System.out.println("Parking available: "+hospital7.parkingAvailable);
System.out.println("Wifi available: "+hospital7.wifiAvailable);
System.out.println("Lab services: "+hospital7.labServices);
System.out.println("Radiology department: "+hospital7.radiologyDepartment);
System.out.println("Daily patients: "+hospital7.dailyPatients);
System.out.println("Hospital type: "+hospital7.hospitalType);
System.out.println("Opening time: "+hospital7.openingTime);
System.out.println("Closing time: "+hospital7.closingTime);

Hospital hospital8 = new Hospital();

System.out.println("Hospital name: "+hospital8.name);
System.out.println("Hospital location: "+hospital8.location);
System.out.println("Hospital city: "+hospital8.city);
System.out.println("Hospital state: "+hospital8.state);
System.out.println("Hospital country: "+hospital8.country);
System.out.println("Number of doctors: "+hospital8.numberOfDoctors);
System.out.println("Number of nurses: "+hospital8.numberOfNurses);
System.out.println("Number of beds: "+hospital8.numberOfBeds);
System.out.println("Emergency service: "+hospital8.emergencyService);
System.out.println("Ambulance service: "+hospital8.ambulanceService);
System.out.println("ICU available: "+hospital8.icuAvailable);
System.out.println("Pharmacy available: "+hospital8.pharmacyAvailable);
System.out.println("Blood bank: "+hospital8.bloodBank);
System.out.println("Surgery facility: "+hospital8.surgeryFacility);
System.out.println("Online appointment: "+hospital8.onlineAppointment);
System.out.println("Insurance accepted: "+hospital8.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital8.cafeteriaAvailable);
System.out.println("Parking available: "+hospital8.parkingAvailable);
System.out.println("Wifi available: "+hospital8.wifiAvailable);
System.out.println("Lab services: "+hospital8.labServices);
System.out.println("Radiology department: "+hospital8.radiologyDepartment);
System.out.println("Daily patients: "+hospital8.dailyPatients);
System.out.println("Hospital type: "+hospital8.hospitalType);
System.out.println("Opening time: "+hospital8.openingTime);
System.out.println("Closing time: "+hospital8.closingTime);

hospital8.name="Sakra Hospital";
hospital8.location="Marathahalli";
hospital8.city="Bangalore";
hospital8.state="Karnataka";
hospital8.country="India";
hospital8.numberOfDoctors=75;
hospital8.numberOfNurses=120;
hospital8.numberOfBeds=280;
hospital8.emergencyService=true;
hospital8.ambulanceService=true;
hospital8.icuAvailable=true;
hospital8.pharmacyAvailable=true;
hospital8.bloodBank=true;
hospital8.surgeryFacility=true;
hospital8.onlineAppointment=true;
hospital8.insuranceAccepted=true;
hospital8.cafeteriaAvailable=true;
hospital8.parkingAvailable=true;
hospital8.wifiAvailable=true;
hospital8.labServices=true;
hospital8.radiologyDepartment=true;
hospital8.dailyPatients=400;
hospital8.hospitalType="Private";
hospital8.openingTime="24 Hours";
hospital8.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital8.name);
System.out.println("Hospital location: "+hospital8.location);
System.out.println("Hospital city: "+hospital8.city);
System.out.println("Hospital state: "+hospital8.state);
System.out.println("Hospital country: "+hospital8.country);
System.out.println("Number of doctors: "+hospital8.numberOfDoctors);
System.out.println("Number of nurses: "+hospital8.numberOfNurses);
System.out.println("Number of beds: "+hospital8.numberOfBeds);
System.out.println("Emergency service: "+hospital8.emergencyService);
System.out.println("Ambulance service: "+hospital8.ambulanceService);
System.out.println("ICU available: "+hospital8.icuAvailable);
System.out.println("Pharmacy available: "+hospital8.pharmacyAvailable);
System.out.println("Blood bank: "+hospital8.bloodBank);
System.out.println("Surgery facility: "+hospital8.surgeryFacility);
System.out.println("Online appointment: "+hospital8.onlineAppointment);
System.out.println("Insurance accepted: "+hospital8.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital8.cafeteriaAvailable);
System.out.println("Parking available: "+hospital8.parkingAvailable);
System.out.println("Wifi available: "+hospital8.wifiAvailable);
System.out.println("Lab services: "+hospital8.labServices);
System.out.println("Radiology department: "+hospital8.radiologyDepartment);
System.out.println("Daily patients: "+hospital8.dailyPatients);
System.out.println("Hospital type: "+hospital8.hospitalType);
System.out.println("Opening time: "+hospital8.openingTime);
System.out.println("Closing time: "+hospital8.closingTime);

Hospital hospital9 = new Hospital();

System.out.println("Hospital name: "+hospital9.name);
System.out.println("Hospital location: "+hospital9.location);
System.out.println("Hospital city: "+hospital9.city);
System.out.println("Hospital state: "+hospital9.state);
System.out.println("Hospital country: "+hospital9.country);
System.out.println("Number of doctors: "+hospital9.numberOfDoctors);
System.out.println("Number of nurses: "+hospital9.numberOfNurses);
System.out.println("Number of beds: "+hospital9.numberOfBeds);
System.out.println("Emergency service: "+hospital9.emergencyService);
System.out.println("Ambulance service: "+hospital9.ambulanceService);
System.out.println("ICU available: "+hospital9.icuAvailable);
System.out.println("Pharmacy available: "+hospital9.pharmacyAvailable);
System.out.println("Blood bank: "+hospital9.bloodBank);
System.out.println("Surgery facility: "+hospital9.surgeryFacility);
System.out.println("Online appointment: "+hospital9.onlineAppointment);
System.out.println("Insurance accepted: "+hospital9.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital9.cafeteriaAvailable);
System.out.println("Parking available: "+hospital9.parkingAvailable);
System.out.println("Wifi available: "+hospital9.wifiAvailable);
System.out.println("Lab services: "+hospital9.labServices);
System.out.println("Radiology department: "+hospital9.radiologyDepartment);
System.out.println("Daily patients: "+hospital9.dailyPatients);
System.out.println("Hospital type: "+hospital9.hospitalType);
System.out.println("Opening time: "+hospital9.openingTime);
System.out.println("Closing time: "+hospital9.closingTime);

hospital9.name="Bowring Hospital";
hospital9.location="Shivajinagar";
hospital9.city="Bangalore";
hospital9.state="Karnataka";
hospital9.country="India";
hospital9.numberOfDoctors=70;
hospital9.numberOfNurses=110;
hospital9.numberOfBeds=260;
hospital9.emergencyService=true;
hospital9.ambulanceService=true;
hospital9.icuAvailable=true;
hospital9.pharmacyAvailable=true;
hospital9.bloodBank=true;
hospital9.surgeryFacility=true;
hospital9.onlineAppointment=false;
hospital9.insuranceAccepted=true;
hospital9.cafeteriaAvailable=true;
hospital9.parkingAvailable=true;
hospital9.wifiAvailable=false;
hospital9.labServices=true;
hospital9.radiologyDepartment=true;
hospital9.dailyPatients=380;
hospital9.hospitalType="Government";
hospital9.openingTime="24 Hours";
hospital9.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital9.name);
System.out.println("Hospital location: "+hospital9.location);
System.out.println("Hospital city: "+hospital9.city);
System.out.println("Hospital state: "+hospital9.state);
System.out.println("Hospital country: "+hospital9.country);
System.out.println("Number of doctors: "+hospital9.numberOfDoctors);
System.out.println("Number of nurses: "+hospital9.numberOfNurses);
System.out.println("Number of beds: "+hospital9.numberOfBeds);
System.out.println("Emergency service: "+hospital9.emergencyService);
System.out.println("Ambulance service: "+hospital9.ambulanceService);
System.out.println("ICU available: "+hospital9.icuAvailable);
System.out.println("Pharmacy available: "+hospital9.pharmacyAvailable);
System.out.println("Blood bank: "+hospital9.bloodBank);
System.out.println("Surgery facility: "+hospital9.surgeryFacility);
System.out.println("Online appointment: "+hospital9.onlineAppointment);
System.out.println("Insurance accepted: "+hospital9.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital9.cafeteriaAvailable);
System.out.println("Parking available: "+hospital9.parkingAvailable);
System.out.println("Wifi available: "+hospital9.wifiAvailable);
System.out.println("Lab services: "+hospital9.labServices);
System.out.println("Radiology department: "+hospital9.radiologyDepartment);
System.out.println("Daily patients: "+hospital9.dailyPatients);
System.out.println("Hospital type: "+hospital9.hospitalType);
System.out.println("Opening time: "+hospital9.openingTime);
System.out.println("Closing time: "+hospital9.closingTime);

Hospital hospital10 = new Hospital();

System.out.println("Hospital name: "+hospital10.name);
System.out.println("Hospital location: "+hospital10.location);
System.out.println("Hospital city: "+hospital10.city);
System.out.println("Hospital state: "+hospital10.state);
System.out.println("Hospital country: "+hospital10.country);
System.out.println("Number of doctors: "+hospital10.numberOfDoctors);
System.out.println("Number of nurses: "+hospital10.numberOfNurses);
System.out.println("Number of beds: "+hospital10.numberOfBeds);
System.out.println("Emergency service: "+hospital10.emergencyService);
System.out.println("Ambulance service: "+hospital10.ambulanceService);
System.out.println("ICU available: "+hospital10.icuAvailable);
System.out.println("Pharmacy available: "+hospital10.pharmacyAvailable);
System.out.println("Blood bank: "+hospital10.bloodBank);
System.out.println("Surgery facility: "+hospital10.surgeryFacility);
System.out.println("Online appointment: "+hospital10.onlineAppointment);
System.out.println("Insurance accepted: "+hospital10.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital10.cafeteriaAvailable);
System.out.println("Parking available: "+hospital10.parkingAvailable);
System.out.println("Wifi available: "+hospital10.wifiAvailable);
System.out.println("Lab services: "+hospital10.labServices);
System.out.println("Radiology department: "+hospital10.radiologyDepartment);
System.out.println("Daily patients: "+hospital10.dailyPatients);
System.out.println("Hospital type: "+hospital10.hospitalType);
System.out.println("Opening time: "+hospital10.openingTime);
System.out.println("Closing time: "+hospital10.closingTime);

hospital10.name="St Johns Hospital";
hospital10.location="Koramangala";
hospital10.city="Bangalore";
hospital10.state="Karnataka";
hospital10.country="India";
hospital10.numberOfDoctors=105;
hospital10.numberOfNurses=180;
hospital10.numberOfBeds=470;
hospital10.emergencyService=true;
hospital10.ambulanceService=true;
hospital10.icuAvailable=true;
hospital10.pharmacyAvailable=true;
hospital10.bloodBank=true;
hospital10.surgeryFacility=true;
hospital10.onlineAppointment=true;
hospital10.insuranceAccepted=true;
hospital10.cafeteriaAvailable=true;
hospital10.parkingAvailable=true;
hospital10.wifiAvailable=true;
hospital10.labServices=true;
hospital10.radiologyDepartment=true;
hospital10.dailyPatients=680;
hospital10.hospitalType="Private";
hospital10.openingTime="24 Hours";
hospital10.closingTime="24 Hours";

System.out.println("Hospital name: "+hospital10.name);
System.out.println("Hospital location: "+hospital10.location);
System.out.println("Hospital city: "+hospital10.city);
System.out.println("Hospital state: "+hospital10.state);
System.out.println("Hospital country: "+hospital10.country);
System.out.println("Number of doctors: "+hospital10.numberOfDoctors);
System.out.println("Number of nurses: "+hospital10.numberOfNurses);
System.out.println("Number of beds: "+hospital10.numberOfBeds);
System.out.println("Emergency service: "+hospital10.emergencyService);
System.out.println("Ambulance service: "+hospital10.ambulanceService);
System.out.println("ICU available: "+hospital10.icuAvailable);
System.out.println("Pharmacy available: "+hospital10.pharmacyAvailable);
System.out.println("Blood bank: "+hospital10.bloodBank);
System.out.println("Surgery facility: "+hospital10.surgeryFacility);
System.out.println("Online appointment: "+hospital10.onlineAppointment);
System.out.println("Insurance accepted: "+hospital10.insuranceAccepted);
System.out.println("Cafeteria available: "+hospital10.cafeteriaAvailable);
System.out.println("Parking available: "+hospital10.parkingAvailable);
System.out.println("Wifi available: "+hospital10.wifiAvailable);
System.out.println("Lab services: "+hospital10.labServices);
System.out.println("Radiology department: "+hospital10.radiologyDepartment);
System.out.println("Daily patients: "+hospital10.dailyPatients);
System.out.println("Hospital type: "+hospital10.hospitalType);
System.out.println("Opening time: "+hospital10.openingTime);
System.out.println("Closing time: "+hospital10.closingTime);

}

}