class HotelRunner{

public static void main(String[] hotelinfo){


Hotel hotel1 = new Hotel();

System.out.println("Hotel name: "+hotel1.name);
System.out.println("Hotel location: "+hotel1.location);
System.out.println("Hotel city: "+hotel1.city);
System.out.println("Hotel state: "+hotel1.state);
System.out.println("Hotel country: "+hotel1.country);
System.out.println("Number of rooms: "+hotel1.numberOfRooms);
System.out.println("Number of floors: "+hotel1.numberOfFloors);
System.out.println("Restaurant available: "+hotel1.restaurant);
System.out.println("Swimming pool: "+hotel1.swimmingPool);
System.out.println("Gym available: "+hotel1.gymAvailable);
System.out.println("Spa available: "+hotel1.spaAvailable);
System.out.println("Wifi available: "+hotel1.wifiAvailable);
System.out.println("Parking available: "+hotel1.parkingAvailable);
System.out.println("Laundry service: "+hotel1.laundryService);
System.out.println("Room service: "+hotel1.roomService);
System.out.println("Conference hall: "+hotel1.conferenceHall);
System.out.println("Bar available: "+hotel1.barAvailable);
System.out.println("Airport pickup: "+hotel1.airportPickup);
System.out.println("Travel desk: "+hotel1.travelDesk);
System.out.println("Security system: "+hotel1.securitySystem);
System.out.println("CCTV available: "+hotel1.cctvAvailable);
System.out.println("Pet friendly: "+hotel1.petFriendly);
System.out.println("Wheelchair access: "+hotel1.wheelchairAccess);
System.out.println("Check in time: "+hotel1.checkInTime);
System.out.println("Check out time: "+hotel1.checkOutTime);
System.out.println("Room price: "+hotel1.roomPrice);



hotel1.name="Taj Hotel";
hotel1.location="MG Road";
hotel1.city="Bangalore";
hotel1.state="Karnataka";
hotel1.country="India";
hotel1.numberOfRooms=200;
hotel1.numberOfFloors=10;
hotel1.restaurant=true;
hotel1.swimmingPool=true;
hotel1.gymAvailable=true;
hotel1.spaAvailable=true;
hotel1.wifiAvailable=true;
hotel1.parkingAvailable=true;
hotel1.laundryService=true;
hotel1.roomService=true;
hotel1.conferenceHall=true;
hotel1.barAvailable=true;
hotel1.airportPickup=true;
hotel1.travelDesk=true;
hotel1.securitySystem=true;
hotel1.cctvAvailable=true;
hotel1.petFriendly=false;
hotel1.wheelchairAccess=true;
hotel1.checkInTime="12:00 PM";
hotel1.checkOutTime="11:00 AM";
hotel1.roomPrice=7500;

System.out.println("Hotel name: "+hotel1.name);
System.out.println("Hotel location: "+hotel1.location);
System.out.println("Hotel city: "+hotel1.city);
System.out.println("Hotel state: "+hotel1.state);
System.out.println("Hotel country: "+hotel1.country);
System.out.println("Number of rooms: "+hotel1.numberOfRooms);
System.out.println("Number of floors: "+hotel1.numberOfFloors);
System.out.println("Restaurant available: "+hotel1.restaurant);
System.out.println("Swimming pool: "+hotel1.swimmingPool);
System.out.println("Gym available: "+hotel1.gymAvailable);
System.out.println("Spa available: "+hotel1.spaAvailable);
System.out.println("Wifi available: "+hotel1.wifiAvailable);
System.out.println("Parking available: "+hotel1.parkingAvailable);
System.out.println("Laundry service: "+hotel1.laundryService);
System.out.println("Room service: "+hotel1.roomService);
System.out.println("Conference hall: "+hotel1.conferenceHall);
System.out.println("Bar available: "+hotel1.barAvailable);
System.out.println("Airport pickup: "+hotel1.airportPickup);
System.out.println("Travel desk: "+hotel1.travelDesk);
System.out.println("Security system: "+hotel1.securitySystem);
System.out.println("CCTV available: "+hotel1.cctvAvailable);
System.out.println("Pet friendly: "+hotel1.petFriendly);
System.out.println("Wheelchair access: "+hotel1.wheelchairAccess);
System.out.println("Check in time: "+hotel1.checkInTime);
System.out.println("Check out time: "+hotel1.checkOutTime);
System.out.println("Room price: "+hotel1.roomPrice);



Hotel hotel2 = new Hotel();

System.out.println("Hotel name: "+hotel2.name);
System.out.println("Hotel location: "+hotel2.location);
System.out.println("Hotel city: "+hotel2.city);
System.out.println("Hotel state: "+hotel2.state);
System.out.println("Hotel country: "+hotel2.country);
System.out.println("Number of rooms: "+hotel2.numberOfRooms);
System.out.println("Number of floors: "+hotel2.numberOfFloors);
System.out.println("Restaurant available: "+hotel2.restaurant);
System.out.println("Swimming pool: "+hotel2.swimmingPool);
System.out.println("Gym available: "+hotel2.gymAvailable);
System.out.println("Spa available: "+hotel2.spaAvailable);
System.out.println("Wifi available: "+hotel2.wifiAvailable);
System.out.println("Parking available: "+hotel2.parkingAvailable);
System.out.println("Laundry service: "+hotel2.laundryService);
System.out.println("Room service: "+hotel2.roomService);
System.out.println("Conference hall: "+hotel2.conferenceHall);
System.out.println("Bar available: "+hotel2.barAvailable);
System.out.println("Airport pickup: "+hotel2.airportPickup);
System.out.println("Travel desk: "+hotel2.travelDesk);
System.out.println("Security system: "+hotel2.securitySystem);
System.out.println("CCTV available: "+hotel2.cctvAvailable);
System.out.println("Pet friendly: "+hotel2.petFriendly);
System.out.println("Wheelchair access: "+hotel2.wheelchairAccess);
System.out.println("Check in time: "+hotel2.checkInTime);
System.out.println("Check out time: "+hotel2.checkOutTime);
System.out.println("Room price: "+hotel2.roomPrice);




hotel2.name="Oberoi Hotel";
hotel2.location="Marine Drive";
hotel2.city="Mumbai";
hotel2.state="Maharashtra";
hotel2.country="India";
hotel2.numberOfRooms=180;
hotel2.numberOfFloors=12;
hotel2.restaurant=true;
hotel2.swimmingPool=true;
hotel2.gymAvailable=true;
hotel2.spaAvailable=true;
hotel2.wifiAvailable=true;
hotel2.parkingAvailable=true;
hotel2.laundryService=true;
hotel2.roomService=true;
hotel2.conferenceHall=true;
hotel2.barAvailable=true;
hotel2.airportPickup=true;
hotel2.travelDesk=true;
hotel2.securitySystem=true;
hotel2.cctvAvailable=true;
hotel2.petFriendly=true;
hotel2.wheelchairAccess=true;
hotel2.checkInTime="1:00 PM";
hotel2.checkOutTime="11:00 AM";
hotel2.roomPrice=8200;

System.out.println("Hotel name: "+hotel2.name);
System.out.println("Hotel location: "+hotel2.location);
System.out.println("Hotel city: "+hotel2.city);
System.out.println("Hotel state: "+hotel2.state);
System.out.println("Hotel country: "+hotel2.country);
System.out.println("Number of rooms: "+hotel2.numberOfRooms);
System.out.println("Number of floors: "+hotel2.numberOfFloors);
System.out.println("Restaurant available: "+hotel2.restaurant);
System.out.println("Swimming pool: "+hotel2.swimmingPool);
System.out.println("Gym available: "+hotel2.gymAvailable);
System.out.println("Spa available: "+hotel2.spaAvailable);
System.out.println("Wifi available: "+hotel2.wifiAvailable);
System.out.println("Parking available: "+hotel2.parkingAvailable);
System.out.println("Laundry service: "+hotel2.laundryService);
System.out.println("Room service: "+hotel2.roomService);
System.out.println("Conference hall: "+hotel2.conferenceHall);
System.out.println("Bar available: "+hotel2.barAvailable);
System.out.println("Airport pickup: "+hotel2.airportPickup);
System.out.println("Travel desk: "+hotel2.travelDesk);
System.out.println("Security system: "+hotel2.securitySystem);
System.out.println("CCTV available: "+hotel2.cctvAvailable);
System.out.println("Pet friendly: "+hotel2.petFriendly);
System.out.println("Wheelchair access: "+hotel2.wheelchairAccess);
System.out.println("Check in time: "+hotel2.checkInTime);
System.out.println("Check out time: "+hotel2.checkOutTime);
System.out.println("Room price: "+hotel2.roomPrice);



Hotel hotel3 = new Hotel();


System.out.println("Hotel name: "+hotel3.name);
System.out.println("Hotel location: "+hotel3.location);
System.out.println("Hotel city: "+hotel3.city);
System.out.println("Hotel state: "+hotel3.state);
System.out.println("Hotel country: "+hotel3.country);
System.out.println("Number of rooms: "+hotel3.numberOfRooms);
System.out.println("Number of floors: "+hotel3.numberOfFloors);
System.out.println("Restaurant available: "+hotel3.restaurant);
System.out.println("Swimming pool: "+hotel3.swimmingPool);
System.out.println("Gym available: "+hotel3.gymAvailable);
System.out.println("Spa available: "+hotel3.spaAvailable);
System.out.println("Wifi available: "+hotel3.wifiAvailable);
System.out.println("Parking available: "+hotel3.parkingAvailable);
System.out.println("Laundry service: "+hotel3.laundryService);
System.out.println("Room service: "+hotel3.roomService);
System.out.println("Conference hall: "+hotel3.conferenceHall);
System.out.println("Bar available: "+hotel3.barAvailable);
System.out.println("Airport pickup: "+hotel3.airportPickup);
System.out.println("Travel desk: "+hotel3.travelDesk);
System.out.println("Security system: "+hotel3.securitySystem);
System.out.println("CCTV available: "+hotel3.cctvAvailable);
System.out.println("Pet friendly: "+hotel3.petFriendly);
System.out.println("Wheelchair access: "+hotel3.wheelchairAccess);
System.out.println("Check in time: "+hotel3.checkInTime);
System.out.println("Check out time: "+hotel3.checkOutTime);
System.out.println("Room price: "+hotel3.roomPrice);


hotel3.name="Leela Palace";
hotel3.location="Old Airport Road";
hotel3.city="Bangalore";
hotel3.state="Karnataka";
hotel3.country="India";
hotel3.numberOfRooms=250;
hotel3.numberOfFloors=15;
hotel3.restaurant=true;
hotel3.swimmingPool=true;
hotel3.gymAvailable=true;
hotel3.spaAvailable=true;
hotel3.wifiAvailable=true;
hotel3.parkingAvailable=true;
hotel3.laundryService=true;
hotel3.roomService=true;
hotel3.conferenceHall=true;
hotel3.barAvailable=true;
hotel3.airportPickup=true;
hotel3.travelDesk=true;
hotel3.securitySystem=true;
hotel3.cctvAvailable=true;
hotel3.petFriendly=true;
hotel3.wheelchairAccess=true;
hotel3.checkInTime="12:00 PM";
hotel3.checkOutTime="11:00 AM";
hotel3.roomPrice=9000;

System.out.println("Hotel name: "+hotel3.name);
System.out.println("Hotel location: "+hotel3.location);
System.out.println("Hotel city: "+hotel3.city);
System.out.println("Hotel state: "+hotel3.state);
System.out.println("Hotel country: "+hotel3.country);
System.out.println("Number of rooms: "+hotel3.numberOfRooms);
System.out.println("Number of floors: "+hotel3.numberOfFloors);
System.out.println("Restaurant available: "+hotel3.restaurant);
System.out.println("Swimming pool: "+hotel3.swimmingPool);
System.out.println("Gym available: "+hotel3.gymAvailable);
System.out.println("Spa available: "+hotel3.spaAvailable);
System.out.println("Wifi available: "+hotel3.wifiAvailable);
System.out.println("Parking available: "+hotel3.parkingAvailable);
System.out.println("Laundry service: "+hotel3.laundryService);
System.out.println("Room service: "+hotel3.roomService);
System.out.println("Conference hall: "+hotel3.conferenceHall);
System.out.println("Bar available: "+hotel3.barAvailable);
System.out.println("Airport pickup: "+hotel3.airportPickup);
System.out.println("Travel desk: "+hotel3.travelDesk);
System.out.println("Security system: "+hotel3.securitySystem);
System.out.println("CCTV available: "+hotel3.cctvAvailable);
System.out.println("Pet friendly: "+hotel3.petFriendly);
System.out.println("Wheelchair access: "+hotel3.wheelchairAccess);
System.out.println("Check in time: "+hotel3.checkInTime);
System.out.println("Check out time: "+hotel3.checkOutTime);
System.out.println("Room price: "+hotel3.roomPrice);


Hotel hotel4 = new Hotel();

System.out.println("Hotel name: "+hotel4.name);
System.out.println("Hotel location: "+hotel4.location);
System.out.println("Hotel city: "+hotel4.city);
System.out.println("Hotel state: "+hotel4.state);
System.out.println("Hotel country: "+hotel4.country);
System.out.println("Number of rooms: "+hotel4.numberOfRooms);
System.out.println("Number of floors: "+hotel4.numberOfFloors);
System.out.println("Restaurant available: "+hotel4.restaurant);
System.out.println("Swimming pool: "+hotel4.swimmingPool);
System.out.println("Gym available: "+hotel4.gymAvailable);
System.out.println("Spa available: "+hotel4.spaAvailable);
System.out.println("Wifi available: "+hotel4.wifiAvailable);
System.out.println("Parking available: "+hotel4.parkingAvailable);
System.out.println("Laundry service: "+hotel4.laundryService);
System.out.println("Room service: "+hotel4.roomService);
System.out.println("Conference hall: "+hotel4.conferenceHall);
System.out.println("Bar available: "+hotel4.barAvailable);
System.out.println("Airport pickup: "+hotel4.airportPickup);
System.out.println("Travel desk: "+hotel4.travelDesk);
System.out.println("Security system: "+hotel4.securitySystem);
System.out.println("CCTV available: "+hotel4.cctvAvailable);
System.out.println("Pet friendly: "+hotel4.petFriendly);
System.out.println("Wheelchair access: "+hotel4.wheelchairAccess);
System.out.println("Check in time: "+hotel4.checkInTime);
System.out.println("Check out time: "+hotel4.checkOutTime);
System.out.println("Room price: "+hotel4.roomPrice);


hotel4.name="ITC Gardenia";
hotel4.location="Residency Road";
hotel4.city="Bangalore";
hotel4.state="Karnataka";
hotel4.country="India";
hotel4.numberOfRooms=300;
hotel4.numberOfFloors=18;
hotel4.restaurant=true;
hotel4.swimmingPool=true;
hotel4.gymAvailable=true;
hotel4.spaAvailable=true;
hotel4.wifiAvailable=true;
hotel4.parkingAvailable=true;
hotel4.laundryService=true;
hotel4.roomService=true;
hotel4.conferenceHall=true;
hotel4.barAvailable=true;
hotel4.airportPickup=true;
hotel4.travelDesk=true;
hotel4.securitySystem=true;
hotel4.cctvAvailable=true;
hotel4.petFriendly=false;
hotel4.wheelchairAccess=true;
hotel4.checkInTime="1:00 PM";
hotel4.checkOutTime="11:00 AM";
hotel4.roomPrice=8500;

System.out.println("Hotel name: "+hotel4.name);
System.out.println("Hotel location: "+hotel4.location);
System.out.println("Hotel city: "+hotel4.city);
System.out.println("Hotel state: "+hotel4.state);
System.out.println("Hotel country: "+hotel4.country);
System.out.println("Number of rooms: "+hotel4.numberOfRooms);
System.out.println("Number of floors: "+hotel4.numberOfFloors);
System.out.println("Restaurant available: "+hotel4.restaurant);
System.out.println("Swimming pool: "+hotel4.swimmingPool);
System.out.println("Gym available: "+hotel4.gymAvailable);
System.out.println("Spa available: "+hotel4.spaAvailable);
System.out.println("Wifi available: "+hotel4.wifiAvailable);
System.out.println("Parking available: "+hotel4.parkingAvailable);
System.out.println("Laundry service: "+hotel4.laundryService);
System.out.println("Room service: "+hotel4.roomService);
System.out.println("Conference hall: "+hotel4.conferenceHall);
System.out.println("Bar available: "+hotel4.barAvailable);
System.out.println("Airport pickup: "+hotel4.airportPickup);
System.out.println("Travel desk: "+hotel4.travelDesk);
System.out.println("Security system: "+hotel4.securitySystem);
System.out.println("CCTV available: "+hotel4.cctvAvailable);
System.out.println("Pet friendly: "+hotel4.petFriendly);
System.out.println("Wheelchair access: "+hotel4.wheelchairAccess);
System.out.println("Check in time: "+hotel4.checkInTime);
System.out.println("Check out time: "+hotel4.checkOutTime);
System.out.println("Room price: "+hotel4.roomPrice);


Hotel hotel5 = new Hotel();

System.out.println("Hotel name: "+hotel5.name);
System.out.println("Hotel location: "+hotel5.location);
System.out.println("Hotel city: "+hotel5.city);
System.out.println("Hotel state: "+hotel5.state);
System.out.println("Hotel country: "+hotel5.country);
System.out.println("Number of rooms: "+hotel5.numberOfRooms);
System.out.println("Number of floors: "+hotel5.numberOfFloors);
System.out.println("Restaurant available: "+hotel5.restaurant);
System.out.println("Swimming pool: "+hotel5.swimmingPool);
System.out.println("Gym available: "+hotel5.gymAvailable);
System.out.println("Spa available: "+hotel5.spaAvailable);
System.out.println("Wifi available: "+hotel5.wifiAvailable);
System.out.println("Parking available: "+hotel5.parkingAvailable);
System.out.println("Laundry service: "+hotel5.laundryService);
System.out.println("Room service: "+hotel5.roomService);
System.out.println("Conference hall: "+hotel5.conferenceHall);
System.out.println("Bar available: "+hotel5.barAvailable);
System.out.println("Airport pickup: "+hotel5.airportPickup);
System.out.println("Travel desk: "+hotel5.travelDesk);
System.out.println("Security system: "+hotel5.securitySystem);
System.out.println("CCTV available: "+hotel5.cctvAvailable);
System.out.println("Pet friendly: "+hotel5.petFriendly);
System.out.println("Wheelchair access: "+hotel5.wheelchairAccess);
System.out.println("Check in time: "+hotel5.checkInTime);
System.out.println("Check out time: "+hotel5.checkOutTime);
System.out.println("Room price: "+hotel5.roomPrice);



hotel5.name="Radisson Blu";
hotel5.location="Marathahalli";
hotel5.city="Bangalore";
hotel5.state="Karnataka";
hotel5.country="India";
hotel5.numberOfRooms=220;
hotel5.numberOfFloors=12;
hotel5.restaurant=true;
hotel5.swimmingPool=true;
hotel5.gymAvailable=true;
hotel5.spaAvailable=false;
hotel5.wifiAvailable=true;
hotel5.parkingAvailable=true;
hotel5.laundryService=true;
hotel5.roomService=true;
hotel5.conferenceHall=true;
hotel5.barAvailable=true;
hotel5.airportPickup=true;
hotel5.travelDesk=true;
hotel5.securitySystem=true;
hotel5.cctvAvailable=true;
hotel5.petFriendly=true;
hotel5.wheelchairAccess=true;
hotel5.checkInTime="12:00 PM";
hotel5.checkOutTime="10:30 AM";
hotel5.roomPrice=6500;

System.out.println("Hotel name: "+hotel5.name);
System.out.println("Hotel location: "+hotel5.location);
System.out.println("Hotel city: "+hotel5.city);
System.out.println("Hotel state: "+hotel5.state);
System.out.println("Hotel country: "+hotel5.country);
System.out.println("Number of rooms: "+hotel5.numberOfRooms);
System.out.println("Number of floors: "+hotel5.numberOfFloors);
System.out.println("Restaurant available: "+hotel5.restaurant);
System.out.println("Swimming pool: "+hotel5.swimmingPool);
System.out.println("Gym available: "+hotel5.gymAvailable);
System.out.println("Spa available: "+hotel5.spaAvailable);
System.out.println("Wifi available: "+hotel5.wifiAvailable);
System.out.println("Parking available: "+hotel5.parkingAvailable);
System.out.println("Laundry service: "+hotel5.laundryService);
System.out.println("Room service: "+hotel5.roomService);
System.out.println("Conference hall: "+hotel5.conferenceHall);
System.out.println("Bar available: "+hotel5.barAvailable);
System.out.println("Airport pickup: "+hotel5.airportPickup);
System.out.println("Travel desk: "+hotel5.travelDesk);
System.out.println("Security system: "+hotel5.securitySystem);
System.out.println("CCTV available: "+hotel5.cctvAvailable);
System.out.println("Pet friendly: "+hotel5.petFriendly);
System.out.println("Wheelchair access: "+hotel5.wheelchairAccess);
System.out.println("Check in time: "+hotel5.checkInTime);
System.out.println("Check out time: "+hotel5.checkOutTime);
System.out.println("Room price: "+hotel5.roomPrice);


Hotel hotel6 = new Hotel();

System.out.println("Hotel name: "+hotel6.name);
System.out.println("Hotel location: "+hotel6.location);
System.out.println("Hotel city: "+hotel6.city);
System.out.println("Hotel state: "+hotel6.state);
System.out.println("Hotel country: "+hotel6.country);
System.out.println("Number of rooms: "+hotel6.numberOfRooms);
System.out.println("Number of floors: "+hotel6.numberOfFloors);
System.out.println("Restaurant available: "+hotel6.restaurant);
System.out.println("Swimming pool: "+hotel6.swimmingPool);
System.out.println("Gym available: "+hotel6.gymAvailable);
System.out.println("Spa available: "+hotel6.spaAvailable);
System.out.println("Wifi available: "+hotel6.wifiAvailable);
System.out.println("Parking available: "+hotel6.parkingAvailable);
System.out.println("Laundry service: "+hotel6.laundryService);
System.out.println("Room service: "+hotel6.roomService);
System.out.println("Conference hall: "+hotel6.conferenceHall);
System.out.println("Bar available: "+hotel6.barAvailable);
System.out.println("Airport pickup: "+hotel6.airportPickup);
System.out.println("Travel desk: "+hotel6.travelDesk);
System.out.println("Security system: "+hotel6.securitySystem);
System.out.println("CCTV available: "+hotel6.cctvAvailable);
System.out.println("Pet friendly: "+hotel6.petFriendly);
System.out.println("Wheelchair access: "+hotel6.wheelchairAccess);
System.out.println("Check in time: "+hotel6.checkInTime);
System.out.println("Check out time: "+hotel6.checkOutTime);
System.out.println("Room price: "+hotel6.roomPrice);


hotel6.name="Hyatt Regency";
hotel6.location="Hebbal";
hotel6.city="Bangalore";
hotel6.state="Karnataka";
hotel6.country="India";
hotel6.numberOfRooms=270;
hotel6.numberOfFloors=16;
hotel6.restaurant=true;
hotel6.swimmingPool=true;
hotel6.gymAvailable=true;
hotel6.spaAvailable=true;
hotel6.wifiAvailable=true;
hotel6.parkingAvailable=true;
hotel6.laundryService=true;
hotel6.roomService=true;
hotel6.conferenceHall=true;
hotel6.barAvailable=true;
hotel6.airportPickup=true;
hotel6.travelDesk=true;
hotel6.securitySystem=true;
hotel6.cctvAvailable=true;
hotel6.petFriendly=true;
hotel6.wheelchairAccess=true;
hotel6.checkInTime="12:00 PM";
hotel6.checkOutTime="11:00 AM";
hotel6.roomPrice=8800;

System.out.println("Hotel name: "+hotel6.name);
System.out.println("Hotel location: "+hotel6.location);
System.out.println("Hotel city: "+hotel6.city);
System.out.println("Hotel state: "+hotel6.state);
System.out.println("Hotel country: "+hotel6.country);
System.out.println("Number of rooms: "+hotel6.numberOfRooms);
System.out.println("Number of floors: "+hotel6.numberOfFloors);
System.out.println("Restaurant available: "+hotel6.restaurant);
System.out.println("Swimming pool: "+hotel6.swimmingPool);
System.out.println("Gym available: "+hotel6.gymAvailable);
System.out.println("Spa available: "+hotel6.spaAvailable);
System.out.println("Wifi available: "+hotel6.wifiAvailable);
System.out.println("Parking available: "+hotel6.parkingAvailable);
System.out.println("Laundry service: "+hotel6.laundryService);
System.out.println("Room service: "+hotel6.roomService);
System.out.println("Conference hall: "+hotel6.conferenceHall);
System.out.println("Bar available: "+hotel6.barAvailable);
System.out.println("Airport pickup: "+hotel6.airportPickup);
System.out.println("Travel desk: "+hotel6.travelDesk);
System.out.println("Security system: "+hotel6.securitySystem);
System.out.println("CCTV available: "+hotel6.cctvAvailable);
System.out.println("Pet friendly: "+hotel6.petFriendly);
System.out.println("Wheelchair access: "+hotel6.wheelchairAccess);
System.out.println("Check in time: "+hotel6.checkInTime);
System.out.println("Check out time: "+hotel6.checkOutTime);
System.out.println("Room price: "+hotel6.roomPrice);



Hotel hotel7 = new Hotel();

System.out.println("Hotel name: "+hotel7.name);
System.out.println("Hotel location: "+hotel7.location);
System.out.println("Hotel city: "+hotel7.city);
System.out.println("Hotel state: "+hotel7.state);
System.out.println("Hotel country: "+hotel7.country);
System.out.println("Number of rooms: "+hotel7.numberOfRooms);
System.out.println("Number of floors: "+hotel7.numberOfFloors);
System.out.println("Restaurant available: "+hotel7.restaurant);
System.out.println("Swimming pool: "+hotel7.swimmingPool);
System.out.println("Gym available: "+hotel7.gymAvailable);
System.out.println("Spa available: "+hotel7.spaAvailable);
System.out.println("Wifi available: "+hotel7.wifiAvailable);
System.out.println("Parking available: "+hotel7.parkingAvailable);
System.out.println("Laundry service: "+hotel7.laundryService);
System.out.println("Room service: "+hotel7.roomService);
System.out.println("Conference hall: "+hotel7.conferenceHall);
System.out.println("Bar available: "+hotel7.barAvailable);
System.out.println("Airport pickup: "+hotel7.airportPickup);
System.out.println("Travel desk: "+hotel7.travelDesk);
System.out.println("Security system: "+hotel7.securitySystem);
System.out.println("CCTV available: "+hotel7.cctvAvailable);
System.out.println("Pet friendly: "+hotel7.petFriendly);
System.out.println("Wheelchair access: "+hotel7.wheelchairAccess);
System.out.println("Check in time: "+hotel7.checkInTime);
System.out.println("Check out time: "+hotel7.checkOutTime);
System.out.println("Room price: "+hotel7.roomPrice);



hotel7.name="Sheraton Hotel";
hotel7.location="Brigade Road";
hotel7.city="Bangalore";
hotel7.state="Karnataka";
hotel7.country="India";
hotel7.numberOfRooms=210;
hotel7.numberOfFloors=14;
hotel7.restaurant=true;
hotel7.swimmingPool=true;
hotel7.gymAvailable=true;
hotel7.spaAvailable=false;
hotel7.wifiAvailable=true;
hotel7.parkingAvailable=true;
hotel7.laundryService=true;
hotel7.roomService=true;
hotel7.conferenceHall=true;
hotel7.barAvailable=true;
hotel7.airportPickup=true;
hotel7.travelDesk=true;
hotel7.securitySystem=true;
hotel7.cctvAvailable=true;
hotel7.petFriendly=false;
hotel7.wheelchairAccess=true;
hotel7.checkInTime="1:00 PM";
hotel7.checkOutTime="11:30 AM";
hotel7.roomPrice=7200;

System.out.println("Hotel name: "+hotel7.name);
System.out.println("Hotel location: "+hotel7.location);
System.out.println("Hotel city: "+hotel7.city);
System.out.println("Hotel state: "+hotel7.state);
System.out.println("Hotel country: "+hotel7.country);
System.out.println("Number of rooms: "+hotel7.numberOfRooms);
System.out.println("Number of floors: "+hotel7.numberOfFloors);
System.out.println("Restaurant available: "+hotel7.restaurant);
System.out.println("Swimming pool: "+hotel7.swimmingPool);
System.out.println("Gym available: "+hotel7.gymAvailable);
System.out.println("Spa available: "+hotel7.spaAvailable);
System.out.println("Wifi available: "+hotel7.wifiAvailable);
System.out.println("Parking available: "+hotel7.parkingAvailable);
System.out.println("Laundry service: "+hotel7.laundryService);
System.out.println("Room service: "+hotel7.roomService);
System.out.println("Conference hall: "+hotel7.conferenceHall);
System.out.println("Bar available: "+hotel7.barAvailable);
System.out.println("Airport pickup: "+hotel7.airportPickup);
System.out.println("Travel desk: "+hotel7.travelDesk);
System.out.println("Security system: "+hotel7.securitySystem);
System.out.println("CCTV available: "+hotel7.cctvAvailable);
System.out.println("Pet friendly: "+hotel7.petFriendly);
System.out.println("Wheelchair access: "+hotel7.wheelchairAccess);
System.out.println("Check in time: "+hotel7.checkInTime);
System.out.println("Check out time: "+hotel7.checkOutTime);
System.out.println("Room price: "+hotel7.roomPrice);



Hotel hotel8 = new Hotel();

System.out.println("Hotel name: "+hotel8.name);
System.out.println("Hotel location: "+hotel8.location);
System.out.println("Hotel city: "+hotel8.city);
System.out.println("Hotel state: "+hotel8.state);
System.out.println("Hotel country: "+hotel8.country);
System.out.println("Number of rooms: "+hotel8.numberOfRooms);
System.out.println("Number of floors: "+hotel8.numberOfFloors);
System.out.println("Restaurant available: "+hotel8.restaurant);
System.out.println("Swimming pool: "+hotel8.swimmingPool);
System.out.println("Gym available: "+hotel8.gymAvailable);
System.out.println("Spa available: "+hotel8.spaAvailable);
System.out.println("Wifi available: "+hotel8.wifiAvailable);
System.out.println("Parking available: "+hotel8.parkingAvailable);
System.out.println("Laundry service: "+hotel8.laundryService);
System.out.println("Room service: "+hotel8.roomService);
System.out.println("Conference hall: "+hotel8.conferenceHall);
System.out.println("Bar available: "+hotel8.barAvailable);
System.out.println("Airport pickup: "+hotel8.airportPickup);
System.out.println("Travel desk: "+hotel8.travelDesk);
System.out.println("Security system: "+hotel8.securitySystem);
System.out.println("CCTV available: "+hotel8.cctvAvailable);
System.out.println("Pet friendly: "+hotel8.petFriendly);
System.out.println("Wheelchair access: "+hotel8.wheelchairAccess);
System.out.println("Check in time: "+hotel8.checkInTime);
System.out.println("Check out time: "+hotel8.checkOutTime);
System.out.println("Room price: "+hotel8.roomPrice);

hotel8.name="Holiday Inn";
hotel8.location="Whitefield";
hotel8.city="Bangalore";
hotel8.state="Karnataka";
hotel8.country="India";
hotel8.numberOfRooms=190;
hotel8.numberOfFloors=11;
hotel8.restaurant=true;
hotel8.swimmingPool=true;
hotel8.gymAvailable=true;
hotel8.spaAvailable=false;
hotel8.wifiAvailable=true;
hotel8.parkingAvailable=true;
hotel8.laundryService=true;
hotel8.roomService=true;
hotel8.conferenceHall=true;
hotel8.barAvailable=false;
hotel8.airportPickup=true;
hotel8.travelDesk=true;
hotel8.securitySystem=true;
hotel8.cctvAvailable=true;
hotel8.petFriendly=true;
hotel8.wheelchairAccess=true;
hotel8.checkInTime="12:30 PM";
hotel8.checkOutTime="11:00 AM";
hotel8.roomPrice=6000;

System.out.println("Hotel name: "+hotel8.name);
System.out.println("Hotel location: "+hotel8.location);
System.out.println("Hotel city: "+hotel8.city);
System.out.println("Hotel state: "+hotel8.state);
System.out.println("Hotel country: "+hotel8.country);
System.out.println("Number of rooms: "+hotel8.numberOfRooms);
System.out.println("Number of floors: "+hotel8.numberOfFloors);
System.out.println("Restaurant available: "+hotel8.restaurant);
System.out.println("Swimming pool: "+hotel8.swimmingPool);
System.out.println("Gym available: "+hotel8.gymAvailable);
System.out.println("Spa available: "+hotel8.spaAvailable);
System.out.println("Wifi available: "+hotel8.wifiAvailable);
System.out.println("Parking available: "+hotel8.parkingAvailable);
System.out.println("Laundry service: "+hotel8.laundryService);
System.out.println("Room service: "+hotel8.roomService);
System.out.println("Conference hall: "+hotel8.conferenceHall);
System.out.println("Bar available: "+hotel8.barAvailable);
System.out.println("Airport pickup: "+hotel8.airportPickup);
System.out.println("Travel desk: "+hotel8.travelDesk);
System.out.println("Security system: "+hotel8.securitySystem);
System.out.println("CCTV available: "+hotel8.cctvAvailable);
System.out.println("Pet friendly: "+hotel8.petFriendly);
System.out.println("Wheelchair access: "+hotel8.wheelchairAccess);
System.out.println("Check in time: "+hotel8.checkInTime);
System.out.println("Check out time: "+hotel8.checkOutTime);
System.out.println("Room price: "+hotel8.roomPrice);


Hotel hotel9 = new Hotel();

System.out.println("Hotel name: "+hotel9.name);
System.out.println("Hotel location: "+hotel9.location);
System.out.println("Hotel city: "+hotel9.city);
System.out.println("Hotel state: "+hotel9.state);
System.out.println("Hotel country: "+hotel9.country);
System.out.println("Number of rooms: "+hotel9.numberOfRooms);
System.out.println("Number of floors: "+hotel9.numberOfFloors);
System.out.println("Restaurant available: "+hotel9.restaurant);
System.out.println("Swimming pool: "+hotel9.swimmingPool);
System.out.println("Gym available: "+hotel9.gymAvailable);
System.out.println("Spa available: "+hotel9.spaAvailable);
System.out.println("Wifi available: "+hotel9.wifiAvailable);
System.out.println("Parking available: "+hotel9.parkingAvailable);
System.out.println("Laundry service: "+hotel9.laundryService);
System.out.println("Room service: "+hotel9.roomService);
System.out.println("Conference hall: "+hotel9.conferenceHall);
System.out.println("Bar available: "+hotel9.barAvailable);
System.out.println("Airport pickup: "+hotel9.airportPickup);
System.out.println("Travel desk: "+hotel9.travelDesk);
System.out.println("Security system: "+hotel9.securitySystem);
System.out.println("CCTV available: "+hotel9.cctvAvailable);
System.out.println("Pet friendly: "+hotel9.petFriendly);
System.out.println("Wheelchair access: "+hotel9.wheelchairAccess);
System.out.println("Check in time: "+hotel9.checkInTime);
System.out.println("Check out time: "+hotel9.checkOutTime);
System.out.println("Room price: "+hotel9.roomPrice);



hotel9.name="Marriott Hotel";
hotel9.location="Outer Ring Road";
hotel9.city="Bangalore";
hotel9.state="Karnataka";
hotel9.country="India";
hotel9.numberOfRooms=260;
hotel9.numberOfFloors=17;
hotel9.restaurant=true;
hotel9.swimmingPool=true;
hotel9.gymAvailable=true;
hotel9.spaAvailable=true;
hotel9.wifiAvailable=true;
hotel9.parkingAvailable=true;
hotel9.laundryService=true;
hotel9.roomService=true;
hotel9.conferenceHall=true;
hotel9.barAvailable=true;
hotel9.airportPickup=true;
hotel9.travelDesk=true;
hotel9.securitySystem=true;
hotel9.cctvAvailable=true;
hotel9.petFriendly=true;
hotel9.wheelchairAccess=true;
hotel9.checkInTime="12:00 PM";
hotel9.checkOutTime="11:00 AM";
hotel9.roomPrice=9200;

System.out.println("Hotel name: "+hotel9.name);
System.out.println("Hotel location: "+hotel9.location);
System.out.println("Hotel city: "+hotel9.city);
System.out.println("Hotel state: "+hotel9.state);
System.out.println("Hotel country: "+hotel9.country);
System.out.println("Number of rooms: "+hotel9.numberOfRooms);
System.out.println("Number of floors: "+hotel9.numberOfFloors);
System.out.println("Restaurant available: "+hotel9.restaurant);
System.out.println("Swimming pool: "+hotel9.swimmingPool);
System.out.println("Gym available: "+hotel9.gymAvailable);
System.out.println("Spa available: "+hotel9.spaAvailable);
System.out.println("Wifi available: "+hotel9.wifiAvailable);
System.out.println("Parking available: "+hotel9.parkingAvailable);
System.out.println("Laundry service: "+hotel9.laundryService);
System.out.println("Room service: "+hotel9.roomService);
System.out.println("Conference hall: "+hotel9.conferenceHall);
System.out.println("Bar available: "+hotel9.barAvailable);
System.out.println("Airport pickup: "+hotel9.airportPickup);
System.out.println("Travel desk: "+hotel9.travelDesk);
System.out.println("Security system: "+hotel9.securitySystem);
System.out.println("CCTV available: "+hotel9.cctvAvailable);
System.out.println("Pet friendly: "+hotel9.petFriendly);
System.out.println("Wheelchair access: "+hotel9.wheelchairAccess);
System.out.println("Check in time: "+hotel9.checkInTime);
System.out.println("Check out time: "+hotel9.checkOutTime);
System.out.println("Room price: "+hotel9.roomPrice);


Hotel hotel10 = new Hotel();

hotel10.name="Park Plaza";
hotel10.location="Yelahanka";
hotel10.city="Bangalore";
hotel10.state="Karnataka";
hotel10.country="India";
hotel10.numberOfRooms=150;
hotel10.numberOfFloors=9;
hotel10.restaurant=true;
hotel10.swimmingPool=false;
hotel10.gymAvailable=true;
hotel10.spaAvailable=false;
hotel10.wifiAvailable=true;
hotel10.parkingAvailable=true;
hotel10.laundryService=true;
hotel10.roomService=true;
hotel10.conferenceHall=true;
hotel10.barAvailable=false;
hotel10.airportPickup=true;
hotel10.travelDesk=true;
hotel10.securitySystem=true;
hotel10.cctvAvailable=true;
hotel10.petFriendly=false;
hotel10.wheelchairAccess=true;
hotel10.checkInTime="1:00 PM";
hotel10.checkOutTime="11:00 AM";
hotel10.roomPrice=5200;

System.out.println("Hotel name: "+hotel10.name);
System.out.println("Hotel location: "+hotel10.location);
System.out.println("Hotel city: "+hotel10.city);
System.out.println("Hotel state: "+hotel10.state);
System.out.println("Hotel country: "+hotel10.country);
System.out.println("Number of rooms: "+hotel10.numberOfRooms);
System.out.println("Number of floors: "+hotel10.numberOfFloors);
System.out.println("Restaurant available: "+hotel10.restaurant);
System.out.println("Swimming pool: "+hotel10.swimmingPool);
System.out.println("Gym available: "+hotel10.gymAvailable);
System.out.println("Spa available: "+hotel10.spaAvailable);
System.out.println("Wifi available: "+hotel10.wifiAvailable);
System.out.println("Parking available: "+hotel10.parkingAvailable);
System.out.println("Laundry service: "+hotel10.laundryService);
System.out.println("Room service: "+hotel10.roomService);
System.out.println("Conference hall: "+hotel10.conferenceHall);
System.out.println("Bar available: "+hotel10.barAvailable);
System.out.println("Airport pickup: "+hotel10.airportPickup);
System.out.println("Travel desk: "+hotel10.travelDesk);
System.out.println("Security system: "+hotel10.securitySystem);
System.out.println("CCTV available: "+hotel10.cctvAvailable);
System.out.println("Pet friendly: "+hotel10.petFriendly);
System.out.println("Wheelchair access: "+hotel10.wheelchairAccess);
System.out.println("Check in time: "+hotel10.checkInTime);
System.out.println("Check out time: "+hotel10.checkOutTime);
System.out.println("Room price: "+hotel10.roomPrice);



}


}