class MarketExecutor {

public static void main(String[] marketinfo) {

Market market1 = new Market();

System.out.println("Market name: "+market1.name);
System.out.println("Market location: "+market1.location);
System.out.println("Market city: "+market1.city);
System.out.println("Market state: "+market1.state);
System.out.println("Market country: "+market1.country);
System.out.println("Number of shops: "+market1.numberOfShops);
System.out.println("Parking available: "+market1.parkingAvailable);
System.out.println("Food stalls: "+market1.foodStalls);
System.out.println("Clothing shops: "+market1.clothingShops);
System.out.println("Vegetable shops: "+market1.vegetableShops);
System.out.println("Fruit shops: "+market1.fruitShops);
System.out.println("Electronics shops: "+market1.electronicsShops);
System.out.println("Jewelry shops: "+market1.jewelryShops);
System.out.println("ATM available: "+market1.atmAvailable);
System.out.println("Security system: "+market1.securitySystem);
System.out.println("CCTV available: "+market1.cctvAvailable);
System.out.println("Public transport access: "+market1.publicTransportAccess);
System.out.println("Restrooms: "+market1.restrooms);
System.out.println("Wifi available: "+market1.wifiAvailable);
System.out.println("Delivery service: "+market1.deliveryService);
System.out.println("Wholesale market: "+market1.wholesaleMarket);
System.out.println("Retail market: "+market1.retailMarket);
System.out.println("Night market: "+market1.nightMarket);
System.out.println("Opening time: "+market1.openingTime);
System.out.println("Closing time: "+market1.closingTime);
System.out.println("Entry fee: "+market1.entryFee);

market1.name="KR Market";
market1.location="Chickpet";
market1.city="Bangalore";
market1.state="Karnataka";
market1.country="India";
market1.numberOfShops=500;
market1.parkingAvailable=true;
market1.foodStalls=true;
market1.clothingShops=true;
market1.vegetableShops=true;
market1.fruitShops=true;
market1.electronicsShops=false;
market1.jewelryShops=false;
market1.atmAvailable=true;
market1.securitySystem=true;
market1.cctvAvailable=true;
market1.publicTransportAccess=true;
market1.restrooms=true;
market1.wifiAvailable=false;
market1.deliveryService=true;
market1.wholesaleMarket=true;
market1.retailMarket=true;
market1.nightMarket=false;
market1.openingTime="6:00 AM";
market1.closingTime="9:00 PM";
market1.entryFee=0;

System.out.println("Market name: "+market1.name);
System.out.println("Market location: "+market1.location);
System.out.println("Market city: "+market1.city);
System.out.println("Market state: "+market1.state);
System.out.println("Market country: "+market1.country);
System.out.println("Number of shops: "+market1.numberOfShops);
System.out.println("Parking available: "+market1.parkingAvailable);
System.out.println("Food stalls: "+market1.foodStalls);
System.out.println("Clothing shops: "+market1.clothingShops);
System.out.println("Vegetable shops: "+market1.vegetableShops);
System.out.println("Fruit shops: "+market1.fruitShops);
System.out.println("Electronics shops: "+market1.electronicsShops);
System.out.println("Jewelry shops: "+market1.jewelryShops);
System.out.println("ATM available: "+market1.atmAvailable);
System.out.println("Security system: "+market1.securitySystem);
System.out.println("CCTV available: "+market1.cctvAvailable);
System.out.println("Public transport access: "+market1.publicTransportAccess);
System.out.println("Restrooms: "+market1.restrooms);
System.out.println("Wifi available: "+market1.wifiAvailable);
System.out.println("Delivery service: "+market1.deliveryService);
System.out.println("Wholesale market: "+market1.wholesaleMarket);
System.out.println("Retail market: "+market1.retailMarket);
System.out.println("Night market: "+market1.nightMarket);
System.out.println("Opening time: "+market1.openingTime);
System.out.println("Closing time: "+market1.closingTime);
System.out.println("Entry fee: "+market1.entryFee);

Market market2 = new Market();

System.out.println("Market name: "+market2.name);
System.out.println("Market location: "+market2.location);
System.out.println("Market city: "+market2.city);
System.out.println("Market state: "+market2.state);
System.out.println("Market country: "+market2.country);
System.out.println("Number of shops: "+market2.numberOfShops);
System.out.println("Parking available: "+market2.parkingAvailable);
System.out.println("Food stalls: "+market2.foodStalls);
System.out.println("Clothing shops: "+market2.clothingShops);
System.out.println("Vegetable shops: "+market2.vegetableShops);
System.out.println("Fruit shops: "+market2.fruitShops);
System.out.println("Electronics shops: "+market2.electronicsShops);
System.out.println("Jewelry shops: "+market2.jewelryShops);
System.out.println("ATM available: "+market2.atmAvailable);
System.out.println("Security system: "+market2.securitySystem);
System.out.println("CCTV available: "+market2.cctvAvailable);
System.out.println("Public transport access: "+market2.publicTransportAccess);
System.out.println("Restrooms: "+market2.restrooms);
System.out.println("Wifi available: "+market2.wifiAvailable);
System.out.println("Delivery service: "+market2.deliveryService);
System.out.println("Wholesale market: "+market2.wholesaleMarket);
System.out.println("Retail market: "+market2.retailMarket);
System.out.println("Night market: "+market2.nightMarket);
System.out.println("Opening time: "+market2.openingTime);
System.out.println("Closing time: "+market2.closingTime);
System.out.println("Entry fee: "+market2.entryFee);

market2.name="Chandni Chowk Market";
market2.location="Old Delhi";
market2.city="Delhi";
market2.state="Delhi";
market2.country="India";
market2.numberOfShops=1000;
market2.parkingAvailable=true;
market2.foodStalls=true;
market2.clothingShops=true;
market2.vegetableShops=true;
market2.fruitShops=true;
market2.electronicsShops=true;
market2.jewelryShops=true;
market2.atmAvailable=true;
market2.securitySystem=true;
market2.cctvAvailable=true;
market2.publicTransportAccess=true;
market2.restrooms=true;
market2.wifiAvailable=true;
market2.deliveryService=true;
market2.wholesaleMarket=true;
market2.retailMarket=true;
market2.nightMarket=true;
market2.openingTime="7:00 AM";
market2.closingTime="10:00 PM";
market2.entryFee=0;

System.out.println("Market name: "+market2.name);
System.out.println("Market location: "+market2.location);
System.out.println("Market city: "+market2.city);
System.out.println("Market state: "+market2.state);
System.out.println("Market country: "+market2.country);
System.out.println("Number of shops: "+market2.numberOfShops);
System.out.println("Parking available: "+market2.parkingAvailable);
System.out.println("Food stalls: "+market2.foodStalls);
System.out.println("Clothing shops: "+market2.clothingShops);
System.out.println("Vegetable shops: "+market2.vegetableShops);
System.out.println("Fruit shops: "+market2.fruitShops);
System.out.println("Electronics shops: "+market2.electronicsShops);
System.out.println("Jewelry shops: "+market2.jewelryShops);
System.out.println("ATM available: "+market2.atmAvailable);
System.out.println("Security system: "+market2.securitySystem);
System.out.println("CCTV available: "+market2.cctvAvailable);
System.out.println("Public transport access: "+market2.publicTransportAccess);
System.out.println("Restrooms: "+market2.restrooms);
System.out.println("Wifi available: "+market2.wifiAvailable);
System.out.println("Delivery service: "+market2.deliveryService);
System.out.println("Wholesale market: "+market2.wholesaleMarket);
System.out.println("Retail market: "+market2.retailMarket);
System.out.println("Night market: "+market2.nightMarket);
System.out.println("Opening time: "+market2.openingTime);
System.out.println("Closing time: "+market2.closingTime);
System.out.println("Entry fee: "+market2.entryFee);

Market market3 = new Market();

System.out.println("Market name: "+market3.name);
System.out.println("Market location: "+market3.location);
System.out.println("Market city: "+market3.city);
System.out.println("Market state: "+market3.state);
System.out.println("Market country: "+market3.country);
System.out.println("Number of shops: "+market3.numberOfShops);
System.out.println("Parking available: "+market3.parkingAvailable);
System.out.println("Food stalls: "+market3.foodStalls);
System.out.println("Clothing shops: "+market3.clothingShops);
System.out.println("Vegetable shops: "+market3.vegetableShops);
System.out.println("Fruit shops: "+market3.fruitShops);
System.out.println("Electronics shops: "+market3.electronicsShops);
System.out.println("Jewelry shops: "+market3.jewelryShops);
System.out.println("ATM available: "+market3.atmAvailable);
System.out.println("Security system: "+market3.securitySystem);
System.out.println("CCTV available: "+market3.cctvAvailable);
System.out.println("Public transport access: "+market3.publicTransportAccess);
System.out.println("Restrooms: "+market3.restrooms);
System.out.println("Wifi available: "+market3.wifiAvailable);
System.out.println("Delivery service: "+market3.deliveryService);
System.out.println("Wholesale market: "+market3.wholesaleMarket);
System.out.println("Retail market: "+market3.retailMarket);
System.out.println("Night market: "+market3.nightMarket);
System.out.println("Opening time: "+market3.openingTime);
System.out.println("Closing time: "+market3.closingTime);
System.out.println("Entry fee: "+market3.entryFee);

market3.name="Commercial Street Market";
market3.location="Commercial Street";
market3.city="Bangalore";
market3.state="Karnataka";
market3.country="India";
market3.numberOfShops=300;
market3.parkingAvailable=true;
market3.foodStalls=true;
market3.clothingShops=true;
market3.vegetableShops=false;
market3.fruitShops=false;
market3.electronicsShops=true;
market3.jewelryShops=true;
market3.atmAvailable=true;
market3.securitySystem=true;
market3.cctvAvailable=true;
market3.publicTransportAccess=true;
market3.restrooms=true;
market3.wifiAvailable=true;
market3.deliveryService=true;
market3.wholesaleMarket=false;
market3.retailMarket=true;
market3.nightMarket=false;
market3.openingTime="10:00 AM";
market3.closingTime="9:30 PM";
market3.entryFee=0;

System.out.println("Market name: "+market3.name);
System.out.println("Market location: "+market3.location);
System.out.println("Market city: "+market3.city);
System.out.println("Market state: "+market3.state);
System.out.println("Market country: "+market3.country);
System.out.println("Number of shops: "+market3.numberOfShops);
System.out.println("Parking available: "+market3.parkingAvailable);
System.out.println("Food stalls: "+market3.foodStalls);
System.out.println("Clothing shops: "+market3.clothingShops);
System.out.println("Vegetable shops: "+market3.vegetableShops);
System.out.println("Fruit shops: "+market3.fruitShops);
System.out.println("Electronics shops: "+market3.electronicsShops);
System.out.println("Jewelry shops: "+market3.jewelryShops);
System.out.println("ATM available: "+market3.atmAvailable);
System.out.println("Security system: "+market3.securitySystem);
System.out.println("CCTV available: "+market3.cctvAvailable);
System.out.println("Public transport access: "+market3.publicTransportAccess);
System.out.println("Restrooms: "+market3.restrooms);
System.out.println("Wifi available: "+market3.wifiAvailable);
System.out.println("Delivery service: "+market3.deliveryService);
System.out.println("Wholesale market: "+market3.wholesaleMarket);
System.out.println("Retail market: "+market3.retailMarket);
System.out.println("Night market: "+market3.nightMarket);
System.out.println("Opening time: "+market3.openingTime);
System.out.println("Closing time: "+market3.closingTime);
System.out.println("Entry fee: "+market3.entryFee);

Market market4 = new Market();

System.out.println("Market name: "+market4.name);
System.out.println("Market location: "+market4.location);
System.out.println("Market city: "+market4.city);
System.out.println("Market state: "+market4.state);
System.out.println("Market country: "+market4.country);
System.out.println("Number of shops: "+market4.numberOfShops);
System.out.println("Parking available: "+market4.parkingAvailable);
System.out.println("Food stalls: "+market4.foodStalls);
System.out.println("Clothing shops: "+market4.clothingShops);
System.out.println("Vegetable shops: "+market4.vegetableShops);
System.out.println("Fruit shops: "+market4.fruitShops);
System.out.println("Electronics shops: "+market4.electronicsShops);
System.out.println("Jewelry shops: "+market4.jewelryShops);
System.out.println("ATM available: "+market4.atmAvailable);
System.out.println("Security system: "+market4.securitySystem);
System.out.println("CCTV available: "+market4.cctvAvailable);
System.out.println("Public transport access: "+market4.publicTransportAccess);
System.out.println("Restrooms: "+market4.restrooms);
System.out.println("Wifi available: "+market4.wifiAvailable);
System.out.println("Delivery service: "+market4.deliveryService);
System.out.println("Wholesale market: "+market4.wholesaleMarket);
System.out.println("Retail market: "+market4.retailMarket);
System.out.println("Night market: "+market4.nightMarket);
System.out.println("Opening time: "+market4.openingTime);
System.out.println("Closing time: "+market4.closingTime);
System.out.println("Entry fee: "+market4.entryFee);

market4.name="Laad Bazaar";
market4.location="Charminar";
market4.city="Hyderabad";
market4.state="Telangana";
market4.country="India";
market4.numberOfShops=250;
market4.parkingAvailable=false;
market4.foodStalls=true;
market4.clothingShops=true;
market4.vegetableShops=false;
market4.fruitShops=false;
market4.electronicsShops=false;
market4.jewelryShops=true;
market4.atmAvailable=true;
market4.securitySystem=true;
market4.cctvAvailable=true;
market4.publicTransportAccess=true;
market4.restrooms=true;
market4.wifiAvailable=false;
market4.deliveryService=true;
market4.wholesaleMarket=false;
market4.retailMarket=true;
market4.nightMarket=true;
market4.openingTime="11:00 AM";
market4.closingTime="10:00 PM";
market4.entryFee=0;

System.out.println("Market name: "+market4.name);
System.out.println("Market location: "+market4.location);
System.out.println("Market city: "+market4.city);
System.out.println("Market state: "+market4.state);
System.out.println("Market country: "+market4.country);
System.out.println("Number of shops: "+market4.numberOfShops);
System.out.println("Parking available: "+market4.parkingAvailable);
System.out.println("Food stalls: "+market4.foodStalls);
System.out.println("Clothing shops: "+market4.clothingShops);
System.out.println("Vegetable shops: "+market4.vegetableShops);
System.out.println("Fruit shops: "+market4.fruitShops);
System.out.println("Electronics shops: "+market4.electronicsShops);
System.out.println("Jewelry shops: "+market4.jewelryShops);
System.out.println("ATM available: "+market4.atmAvailable);
System.out.println("Security system: "+market4.securitySystem);
System.out.println("CCTV available: "+market4.cctvAvailable);
System.out.println("Public transport access: "+market4.publicTransportAccess);
System.out.println("Restrooms: "+market4.restrooms);
System.out.println("Wifi available: "+market4.wifiAvailable);
System.out.println("Delivery service: "+market4.deliveryService);
System.out.println("Wholesale market: "+market4.wholesaleMarket);
System.out.println("Retail market: "+market4.retailMarket);
System.out.println("Night market: "+market4.nightMarket);
System.out.println("Opening time: "+market4.openingTime);
System.out.println("Closing time: "+market4.closingTime);
System.out.println("Entry fee: "+market4.entryFee);

Market market5 = new Market();

System.out.println("Market name: "+market5.name);
System.out.println("Market location: "+market5.location);
System.out.println("Market city: "+market5.city);
System.out.println("Market state: "+market5.state);
System.out.println("Market country: "+market5.country);
System.out.println("Number of shops: "+market5.numberOfShops);
System.out.println("Parking available: "+market5.parkingAvailable);
System.out.println("Food stalls: "+market5.foodStalls);
System.out.println("Clothing shops: "+market5.clothingShops);
System.out.println("Vegetable shops: "+market5.vegetableShops);
System.out.println("Fruit shops: "+market5.fruitShops);
System.out.println("Electronics shops: "+market5.electronicsShops);
System.out.println("Jewelry shops: "+market5.jewelryShops);
System.out.println("ATM available: "+market5.atmAvailable);
System.out.println("Security system: "+market5.securitySystem);
System.out.println("CCTV available: "+market5.cctvAvailable);
System.out.println("Public transport access: "+market5.publicTransportAccess);
System.out.println("Restrooms: "+market5.restrooms);
System.out.println("Wifi available: "+market5.wifiAvailable);
System.out.println("Delivery service: "+market5.deliveryService);
System.out.println("Wholesale market: "+market5.wholesaleMarket);
System.out.println("Retail market: "+market5.retailMarket);
System.out.println("Night market: "+market5.nightMarket);
System.out.println("Opening time: "+market5.openingTime);
System.out.println("Closing time: "+market5.closingTime);
System.out.println("Entry fee: "+market5.entryFee);

market5.name="Crawford Market";
market5.location="Fort";
market5.city="Mumbai";
market5.state="Maharashtra";
market5.country="India";
market5.numberOfShops=400;
market5.parkingAvailable=true;
market5.foodStalls=true;
market5.clothingShops=false;
market5.vegetableShops=true;
market5.fruitShops=true;
market5.electronicsShops=false;
market5.jewelryShops=false;
market5.atmAvailable=true;
market5.securitySystem=true;
market5.cctvAvailable=true;
market5.publicTransportAccess=true;
market5.restrooms=true;
market5.wifiAvailable=true;
market5.deliveryService=true;
market5.wholesaleMarket=true;
market5.retailMarket=true;
market5.nightMarket=false;
market5.openingTime="7:00 AM";
market5.closingTime="8:00 PM";
market5.entryFee=0;

System.out.println("Market name: "+market5.name);
System.out.println("Market location: "+market5.location);
System.out.println("Market city: "+market5.city);
System.out.println("Market state: "+market5.state);
System.out.println("Market country: "+market5.country);
System.out.println("Number of shops: "+market5.numberOfShops);
System.out.println("Parking available: "+market5.parkingAvailable);
System.out.println("Food stalls: "+market5.foodStalls);
System.out.println("Clothing shops: "+market5.clothingShops);
System.out.println("Vegetable shops: "+market5.vegetableShops);
System.out.println("Fruit shops: "+market5.fruitShops);
System.out.println("Electronics shops: "+market5.electronicsShops);
System.out.println("Jewelry shops: "+market5.jewelryShops);
System.out.println("ATM available: "+market5.atmAvailable);
System.out.println("Security system: "+market5.securitySystem);
System.out.println("CCTV available: "+market5.cctvAvailable);
System.out.println("Public transport access: "+market5.publicTransportAccess);
System.out.println("Restrooms: "+market5.restrooms);
System.out.println("Wifi available: "+market5.wifiAvailable);
System.out.println("Delivery service: "+market5.deliveryService);
System.out.println("Wholesale market: "+market5.wholesaleMarket);
System.out.println("Retail market: "+market5.retailMarket);
System.out.println("Night market: "+market5.nightMarket);
System.out.println("Opening time: "+market5.openingTime);
System.out.println("Closing time: "+market5.closingTime);
System.out.println("Entry fee: "+market5.entryFee);

Market market6 = new Market();

System.out.println("Market name: "+market6.name);
System.out.println("Market location: "+market6.location);
System.out.println("Market city: "+market6.city);
System.out.println("Market state: "+market6.state);
System.out.println("Market country: "+market6.country);
System.out.println("Number of shops: "+market6.numberOfShops);
System.out.println("Parking available: "+market6.parkingAvailable);
System.out.println("Food stalls: "+market6.foodStalls);
System.out.println("Clothing shops: "+market6.clothingShops);
System.out.println("Vegetable shops: "+market6.vegetableShops);
System.out.println("Fruit shops: "+market6.fruitShops);
System.out.println("Electronics shops: "+market6.electronicsShops);
System.out.println("Jewelry shops: "+market6.jewelryShops);
System.out.println("ATM available: "+market6.atmAvailable);
System.out.println("Security system: "+market6.securitySystem);
System.out.println("CCTV available: "+market6.cctvAvailable);
System.out.println("Public transport access: "+market6.publicTransportAccess);
System.out.println("Restrooms: "+market6.restrooms);
System.out.println("Wifi available: "+market6.wifiAvailable);
System.out.println("Delivery service: "+market6.deliveryService);
System.out.println("Wholesale market: "+market6.wholesaleMarket);
System.out.println("Retail market: "+market6.retailMarket);
System.out.println("Night market: "+market6.nightMarket);
System.out.println("Opening time: "+market6.openingTime);
System.out.println("Closing time: "+market6.closingTime);
System.out.println("Entry fee: "+market6.entryFee);

market6.name="Sarojini Nagar Market";
market6.location="Sarojini Nagar";
market6.city="Delhi";
market6.state="Delhi";
market6.country="India";
market6.numberOfShops=350;
market6.parkingAvailable=true;
market6.foodStalls=true;
market6.clothingShops=true;
market6.vegetableShops=false;
market6.fruitShops=false;
market6.electronicsShops=true;
market6.jewelryShops=true;
market6.atmAvailable=true;
market6.securitySystem=true;
market6.cctvAvailable=true;
market6.publicTransportAccess=true;
market6.restrooms=true;
market6.wifiAvailable=true;
market6.deliveryService=true;
market6.wholesaleMarket=false;
market6.retailMarket=true;
market6.nightMarket=false;
market6.openingTime="10:00 AM";
market6.closingTime="9:00 PM";
market6.entryFee=0;

System.out.println("Market name: "+market6.name);
System.out.println("Market location: "+market6.location);
System.out.println("Market city: "+market6.city);
System.out.println("Market state: "+market6.state);
System.out.println("Market country: "+market6.country);
System.out.println("Number of shops: "+market6.numberOfShops);
System.out.println("Parking available: "+market6.parkingAvailable);
System.out.println("Food stalls: "+market6.foodStalls);
System.out.println("Clothing shops: "+market6.clothingShops);
System.out.println("Vegetable shops: "+market6.vegetableShops);
System.out.println("Fruit shops: "+market6.fruitShops);
System.out.println("Electronics shops: "+market6.electronicsShops);
System.out.println("Jewelry shops: "+market6.jewelryShops);
System.out.println("ATM available: "+market6.atmAvailable);
System.out.println("Security system: "+market6.securitySystem);
System.out.println("CCTV available: "+market6.cctvAvailable);
System.out.println("Public transport access: "+market6.publicTransportAccess);
System.out.println("Restrooms: "+market6.restrooms);
System.out.println("Wifi available: "+market6.wifiAvailable);
System.out.println("Delivery service: "+market6.deliveryService);
System.out.println("Wholesale market: "+market6.wholesaleMarket);
System.out.println("Retail market: "+market6.retailMarket);
System.out.println("Night market: "+market6.nightMarket);
System.out.println("Opening time: "+market6.openingTime);
System.out.println("Closing time: "+market6.closingTime);
System.out.println("Entry fee: "+market6.entryFee);

Market market7 = new Market();

System.out.println("Market name: "+market7.name);
System.out.println("Market location: "+market7.location);
System.out.println("Market city: "+market7.city);
System.out.println("Market state: "+market7.state);
System.out.println("Market country: "+market7.country);
System.out.println("Number of shops: "+market7.numberOfShops);
System.out.println("Parking available: "+market7.parkingAvailable);
System.out.println("Food stalls: "+market7.foodStalls);
System.out.println("Clothing shops: "+market7.clothingShops);
System.out.println("Vegetable shops: "+market7.vegetableShops);
System.out.println("Fruit shops: "+market7.fruitShops);
System.out.println("Electronics shops: "+market7.electronicsShops);
System.out.println("Jewelry shops: "+market7.jewelryShops);
System.out.println("ATM available: "+market7.atmAvailable);
System.out.println("Security system: "+market7.securitySystem);
System.out.println("CCTV available: "+market7.cctvAvailable);
System.out.println("Public transport access: "+market7.publicTransportAccess);
System.out.println("Restrooms: "+market7.restrooms);
System.out.println("Wifi available: "+market7.wifiAvailable);
System.out.println("Delivery service: "+market7.deliveryService);
System.out.println("Wholesale market: "+market7.wholesaleMarket);
System.out.println("Retail market: "+market7.retailMarket);
System.out.println("Night market: "+market7.nightMarket);
System.out.println("Opening time: "+market7.openingTime);
System.out.println("Closing time: "+market7.closingTime);
System.out.println("Entry fee: "+market7.entryFee);

market7.name="Johari Bazaar";
market7.location="Johari Bazaar Road";
market7.city="Jaipur";
market7.state="Rajasthan";
market7.country="India";
market7.numberOfShops=280;
market7.parkingAvailable=true;
market7.foodStalls=true;
market7.clothingShops=true;
market7.vegetableShops=false;
market7.fruitShops=false;
market7.electronicsShops=false;
market7.jewelryShops=true;
market7.atmAvailable=true;
market7.securitySystem=true;
market7.cctvAvailable=true;
market7.publicTransportAccess=true;
market7.restrooms=true;
market7.wifiAvailable=false;
market7.deliveryService=true;
market7.wholesaleMarket=false;
market7.retailMarket=true;
market7.nightMarket=true;
market7.openingTime="10:30 AM";
market7.closingTime="9:30 PM";
market7.entryFee=0;


System.out.println("Market name: "+market7.name);
System.out.println("Market location: "+market7.location);
System.out.println("Market city: "+market7.city);
System.out.println("Market state: "+market7.state);
System.out.println("Market country: "+market7.country);
System.out.println("Number of shops: "+market7.numberOfShops);
System.out.println("Parking available: "+market7.parkingAvailable);
System.out.println("Food stalls: "+market7.foodStalls);
System.out.println("Clothing shops: "+market7.clothingShops);
System.out.println("Vegetable shops: "+market7.vegetableShops);
System.out.println("Fruit shops: "+market7.fruitShops);
System.out.println("Electronics shops: "+market7.electronicsShops);
System.out.println("Jewelry shops: "+market7.jewelryShops);
System.out.println("ATM available: "+market7.atmAvailable);
System.out.println("Security system: "+market7.securitySystem);
System.out.println("CCTV available: "+market7.cctvAvailable);
System.out.println("Public transport access: "+market7.publicTransportAccess);
System.out.println("Restrooms: "+market7.restrooms);
System.out.println("Wifi available: "+market7.wifiAvailable);
System.out.println("Delivery service: "+market7.deliveryService);
System.out.println("Wholesale market: "+market7.wholesaleMarket);
System.out.println("Retail market: "+market7.retailMarket);
System.out.println("Night market: "+market7.nightMarket);
System.out.println("Opening time: "+market7.openingTime);
System.out.println("Closing time: "+market7.closingTime);
System.out.println("Entry fee: "+market7.entryFee);


Market market8 = new Market();

System.out.println("Market name: "+market8.name);
System.out.println("Market location: "+market8.location);
System.out.println("Market city: "+market8.city);
System.out.println("Market state: "+market8.state);
System.out.println("Market country: "+market8.country);
System.out.println("Number of shops: "+market8.numberOfShops);
System.out.println("Parking available: "+market8.parkingAvailable);
System.out.println("Food stalls: "+market8.foodStalls);
System.out.println("Clothing shops: "+market8.clothingShops);
System.out.println("Vegetable shops: "+market8.vegetableShops);
System.out.println("Fruit shops: "+market8.fruitShops);
System.out.println("Electronics shops: "+market8.electronicsShops);
System.out.println("Jewelry shops: "+market8.jewelryShops);
System.out.println("ATM available: "+market8.atmAvailable);
System.out.println("Security system: "+market8.securitySystem);
System.out.println("CCTV available: "+market8.cctvAvailable);
System.out.println("Public transport access: "+market8.publicTransportAccess);
System.out.println("Restrooms: "+market8.restrooms);
System.out.println("Wifi available: "+market8.wifiAvailable);
System.out.println("Delivery service: "+market8.deliveryService);
System.out.println("Wholesale market: "+market8.wholesaleMarket);
System.out.println("Retail market: "+market8.retailMarket);
System.out.println("Night market: "+market8.nightMarket);
System.out.println("Opening time: "+market8.openingTime);
System.out.println("Closing time: "+market8.closingTime);
System.out.println("Entry fee: "+market8.entryFee);

market8.name="New Market";
market8.location="Dharmatala";
market8.city="Kolkata";
market8.state="West Bengal";
market8.country="India";
market8.numberOfShops=500;
market8.parkingAvailable=true;
market8.foodStalls=true;
market8.clothingShops=true;
market8.vegetableShops=true;
market8.fruitShops=true;
market8.electronicsShops=true;
market8.jewelryShops=false;
market8.atmAvailable=true;
market8.securitySystem=true;
market8.cctvAvailable=true;
market8.publicTransportAccess=true;
market8.restrooms=true;
market8.wifiAvailable=true;
market8.deliveryService=true;
market8.wholesaleMarket=true;
market8.retailMarket=true;
market8.nightMarket=false;
market8.openingTime="8:00 AM";
market8.closingTime="9:00 PM";
market8.entryFee=0;

System.out.println("Market name: "+market8.name);
System.out.println("Market location: "+market8.location);
System.out.println("Market city: "+market8.city);
System.out.println("Market state: "+market8.state);
System.out.println("Market country: "+market8.country);
System.out.println("Number of shops: "+market8.numberOfShops);
System.out.println("Parking available: "+market8.parkingAvailable);
System.out.println("Food stalls: "+market8.foodStalls);
System.out.println("Clothing shops: "+market8.clothingShops);
System.out.println("Vegetable shops: "+market8.vegetableShops);
System.out.println("Fruit shops: "+market8.fruitShops);
System.out.println("Electronics shops: "+market8.electronicsShops);
System.out.println("Jewelry shops: "+market8.jewelryShops);
System.out.println("ATM available: "+market8.atmAvailable);
System.out.println("Security system: "+market8.securitySystem);
System.out.println("CCTV available: "+market8.cctvAvailable);
System.out.println("Public transport access: "+market8.publicTransportAccess);
System.out.println("Restrooms: "+market8.restrooms);
System.out.println("Wifi available: "+market8.wifiAvailable);
System.out.println("Delivery service: "+market8.deliveryService);
System.out.println("Wholesale market: "+market8.wholesaleMarket);
System.out.println("Retail market: "+market8.retailMarket);
System.out.println("Night market: "+market8.nightMarket);
System.out.println("Opening time: "+market8.openingTime);
System.out.println("Closing time: "+market8.closingTime);
System.out.println("Entry fee: "+market8.entryFee);

Market market9 = new Market();


System.out.println("Market name: "+market9.name);
System.out.println("Market location: "+market9.location);
System.out.println("Market city: "+market9.city);
System.out.println("Market state: "+market9.state);
System.out.println("Market country: "+market9.country);
System.out.println("Number of shops: "+market9.numberOfShops);
System.out.println("Parking available: "+market9.parkingAvailable);
System.out.println("Food stalls: "+market9.foodStalls);
System.out.println("Clothing shops: "+market9.clothingShops);
System.out.println("Vegetable shops: "+market9.vegetableShops);
System.out.println("Fruit shops: "+market9.fruitShops);
System.out.println("Electronics shops: "+market9.electronicsShops);
System.out.println("Jewelry shops: "+market9.jewelryShops);
System.out.println("ATM available: "+market9.atmAvailable);
System.out.println("Security system: "+market9.securitySystem);
System.out.println("CCTV available: "+market9.cctvAvailable);
System.out.println("Public transport access: "+market9.publicTransportAccess);
System.out.println("Restrooms: "+market9.restrooms);
System.out.println("Wifi available: "+market9.wifiAvailable);
System.out.println("Delivery service: "+market9.deliveryService);
System.out.println("Wholesale market: "+market9.wholesaleMarket);
System.out.println("Retail market: "+market9.retailMarket);
System.out.println("Night market: "+market9.nightMarket);
System.out.println("Opening time: "+market9.openingTime);
System.out.println("Closing time: "+market9.closingTime);
System.out.println("Entry fee: "+market9.entryFee);

market9.name="Pondy Bazaar";
market9.location="T Nagar";
market9.city="Chennai";
market9.state="Tamil Nadu";
market9.country="India";
market9.numberOfShops=420;
market9.parkingAvailable=true;
market9.foodStalls=true;
market9.clothingShops=true;
market9.vegetableShops=false;
market9.fruitShops=false;
market9.electronicsShops=true;
market9.jewelryShops=true;
market9.atmAvailable=true;
market9.securitySystem=true;
market9.cctvAvailable=true;
market9.publicTransportAccess=true;
market9.restrooms=true;
market9.wifiAvailable=true;
market9.deliveryService=true;
market9.wholesaleMarket=false;
market9.retailMarket=true;
market9.nightMarket=true;
market9.openingTime="10:00 AM";
market9.closingTime="10:00 PM";
market9.entryFee=0;

System.out.println("Market name: "+market9.name);
System.out.println("Market location: "+market9.location);
System.out.println("Market city: "+market9.city);
System.out.println("Market state: "+market9.state);
System.out.println("Market country: "+market9.country);
System.out.println("Number of shops: "+market9.numberOfShops);
System.out.println("Parking available: "+market9.parkingAvailable);
System.out.println("Food stalls: "+market9.foodStalls);
System.out.println("Clothing shops: "+market9.clothingShops);
System.out.println("Vegetable shops: "+market9.vegetableShops);
System.out.println("Fruit shops: "+market9.fruitShops);
System.out.println("Electronics shops: "+market9.electronicsShops);
System.out.println("Jewelry shops: "+market9.jewelryShops);
System.out.println("ATM available: "+market9.atmAvailable);
System.out.println("Security system: "+market9.securitySystem);
System.out.println("CCTV available: "+market9.cctvAvailable);
System.out.println("Public transport access: "+market9.publicTransportAccess);
System.out.println("Restrooms: "+market9.restrooms);
System.out.println("Wifi available: "+market9.wifiAvailable);
System.out.println("Delivery service: "+market9.deliveryService);
System.out.println("Wholesale market: "+market9.wholesaleMarket);
System.out.println("Retail market: "+market9.retailMarket);
System.out.println("Night market: "+market9.nightMarket);
System.out.println("Opening time: "+market9.openingTime);
System.out.println("Closing time: "+market9.closingTime);
System.out.println("Entry fee: "+market9.entryFee);

Market market10 = new Market();

System.out.println("Market name: "+market10.name);
System.out.println("Market location: "+market10.location);
System.out.println("Market city: "+market10.city);
System.out.println("Market state: "+market10.state);
System.out.println("Market country: "+market10.country);
System.out.println("Number of shops: "+market10.numberOfShops);
System.out.println("Parking available: "+market10.parkingAvailable);
System.out.println("Food stalls: "+market10.foodStalls);
System.out.println("Clothing shops: "+market10.clothingShops);
System.out.println("Vegetable shops: "+market10.vegetableShops);
System.out.println("Fruit shops: "+market10.fruitShops);
System.out.println("Electronics shops: "+market10.electronicsShops);
System.out.println("Jewelry shops: "+market10.jewelryShops);
System.out.println("ATM available: "+market10.atmAvailable);
System.out.println("Security system: "+market10.securitySystem);
System.out.println("CCTV available: "+market10.cctvAvailable);
System.out.println("Public transport access: "+market10.publicTransportAccess);
System.out.println("Restrooms: "+market10.restrooms);
System.out.println("Wifi available: "+market10.wifiAvailable);
System.out.println("Delivery service: "+market10.deliveryService);
System.out.println("Wholesale market: "+market10.wholesaleMarket);
System.out.println("Retail market: "+market10.retailMarket);
System.out.println("Night market: "+market10.nightMarket);
System.out.println("Opening time: "+market10.openingTime);
System.out.println("Closing time: "+market10.closingTime);
System.out.println("Entry fee: "+market10.entryFee);

market10.name="MG Road Market";
market10.location="MG Road";
market10.city="Bangalore";
market10.state="Karnataka";
market10.country="India";
market10.numberOfShops=350;
market10.parkingAvailable=true;
market10.foodStalls=true;
market10.clothingShops=true;
market10.vegetableShops=false;
market10.fruitShops=false;
market10.electronicsShops=true;
market10.jewelryShops=true;
market10.atmAvailable=true;
market10.securitySystem=true;
market10.cctvAvailable=true;
market10.publicTransportAccess=true;
market10.restrooms=true;
market10.wifiAvailable=true;
market10.deliveryService=true;
market10.wholesaleMarket=false;
market10.retailMarket=true;
market10.nightMarket=true;
market10.openingTime="10:00 AM";
market10.closingTime="10:30 PM";
market10.entryFee=0;

System.out.println("Market name: "+market10.name);
System.out.println("Market location: "+market10.location);
System.out.println("Market city: "+market10.city);
System.out.println("Market state: "+market10.state);
System.out.println("Market country: "+market10.country);
System.out.println("Number of shops: "+market10.numberOfShops);
System.out.println("Parking available: "+market10.parkingAvailable);
System.out.println("Food stalls: "+market10.foodStalls);
System.out.println("Clothing shops: "+market10.clothingShops);
System.out.println("Vegetable shops: "+market10.vegetableShops);
System.out.println("Fruit shops: "+market10.fruitShops);
System.out.println("Electronics shops: "+market10.electronicsShops);
System.out.println("Jewelry shops: "+market10.jewelryShops);
System.out.println("ATM available: "+market10.atmAvailable);
System.out.println("Security system: "+market10.securitySystem);
System.out.println("CCTV available: "+market10.cctvAvailable);
System.out.println("Public transport access: "+market10.publicTransportAccess);
System.out.println("Restrooms: "+market10.restrooms);
System.out.println("Wifi available: "+market10.wifiAvailable);
System.out.println("Delivery service: "+market10.deliveryService);
System.out.println("Wholesale market: "+market10.wholesaleMarket);
System.out.println("Retail market: "+market10.retailMarket);
System.out.println("Night market: "+market10.nightMarket);
System.out.println("Opening time: "+market10.openingTime);
System.out.println("Closing time: "+market10.closingTime);
System.out.println("Entry fee: "+market10.entryFee);




}


}