public class MuseumExecutor {

public static void main(String[] args) {

Museum museum1 = new Museum();

System.out.println("Museum name: "+museum1.name);
System.out.println("Museum location: "+museum1.location);
System.out.println("Museum city: "+museum1.city);
System.out.println("Museum state: "+museum1.state);
System.out.println("Museum country: "+museum1.country);
System.out.println("Number of galleries: "+museum1.numberOfGalleries);
System.out.println("Number of artifacts: "+museum1.numberOfArtifacts);
System.out.println("Guided tours: "+museum1.guidedTours);
System.out.println("Parking available: "+museum1.parkingAvailable);
System.out.println("Wifi available: "+museum1.wifiAvailable);
System.out.println("Photography allowed: "+museum1.photographyAllowed);
System.out.println("Gift shop: "+museum1.giftShop);
System.out.println("Cafeteria: "+museum1.cafeteria);
System.out.println("Security system: "+museum1.securitySystem);
System.out.println("CCTV available: "+museum1.cctvAvailable);
System.out.println("Air conditioned: "+museum1.airConditioned);
System.out.println("Wheelchair access: "+museum1.wheelchairAccess);
System.out.println("Online ticket: "+museum1.onlineTicket);
System.out.println("Audio guide: "+museum1.audioGuide);
System.out.println("Exhibition hall: "+museum1.exhibitionHall);
System.out.println("Research center: "+museum1.researchCenter);
System.out.println("Library available: "+museum1.libraryAvailable);
System.out.println("Opening time: "+museum1.openingTime);
System.out.println("Closing time: "+museum1.closingTime);
System.out.println("Entry fee: "+museum1.entryFee);

museum1.name="National Museum";
museum1.location="Janpath Road";
museum1.city="New Delhi";
museum1.state="Delhi";
museum1.country="India";
museum1.numberOfGalleries=30;
museum1.numberOfArtifacts=200000;
museum1.guidedTours=true;
museum1.parkingAvailable=true;
museum1.wifiAvailable=true;
museum1.photographyAllowed=false;
museum1.giftShop=true;
museum1.cafeteria=true;
museum1.securitySystem=true;
museum1.cctvAvailable=true;
museum1.airConditioned=true;
museum1.wheelchairAccess=true;
museum1.onlineTicket=true;
museum1.audioGuide=true;
museum1.exhibitionHall=true;
museum1.researchCenter=true;
museum1.libraryAvailable=true;
museum1.openingTime="10:00 AM";
museum1.closingTime="6:00 PM";
museum1.entryFee=50;

System.out.println("Museum name: "+museum1.name);
System.out.println("Museum location: "+museum1.location);
System.out.println("Museum city: "+museum1.city);
System.out.println("Museum state: "+museum1.state);
System.out.println("Museum country: "+museum1.country);
System.out.println("Number of galleries: "+museum1.numberOfGalleries);
System.out.println("Number of artifacts: "+museum1.numberOfArtifacts);
System.out.println("Guided tours: "+museum1.guidedTours);
System.out.println("Parking available: "+museum1.parkingAvailable);
System.out.println("Wifi available: "+museum1.wifiAvailable);
System.out.println("Photography allowed: "+museum1.photographyAllowed);
System.out.println("Gift shop: "+museum1.giftShop);
System.out.println("Cafeteria: "+museum1.cafeteria);
System.out.println("Security system: "+museum1.securitySystem);
System.out.println("CCTV available: "+museum1.cctvAvailable);
System.out.println("Air conditioned: "+museum1.airConditioned);
System.out.println("Wheelchair access: "+museum1.wheelchairAccess);
System.out.println("Online ticket: "+museum1.onlineTicket);
System.out.println("Audio guide: "+museum1.audioGuide);
System.out.println("Exhibition hall: "+museum1.exhibitionHall);
System.out.println("Research center: "+museum1.researchCenter);
System.out.println("Library available: "+museum1.libraryAvailable);
System.out.println("Opening time: "+museum1.openingTime);
System.out.println("Closing time: "+museum1.closingTime);
System.out.println("Entry fee: "+museum1.entryFee);

Museum museum2 = new Museum();

System.out.println("Museum name: "+museum2.name);
System.out.println("Museum location: "+museum2.location);
System.out.println("Museum city: "+museum2.city);
System.out.println("Museum state: "+museum2.state);
System.out.println("Museum country: "+museum2.country);
System.out.println("Number of galleries: "+museum2.numberOfGalleries);
System.out.println("Number of artifacts: "+museum2.numberOfArtifacts);
System.out.println("Guided tours: "+museum2.guidedTours);
System.out.println("Parking available: "+museum2.parkingAvailable);
System.out.println("Wifi available: "+museum2.wifiAvailable);
System.out.println("Photography allowed: "+museum2.photographyAllowed);
System.out.println("Gift shop: "+museum2.giftShop);
System.out.println("Cafeteria: "+museum2.cafeteria);
System.out.println("Security system: "+museum2.securitySystem);
System.out.println("CCTV available: "+museum2.cctvAvailable);
System.out.println("Air conditioned: "+museum2.airConditioned);
System.out.println("Wheelchair access: "+museum2.wheelchairAccess);
System.out.println("Online ticket: "+museum2.onlineTicket);
System.out.println("Audio guide: "+museum2.audioGuide);
System.out.println("Exhibition hall: "+museum2.exhibitionHall);
System.out.println("Research center: "+museum2.researchCenter);
System.out.println("Library available: "+museum2.libraryAvailable);
System.out.println("Opening time: "+museum2.openingTime);
System.out.println("Closing time: "+museum2.closingTime);
System.out.println("Entry fee: "+museum2.entryFee);

museum2.name="Indian Museum";
museum2.location="Park Street";
museum2.city="Kolkata";
museum2.state="West Bengal";
museum2.country="India";
museum2.numberOfGalleries=35;
museum2.numberOfArtifacts=150000;
museum2.guidedTours=true;
museum2.parkingAvailable=true;
museum2.wifiAvailable=false;
museum2.photographyAllowed=true;
museum2.giftShop=true;
museum2.cafeteria=true;
museum2.securitySystem=true;
museum2.cctvAvailable=true;
museum2.airConditioned=true;
museum2.wheelchairAccess=true;
museum2.onlineTicket=true;
museum2.audioGuide=true;
museum2.exhibitionHall=true;
museum2.researchCenter=false;
museum2.libraryAvailable=true;
museum2.openingTime="10:00 AM";
museum2.closingTime="5:00 PM";
museum2.entryFee=30;

System.out.println("Museum name: "+museum2.name);
System.out.println("Museum location: "+museum2.location);
System.out.println("Museum city: "+museum2.city);
System.out.println("Museum state: "+museum2.state);
System.out.println("Museum country: "+museum2.country);
System.out.println("Number of galleries: "+museum2.numberOfGalleries);
System.out.println("Number of artifacts: "+museum2.numberOfArtifacts);
System.out.println("Guided tours: "+museum2.guidedTours);
System.out.println("Parking available: "+museum2.parkingAvailable);
System.out.println("Wifi available: "+museum2.wifiAvailable);
System.out.println("Photography allowed: "+museum2.photographyAllowed);
System.out.println("Gift shop: "+museum2.giftShop);
System.out.println("Cafeteria: "+museum2.cafeteria);
System.out.println("Security system: "+museum2.securitySystem);
System.out.println("CCTV available: "+museum2.cctvAvailable);
System.out.println("Air conditioned: "+museum2.airConditioned);
System.out.println("Wheelchair access: "+museum2.wheelchairAccess);
System.out.println("Online ticket: "+museum2.onlineTicket);
System.out.println("Audio guide: "+museum2.audioGuide);
System.out.println("Exhibition hall: "+museum2.exhibitionHall);
System.out.println("Research center: "+museum2.researchCenter);
System.out.println("Library available: "+museum2.libraryAvailable);
System.out.println("Opening time: "+museum2.openingTime);
System.out.println("Closing time: "+museum2.closingTime);
System.out.println("Entry fee: "+museum2.entryFee);

Museum museum3 = new Museum();

System.out.println("Museum name: "+museum3.name);
System.out.println("Museum location: "+museum3.location);
System.out.println("Museum city: "+museum3.city);
System.out.println("Museum state: "+museum3.state);
System.out.println("Museum country: "+museum3.country);
System.out.println("Number of galleries: "+museum3.numberOfGalleries);
System.out.println("Number of artifacts: "+museum3.numberOfArtifacts);
System.out.println("Guided tours: "+museum3.guidedTours);
System.out.println("Parking available: "+museum3.parkingAvailable);
System.out.println("Wifi available: "+museum3.wifiAvailable);
System.out.println("Photography allowed: "+museum3.photographyAllowed);
System.out.println("Gift shop: "+museum3.giftShop);
System.out.println("Cafeteria: "+museum3.cafeteria);
System.out.println("Security system: "+museum3.securitySystem);
System.out.println("CCTV available: "+museum3.cctvAvailable);
System.out.println("Air conditioned: "+museum3.airConditioned);
System.out.println("Wheelchair access: "+museum3.wheelchairAccess);
System.out.println("Online ticket: "+museum3.onlineTicket);
System.out.println("Audio guide: "+museum3.audioGuide);
System.out.println("Exhibition hall: "+museum3.exhibitionHall);
System.out.println("Research center: "+museum3.researchCenter);
System.out.println("Library available: "+museum3.libraryAvailable);
System.out.println("Opening time: "+museum3.openingTime);
System.out.println("Closing time: "+museum3.closingTime);
System.out.println("Entry fee: "+museum3.entryFee);

museum3.name="Salar Jung Museum";
museum3.location="Darulshifa";
museum3.city="Hyderabad";
museum3.state="Telangana";
museum3.country="India";
museum3.numberOfGalleries=38;
museum3.numberOfArtifacts=43000;
museum3.guidedTours=true;
museum3.parkingAvailable=true;
museum3.wifiAvailable=true;
museum3.photographyAllowed=true;
museum3.giftShop=true;
museum3.cafeteria=true;
museum3.securitySystem=true;
museum3.cctvAvailable=true;
museum3.airConditioned=true;
museum3.wheelchairAccess=true;
museum3.onlineTicket=true;
museum3.audioGuide=true;
museum3.exhibitionHall=true;
museum3.researchCenter=true;
museum3.libraryAvailable=true;
museum3.openingTime="10:00 AM";
museum3.closingTime="5:00 PM";
museum3.entryFee=40;

System.out.println("Museum name: "+museum3.name);
System.out.println("Museum location: "+museum3.location);
System.out.println("Museum city: "+museum3.city);
System.out.println("Museum state: "+museum3.state);
System.out.println("Museum country: "+museum3.country);
System.out.println("Number of galleries: "+museum3.numberOfGalleries);
System.out.println("Number of artifacts: "+museum3.numberOfArtifacts);
System.out.println("Guided tours: "+museum3.guidedTours);
System.out.println("Parking available: "+museum3.parkingAvailable);
System.out.println("Wifi available: "+museum3.wifiAvailable);
System.out.println("Photography allowed: "+museum3.photographyAllowed);
System.out.println("Gift shop: "+museum3.giftShop);
System.out.println("Cafeteria: "+museum3.cafeteria);
System.out.println("Security system: "+museum3.securitySystem);
System.out.println("CCTV available: "+museum3.cctvAvailable);
System.out.println("Air conditioned: "+museum3.airConditioned);
System.out.println("Wheelchair access: "+museum3.wheelchairAccess);
System.out.println("Online ticket: "+museum3.onlineTicket);
System.out.println("Audio guide: "+museum3.audioGuide);
System.out.println("Exhibition hall: "+museum3.exhibitionHall);
System.out.println("Research center: "+museum3.researchCenter);
System.out.println("Library available: "+museum3.libraryAvailable);
System.out.println("Opening time: "+museum3.openingTime);
System.out.println("Closing time: "+museum3.closingTime);
System.out.println("Entry fee: "+museum3.entryFee);




Museum museum4 = new Museum();

System.out.println("Museum name: "+museum4.name);
System.out.println("Museum location: "+museum4.location);
System.out.println("Museum city: "+museum4.city);
System.out.println("Museum state: "+museum4.state);
System.out.println("Museum country: "+museum4.country);
System.out.println("Number of galleries: "+museum4.numberOfGalleries);
System.out.println("Number of artifacts: "+museum4.numberOfArtifacts);
System.out.println("Guided tours: "+museum4.guidedTours);
System.out.println("Parking available: "+museum4.parkingAvailable);
System.out.println("Wifi available: "+museum4.wifiAvailable);
System.out.println("Photography allowed: "+museum4.photographyAllowed);
System.out.println("Gift shop: "+museum4.giftShop);
System.out.println("Cafeteria: "+museum4.cafeteria);
System.out.println("Security system: "+museum4.securitySystem);
System.out.println("CCTV available: "+museum4.cctvAvailable);
System.out.println("Air conditioned: "+museum4.airConditioned);
System.out.println("Wheelchair access: "+museum4.wheelchairAccess);
System.out.println("Online ticket: "+museum4.onlineTicket);
System.out.println("Audio guide: "+museum4.audioGuide);
System.out.println("Exhibition hall: "+museum4.exhibitionHall);
System.out.println("Research center: "+museum4.researchCenter);
System.out.println("Library available: "+museum4.libraryAvailable);
System.out.println("Opening time: "+museum4.openingTime);
System.out.println("Closing time: "+museum4.closingTime);
System.out.println("Entry fee: "+museum4.entryFee);

museum4.name="Government Museum";
museum4.location="Egmore";
museum4.city="Chennai";
museum4.state="Tamil Nadu";
museum4.country="India";
museum4.numberOfGalleries=40;
museum4.numberOfArtifacts=70000;
museum4.guidedTours=true;
museum4.parkingAvailable=true;
museum4.wifiAvailable=false;
museum4.photographyAllowed=true;
museum4.giftShop=true;
museum4.cafeteria=true;
museum4.securitySystem=true;
museum4.cctvAvailable=true;
museum4.airConditioned=true;
museum4.wheelchairAccess=true;
museum4.onlineTicket=false;
museum4.audioGuide=true;
museum4.exhibitionHall=true;
museum4.researchCenter=true;
museum4.libraryAvailable=true;
museum4.openingTime="9:30 AM";
museum4.closingTime="5:00 PM";
museum4.entryFee=25;

System.out.println("Museum name: "+museum4.name);
System.out.println("Museum location: "+museum4.location);
System.out.println("Museum city: "+museum4.city);
System.out.println("Museum state: "+museum4.state);
System.out.println("Museum country: "+museum4.country);
System.out.println("Number of galleries: "+museum4.numberOfGalleries);
System.out.println("Number of artifacts: "+museum4.numberOfArtifacts);
System.out.println("Guided tours: "+museum4.guidedTours);
System.out.println("Parking available: "+museum4.parkingAvailable);
System.out.println("Wifi available: "+museum4.wifiAvailable);
System.out.println("Photography allowed: "+museum4.photographyAllowed);
System.out.println("Gift shop: "+museum4.giftShop);
System.out.println("Cafeteria: "+museum4.cafeteria);
System.out.println("Security system: "+museum4.securitySystem);
System.out.println("CCTV available: "+museum4.cctvAvailable);
System.out.println("Air conditioned: "+museum4.airConditioned);
System.out.println("Wheelchair access: "+museum4.wheelchairAccess);
System.out.println("Online ticket: "+museum4.onlineTicket);
System.out.println("Audio guide: "+museum4.audioGuide);
System.out.println("Exhibition hall: "+museum4.exhibitionHall);
System.out.println("Research center: "+museum4.researchCenter);
System.out.println("Library available: "+museum4.libraryAvailable);
System.out.println("Opening time: "+museum4.openingTime);
System.out.println("Closing time: "+museum4.closingTime);
System.out.println("Entry fee: "+museum4.entryFee);


Museum museum6 = new Museum();

System.out.println("Museum name: "+museum6.name);
System.out.println("Museum location: "+museum6.location);
System.out.println("Museum city: "+museum6.city);
System.out.println("Museum state: "+museum6.state);
System.out.println("Museum country: "+museum6.country);
System.out.println("Number of galleries: "+museum6.numberOfGalleries);
System.out.println("Number of artifacts: "+museum6.numberOfArtifacts);
System.out.println("Guided tours: "+museum6.guidedTours);
System.out.println("Parking available: "+museum6.parkingAvailable);
System.out.println("Wifi available: "+museum6.wifiAvailable);
System.out.println("Photography allowed: "+museum6.photographyAllowed);
System.out.println("Gift shop: "+museum6.giftShop);
System.out.println("Cafeteria: "+museum6.cafeteria);
System.out.println("Security system: "+museum6.securitySystem);
System.out.println("CCTV available: "+museum6.cctvAvailable);
System.out.println("Air conditioned: "+museum6.airConditioned);
System.out.println("Wheelchair access: "+museum6.wheelchairAccess);
System.out.println("Online ticket: "+museum6.onlineTicket);
System.out.println("Audio guide: "+museum6.audioGuide);
System.out.println("Exhibition hall: "+museum6.exhibitionHall);
System.out.println("Research center: "+museum6.researchCenter);
System.out.println("Library available: "+museum6.libraryAvailable);
System.out.println("Opening time: "+museum6.openingTime);
System.out.println("Closing time: "+museum6.closingTime);
System.out.println("Entry fee: "+museum6.entryFee);


museum6.name="Indian Museum";
museum6.location="Park Street";
museum6.city="Kolkata";
museum6.state="West Bengal";
museum6.country="India";
museum6.numberOfGalleries=35;
museum6.numberOfArtifacts=100000;
museum6.guidedTours=true;
museum6.parkingAvailable=true;
museum6.wifiAvailable=true;
museum6.photographyAllowed=false;
museum6.giftShop=true;
museum6.cafeteria=true;
museum6.securitySystem=true;
museum6.cctvAvailable=true;
museum6.airConditioned=true;
museum6.wheelchairAccess=true;
museum6.onlineTicket=true;
museum6.audioGuide=true;
museum6.exhibitionHall=true;
museum6.researchCenter=true;
museum6.libraryAvailable=true;
museum6.openingTime="10:00 AM";
museum6.closingTime="5:00 PM";
museum6.entryFee=50;

System.out.println("Museum name: "+museum6.name);
System.out.println("Museum location: "+museum6.location);
System.out.println("Museum city: "+museum6.city);
System.out.println("Museum state: "+museum6.state);
System.out.println("Museum country: "+museum6.country);
System.out.println("Number of galleries: "+museum6.numberOfGalleries);
System.out.println("Number of artifacts: "+museum6.numberOfArtifacts);
System.out.println("Guided tours: "+museum6.guidedTours);
System.out.println("Parking available: "+museum6.parkingAvailable);
System.out.println("Wifi available: "+museum6.wifiAvailable);
System.out.println("Photography allowed: "+museum6.photographyAllowed);
System.out.println("Gift shop: "+museum6.giftShop);
System.out.println("Cafeteria: "+museum6.cafeteria);
System.out.println("Security system: "+museum6.securitySystem);
System.out.println("CCTV available: "+museum6.cctvAvailable);
System.out.println("Air conditioned: "+museum6.airConditioned);
System.out.println("Wheelchair access: "+museum6.wheelchairAccess);
System.out.println("Online ticket: "+museum6.onlineTicket);
System.out.println("Audio guide: "+museum6.audioGuide);
System.out.println("Exhibition hall: "+museum6.exhibitionHall);
System.out.println("Research center: "+museum6.researchCenter);
System.out.println("Library available: "+museum6.libraryAvailable);
System.out.println("Opening time: "+museum6.openingTime);
System.out.println("Closing time: "+museum6.closingTime);
System.out.println("Entry fee: "+museum6.entryFee);



Museum museum7 = new Museum();

System.out.println("Museum name: "+museum7.name);
System.out.println("Museum location: "+museum7.location);
System.out.println("Museum city: "+museum7.city);
System.out.println("Museum state: "+museum7.state);
System.out.println("Museum country: "+museum7.country);
System.out.println("Number of galleries: "+museum7.numberOfGalleries);
System.out.println("Number of artifacts: "+museum7.numberOfArtifacts);
System.out.println("Guided tours: "+museum7.guidedTours);
System.out.println("Parking available: "+museum7.parkingAvailable);
System.out.println("Wifi available: "+museum7.wifiAvailable);
System.out.println("Photography allowed: "+museum7.photographyAllowed);
System.out.println("Gift shop: "+museum7.giftShop);
System.out.println("Cafeteria: "+museum7.cafeteria);
System.out.println("Security system: "+museum7.securitySystem);
System.out.println("CCTV available: "+museum7.cctvAvailable);
System.out.println("Air conditioned: "+museum7.airConditioned);
System.out.println("Wheelchair access: "+museum7.wheelchairAccess);
System.out.println("Online ticket: "+museum7.onlineTicket);
System.out.println("Audio guide: "+museum7.audioGuide);
System.out.println("Exhibition hall: "+museum7.exhibitionHall);
System.out.println("Research center: "+museum7.researchCenter);
System.out.println("Library available: "+museum7.libraryAvailable);
System.out.println("Opening time: "+museum7.openingTime);
System.out.println("Closing time: "+museum7.closingTime);
System.out.println("Entry fee: "+museum7.entryFee);


museum7.name="National Museum";
museum7.location="Janpath";
museum7.city="New Delhi";
museum7.state="Delhi";
museum7.country="India";
museum7.numberOfGalleries=28;
museum7.numberOfArtifacts=200000;
museum7.guidedTours=true;
museum7.parkingAvailable=true;
museum7.wifiAvailable=true;
museum7.photographyAllowed=true;
museum7.giftShop=true;
museum7.cafeteria=true;
museum7.securitySystem=true;
museum7.cctvAvailable=true;
museum7.airConditioned=true;
museum7.wheelchairAccess=true;
museum7.onlineTicket=true;
museum7.audioGuide=true;
museum7.exhibitionHall=true;
museum7.researchCenter=true;
museum7.libraryAvailable=true;
museum7.openingTime="10:00 AM";
museum7.closingTime="6:00 PM";
museum7.entryFee=60;

System.out.println("Museum name: "+museum7.name);
System.out.println("Museum location: "+museum7.location);
System.out.println("Museum city: "+museum7.city);
System.out.println("Museum state: "+museum7.state);
System.out.println("Museum country: "+museum7.country);
System.out.println("Number of galleries: "+museum7.numberOfGalleries);
System.out.println("Number of artifacts: "+museum7.numberOfArtifacts);
System.out.println("Guided tours: "+museum7.guidedTours);
System.out.println("Parking available: "+museum7.parkingAvailable);
System.out.println("Wifi available: "+museum7.wifiAvailable);
System.out.println("Photography allowed: "+museum7.photographyAllowed);
System.out.println("Gift shop: "+museum7.giftShop);
System.out.println("Cafeteria: "+museum7.cafeteria);
System.out.println("Security system: "+museum7.securitySystem);
System.out.println("CCTV available: "+museum7.cctvAvailable);
System.out.println("Air conditioned: "+museum7.airConditioned);
System.out.println("Wheelchair access: "+museum7.wheelchairAccess);
System.out.println("Online ticket: "+museum7.onlineTicket);
System.out.println("Audio guide: "+museum7.audioGuide);
System.out.println("Exhibition hall: "+museum7.exhibitionHall);
System.out.println("Research center: "+museum7.researchCenter);
System.out.println("Library available: "+museum7.libraryAvailable);
System.out.println("Opening time: "+museum7.openingTime);
System.out.println("Closing time: "+museum7.closingTime);
System.out.println("Entry fee: "+museum7.entryFee);


Museum museum8 = new Museum();

System.out.println("Museum name: "+museum8.name);
System.out.println("Museum location: "+museum8.location);
System.out.println("Museum city: "+museum8.city);
System.out.println("Museum state: "+museum8.state);
System.out.println("Museum country: "+museum8.country);
System.out.println("Number of galleries: "+museum8.numberOfGalleries);
System.out.println("Number of artifacts: "+museum8.numberOfArtifacts);
System.out.println("Guided tours: "+museum8.guidedTours);
System.out.println("Parking available: "+museum8.parkingAvailable);
System.out.println("Wifi available: "+museum8.wifiAvailable);
System.out.println("Photography allowed: "+museum8.photographyAllowed);
System.out.println("Gift shop: "+museum8.giftShop);
System.out.println("Cafeteria: "+museum8.cafeteria);
System.out.println("Security system: "+museum8.securitySystem);
System.out.println("CCTV available: "+museum8.cctvAvailable);
System.out.println("Air conditioned: "+museum8.airConditioned);
System.out.println("Wheelchair access: "+museum8.wheelchairAccess);
System.out.println("Online ticket: "+museum8.onlineTicket);
System.out.println("Audio guide: "+museum8.audioGuide);
System.out.println("Exhibition hall: "+museum8.exhibitionHall);
System.out.println("Research center: "+museum8.researchCenter);
System.out.println("Library available: "+museum8.libraryAvailable);
System.out.println("Opening time: "+museum8.openingTime);
System.out.println("Closing time: "+museum8.closingTime);
System.out.println("Entry fee: "+museum8.entryFee);


museum8.name="Visvesvaraya Industrial Museum";
museum8.location="Cubbon Park";
museum8.city="Bangalore";
museum8.state="Karnataka";
museum8.country="India";
museum8.numberOfGalleries=12;
museum8.numberOfArtifacts=8000;
museum8.guidedTours=true;
museum8.parkingAvailable=true;
museum8.wifiAvailable=true;
museum8.photographyAllowed=true;
museum8.giftShop=true;
museum8.cafeteria=true;
museum8.securitySystem=true;
museum8.cctvAvailable=true;
museum8.airConditioned=true;
museum8.wheelchairAccess=true;
museum8.onlineTicket=true;
museum8.audioGuide=true;
museum8.exhibitionHall=true;
museum8.researchCenter=false;
museum8.libraryAvailable=true;
museum8.openingTime="9:30 AM";
museum8.closingTime="5:30 PM";
museum8.entryFee=40;

System.out.println("Museum name: "+museum8.name);
System.out.println("Museum location: "+museum8.location);
System.out.println("Museum city: "+museum8.city);
System.out.println("Museum state: "+museum8.state);
System.out.println("Museum country: "+museum8.country);
System.out.println("Number of galleries: "+museum8.numberOfGalleries);
System.out.println("Number of artifacts: "+museum8.numberOfArtifacts);
System.out.println("Guided tours: "+museum8.guidedTours);
System.out.println("Parking available: "+museum8.parkingAvailable);
System.out.println("Wifi available: "+museum8.wifiAvailable);
System.out.println("Photography allowed: "+museum8.photographyAllowed);
System.out.println("Gift shop: "+museum8.giftShop);
System.out.println("Cafeteria: "+museum8.cafeteria);
System.out.println("Security system: "+museum8.securitySystem);
System.out.println("CCTV available: "+museum8.cctvAvailable);
System.out.println("Air conditioned: "+museum8.airConditioned);
System.out.println("Wheelchair access: "+museum8.wheelchairAccess);
System.out.println("Online ticket: "+museum8.onlineTicket);
System.out.println("Audio guide: "+museum8.audioGuide);
System.out.println("Exhibition hall: "+museum8.exhibitionHall);
System.out.println("Research center: "+museum8.researchCenter);
System.out.println("Library available: "+museum8.libraryAvailable);
System.out.println("Opening time: "+museum8.openingTime);
System.out.println("Closing time: "+museum8.closingTime);
System.out.println("Entry fee: "+museum8.entryFee);



Museum museum9 = new Museum();

System.out.println("Museum name: "+museum9.name);
System.out.println("Museum location: "+museum9.location);
System.out.println("Museum city: "+museum9.city);
System.out.println("Museum state: "+museum9.state);
System.out.println("Museum country: "+museum9.country);
System.out.println("Number of galleries: "+museum9.numberOfGalleries);
System.out.println("Number of artifacts: "+museum9.numberOfArtifacts);
System.out.println("Guided tours: "+museum9.guidedTours);
System.out.println("Parking available: "+museum9.parkingAvailable);
System.out.println("Wifi available: "+museum9.wifiAvailable);
System.out.println("Photography allowed: "+museum9.photographyAllowed);
System.out.println("Gift shop: "+museum9.giftShop);
System.out.println("Cafeteria: "+museum9.cafeteria);
System.out.println("Security system: "+museum9.securitySystem);
System.out.println("CCTV available: "+museum9.cctvAvailable);
System.out.println("Air conditioned: "+museum9.airConditioned);
System.out.println("Wheelchair access: "+museum9.wheelchairAccess);
System.out.println("Online ticket: "+museum9.onlineTicket);
System.out.println("Audio guide: "+museum9.audioGuide);
System.out.println("Exhibition hall: "+museum9.exhibitionHall);
System.out.println("Research center: "+museum9.researchCenter);
System.out.println("Library available: "+museum9.libraryAvailable);
System.out.println("Opening time: "+museum9.openingTime);
System.out.println("Closing time: "+museum9.closingTime);
System.out.println("Entry fee: "+museum9.entryFee);

museum9.name="Chhatrapati Shivaji Maharaj Museum";
museum9.location="Fort";
museum9.city="Mumbai";
museum9.state="Maharashtra";
museum9.country="India";
museum9.numberOfGalleries=50;
museum9.numberOfArtifacts=70000;
museum9.guidedTours=true;
museum9.parkingAvailable=true;
museum9.wifiAvailable=true;
museum9.photographyAllowed=true;
museum9.giftShop=true;
museum9.cafeteria=true;
museum9.securitySystem=true;
museum9.cctvAvailable=true;
museum9.airConditioned=true;
museum9.wheelchairAccess=true;
museum9.onlineTicket=true;
museum9.audioGuide=true;
museum9.exhibitionHall=true;
museum9.researchCenter=true;
museum9.libraryAvailable=true;
museum9.openingTime="10:15 AM";
museum9.closingTime="6:00 PM";
museum9.entryFee=85;

System.out.println("Museum name: "+museum9.name);
System.out.println("Museum location: "+museum9.location);
System.out.println("Museum city: "+museum9.city);
System.out.println("Museum state: "+museum9.state);
System.out.println("Museum country: "+museum9.country);
System.out.println("Number of galleries: "+museum9.numberOfGalleries);
System.out.println("Number of artifacts: "+museum9.numberOfArtifacts);
System.out.println("Guided tours: "+museum9.guidedTours);
System.out.println("Parking available: "+museum9.parkingAvailable);
System.out.println("Wifi available: "+museum9.wifiAvailable);
System.out.println("Photography allowed: "+museum9.photographyAllowed);
System.out.println("Gift shop: "+museum9.giftShop);
System.out.println("Cafeteria: "+museum9.cafeteria);
System.out.println("Security system: "+museum9.securitySystem);
System.out.println("CCTV available: "+museum9.cctvAvailable);
System.out.println("Air conditioned: "+museum9.airConditioned);
System.out.println("Wheelchair access: "+museum9.wheelchairAccess);
System.out.println("Online ticket: "+museum9.onlineTicket);
System.out.println("Audio guide: "+museum9.audioGuide);
System.out.println("Exhibition hall: "+museum9.exhibitionHall);
System.out.println("Research center: "+museum9.researchCenter);
System.out.println("Library available: "+museum9.libraryAvailable);
System.out.println("Opening time: "+museum9.openingTime);
System.out.println("Closing time: "+museum9.closingTime);
System.out.println("Entry fee: "+museum9.entryFee);


Museum museum10 = new Museum();

System.out.println("Museum name: "+museum10.name);
System.out.println("Museum location: "+museum10.location);
System.out.println("Museum city: "+museum10.city);
System.out.println("Museum state: "+museum10.state);
System.out.println("Museum country: "+museum10.country);
System.out.println("Number of galleries: "+museum10.numberOfGalleries);
System.out.println("Number of artifacts: "+museum10.numberOfArtifacts);
System.out.println("Guided tours: "+museum10.guidedTours);
System.out.println("Parking available: "+museum10.parkingAvailable);
System.out.println("Wifi available: "+museum10.wifiAvailable);
System.out.println("Photography allowed: "+museum10.photographyAllowed);
System.out.println("Gift shop: "+museum10.giftShop);
System.out.println("Cafeteria: "+museum10.cafeteria);
System.out.println("Security system: "+museum10.securitySystem);
System.out.println("CCTV available: "+museum10.cctvAvailable);
System.out.println("Air conditioned: "+museum10.airConditioned);
System.out.println("Wheelchair access: "+museum10.wheelchairAccess);
System.out.println("Online ticket: "+museum10.onlineTicket);
System.out.println("Audio guide: "+museum10.audioGuide);
System.out.println("Exhibition hall: "+museum10.exhibitionHall);
System.out.println("Research center: "+museum10.researchCenter);
System.out.println("Library available: "+museum10.libraryAvailable);
System.out.println("Opening time: "+museum10.openingTime);
System.out.println("Closing time: "+museum10.closingTime);
System.out.println("Entry fee: "+museum10.entryFee);

museum10.name="Rail Museum";
museum10.location="Chanakyapuri";
museum10.city="New Delhi";
museum10.state="Delhi";
museum10.country="India";
museum10.numberOfGalleries=15;
museum10.numberOfArtifacts=10000;
museum10.guidedTours=true;
museum10.parkingAvailable=true;
museum10.wifiAvailable=false;
museum10.photographyAllowed=true;
museum10.giftShop=true;
museum10.cafeteria=true;
museum10.securitySystem=true;
museum10.cctvAvailable=true;
museum10.airConditioned=false;
museum10.wheelchairAccess=true;
museum10.onlineTicket=true;
museum10.audioGuide=true;
museum10.exhibitionHall=true;
museum10.researchCenter=false;
museum10.libraryAvailable=true;
museum10.openingTime="10:00 AM";
museum10.closingTime="5:00 PM";
museum10.entryFee=30;

System.out.println("Museum name: "+museum10.name);
System.out.println("Museum location: "+museum10.location);
System.out.println("Museum city: "+museum10.city);
System.out.println("Museum state: "+museum10.state);
System.out.println("Museum country: "+museum10.country);
System.out.println("Number of galleries: "+museum10.numberOfGalleries);
System.out.println("Number of artifacts: "+museum10.numberOfArtifacts);
System.out.println("Guided tours: "+museum10.guidedTours);
System.out.println("Parking available: "+museum10.parkingAvailable);
System.out.println("Wifi available: "+museum10.wifiAvailable);
System.out.println("Photography allowed: "+museum10.photographyAllowed);
System.out.println("Gift shop: "+museum10.giftShop);
System.out.println("Cafeteria: "+museum10.cafeteria);
System.out.println("Security system: "+museum10.securitySystem);
System.out.println("CCTV available: "+museum10.cctvAvailable);
System.out.println("Air conditioned: "+museum10.airConditioned);
System.out.println("Wheelchair access: "+museum10.wheelchairAccess);
System.out.println("Online ticket: "+museum10.onlineTicket);
System.out.println("Audio guide: "+museum10.audioGuide);
System.out.println("Exhibition hall: "+museum10.exhibitionHall);
System.out.println("Research center: "+museum10.researchCenter);
System.out.println("Library available: "+museum10.libraryAvailable);
System.out.println("Opening time: "+museum10.openingTime);
System.out.println("Closing time: "+museum10.closingTime);
System.out.println("Entry fee: "+museum10.entryFee);


}
}