class PostOfficeRunner{
public static void main(String[] officeinfo){

PostOffice postOffice1 = new PostOffice();

System.out.println("PostOffice name: "+postOffice1.name);
System.out.println("PostOffice location: "+postOffice1.location);
System.out.println("PostOffice city: "+postOffice1.city);
System.out.println("PostOffice state: "+postOffice1.state);
System.out.println("PostOffice country: "+postOffice1.country);
System.out.println("PostOffice postal code: "+postOffice1.postalCode);
System.out.println("PostOffice number of counters: "+postOffice1.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice1.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice1.parcelService);
System.out.println("PostOffice speed post: "+postOffice1.speedPost);
System.out.println("PostOffice registered post: "+postOffice1.registeredPost);
System.out.println("PostOffice money order: "+postOffice1.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice1.bankingService);
System.out.println("PostOffice atm available: "+postOffice1.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice1.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice1.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice1.passportService);
System.out.println("PostOffice philately service: "+postOffice1.philatelyService);
System.out.println("PostOffice savings account: "+postOffice1.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice1.insuranceService);
System.out.println("PostOffice courier service: "+postOffice1.courierService);
System.out.println("PostOffice cctv available: "+postOffice1.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice1.openingTime);
System.out.println("PostOffice closing time: "+postOffice1.closingTime);
System.out.println("PostOffice daily customers: "+postOffice1.dailyCustomers);




postOffice1.name = "Bangalore GPO";
postOffice1.location = "Vidhana Soudha Road";
postOffice1.city = "Bangalore";
postOffice1.state = "Karnataka";
postOffice1.country = "India";
postOffice1.postalCode = "560001";
postOffice1.numberOfCounters = 15;
postOffice1.numberOfStaff = 40;
postOffice1.parcelService = true;
postOffice1.speedPost = true;
postOffice1.registeredPost = true;
postOffice1.moneyOrder = true;
postOffice1.bankingService = true;
postOffice1.atmAvailable = true;
postOffice1.parkingAvailable = true;
postOffice1.wifiAvailable = true;
postOffice1.passportService = true;
postOffice1.philatelyService = true;
postOffice1.savingsAccount = true;
postOffice1.insuranceService = true;
postOffice1.courierService = true;
postOffice1.cctvAvailable = true;
postOffice1.openingTime = "09:00 AM";
postOffice1.closingTime = "05:00 PM";
postOffice1.dailyCustomers = 800;

System.out.println("PostOffice name: "+postOffice1.name);
System.out.println("PostOffice location: "+postOffice1.location);
System.out.println("PostOffice city: "+postOffice1.city);
System.out.println("PostOffice state: "+postOffice1.state);
System.out.println("PostOffice country: "+postOffice1.country);
System.out.println("PostOffice postal code: "+postOffice1.postalCode);
System.out.println("PostOffice number of counters: "+postOffice1.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice1.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice1.parcelService);
System.out.println("PostOffice speed post: "+postOffice1.speedPost);
System.out.println("PostOffice registered post: "+postOffice1.registeredPost);
System.out.println("PostOffice money order: "+postOffice1.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice1.bankingService);
System.out.println("PostOffice atm available: "+postOffice1.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice1.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice1.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice1.passportService);
System.out.println("PostOffice philately service: "+postOffice1.philatelyService);
System.out.println("PostOffice savings account: "+postOffice1.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice1.insuranceService);
System.out.println("PostOffice courier service: "+postOffice1.courierService);
System.out.println("PostOffice cctv available: "+postOffice1.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice1.openingTime);
System.out.println("PostOffice closing time: "+postOffice1.closingTime);
System.out.println("PostOffice daily customers: "+postOffice1.dailyCustomers);


PostOffice postOffice2 = new PostOffice();

System.out.println("PostOffice name: "+postOffice2.name);
System.out.println("PostOffice location: "+postOffice2.location);
System.out.println("PostOffice city: "+postOffice2.city);
System.out.println("PostOffice state: "+postOffice2.state);
System.out.println("PostOffice country: "+postOffice2.country);
System.out.println("PostOffice postal code: "+postOffice2.postalCode);
System.out.println("PostOffice number of counters: "+postOffice2.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice2.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice2.parcelService);
System.out.println("PostOffice speed post: "+postOffice2.speedPost);
System.out.println("PostOffice registered post: "+postOffice2.registeredPost);
System.out.println("PostOffice money order: "+postOffice2.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice2.bankingService);
System.out.println("PostOffice atm available: "+postOffice2.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice2.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice2.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice2.passportService);
System.out.println("PostOffice philately service: "+postOffice2.philatelyService);
System.out.println("PostOffice savings account: "+postOffice2.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice2.insuranceService);
System.out.println("PostOffice courier service: "+postOffice2.courierService);
System.out.println("PostOffice cctv available: "+postOffice2.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice2.openingTime);
System.out.println("PostOffice closing time: "+postOffice2.closingTime);
System.out.println("PostOffice daily customers: "+postOffice2.dailyCustomers);


postOffice2.name = "Mysore Head Post Office";
postOffice2.location = "Sayyaji Rao Road";
postOffice2.city = "Mysore";
postOffice2.state = "Karnataka";
postOffice2.country = "India";
postOffice2.postalCode = "570001";
postOffice2.numberOfCounters = 10;
postOffice2.numberOfStaff = 25;
postOffice2.parcelService = true;
postOffice2.speedPost = true;
postOffice2.registeredPost = true;
postOffice2.moneyOrder = true;
postOffice2.bankingService = true;
postOffice2.atmAvailable = false;
postOffice2.parkingAvailable = true;
postOffice2.wifiAvailable = false;
postOffice2.passportService = false;
postOffice2.philatelyService = true;
postOffice2.savingsAccount = true;
postOffice2.insuranceService = true;
postOffice2.courierService = true;
postOffice2.cctvAvailable = true;
postOffice2.openingTime = "09:30 AM";
postOffice2.closingTime = "05:30 PM";
postOffice2.dailyCustomers = 500;

System.out.println("PostOffice name: "+postOffice2.name);
System.out.println("PostOffice location: "+postOffice2.location);
System.out.println("PostOffice city: "+postOffice2.city);
System.out.println("PostOffice state: "+postOffice2.state);
System.out.println("PostOffice country: "+postOffice2.country);
System.out.println("PostOffice postal code: "+postOffice2.postalCode);
System.out.println("PostOffice number of counters: "+postOffice2.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice2.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice2.parcelService);
System.out.println("PostOffice speed post: "+postOffice2.speedPost);
System.out.println("PostOffice registered post: "+postOffice2.registeredPost);
System.out.println("PostOffice money order: "+postOffice2.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice2.bankingService);
System.out.println("PostOffice atm available: "+postOffice2.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice2.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice2.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice2.passportService);
System.out.println("PostOffice philately service: "+postOffice2.philatelyService);
System.out.println("PostOffice savings account: "+postOffice2.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice2.insuranceService);
System.out.println("PostOffice courier service: "+postOffice2.courierService);
System.out.println("PostOffice cctv available: "+postOffice2.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice2.openingTime);
System.out.println("PostOffice closing time: "+postOffice2.closingTime);
System.out.println("PostOffice daily customers: "+postOffice2.dailyCustomers);



PostOffice postOffice3 = new PostOffice();

System.out.println("PostOffice name: "+postOffice3.name);
System.out.println("PostOffice location: "+postOffice3.location);
System.out.println("PostOffice city: "+postOffice3.city);
System.out.println("PostOffice state: "+postOffice3.state);
System.out.println("PostOffice country: "+postOffice3.country);
System.out.println("PostOffice postal code: "+postOffice3.postalCode);
System.out.println("PostOffice number of counters: "+postOffice3.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice3.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice3.parcelService);
System.out.println("PostOffice speed post: "+postOffice3.speedPost);
System.out.println("PostOffice registered post: "+postOffice3.registeredPost);
System.out.println("PostOffice money order: "+postOffice3.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice3.bankingService);
System.out.println("PostOffice atm available: "+postOffice3.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice3.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice3.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice3.passportService);
System.out.println("PostOffice philately service: "+postOffice3.philatelyService);
System.out.println("PostOffice savings account: "+postOffice3.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice3.insuranceService);
System.out.println("PostOffice courier service: "+postOffice3.courierService);
System.out.println("PostOffice cctv available: "+postOffice3.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice3.openingTime);
System.out.println("PostOffice closing time: "+postOffice3.closingTime);
System.out.println("PostOffice daily customers: "+postOffice3.dailyCustomers);


postOffice3.name = "Delhi GPO";
postOffice3.location = "Connaught Place";
postOffice3.city = "New Delhi";
postOffice3.state = "Delhi";
postOffice3.country = "India";
postOffice3.postalCode = "110001";
postOffice3.numberOfCounters = 20;
postOffice3.numberOfStaff = 60;
postOffice3.parcelService = true;
postOffice3.speedPost = true;
postOffice3.registeredPost = true;
postOffice3.moneyOrder = true;
postOffice3.bankingService = true;
postOffice3.atmAvailable = true;
postOffice3.parkingAvailable = true;
postOffice3.wifiAvailable = true;
postOffice3.passportService = true;
postOffice3.philatelyService = true;
postOffice3.savingsAccount = true;
postOffice3.insuranceService = true;
postOffice3.courierService = true;
postOffice3.cctvAvailable = true;
postOffice3.openingTime = "09:00 AM";
postOffice3.closingTime = "06:00 PM";
postOffice3.dailyCustomers = 1200;

System.out.println("PostOffice name: "+postOffice3.name);
System.out.println("PostOffice location: "+postOffice3.location);
System.out.println("PostOffice city: "+postOffice3.city);
System.out.println("PostOffice state: "+postOffice3.state);
System.out.println("PostOffice country: "+postOffice3.country);
System.out.println("PostOffice postal code: "+postOffice3.postalCode);
System.out.println("PostOffice number of counters: "+postOffice3.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice3.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice3.parcelService);
System.out.println("PostOffice speed post: "+postOffice3.speedPost);
System.out.println("PostOffice registered post: "+postOffice3.registeredPost);
System.out.println("PostOffice money order: "+postOffice3.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice3.bankingService);
System.out.println("PostOffice atm available: "+postOffice3.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice3.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice3.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice3.passportService);
System.out.println("PostOffice philately service: "+postOffice3.philatelyService);
System.out.println("PostOffice savings account: "+postOffice3.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice3.insuranceService);
System.out.println("PostOffice courier service: "+postOffice3.courierService);
System.out.println("PostOffice cctv available: "+postOffice3.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice3.openingTime);
System.out.println("PostOffice closing time: "+postOffice3.closingTime);
System.out.println("PostOffice daily customers: "+postOffice3.dailyCustomers);


PostOffice postOffice4 = new PostOffice();

System.out.println("PostOffice name: "+postOffice4.name);
System.out.println("PostOffice location: "+postOffice4.location);
System.out.println("PostOffice city: "+postOffice4.city);
System.out.println("PostOffice state: "+postOffice4.state);
System.out.println("PostOffice country: "+postOffice4.country);
System.out.println("PostOffice postal code: "+postOffice4.postalCode);
System.out.println("PostOffice number of counters: "+postOffice4.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice4.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice4.parcelService);
System.out.println("PostOffice speed post: "+postOffice4.speedPost);
System.out.println("PostOffice registered post: "+postOffice4.registeredPost);
System.out.println("PostOffice money order: "+postOffice4.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice4.bankingService);
System.out.println("PostOffice atm available: "+postOffice4.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice4.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice4.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice4.passportService);
System.out.println("PostOffice philately service: "+postOffice4.philatelyService);
System.out.println("PostOffice savings account: "+postOffice4.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice4.insuranceService);
System.out.println("PostOffice courier service: "+postOffice4.courierService);
System.out.println("PostOffice cctv available: "+postOffice4.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice4.openingTime);
System.out.println("PostOffice closing time: "+postOffice4.closingTime);
System.out.println("PostOffice daily customers: "+postOffice4.dailyCustomers);




postOffice4.name = "Chennai GPO";
postOffice4.location = "Anna Salai";
postOffice4.city = "Chennai";
postOffice4.state = "Tamil Nadu";
postOffice4.country = "India";
postOffice4.postalCode = "600001";
postOffice4.numberOfCounters = 14;
postOffice4.numberOfStaff = 35;
postOffice4.parcelService = true;
postOffice4.speedPost = true;
postOffice4.registeredPost = true;
postOffice4.moneyOrder = true;
postOffice4.bankingService = true;
postOffice4.atmAvailable = true;
postOffice4.parkingAvailable = true;
postOffice4.wifiAvailable = true;
postOffice4.passportService = true;
postOffice4.philatelyService = true;
postOffice4.savingsAccount = true;
postOffice4.insuranceService = true;
postOffice4.courierService = true;
postOffice4.cctvAvailable = true;
postOffice4.openingTime = "09:00 AM";
postOffice4.closingTime = "05:30 PM";
postOffice4.dailyCustomers = 750;

System.out.println("PostOffice name: "+postOffice4.name);
System.out.println("PostOffice location: "+postOffice4.location);
System.out.println("PostOffice city: "+postOffice4.city);
System.out.println("PostOffice state: "+postOffice4.state);
System.out.println("PostOffice country: "+postOffice4.country);
System.out.println("PostOffice postal code: "+postOffice4.postalCode);
System.out.println("PostOffice number of counters: "+postOffice4.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice4.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice4.parcelService);
System.out.println("PostOffice speed post: "+postOffice4.speedPost);
System.out.println("PostOffice registered post: "+postOffice4.registeredPost);
System.out.println("PostOffice money order: "+postOffice4.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice4.bankingService);
System.out.println("PostOffice atm available: "+postOffice4.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice4.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice4.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice4.passportService);
System.out.println("PostOffice philately service: "+postOffice4.philatelyService);
System.out.println("PostOffice savings account: "+postOffice4.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice4.insuranceService);
System.out.println("PostOffice courier service: "+postOffice4.courierService);
System.out.println("PostOffice cctv available: "+postOffice4.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice4.openingTime);
System.out.println("PostOffice closing time: "+postOffice4.closingTime);
System.out.println("PostOffice daily customers: "+postOffice4.dailyCustomers);



PostOffice postOffice5 = new PostOffice();

System.out.println("PostOffice name: "+postOffice5.name);
System.out.println("PostOffice location: "+postOffice5.location);
System.out.println("PostOffice city: "+postOffice5.city);
System.out.println("PostOffice state: "+postOffice5.state);
System.out.println("PostOffice country: "+postOffice5.country);
System.out.println("PostOffice postal code: "+postOffice5.postalCode);
System.out.println("PostOffice number of counters: "+postOffice5.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice5.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice5.parcelService);
System.out.println("PostOffice speed post: "+postOffice5.speedPost);
System.out.println("PostOffice registered post: "+postOffice5.registeredPost);
System.out.println("PostOffice money order: "+postOffice5.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice5.bankingService);
System.out.println("PostOffice atm available: "+postOffice5.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice5.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice5.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice5.passportService);
System.out.println("PostOffice philately service: "+postOffice5.philatelyService);
System.out.println("PostOffice savings account: "+postOffice5.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice5.insuranceService);
System.out.println("PostOffice courier service: "+postOffice5.courierService);
System.out.println("PostOffice cctv available: "+postOffice5.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice5.openingTime);
System.out.println("PostOffice closing time: "+postOffice5.closingTime);
System.out.println("PostOffice daily customers: "+postOffice5.dailyCustomers);


postOffice5.name = "Hyderabad GPO";
postOffice5.location = "Abids";
postOffice5.city = "Hyderabad";
postOffice5.state = "Telangana";
postOffice5.country = "India";
postOffice5.postalCode = "500001";
postOffice5.numberOfCounters = 16;
postOffice5.numberOfStaff = 42;
postOffice5.parcelService = true;
postOffice5.speedPost = true;
postOffice5.registeredPost = true;
postOffice5.moneyOrder = true;
postOffice5.bankingService = true;
postOffice5.atmAvailable = true;
postOffice5.parkingAvailable = true;
postOffice5.wifiAvailable = false;
postOffice5.passportService = true;
postOffice5.philatelyService = true;
postOffice5.savingsAccount = true;
postOffice5.insuranceService = true;
postOffice5.courierService = true;
postOffice5.cctvAvailable = true;
postOffice5.openingTime = "09:00 AM";
postOffice5.closingTime = "05:00 PM";
postOffice5.dailyCustomers = 820;

System.out.println("PostOffice name: "+postOffice5.name);
System.out.println("PostOffice location: "+postOffice5.location);
System.out.println("PostOffice city: "+postOffice5.city);
System.out.println("PostOffice state: "+postOffice5.state);
System.out.println("PostOffice country: "+postOffice5.country);
System.out.println("PostOffice postal code: "+postOffice5.postalCode);
System.out.println("PostOffice number of counters: "+postOffice5.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice5.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice5.parcelService);
System.out.println("PostOffice speed post: "+postOffice5.speedPost);
System.out.println("PostOffice registered post: "+postOffice5.registeredPost);
System.out.println("PostOffice money order: "+postOffice5.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice5.bankingService);
System.out.println("PostOffice atm available: "+postOffice5.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice5.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice5.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice5.passportService);
System.out.println("PostOffice philately service: "+postOffice5.philatelyService);
System.out.println("PostOffice savings account: "+postOffice5.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice5.insuranceService);
System.out.println("PostOffice courier service: "+postOffice5.courierService);
System.out.println("PostOffice cctv available: "+postOffice5.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice5.openingTime);
System.out.println("PostOffice closing time: "+postOffice5.closingTime);
System.out.println("PostOffice daily customers: "+postOffice5.dailyCustomers);


PostOffice postOffice6 = new PostOffice();

System.out.println("PostOffice name: "+postOffice6.name);
System.out.println("PostOffice location: "+postOffice6.location);
System.out.println("PostOffice city: "+postOffice6.city);
System.out.println("PostOffice state: "+postOffice6.state);
System.out.println("PostOffice country: "+postOffice6.country);
System.out.println("PostOffice postal code: "+postOffice6.postalCode);
System.out.println("PostOffice number of counters: "+postOffice6.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice6.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice6.parcelService);
System.out.println("PostOffice speed post: "+postOffice6.speedPost);
System.out.println("PostOffice registered post: "+postOffice6.registeredPost);
System.out.println("PostOffice money order: "+postOffice6.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice6.bankingService);
System.out.println("PostOffice atm available: "+postOffice6.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice6.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice6.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice6.passportService);
System.out.println("PostOffice philately service: "+postOffice6.philatelyService);
System.out.println("PostOffice savings account: "+postOffice6.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice6.insuranceService);
System.out.println("PostOffice courier service: "+postOffice6.courierService);
System.out.println("PostOffice cctv available: "+postOffice6.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice6.openingTime);
System.out.println("PostOffice closing time: "+postOffice6.closingTime);
System.out.println("PostOffice daily customers: "+postOffice6.dailyCustomers);



postOffice6.name = "Mumbai GPO";
postOffice6.location = "Fort";
postOffice6.city = "Mumbai";
postOffice6.state = "Maharashtra";
postOffice6.country = "India";
postOffice6.postalCode = "400001";
postOffice6.numberOfCounters = 20;
postOffice6.numberOfStaff = 60;
postOffice6.parcelService = true;
postOffice6.speedPost = true;
postOffice6.registeredPost = true;
postOffice6.moneyOrder = true;
postOffice6.bankingService = true;
postOffice6.atmAvailable = true;
postOffice6.parkingAvailable = true;
postOffice6.wifiAvailable = true;
postOffice6.passportService = true;
postOffice6.philatelyService = true;
postOffice6.savingsAccount = true;
postOffice6.insuranceService = true;
postOffice6.courierService = true;
postOffice6.cctvAvailable = true;
postOffice6.openingTime = "09:00 AM";
postOffice6.closingTime = "06:00 PM";
postOffice6.dailyCustomers = 1200;

System.out.println("PostOffice name: "+postOffice6.name);
System.out.println("PostOffice location: "+postOffice6.location);
System.out.println("PostOffice city: "+postOffice6.city);
System.out.println("PostOffice state: "+postOffice6.state);
System.out.println("PostOffice country: "+postOffice6.country);
System.out.println("PostOffice postal code: "+postOffice6.postalCode);
System.out.println("PostOffice number of counters: "+postOffice6.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice6.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice6.parcelService);
System.out.println("PostOffice speed post: "+postOffice6.speedPost);
System.out.println("PostOffice registered post: "+postOffice6.registeredPost);
System.out.println("PostOffice money order: "+postOffice6.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice6.bankingService);
System.out.println("PostOffice atm available: "+postOffice6.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice6.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice6.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice6.passportService);
System.out.println("PostOffice philately service: "+postOffice6.philatelyService);
System.out.println("PostOffice savings account: "+postOffice6.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice6.insuranceService);
System.out.println("PostOffice courier service: "+postOffice6.courierService);
System.out.println("PostOffice cctv available: "+postOffice6.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice6.openingTime);
System.out.println("PostOffice closing time: "+postOffice6.closingTime);
System.out.println("PostOffice daily customers: "+postOffice6.dailyCustomers);



PostOffice postOffice7 = new PostOffice();

System.out.println("PostOffice name: "+postOffice7.name);
System.out.println("PostOffice location: "+postOffice7.location);
System.out.println("PostOffice city: "+postOffice7.city);
System.out.println("PostOffice state: "+postOffice7.state);
System.out.println("PostOffice country: "+postOffice7.country);
System.out.println("PostOffice postal code: "+postOffice7.postalCode);
System.out.println("PostOffice number of counters: "+postOffice7.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice7.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice7.parcelService);
System.out.println("PostOffice speed post: "+postOffice7.speedPost);
System.out.println("PostOffice registered post: "+postOffice7.registeredPost);
System.out.println("PostOffice money order: "+postOffice7.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice7.bankingService);
System.out.println("PostOffice atm available: "+postOffice7.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice7.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice7.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice7.passportService);
System.out.println("PostOffice philately service: "+postOffice7.philatelyService);
System.out.println("PostOffice savings account: "+postOffice7.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice7.insuranceService);
System.out.println("PostOffice courier service: "+postOffice7.courierService);
System.out.println("PostOffice cctv available: "+postOffice7.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice7.openingTime);
System.out.println("PostOffice closing time: "+postOffice7.closingTime);
System.out.println("PostOffice daily customers: "+postOffice7.dailyCustomers);


postOffice7.name = "Delhi GPO";
postOffice7.location = "Connaught Place";
postOffice7.city = "New Delhi";
postOffice7.state = "Delhi";
postOffice7.country = "India";
postOffice7.postalCode = "110001";
postOffice7.numberOfCounters = 18;
postOffice7.numberOfStaff = 50;
postOffice7.parcelService = true;
postOffice7.speedPost = true;
postOffice7.registeredPost = true;
postOffice7.moneyOrder = true;
postOffice7.bankingService = true;
postOffice7.atmAvailable = true;
postOffice7.parkingAvailable = true;
postOffice7.wifiAvailable = true;
postOffice7.passportService = true;
postOffice7.philatelyService = true;
postOffice7.savingsAccount = true;
postOffice7.insuranceService = true;
postOffice7.courierService = true;
postOffice7.cctvAvailable = true;
postOffice7.openingTime = "09:30 AM";
postOffice7.closingTime = "05:30 PM";
postOffice7.dailyCustomers = 950;

System.out.println("PostOffice name: "+postOffice7.name);
System.out.println("PostOffice location: "+postOffice7.location);
System.out.println("PostOffice city: "+postOffice7.city);
System.out.println("PostOffice state: "+postOffice7.state);
System.out.println("PostOffice country: "+postOffice7.country);
System.out.println("PostOffice postal code: "+postOffice7.postalCode);
System.out.println("PostOffice number of counters: "+postOffice7.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice7.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice7.parcelService);
System.out.println("PostOffice speed post: "+postOffice7.speedPost);
System.out.println("PostOffice registered post: "+postOffice7.registeredPost);
System.out.println("PostOffice money order: "+postOffice7.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice7.bankingService);
System.out.println("PostOffice atm available: "+postOffice7.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice7.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice7.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice7.passportService);
System.out.println("PostOffice philately service: "+postOffice7.philatelyService);
System.out.println("PostOffice savings account: "+postOffice7.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice7.insuranceService);
System.out.println("PostOffice courier service: "+postOffice7.courierService);
System.out.println("PostOffice cctv available: "+postOffice7.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice7.openingTime);
System.out.println("PostOffice closing time: "+postOffice7.closingTime);
System.out.println("PostOffice daily customers: "+postOffice7.dailyCustomers);


PostOffice postOffice8 = new PostOffice();

System.out.println("PostOffice name: "+postOffice8.name);
System.out.println("PostOffice location: "+postOffice8.location);
System.out.println("PostOffice city: "+postOffice8.city);
System.out.println("PostOffice state: "+postOffice8.state);
System.out.println("PostOffice country: "+postOffice8.country);
System.out.println("PostOffice postal code: "+postOffice8.postalCode);
System.out.println("PostOffice number of counters: "+postOffice8.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice8.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice8.parcelService);
System.out.println("PostOffice speed post: "+postOffice8.speedPost);
System.out.println("PostOffice registered post: "+postOffice8.registeredPost);
System.out.println("PostOffice money order: "+postOffice8.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice8.bankingService);
System.out.println("PostOffice atm available: "+postOffice8.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice8.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice8.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice8.passportService);
System.out.println("PostOffice philately service: "+postOffice8.philatelyService);
System.out.println("PostOffice savings account: "+postOffice8.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice8.insuranceService);
System.out.println("PostOffice courier service: "+postOffice8.courierService);
System.out.println("PostOffice cctv available: "+postOffice8.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice8.openingTime);
System.out.println("PostOffice closing time: "+postOffice8.closingTime);
System.out.println("PostOffice daily customers: "+postOffice8.dailyCustomers);



postOffice8.name = "Bangalore GPO";
postOffice8.location = "Rajbhavan Road";
postOffice8.city = "Bangalore";
postOffice8.state = "Karnataka";
postOffice8.country = "India";
postOffice8.postalCode = "560001";
postOffice8.numberOfCounters = 16;
postOffice8.numberOfStaff = 45;
postOffice8.parcelService = true;
postOffice8.speedPost = true;
postOffice8.registeredPost = true;
postOffice8.moneyOrder = true;
postOffice8.bankingService = true;
postOffice8.atmAvailable = true;
postOffice8.parkingAvailable = true;
postOffice8.wifiAvailable = true;
postOffice8.passportService = true;
postOffice8.philatelyService = true;
postOffice8.savingsAccount = true;
postOffice8.insuranceService = true;
postOffice8.courierService = true;
postOffice8.cctvAvailable = true;
postOffice8.openingTime = "09:00 AM";
postOffice8.closingTime = "05:30 PM";
postOffice8.dailyCustomers = 870;

System.out.println("PostOffice name: "+postOffice8.name);
System.out.println("PostOffice location: "+postOffice8.location);
System.out.println("PostOffice city: "+postOffice8.city);
System.out.println("PostOffice state: "+postOffice8.state);
System.out.println("PostOffice country: "+postOffice8.country);
System.out.println("PostOffice postal code: "+postOffice8.postalCode);
System.out.println("PostOffice number of counters: "+postOffice8.numberOfCounters);
System.out.println("PostOffice number of staff: "+postOffice8.numberOfStaff);
System.out.println("PostOffice parcel service: "+postOffice8.parcelService);
System.out.println("PostOffice speed post: "+postOffice8.speedPost);
System.out.println("PostOffice registered post: "+postOffice8.registeredPost);
System.out.println("PostOffice money order: "+postOffice8.moneyOrder);
System.out.println("PostOffice banking service: "+postOffice8.bankingService);
System.out.println("PostOffice atm available: "+postOffice8.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice8.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice8.wifiAvailable);
System.out.println("PostOffice passport service: "+postOffice8.passportService);
System.out.println("PostOffice philately service: "+postOffice8.philatelyService);
System.out.println("PostOffice savings account: "+postOffice8.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice8.insuranceService);
System.out.println("PostOffice courier service: "+postOffice8.courierService);
System.out.println("PostOffice cctv available: "+postOffice8.cctvAvailable);
System.out.println("PostOffice opening time: "+postOffice8.openingTime);
System.out.println("PostOffice closing time: "+postOffice8.closingTime);
System.out.println("PostOffice daily customers: "+postOffice8.dailyCustomers);



PostOffice postOffice9 = new PostOffice();

System.out.println("PostOffice name: "+postOffice9.name);
System.out.println("PostOffice location: "+postOffice9.location);
System.out.println("PostOffice city: "+postOffice9.city);
System.out.println("PostOffice state: "+postOffice9.state);
System.out.println("PostOffice country: "+postOffice9.country);
System.out.println("PostOffice postal code: "+postOffice9.postalCode);
System.out.println("PostOffice number of counters: "+postOffice9.numberOfCounters);
System.out.println("PostOffice number of employees: "+postOffice9.numberOfEmployees);
System.out.println("PostOffice daily customers: "+postOffice9.dailyCustomers);
System.out.println("PostOffice speed post service: "+postOffice9.speedPostService);
System.out.println("PostOffice registered post service: "+postOffice9.registeredPostService);
System.out.println("PostOffice parcel service: "+postOffice9.parcelService);
System.out.println("PostOffice money order service: "+postOffice9.moneyOrderService);
System.out.println("PostOffice savings account: "+postOffice9.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice9.insuranceService);
System.out.println("PostOffice ATM available: "+postOffice9.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice9.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice9.wifiAvailable);
System.out.println("PostOffice waiting area: "+postOffice9.waitingArea);
System.out.println("PostOffice restrooms: "+postOffice9.restrooms);
System.out.println("PostOffice security system: "+postOffice9.securitySystem);
System.out.println("PostOffice courier service: "+postOffice9.courierService);
System.out.println("PostOffice opening time: "+postOffice9.openingTime);
System.out.println("PostOffice closing time: "+postOffice9.closingTime);
System.out.println("PostOffice entry fee: "+postOffice9.entryFee);



postOffice9.name = "MG Road Post Office";
postOffice9.location = "MG Road";
postOffice9.city = "Bangalore";
postOffice9.state = "Karnataka";
postOffice9.country = "India";
postOffice9.postalCode = "560001";
postOffice9.numberOfCounters = 12;
postOffice9.numberOfEmployees = 40;
postOffice9.dailyCustomers = 900;
postOffice9.speedPostService = true;
postOffice9.registeredPostService = true;
postOffice9.parcelService = true;
postOffice9.moneyOrderService = true;
postOffice9.savingsAccount = true;
postOffice9.insuranceService = true;
postOffice9.atmAvailable = true;
postOffice9.parkingAvailable = true;
postOffice9.wifiAvailable = false;
postOffice9.waitingArea = true;
postOffice9.restrooms = true;
postOffice9.securitySystem = true;
postOffice9.courierService = true;
postOffice9.openingTime = "9:00 AM";
postOffice9.closingTime = "5:00 PM";
postOffice9.entryFee = 0;

System.out.println("PostOffice name: "+postOffice9.name);
System.out.println("PostOffice location: "+postOffice9.location);
System.out.println("PostOffice city: "+postOffice9.city);
System.out.println("PostOffice state: "+postOffice9.state);
System.out.println("PostOffice country: "+postOffice9.country);
System.out.println("PostOffice postal code: "+postOffice9.postalCode);
System.out.println("PostOffice number of counters: "+postOffice9.numberOfCounters);
System.out.println("PostOffice number of employees: "+postOffice9.numberOfEmployees);
System.out.println("PostOffice daily customers: "+postOffice9.dailyCustomers);
System.out.println("PostOffice speed post service: "+postOffice9.speedPostService);
System.out.println("PostOffice registered post service: "+postOffice9.registeredPostService);
System.out.println("PostOffice parcel service: "+postOffice9.parcelService);
System.out.println("PostOffice money order service: "+postOffice9.moneyOrderService);
System.out.println("PostOffice savings account: "+postOffice9.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice9.insuranceService);
System.out.println("PostOffice ATM available: "+postOffice9.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice9.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice9.wifiAvailable);
System.out.println("PostOffice waiting area: "+postOffice9.waitingArea);
System.out.println("PostOffice restrooms: "+postOffice9.restrooms);
System.out.println("PostOffice security system: "+postOffice9.securitySystem);
System.out.println("PostOffice courier service: "+postOffice9.courierService);
System.out.println("PostOffice opening time: "+postOffice9.openingTime);
System.out.println("PostOffice closing time: "+postOffice9.closingTime);
System.out.println("PostOffice entry fee: "+postOffice9.entryFee);



PostOffice postOffice10 = new PostOffice();

System.out.println("PostOffice name: "+postOffice10.name);
System.out.println("PostOffice location: "+postOffice10.location);
System.out.println("PostOffice city: "+postOffice10.city);
System.out.println("PostOffice state: "+postOffice10.state);
System.out.println("PostOffice country: "+postOffice10.country);
System.out.println("PostOffice postal code: "+postOffice10.postalCode);
System.out.println("PostOffice number of counters: "+postOffice10.numberOfCounters);
System.out.println("PostOffice number of employees: "+postOffice10.numberOfEmployees);
System.out.println("PostOffice daily customers: "+postOffice10.dailyCustomers);
System.out.println("PostOffice speed post service: "+postOffice10.speedPostService);
System.out.println("PostOffice registered post service: "+postOffice10.registeredPostService);
System.out.println("PostOffice parcel service: "+postOffice10.parcelService);
System.out.println("PostOffice money order service: "+postOffice10.moneyOrderService);
System.out.println("PostOffice savings account: "+postOffice10.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice10.insuranceService);
System.out.println("PostOffice ATM available: "+postOffice10.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice10.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice10.wifiAvailable);
System.out.println("PostOffice waiting area: "+postOffice10.waitingArea);
System.out.println("PostOffice restrooms: "+postOffice10.restrooms);
System.out.println("PostOffice security system: "+postOffice10.securitySystem);
System.out.println("PostOffice courier service: "+postOffice10.courierService);
System.out.println("PostOffice opening time: "+postOffice10.openingTime);
System.out.println("PostOffice closing time: "+postOffice10.closingTime);
System.out.println("PostOffice entry fee: "+postOffice10.entryFee);



postOffice10.name = "Connaught Place Post Office";
postOffice10.location = "Connaught Place";
postOffice10.city = "New Delhi";
postOffice10.state = "Delhi";
postOffice10.country = "India";
postOffice10.postalCode = "110001";
postOffice10.numberOfCounters = 14;
postOffice10.numberOfEmployees = 45;
postOffice10.dailyCustomers = 1000;
postOffice10.speedPostService = true;
postOffice10.registeredPostService = true;
postOffice10.parcelService = true;
postOffice10.moneyOrderService = true;
postOffice10.savingsAccount = true;
postOffice10.insuranceService = true;
postOffice10.atmAvailable = true;
postOffice10.parkingAvailable = true;
postOffice10.wifiAvailable = true;
postOffice10.waitingArea = true;
postOffice10.restrooms = true;
postOffice10.securitySystem = true;
postOffice10.courierService = true;
postOffice10.openingTime = "9:00 AM";
postOffice10.closingTime = "5:30 PM";
postOffice10.entryFee = 0;

System.out.println("PostOffice name: "+postOffice10.name);
System.out.println("PostOffice location: "+postOffice10.location);
System.out.println("PostOffice city: "+postOffice10.city);
System.out.println("PostOffice state: "+postOffice10.state);
System.out.println("PostOffice country: "+postOffice10.country);
System.out.println("PostOffice postal code: "+postOffice10.postalCode);
System.out.println("PostOffice number of counters: "+postOffice10.numberOfCounters);
System.out.println("PostOffice number of employees: "+postOffice10.numberOfEmployees);
System.out.println("PostOffice daily customers: "+postOffice10.dailyCustomers);
System.out.println("PostOffice speed post service: "+postOffice10.speedPostService);
System.out.println("PostOffice registered post service: "+postOffice10.registeredPostService);
System.out.println("PostOffice parcel service: "+postOffice10.parcelService);
System.out.println("PostOffice money order service: "+postOffice10.moneyOrderService);
System.out.println("PostOffice savings account: "+postOffice10.savingsAccount);
System.out.println("PostOffice insurance service: "+postOffice10.insuranceService);
System.out.println("PostOffice ATM available: "+postOffice10.atmAvailable);
System.out.println("PostOffice parking available: "+postOffice10.parkingAvailable);
System.out.println("PostOffice wifi available: "+postOffice10.wifiAvailable);
System.out.println("PostOffice waiting area: "+postOffice10.waitingArea);
System.out.println("PostOffice restrooms: "+postOffice10.restrooms);
System.out.println("PostOffice security system: "+postOffice10.securitySystem);
System.out.println("PostOffice courier service: "+postOffice10.courierService);
System.out.println("PostOffice opening time: "+postOffice10.openingTime);
System.out.println("PostOffice closing time: "+postOffice10.closingTime);
System.out.println("PostOffice entry fee: "+postOffice10.entryFee);


}
}