class  ShoppingMallRunner{


public static void main(String[] mallinfo){


 ShoppingMall shoppingMall1 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall1.name);
System.out.println("Location: "+shoppingMall1.location);
System.out.println("City: "+shoppingMall1.city);
System.out.println("State: "+shoppingMall1.state);
System.out.println("Country: "+shoppingMall1.country);
System.out.println("Number Of Floors: "+shoppingMall1.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall1.numberOfShops);
System.out.println("Food Court: "+shoppingMall1.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall1.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall1.gamingZone);
System.out.println("Parking Available: "+shoppingMall1.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall1.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall1.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall1.escalatorAvailable);
System.out.println("Security System: "+shoppingMall1.securitySystem);
System.out.println("CCTV Available: "+shoppingMall1.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall1.atmAvailable);
System.out.println("Supermarket: "+shoppingMall1.supermarket);
System.out.println("Clothing Stores: "+shoppingMall1.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall1.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall1.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall1.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall1.openingTime);
System.out.println("Closing Time: "+shoppingMall1.closingTime);
System.out.println("Entry Fee: "+shoppingMall1.entryFee);


shoppingMall1.name = "Orion Mall";
shoppingMall1.location = "Rajajinagar";
shoppingMall1.city = "Bangalore";
shoppingMall1.state = "Karnataka";
shoppingMall1.country = "India";
shoppingMall1.numberOfFloors = 6;
shoppingMall1.numberOfShops = 250;
shoppingMall1.foodCourt = true;
shoppingMall1.cinemaHall = true;
shoppingMall1.gamingZone = true;
shoppingMall1.parkingAvailable = true;
shoppingMall1.wifiAvailable = true;
shoppingMall1.elevatorAvailable = true;
shoppingMall1.escalatorAvailable = true;
shoppingMall1.securitySystem = true;
shoppingMall1.cctvAvailable = true;
shoppingMall1.atmAvailable = true;
shoppingMall1.supermarket = true;
shoppingMall1.clothingStores = true;
shoppingMall1.electronicsStores = true;
shoppingMall1.kidsPlayArea = true;
shoppingMall1.wheelchairAccess = true;
shoppingMall1.openingTime = "10:00 AM";
shoppingMall1.closingTime = "10:00 PM";
shoppingMall1.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall1.name);
System.out.println("Location: "+shoppingMall1.location);
System.out.println("City: "+shoppingMall1.city);
System.out.println("State: "+shoppingMall1.state);
System.out.println("Country: "+shoppingMall1.country);
System.out.println("Number Of Floors: "+shoppingMall1.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall1.numberOfShops);
System.out.println("Food Court: "+shoppingMall1.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall1.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall1.gamingZone);
System.out.println("Parking Available: "+shoppingMall1.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall1.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall1.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall1.escalatorAvailable);
System.out.println("Security System: "+shoppingMall1.securitySystem);
System.out.println("CCTV Available: "+shoppingMall1.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall1.atmAvailable);
System.out.println("Supermarket: "+shoppingMall1.supermarket);
System.out.println("Clothing Stores: "+shoppingMall1.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall1.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall1.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall1.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall1.openingTime);
System.out.println("Closing Time: "+shoppingMall1.closingTime);
System.out.println("Entry Fee: "+shoppingMall1.entryFee);


ShoppingMall shoppingMall2 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall2.name);
System.out.println("Location: "+shoppingMall2.location);
System.out.println("City: "+shoppingMall2.city);
System.out.println("State: "+shoppingMall2.state);
System.out.println("Country: "+shoppingMall2.country);
System.out.println("Number Of Floors: "+shoppingMall2.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall2.numberOfShops);
System.out.println("Food Court: "+shoppingMall2.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall2.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall2.gamingZone);
System.out.println("Parking Available: "+shoppingMall2.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall2.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall2.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall2.escalatorAvailable);
System.out.println("Security System: "+shoppingMall2.securitySystem);
System.out.println("CCTV Available: "+shoppingMall2.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall2.atmAvailable);
System.out.println("Supermarket: "+shoppingMall2.supermarket);
System.out.println("Clothing Stores: "+shoppingMall2.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall2.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall2.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall2.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall2.openingTime);
System.out.println("Closing Time: "+shoppingMall2.closingTime);
System.out.println("Entry Fee: "+shoppingMall2.entryFee);

shoppingMall2.name = "Garuda Mall";
shoppingMall2.location = "Magrath Road";
shoppingMall2.city = "Bangalore";
shoppingMall2.state = "Karnataka";
shoppingMall2.country = "India";
shoppingMall2.numberOfFloors = 5;
shoppingMall2.numberOfShops = 180;
shoppingMall2.foodCourt = true;
shoppingMall2.cinemaHall = true;
shoppingMall2.gamingZone = true;
shoppingMall2.parkingAvailable = true;
shoppingMall2.wifiAvailable = true;
shoppingMall2.elevatorAvailable = true;
shoppingMall2.escalatorAvailable = true;
shoppingMall2.securitySystem = true;
shoppingMall2.cctvAvailable = true;
shoppingMall2.atmAvailable = true;
shoppingMall2.supermarket = true;
shoppingMall2.clothingStores = true;
shoppingMall2.electronicsStores = true;
shoppingMall2.kidsPlayArea = true;
shoppingMall2.wheelchairAccess = true;
shoppingMall2.openingTime = "10:30 AM";
shoppingMall2.closingTime = "10:30 PM";
shoppingMall2.entryFee = 0;


System.out.println("Shopping Mall name: "+shoppingMall2.name);
System.out.println("Location: "+shoppingMall2.location);
System.out.println("City: "+shoppingMall2.city);
System.out.println("State: "+shoppingMall2.state);
System.out.println("Country: "+shoppingMall2.country);
System.out.println("Number Of Floors: "+shoppingMall2.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall2.numberOfShops);
System.out.println("Food Court: "+shoppingMall2.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall2.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall2.gamingZone);
System.out.println("Parking Available: "+shoppingMall2.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall2.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall2.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall2.escalatorAvailable);
System.out.println("Security System: "+shoppingMall2.securitySystem);
System.out.println("CCTV Available: "+shoppingMall2.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall2.atmAvailable);
System.out.println("Supermarket: "+shoppingMall2.supermarket);
System.out.println("Clothing Stores: "+shoppingMall2.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall2.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall2.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall2.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall2.openingTime);
System.out.println("Closing Time: "+shoppingMall2.closingTime);
System.out.println("Entry Fee: "+shoppingMall2.entryFee);




ShoppingMall shoppingMall3 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall3.name);
System.out.println("Location: "+shoppingMall3.location);
System.out.println("City: "+shoppingMall3.city);
System.out.println("State: "+shoppingMall3.state);
System.out.println("Country: "+shoppingMall3.country);
System.out.println("Number Of Floors: "+shoppingMall3.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall3.numberOfShops);
System.out.println("Food Court: "+shoppingMall3.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall3.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall3.gamingZone);
System.out.println("Parking Available: "+shoppingMall3.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall3.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall3.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall3.escalatorAvailable);
System.out.println("Security System: "+shoppingMall3.securitySystem);
System.out.println("CCTV Available: "+shoppingMall3.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall3.atmAvailable);
System.out.println("Supermarket: "+shoppingMall3.supermarket);
System.out.println("Clothing Stores: "+shoppingMall3.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall3.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall3.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall3.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall3.openingTime);
System.out.println("Closing Time: "+shoppingMall3.closingTime);
System.out.println("Entry Fee: "+shoppingMall3.entryFee);


shoppingMall3.name = "Forum Mall";
shoppingMall3.location = "Koramangala";
shoppingMall3.city = "Bangalore";
shoppingMall3.state = "Karnataka";
shoppingMall3.country = "India";
shoppingMall3.numberOfFloors = 6;
shoppingMall3.numberOfShops = 200;
shoppingMall3.foodCourt = true;
shoppingMall3.cinemaHall = true;
shoppingMall3.gamingZone = true;
shoppingMall3.parkingAvailable = true;
shoppingMall3.wifiAvailable = true;
shoppingMall3.elevatorAvailable = true;
shoppingMall3.escalatorAvailable = true;
shoppingMall3.securitySystem = true;
shoppingMall3.cctvAvailable = true;
shoppingMall3.atmAvailable = true;
shoppingMall3.supermarket = true;
shoppingMall3.clothingStores = true;
shoppingMall3.electronicsStores = true;
shoppingMall3.kidsPlayArea = true;
shoppingMall3.wheelchairAccess = true;
shoppingMall3.openingTime = "10:00 AM";
shoppingMall3.closingTime = "10:00 PM";
shoppingMall3.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall3.name);
System.out.println("Location: "+shoppingMall3.location);
System.out.println("City: "+shoppingMall3.city);
System.out.println("State: "+shoppingMall3.state);
System.out.println("Country: "+shoppingMall3.country);
System.out.println("Number Of Floors: "+shoppingMall3.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall3.numberOfShops);
System.out.println("Food Court: "+shoppingMall3.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall3.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall3.gamingZone);
System.out.println("Parking Available: "+shoppingMall3.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall3.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall3.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall3.escalatorAvailable);
System.out.println("Security System: "+shoppingMall3.securitySystem);
System.out.println("CCTV Available: "+shoppingMall3.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall3.atmAvailable);
System.out.println("Supermarket: "+shoppingMall3.supermarket);
System.out.println("Clothing Stores: "+shoppingMall3.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall3.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall3.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall3.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall3.openingTime);
System.out.println("Closing Time: "+shoppingMall3.closingTime);
System.out.println("Entry Fee: "+shoppingMall3.entryFee);


ShoppingMall shoppingMall4 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall4.name);
System.out.println("Location: "+shoppingMall4.location);
System.out.println("City: "+shoppingMall4.city);
System.out.println("State: "+shoppingMall4.state);
System.out.println("Country: "+shoppingMall4.country);
System.out.println("Number Of Floors: "+shoppingMall4.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall4.numberOfShops);
System.out.println("Food Court: "+shoppingMall4.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall4.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall4.gamingZone);
System.out.println("Parking Available: "+shoppingMall4.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall4.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall4.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall4.escalatorAvailable);
System.out.println("Security System: "+shoppingMall4.securitySystem);
System.out.println("CCTV Available: "+shoppingMall4.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall4.atmAvailable);
System.out.println("Supermarket: "+shoppingMall4.supermarket);
System.out.println("Clothing Stores: "+shoppingMall4.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall4.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall4.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall4.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall4.openingTime);
System.out.println("Closing Time: "+shoppingMall4.closingTime);
System.out.println("Entry Fee: "+shoppingMall4.entryFee);

shoppingMall4.name = "Phoenix Marketcity";
shoppingMall4.location = "Whitefield";
shoppingMall4.city = "Bangalore";
shoppingMall4.state = "Karnataka";
shoppingMall4.country = "India";
shoppingMall4.numberOfFloors = 7;
shoppingMall4.numberOfShops = 300;
shoppingMall4.foodCourt = true;
shoppingMall4.cinemaHall = true;
shoppingMall4.gamingZone = true;
shoppingMall4.parkingAvailable = true;
shoppingMall4.wifiAvailable = true;
shoppingMall4.elevatorAvailable = true;
shoppingMall4.escalatorAvailable = true;
shoppingMall4.securitySystem = true;
shoppingMall4.cctvAvailable = true;
shoppingMall4.atmAvailable = true;
shoppingMall4.supermarket = true;
shoppingMall4.clothingStores = true;
shoppingMall4.electronicsStores = true;
shoppingMall4.kidsPlayArea = true;
shoppingMall4.wheelchairAccess = true;
shoppingMall4.openingTime = "10:00 AM";
shoppingMall4.closingTime = "11:00 PM";
shoppingMall4.entryFee = 0;


System.out.println("Shopping Mall name: "+shoppingMall4.name);
System.out.println("Location: "+shoppingMall4.location);
System.out.println("City: "+shoppingMall4.city);
System.out.println("State: "+shoppingMall4.state);
System.out.println("Country: "+shoppingMall4.country);
System.out.println("Number Of Floors: "+shoppingMall4.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall4.numberOfShops);
System.out.println("Food Court: "+shoppingMall4.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall4.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall4.gamingZone);
System.out.println("Parking Available: "+shoppingMall4.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall4.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall4.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall4.escalatorAvailable);
System.out.println("Security System: "+shoppingMall4.securitySystem);
System.out.println("CCTV Available: "+shoppingMall4.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall4.atmAvailable);
System.out.println("Supermarket: "+shoppingMall4.supermarket);
System.out.println("Clothing Stores: "+shoppingMall4.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall4.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall4.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall4.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall4.openingTime);
System.out.println("Closing Time: "+shoppingMall4.closingTime);
System.out.println("Entry Fee: "+shoppingMall4.entryFee);


ShoppingMall shoppingMall5 = new ShoppingMall();

shoppingMall5.name = "Lulu Mall";
shoppingMall5.location = "Rajaji Nagar";
shoppingMall5.city = "Bangalore";
shoppingMall5.state = "Karnataka";
shoppingMall5.country = "India";
shoppingMall5.numberOfFloors = 8;
shoppingMall5.numberOfShops = 350;
shoppingMall5.foodCourt = true;
shoppingMall5.cinemaHall = true;
shoppingMall5.gamingZone = true;
shoppingMall5.parkingAvailable = true;
shoppingMall5.wifiAvailable = true;
shoppingMall5.elevatorAvailable = true;
shoppingMall5.escalatorAvailable = true;
shoppingMall5.securitySystem = true;
shoppingMall5.cctvAvailable = true;
shoppingMall5.atmAvailable = true;
shoppingMall5.supermarket = true;
shoppingMall5.clothingStores = true;
shoppingMall5.electronicsStores = true;
shoppingMall5.kidsPlayArea = true;
shoppingMall5.wheelchairAccess = true;
shoppingMall5.openingTime = "10:00 AM";
shoppingMall5.closingTime = "11:00 PM";
shoppingMall5.entryFee = 0;


System.out.println("Shopping Mall name: "+shoppingMall5.name);
System.out.println("Location: "+shoppingMall5.location);
System.out.println("City: "+shoppingMall5.city);
System.out.println("State: "+shoppingMall5.state);
System.out.println("Country: "+shoppingMall5.country);
System.out.println("Number Of Floors: "+shoppingMall5.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall5.numberOfShops);
System.out.println("Food Court: "+shoppingMall5.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall5.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall5.gamingZone);
System.out.println("Parking Available: "+shoppingMall5.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall5.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall5.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall5.escalatorAvailable);
System.out.println("Security System: "+shoppingMall5.securitySystem);
System.out.println("CCTV Available: "+shoppingMall5.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall5.atmAvailable);
System.out.println("Supermarket: "+shoppingMall5.supermarket);
System.out.println("Clothing Stores: "+shoppingMall5.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall5.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall5.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall5.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall5.openingTime);
System.out.println("Closing Time: "+shoppingMall5.closingTime);
System.out.println("Entry Fee: "+shoppingMall5.entryFee);



ShoppingMall shoppingMall6 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall6.name);
System.out.println("Location: "+shoppingMall6.location);
System.out.println("City: "+shoppingMall6.city);
System.out.println("State: "+shoppingMall6.state);
System.out.println("Country: "+shoppingMall6.country);
System.out.println("Number Of Floors: "+shoppingMall6.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall6.numberOfShops);
System.out.println("Food Court: "+shoppingMall6.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall6.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall6.gamingZone);
System.out.println("Parking Available: "+shoppingMall6.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall6.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall6.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall6.escalatorAvailable);
System.out.println("Security System: "+shoppingMall6.securitySystem);
System.out.println("CCTV Available: "+shoppingMall6.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall6.atmAvailable);
System.out.println("Supermarket: "+shoppingMall6.supermarket);
System.out.println("Clothing Stores: "+shoppingMall6.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall6.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall6.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall6.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall6.openingTime);
System.out.println("Closing Time: "+shoppingMall6.closingTime);
System.out.println("Entry Fee: "+shoppingMall6.entryFee);

shoppingMall6.name = "GT World Mall";
shoppingMall6.location = "Magadi Road";
shoppingMall6.city = "Bangalore";
shoppingMall6.state = "Karnataka";
shoppingMall6.country = "India";
shoppingMall6.numberOfFloors = 5;
shoppingMall6.numberOfShops = 150;
shoppingMall6.foodCourt = true;
shoppingMall6.cinemaHall = true;
shoppingMall6.gamingZone = false;
shoppingMall6.parkingAvailable = true;
shoppingMall6.wifiAvailable = true;
shoppingMall6.elevatorAvailable = true;
shoppingMall6.escalatorAvailable = true;
shoppingMall6.securitySystem = true;
shoppingMall6.cctvAvailable = true;
shoppingMall6.atmAvailable = true;
shoppingMall6.supermarket = true;
shoppingMall6.clothingStores = true;
shoppingMall6.electronicsStores = true;
shoppingMall6.kidsPlayArea = false;
shoppingMall6.wheelchairAccess = true;
shoppingMall6.openingTime = "10:00 AM";
shoppingMall6.closingTime = "10:00 PM";
shoppingMall6.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall6.name);
System.out.println("Location: "+shoppingMall6.location);
System.out.println("City: "+shoppingMall6.city);
System.out.println("State: "+shoppingMall6.state);
System.out.println("Country: "+shoppingMall6.country);
System.out.println("Number Of Floors: "+shoppingMall6.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall6.numberOfShops);
System.out.println("Food Court: "+shoppingMall6.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall6.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall6.gamingZone);
System.out.println("Parking Available: "+shoppingMall6.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall6.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall6.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall6.escalatorAvailable);
System.out.println("Security System: "+shoppingMall6.securitySystem);
System.out.println("CCTV Available: "+shoppingMall6.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall6.atmAvailable);
System.out.println("Supermarket: "+shoppingMall6.supermarket);
System.out.println("Clothing Stores: "+shoppingMall6.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall6.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall6.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall6.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall6.openingTime);
System.out.println("Closing Time: "+shoppingMall6.closingTime);
System.out.println("Entry Fee: "+shoppingMall6.entryFee);

ShoppingMall shoppingMall7 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall7.name);
System.out.println("Location: "+shoppingMall7.location);
System.out.println("City: "+shoppingMall7.city);
System.out.println("State: "+shoppingMall7.state);
System.out.println("Country: "+shoppingMall7.country);
System.out.println("Number Of Floors: "+shoppingMall7.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall7.numberOfShops);
System.out.println("Food Court: "+shoppingMall7.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall7.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall7.gamingZone);
System.out.println("Parking Available: "+shoppingMall7.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall7.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall7.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall7.escalatorAvailable);
System.out.println("Security System: "+shoppingMall7.securitySystem);
System.out.println("CCTV Available: "+shoppingMall7.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall7.atmAvailable);
System.out.println("Supermarket: "+shoppingMall7.supermarket);
System.out.println("Clothing Stores: "+shoppingMall7.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall7.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall7.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall7.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall7.openingTime);
System.out.println("Closing Time: "+shoppingMall7.closingTime);
System.out.println("Entry Fee: "+shoppingMall7.entryFee);

shoppingMall7.name = "Central Mall";
shoppingMall7.location = "Bellandur";
shoppingMall7.city = "Bangalore";
shoppingMall7.state = "Karnataka";
shoppingMall7.country = "India";
shoppingMall7.numberOfFloors = 4;
shoppingMall7.numberOfShops = 120;
shoppingMall7.foodCourt = true;
shoppingMall7.cinemaHall = true;
shoppingMall7.gamingZone = true;
shoppingMall7.parkingAvailable = true;
shoppingMall7.wifiAvailable = true;
shoppingMall7.elevatorAvailable = true;
shoppingMall7.escalatorAvailable = true;
shoppingMall7.securitySystem = true;
shoppingMall7.cctvAvailable = true;
shoppingMall7.atmAvailable = true;
shoppingMall7.supermarket = false;
shoppingMall7.clothingStores = true;
shoppingMall7.electronicsStores = true;
shoppingMall7.kidsPlayArea = true;
shoppingMall7.wheelchairAccess = true;
shoppingMall7.openingTime = "10:30 AM";
shoppingMall7.closingTime = "10:30 PM";
shoppingMall7.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall7.name);
System.out.println("Location: "+shoppingMall7.location);
System.out.println("City: "+shoppingMall7.city);
System.out.println("State: "+shoppingMall7.state);
System.out.println("Country: "+shoppingMall7.country);
System.out.println("Number Of Floors: "+shoppingMall7.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall7.numberOfShops);
System.out.println("Food Court: "+shoppingMall7.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall7.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall7.gamingZone);
System.out.println("Parking Available: "+shoppingMall7.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall7.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall7.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall7.escalatorAvailable);
System.out.println("Security System: "+shoppingMall7.securitySystem);
System.out.println("CCTV Available: "+shoppingMall7.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall7.atmAvailable);
System.out.println("Supermarket: "+shoppingMall7.supermarket);
System.out.println("Clothing Stores: "+shoppingMall7.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall7.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall7.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall7.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall7.openingTime);
System.out.println("Closing Time: "+shoppingMall7.closingTime);
System.out.println("Entry Fee: "+shoppingMall7.entryFee);


ShoppingMall shoppingMall8 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall8.name);
System.out.println("Location: "+shoppingMall8.location);
System.out.println("City: "+shoppingMall8.city);
System.out.println("State: "+shoppingMall8.state);
System.out.println("Country: "+shoppingMall8.country);
System.out.println("Number Of Floors: "+shoppingMall8.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall8.numberOfShops);
System.out.println("Food Court: "+shoppingMall8.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall8.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall8.gamingZone);
System.out.println("Parking Available: "+shoppingMall8.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall8.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall8.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall8.escalatorAvailable);
System.out.println("Security System: "+shoppingMall8.securitySystem);
System.out.println("CCTV Available: "+shoppingMall8.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall8.atmAvailable);
System.out.println("Supermarket: "+shoppingMall8.supermarket);
System.out.println("Clothing Stores: "+shoppingMall8.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall8.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall8.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall8.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall8.openingTime);
System.out.println("Closing Time: "+shoppingMall8.closingTime);
System.out.println("Entry Fee: "+shoppingMall8.entryFee);

shoppingMall8.name = "Esteem Mall";
shoppingMall8.location = "Hebbal";
shoppingMall8.city = "Bangalore";
shoppingMall8.state = "Karnataka";
shoppingMall8.country = "India";
shoppingMall8.numberOfFloors = 4;
shoppingMall8.numberOfShops = 100;
shoppingMall8.foodCourt = true;
shoppingMall8.cinemaHall = false;
shoppingMall8.gamingZone = true;
shoppingMall8.parkingAvailable = true;
shoppingMall8.wifiAvailable = true;
shoppingMall8.elevatorAvailable = true;
shoppingMall8.escalatorAvailable = true;
shoppingMall8.securitySystem = true;
shoppingMall8.cctvAvailable = true;
shoppingMall8.atmAvailable = true;
shoppingMall8.supermarket = true;
shoppingMall8.clothingStores = true;
shoppingMall8.electronicsStores = false;
shoppingMall8.kidsPlayArea = true;
shoppingMall8.wheelchairAccess = true;
shoppingMall8.openingTime = "10:00 AM";
shoppingMall8.closingTime = "9:30 PM";
shoppingMall8.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall8.name);
System.out.println("Location: "+shoppingMall8.location);
System.out.println("City: "+shoppingMall8.city);
System.out.println("State: "+shoppingMall8.state);
System.out.println("Country: "+shoppingMall8.country);
System.out.println("Number Of Floors: "+shoppingMall8.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall8.numberOfShops);
System.out.println("Food Court: "+shoppingMall8.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall8.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall8.gamingZone);
System.out.println("Parking Available: "+shoppingMall8.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall8.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall8.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall8.escalatorAvailable);
System.out.println("Security System: "+shoppingMall8.securitySystem);
System.out.println("CCTV Available: "+shoppingMall8.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall8.atmAvailable);
System.out.println("Supermarket: "+shoppingMall8.supermarket);
System.out.println("Clothing Stores: "+shoppingMall8.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall8.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall8.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall8.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall8.openingTime);
System.out.println("Closing Time: "+shoppingMall8.closingTime);
System.out.println("Entry Fee: "+shoppingMall8.entryFee);

ShoppingMall shoppingMall9 = new ShoppingMall();
System.out.println("Shopping Mall name: "+shoppingMall9.name);
System.out.println("Location: "+shoppingMall9.location);
System.out.println("City: "+shoppingMall9.city);
System.out.println("State: "+shoppingMall9.state);
System.out.println("Country: "+shoppingMall9.country);
System.out.println("Number Of Floors: "+shoppingMall9.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall9.numberOfShops);
System.out.println("Food Court: "+shoppingMall9.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall9.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall9.gamingZone);
System.out.println("Parking Available: "+shoppingMall9.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall9.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall9.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall9.escalatorAvailable);
System.out.println("Security System: "+shoppingMall9.securitySystem);
System.out.println("CCTV Available: "+shoppingMall9.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall9.atmAvailable);
System.out.println("Supermarket: "+shoppingMall9.supermarket);
System.out.println("Clothing Stores: "+shoppingMall9.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall9.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall9.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall9.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall9.openingTime);
System.out.println("Closing Time: "+shoppingMall9.closingTime);
System.out.println("Entry Fee: "+shoppingMall9.entryFee);

shoppingMall9.name = "Royal Meenakshi Mall";
shoppingMall9.location = "Bannerghatta Road";
shoppingMall9.city = "Bangalore";
shoppingMall9.state = "Karnataka";
shoppingMall9.country = "India";
shoppingMall9.numberOfFloors = 5;
shoppingMall9.numberOfShops = 160;
shoppingMall9.foodCourt = true;
shoppingMall9.cinemaHall = true;
shoppingMall9.gamingZone = true;
shoppingMall9.parkingAvailable = true;
shoppingMall9.wifiAvailable = true;
shoppingMall9.elevatorAvailable = true;
shoppingMall9.escalatorAvailable = true;
shoppingMall9.securitySystem = true;
shoppingMall9.cctvAvailable = true;
shoppingMall9.atmAvailable = true;
shoppingMall9.supermarket = true;
shoppingMall9.clothingStores = true;
shoppingMall9.electronicsStores = true;
shoppingMall9.kidsPlayArea = true;
shoppingMall9.wheelchairAccess = true;
shoppingMall9.openingTime = "10:00 AM";
shoppingMall9.closingTime = "10:00 PM";
shoppingMall9.entryFee = 0;


System.out.println("Shopping Mall name: "+shoppingMall9.name);
System.out.println("Location: "+shoppingMall9.location);
System.out.println("City: "+shoppingMall9.city);
System.out.println("State: "+shoppingMall9.state);
System.out.println("Country: "+shoppingMall9.country);
System.out.println("Number Of Floors: "+shoppingMall9.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall9.numberOfShops);
System.out.println("Food Court: "+shoppingMall9.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall9.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall9.gamingZone);
System.out.println("Parking Available: "+shoppingMall9.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall9.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall9.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall9.escalatorAvailable);
System.out.println("Security System: "+shoppingMall9.securitySystem);
System.out.println("CCTV Available: "+shoppingMall9.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall9.atmAvailable);
System.out.println("Supermarket: "+shoppingMall9.supermarket);
System.out.println("Clothing Stores: "+shoppingMall9.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall9.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall9.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall9.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall9.openingTime);
System.out.println("Closing Time: "+shoppingMall9.closingTime);
System.out.println("Entry Fee: "+shoppingMall9.entryFee);


ShoppingMall shoppingMall10 = new ShoppingMall();

System.out.println("Shopping Mall name: "+shoppingMall10.name);
System.out.println("Location: "+shoppingMall10.location);
System.out.println("City: "+shoppingMall10.city);
System.out.println("State: "+shoppingMall10.state);
System.out.println("Country: "+shoppingMall10.country);
System.out.println("Number Of Floors: "+shoppingMall10.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall10.numberOfShops);
System.out.println("Food Court: "+shoppingMall10.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall10.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall10.gamingZone);
System.out.println("Parking Available: "+shoppingMall10.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall10.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall10.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall10.escalatorAvailable);
System.out.println("Security System: "+shoppingMall10.securitySystem);
System.out.println("CCTV Available: "+shoppingMall10.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall10.atmAvailable);
System.out.println("Supermarket: "+shoppingMall10.supermarket);
System.out.println("Clothing Stores: "+shoppingMall10.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall10.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall10.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall10.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall10.openingTime);
System.out.println("Closing Time: "+shoppingMall10.closingTime);
System.out.println("Entry Fee: "+shoppingMall10.entryFee);


shoppingMall10.name = "Garuda Yelahanka Mall";
shoppingMall10.location = "Yelahanka";
shoppingMall10.city = "Bangalore";
shoppingMall10.state = "Karnataka";
shoppingMall10.country = "India";
shoppingMall10.numberOfFloors = 4;
shoppingMall10.numberOfShops = 140;
shoppingMall10.foodCourt = true;
shoppingMall10.cinemaHall = true;
shoppingMall10.gamingZone = true;
shoppingMall10.parkingAvailable = true;
shoppingMall10.wifiAvailable = true;
shoppingMall10.elevatorAvailable = true;
shoppingMall10.escalatorAvailable = true;
shoppingMall10.securitySystem = true;
shoppingMall10.cctvAvailable = true;
shoppingMall10.atmAvailable = true;
shoppingMall10.supermarket = true;
shoppingMall10.clothingStores = true;
shoppingMall10.electronicsStores = true;
shoppingMall10.kidsPlayArea = true;
shoppingMall10.wheelchairAccess = true;
shoppingMall10.openingTime = "10:00 AM";
shoppingMall10.closingTime = "10:00 PM";
shoppingMall10.entryFee = 0;

System.out.println("Shopping Mall name: "+shoppingMall10.name);
System.out.println("Location: "+shoppingMall10.location);
System.out.println("City: "+shoppingMall10.city);
System.out.println("State: "+shoppingMall10.state);
System.out.println("Country: "+shoppingMall10.country);
System.out.println("Number Of Floors: "+shoppingMall10.numberOfFloors);
System.out.println("Number Of Shops: "+shoppingMall10.numberOfShops);
System.out.println("Food Court: "+shoppingMall10.foodCourt);
System.out.println("Cinema Hall: "+shoppingMall10.cinemaHall);
System.out.println("Gaming Zone: "+shoppingMall10.gamingZone);
System.out.println("Parking Available: "+shoppingMall10.parkingAvailable);
System.out.println("Wifi Available: "+shoppingMall10.wifiAvailable);
System.out.println("Elevator Available: "+shoppingMall10.elevatorAvailable);
System.out.println("Escalator Available: "+shoppingMall10.escalatorAvailable);
System.out.println("Security System: "+shoppingMall10.securitySystem);
System.out.println("CCTV Available: "+shoppingMall10.cctvAvailable);
System.out.println("ATM Available: "+shoppingMall10.atmAvailable);
System.out.println("Supermarket: "+shoppingMall10.supermarket);
System.out.println("Clothing Stores: "+shoppingMall10.clothingStores);
System.out.println("Electronics Stores: "+shoppingMall10.electronicsStores);
System.out.println("Kids Play Area: "+shoppingMall10.kidsPlayArea);
System.out.println("Wheelchair Access: "+shoppingMall10.wheelchairAccess);
System.out.println("Opening Time: "+shoppingMall10.openingTime);
System.out.println("Closing Time: "+shoppingMall10.closingTime);
System.out.println("Entry Fee: "+shoppingMall10.entryFee);




}
}