class StadiumRunner{
public static void main(String[] stadiuminfo){

Stadium stadium1 = new Stadium();

System.out.println("Stadium name: "+stadium1.name);
System.out.println("Location: "+stadium1.location);
System.out.println("City: "+stadium1.city);
System.out.println("State: "+stadium1.state);
System.out.println("Country: "+stadium1.country);
System.out.println("Seating Capacity: "+stadium1.seatingCapacity);
System.out.println("Stadium Type: "+stadium1.stadiumType);
System.out.println("Flood Lights: "+stadium1.floodLights);
System.out.println("Parking Available: "+stadium1.parkingAvailable);
System.out.println("VIP Lounge: "+stadium1.vipLounge);
System.out.println("Media Room: "+stadium1.mediaRoom);
System.out.println("Locker Rooms: "+stadium1.lockerRooms);
System.out.println("Security System: "+stadium1.securitySystem);
System.out.println("Food Stalls: "+stadium1.foodStalls);
System.out.println("Ticket Counter: "+stadium1.ticketCounter);
System.out.println("Online Booking: "+stadium1.onlineBooking);
System.out.println("Practice Ground: "+stadium1.practiceGround);
System.out.println("Scoreboard: "+stadium1.scoreboard);
System.out.println("First Aid: "+stadium1.firstAid);
System.out.println("CCTV Available: "+stadium1.cctvAvailable);
System.out.println("Public Transport Access: "+stadium1.publicTransportAccess);
System.out.println("Restroom Available: "+stadium1.restroomAvailable);
System.out.println("Opening Time: "+stadium1.openingTime);
System.out.println("Closing Time: "+stadium1.closingTime);
System.out.println("Ticket Price: "+stadium1.ticketPrice);

stadium1.name = "Chinnaswamy Stadium";
stadium1.location = "MG Road";
stadium1.city = "Bangalore";
stadium1.state = "Karnataka";
stadium1.country = "India";
stadium1.seatingCapacity = 40000;
stadium1.stadiumType = "Cricket";
stadium1.floodLights = true;
stadium1.parkingAvailable = true;
stadium1.vipLounge = true;
stadium1.mediaRoom = true;
stadium1.lockerRooms = true;
stadium1.securitySystem = true;
stadium1.foodStalls = true;
stadium1.ticketCounter = true;
stadium1.onlineBooking = true;
stadium1.practiceGround = true;
stadium1.scoreboard = true;
stadium1.firstAid = true;
stadium1.cctvAvailable = true;
stadium1.publicTransportAccess = true;
stadium1.restroomAvailable = true;
stadium1.openingTime = "9:00 AM";
stadium1.closingTime = "10:30 PM";
stadium1.ticketPrice = 600;


System.out.println("Stadium name: "+stadium1.name);
System.out.println("Location: "+stadium1.location);
System.out.println("City: "+stadium1.city);
System.out.println("State: "+stadium1.state);
System.out.println("Country: "+stadium1.country);
System.out.println("Seating Capacity: "+stadium1.seatingCapacity);
System.out.println("Stadium Type: "+stadium1.stadiumType);
System.out.println("Flood Lights: "+stadium1.floodLights);
System.out.println("Parking Available: "+stadium1.parkingAvailable);
System.out.println("VIP Lounge: "+stadium1.vipLounge);
System.out.println("Media Room: "+stadium1.mediaRoom);
System.out.println("Locker Rooms: "+stadium1.lockerRooms);
System.out.println("Security System: "+stadium1.securitySystem);
System.out.println("Food Stalls: "+stadium1.foodStalls);
System.out.println("Ticket Counter: "+stadium1.ticketCounter);
System.out.println("Online Booking: "+stadium1.onlineBooking);
System.out.println("Practice Ground: "+stadium1.practiceGround);
System.out.println("Scoreboard: "+stadium1.scoreboard);
System.out.println("First Aid: "+stadium1.firstAid);
System.out.println("CCTV Available: "+stadium1.cctvAvailable);
System.out.println("Public Transport Access: "+stadium1.publicTransportAccess);
System.out.println("Restroom Available: "+stadium1.restroomAvailable);
System.out.println("Opening Time: "+stadium1.openingTime);
System.out.println("Closing Time: "+stadium1.closingTime);
System.out.println("Ticket Price: "+stadium1.ticketPrice);


Stadium stadium2 = new Stadium();

System.out.println("Stadium name: "+stadium2.name);
System.out.println("Location: "+stadium2.location);
System.out.println("City: "+stadium2.city);
System.out.println("State: "+stadium2.state);
System.out.println("Country: "+stadium2.country);
System.out.println("Seating Capacity: "+stadium2.seatingCapacity);
System.out.println("Stadium Type: "+stadium2.stadiumType);
System.out.println("Flood Lights: "+stadium2.floodLights);
System.out.println("Parking Available: "+stadium2.parkingAvailable);
System.out.println("VIP Lounge: "+stadium2.vipLounge);
System.out.println("Media Room: "+stadium2.mediaRoom);
System.out.println("Locker Rooms: "+stadium2.lockerRooms);
System.out.println("Security System: "+stadium2.securitySystem);
System.out.println("Food Stalls: "+stadium2.foodStalls);
System.out.println("Ticket Counter: "+stadium2.ticketCounter);
System.out.println("Online Booking: "+stadium2.onlineBooking);
System.out.println("Practice Ground: "+stadium2.practiceGround);
System.out.println("Scoreboard: "+stadium2.scoreboard);
System.out.println("First Aid: "+stadium2.firstAid);
System.out.println("CCTV Available: "+stadium2.cctvAvailable);
System.out.println("Public Transport Access: "+stadium2.publicTransportAccess);
System.out.println("Restroom Available: "+stadium2.restroomAvailable);
System.out.println("Opening Time: "+stadium2.openingTime);
System.out.println("Closing Time: "+stadium2.closingTime);
System.out.println("Ticket Price: "+stadium2.ticketPrice);


stadium2.name = "Narendra Modi Stadium";
stadium2.location = "Motera";
stadium2.city = "Ahmedabad";
stadium2.state = "Gujarat";
stadium2.country = "India";
stadium2.seatingCapacity = 132000;
stadium2.stadiumType = "Cricket";
stadium2.floodLights = true;
stadium2.parkingAvailable = true;
stadium2.vipLounge = true;
stadium2.mediaRoom = true;
stadium2.lockerRooms = true;
stadium2.securitySystem = true;
stadium2.foodStalls = true;
stadium2.ticketCounter = true;
stadium2.onlineBooking = true;
stadium2.practiceGround = true;
stadium2.scoreboard = true;
stadium2.firstAid = true;
stadium2.cctvAvailable = true;
stadium2.publicTransportAccess = true;
stadium2.restroomAvailable = true;
stadium2.openingTime = "8:30 AM";
stadium2.closingTime = "11:00 PM";
stadium2.ticketPrice = 700;

System.out.println("Stadium name: "+stadium2.name);
System.out.println("Location: "+stadium2.location);
System.out.println("City: "+stadium2.city);
System.out.println("State: "+stadium2.state);
System.out.println("Country: "+stadium2.country);
System.out.println("Seating Capacity: "+stadium2.seatingCapacity);
System.out.println("Stadium Type: "+stadium2.stadiumType);
System.out.println("Flood Lights: "+stadium2.floodLights);
System.out.println("Parking Available: "+stadium2.parkingAvailable);
System.out.println("VIP Lounge: "+stadium2.vipLounge);
System.out.println("Media Room: "+stadium2.mediaRoom);
System.out.println("Locker Rooms: "+stadium2.lockerRooms);
System.out.println("Security System: "+stadium2.securitySystem);
System.out.println("Food Stalls: "+stadium2.foodStalls);
System.out.println("Ticket Counter: "+stadium2.ticketCounter);
System.out.println("Online Booking: "+stadium2.onlineBooking);
System.out.println("Practice Ground: "+stadium2.practiceGround);
System.out.println("Scoreboard: "+stadium2.scoreboard);
System.out.println("First Aid: "+stadium2.firstAid);
System.out.println("CCTV Available: "+stadium2.cctvAvailable);
System.out.println("Public Transport Access: "+stadium2.publicTransportAccess);
System.out.println("Restroom Available: "+stadium2.restroomAvailable);
System.out.println("Opening Time: "+stadium2.openingTime);
System.out.println("Closing Time: "+stadium2.closingTime);
System.out.println("Ticket Price: "+stadium2.ticketPrice);



Stadium stadium3 = new Stadium();

System.out.println("Stadium name: "+stadium3.name);
System.out.println("Location: "+stadium3.location);
System.out.println("City: "+stadium3.city);
System.out.println("State: "+stadium3.state);
System.out.println("Country: "+stadium3.country);
System.out.println("Seating Capacity: "+stadium3.seatingCapacity);
System.out.println("Stadium Type: "+stadium3.stadiumType);
System.out.println("Flood Lights: "+stadium3.floodLights);
System.out.println("Parking Available: "+stadium3.parkingAvailable);
System.out.println("VIP Lounge: "+stadium3.vipLounge);
System.out.println("Media Room: "+stadium3.mediaRoom);
System.out.println("Locker Rooms: "+stadium3.lockerRooms);
System.out.println("Security System: "+stadium3.securitySystem);
System.out.println("Food Stalls: "+stadium3.foodStalls);
System.out.println("Ticket Counter: "+stadium3.ticketCounter);
System.out.println("Online Booking: "+stadium3.onlineBooking);
System.out.println("Practice Ground: "+stadium3.practiceGround);
System.out.println("Scoreboard: "+stadium3.scoreboard);
System.out.println("First Aid: "+stadium3.firstAid);
System.out.println("CCTV Available: "+stadium3.cctvAvailable);
System.out.println("Public Transport Access: "+stadium3.publicTransportAccess);
System.out.println("Restroom Available: "+stadium3.restroomAvailable);
System.out.println("Opening Time: "+stadium3.openingTime);
System.out.println("Closing Time: "+stadium3.closingTime);
System.out.println("Ticket Price: "+stadium3.ticketPrice);


stadium3.name = "Jawaharlal Nehru Stadium";
stadium3.location = "Lodhi Road";
stadium3.city = "Delhi";
stadium3.state = "Delhi";
stadium3.country = "India";
stadium3.seatingCapacity = 60000;
stadium3.stadiumType = "Multi Purpose";
stadium3.floodLights = true;
stadium3.parkingAvailable = true;
stadium3.vipLounge = true;
stadium3.mediaRoom = true;
stadium3.lockerRooms = true;
stadium3.securitySystem = true;
stadium3.foodStalls = true;
stadium3.ticketCounter = true;
stadium3.onlineBooking = true;
stadium3.practiceGround = true;
stadium3.scoreboard = true;
stadium3.firstAid = true;
stadium3.cctvAvailable = true;
stadium3.publicTransportAccess = true;
stadium3.restroomAvailable = true;
stadium3.openingTime = "9:00 AM";
stadium3.closingTime = "10:00 PM";
stadium3.ticketPrice = 400;

System.out.println("Stadium name: "+stadium3.name);
System.out.println("Location: "+stadium3.location);
System.out.println("City: "+stadium3.city);
System.out.println("State: "+stadium3.state);
System.out.println("Country: "+stadium3.country);
System.out.println("Seating Capacity: "+stadium3.seatingCapacity);
System.out.println("Stadium Type: "+stadium3.stadiumType);
System.out.println("Flood Lights: "+stadium3.floodLights);
System.out.println("Parking Available: "+stadium3.parkingAvailable);
System.out.println("VIP Lounge: "+stadium3.vipLounge);
System.out.println("Media Room: "+stadium3.mediaRoom);
System.out.println("Locker Rooms: "+stadium3.lockerRooms);
System.out.println("Security System: "+stadium3.securitySystem);
System.out.println("Food Stalls: "+stadium3.foodStalls);
System.out.println("Ticket Counter: "+stadium3.ticketCounter);
System.out.println("Online Booking: "+stadium3.onlineBooking);
System.out.println("Practice Ground: "+stadium3.practiceGround);
System.out.println("Scoreboard: "+stadium3.scoreboard);
System.out.println("First Aid: "+stadium3.firstAid);
System.out.println("CCTV Available: "+stadium3.cctvAvailable);
System.out.println("Public Transport Access: "+stadium3.publicTransportAccess);
System.out.println("Restroom Available: "+stadium3.restroomAvailable);
System.out.println("Opening Time: "+stadium3.openingTime);
System.out.println("Closing Time: "+stadium3.closingTime);
System.out.println("Ticket Price: "+stadium3.ticketPrice);


Stadium stadium4 = new Stadium();

System.out.println("Stadium name: "+stadium4.name);
System.out.println("Location: "+stadium4.location);
System.out.println("City: "+stadium4.city);
System.out.println("State: "+stadium4.state);
System.out.println("Country: "+stadium4.country);
System.out.println("Seating Capacity: "+stadium4.seatingCapacity);
System.out.println("Stadium Type: "+stadium4.stadiumType);
System.out.println("Flood Lights: "+stadium4.floodLights);
System.out.println("Parking Available: "+stadium4.parkingAvailable);
System.out.println("VIP Lounge: "+stadium4.vipLounge);
System.out.println("Media Room: "+stadium4.mediaRoom);
System.out.println("Locker Rooms: "+stadium4.lockerRooms);
System.out.println("Security System: "+stadium4.securitySystem);
System.out.println("Food Stalls: "+stadium4.foodStalls);
System.out.println("Ticket Counter: "+stadium4.ticketCounter);
System.out.println("Online Booking: "+stadium4.onlineBooking);
System.out.println("Practice Ground: "+stadium4.practiceGround);
System.out.println("Scoreboard: "+stadium4.scoreboard);
System.out.println("First Aid: "+stadium4.firstAid);
System.out.println("CCTV Available: "+stadium4.cctvAvailable);
System.out.println("Public Transport Access: "+stadium4.publicTransportAccess);
System.out.println("Restroom Available: "+stadium4.restroomAvailable);
System.out.println("Opening Time: "+stadium4.openingTime);
System.out.println("Closing Time: "+stadium4.closingTime);
System.out.println("Ticket Price: "+stadium4.ticketPrice);

stadium4.name = "Rajiv Gandhi Stadium";
stadium4.location = "Uppal";
stadium4.city = "Hyderabad";
stadium4.state = "Telangana";
stadium4.country = "India";
stadium4.seatingCapacity = 55000;
stadium4.stadiumType = "Cricket";
stadium4.floodLights = true;
stadium4.parkingAvailable = true;
stadium4.vipLounge = true;
stadium4.mediaRoom = true;
stadium4.lockerRooms = true;
stadium4.securitySystem = true;
stadium4.foodStalls = true;
stadium4.ticketCounter = true;
stadium4.onlineBooking = true;
stadium4.practiceGround = true;
stadium4.scoreboard = true;
stadium4.firstAid = true;
stadium4.cctvAvailable = true;
stadium4.publicTransportAccess = true;
stadium4.restroomAvailable = true;
stadium4.openingTime = "8:30 AM";
stadium4.closingTime = "10:30 PM";
stadium4.ticketPrice = 500;

System.out.println("Stadium name: "+stadium4.name);
System.out.println("Location: "+stadium4.location);
System.out.println("City: "+stadium4.city);
System.out.println("State: "+stadium4.state);
System.out.println("Country: "+stadium4.country);
System.out.println("Seating Capacity: "+stadium4.seatingCapacity);
System.out.println("Stadium Type: "+stadium4.stadiumType);
System.out.println("Flood Lights: "+stadium4.floodLights);
System.out.println("Parking Available: "+stadium4.parkingAvailable);
System.out.println("VIP Lounge: "+stadium4.vipLounge);
System.out.println("Media Room: "+stadium4.mediaRoom);
System.out.println("Locker Rooms: "+stadium4.lockerRooms);
System.out.println("Security System: "+stadium4.securitySystem);
System.out.println("Food Stalls: "+stadium4.foodStalls);
System.out.println("Ticket Counter: "+stadium4.ticketCounter);
System.out.println("Online Booking: "+stadium4.onlineBooking);
System.out.println("Practice Ground: "+stadium4.practiceGround);
System.out.println("Scoreboard: "+stadium4.scoreboard);
System.out.println("First Aid: "+stadium4.firstAid);
System.out.println("CCTV Available: "+stadium4.cctvAvailable);
System.out.println("Public Transport Access: "+stadium4.publicTransportAccess);
System.out.println("Restroom Available: "+stadium4.restroomAvailable);
System.out.println("Opening Time: "+stadium4.openingTime);
System.out.println("Closing Time: "+stadium4.closingTime);
System.out.println("Ticket Price: "+stadium4.ticketPrice);


Stadium stadium5 = new Stadium();


System.out.println("Stadium name: "+stadium5.name);
System.out.println("Location: "+stadium5.location);
System.out.println("City: "+stadium5.city);
System.out.println("State: "+stadium5.state);
System.out.println("Country: "+stadium5.country);
System.out.println("Seating Capacity: "+stadium5.seatingCapacity);
System.out.println("Stadium Type: "+stadium5.stadiumType);
System.out.println("Flood Lights: "+stadium5.floodLights);
System.out.println("Parking Available: "+stadium5.parkingAvailable);
System.out.println("VIP Lounge: "+stadium5.vipLounge);
System.out.println("Media Room: "+stadium5.mediaRoom);
System.out.println("Locker Rooms: "+stadium5.lockerRooms);
System.out.println("Security System: "+stadium5.securitySystem);
System.out.println("Food Stalls: "+stadium5.foodStalls);
System.out.println("Ticket Counter: "+stadium5.ticketCounter);
System.out.println("Online Booking: "+stadium5.onlineBooking);
System.out.println("Practice Ground: "+stadium5.practiceGround);
System.out.println("Scoreboard: "+stadium5.scoreboard);
System.out.println("First Aid: "+stadium5.firstAid);
System.out.println("CCTV Available: "+stadium5.cctvAvailable);
System.out.println("Public Transport Access: "+stadium5.publicTransportAccess);
System.out.println("Restroom Available: "+stadium5.restroomAvailable);
System.out.println("Opening Time: "+stadium5.openingTime);
System.out.println("Closing Time: "+stadium5.closingTime);
System.out.println("Ticket Price: "+stadium5.ticketPrice);

stadium5.name = "MA Chidambaram Stadium";
stadium5.location = "Chepauk";
stadium5.city = "Chennai";
stadium5.state = "Tamil Nadu";
stadium5.country = "India";
stadium5.seatingCapacity = 50000;
stadium5.stadiumType = "Cricket";
stadium5.floodLights = true;
stadium5.parkingAvailable = true;
stadium5.vipLounge = true;
stadium5.mediaRoom = true;
stadium5.lockerRooms = true;
stadium5.securitySystem = true;
stadium5.foodStalls = true;
stadium5.ticketCounter = true;
stadium5.onlineBooking = true;
stadium5.practiceGround = true;
stadium5.scoreboard = true;
stadium5.firstAid = true;
stadium5.cctvAvailable = true;
stadium5.publicTransportAccess = true;
stadium5.restroomAvailable = true;
stadium5.openingTime = "9:00 AM";
stadium5.closingTime = "10:30 PM";
stadium5.ticketPrice = 650;

System.out.println("Stadium name: "+stadium5.name);
System.out.println("Location: "+stadium5.location);
System.out.println("City: "+stadium5.city);
System.out.println("State: "+stadium5.state);
System.out.println("Country: "+stadium5.country);
System.out.println("Seating Capacity: "+stadium5.seatingCapacity);
System.out.println("Stadium Type: "+stadium5.stadiumType);
System.out.println("Flood Lights: "+stadium5.floodLights);
System.out.println("Parking Available: "+stadium5.parkingAvailable);
System.out.println("VIP Lounge: "+stadium5.vipLounge);
System.out.println("Media Room: "+stadium5.mediaRoom);
System.out.println("Locker Rooms: "+stadium5.lockerRooms);
System.out.println("Security System: "+stadium5.securitySystem);
System.out.println("Food Stalls: "+stadium5.foodStalls);
System.out.println("Ticket Counter: "+stadium5.ticketCounter);
System.out.println("Online Booking: "+stadium5.onlineBooking);
System.out.println("Practice Ground: "+stadium5.practiceGround);
System.out.println("Scoreboard: "+stadium5.scoreboard);
System.out.println("First Aid: "+stadium5.firstAid);
System.out.println("CCTV Available: "+stadium5.cctvAvailable);
System.out.println("Public Transport Access: "+stadium5.publicTransportAccess);
System.out.println("Restroom Available: "+stadium5.restroomAvailable);
System.out.println("Opening Time: "+stadium5.openingTime);
System.out.println("Closing Time: "+stadium5.closingTime);
System.out.println("Ticket Price: "+stadium5.ticketPrice);


Stadium stadium6 = new Stadium();

System.out.println("Stadium name: "+stadium6.name);
System.out.println("Location: "+stadium6.location);
System.out.println("City: "+stadium6.city);
System.out.println("State: "+stadium6.state);
System.out.println("Country: "+stadium6.country);
System.out.println("Seating Capacity: "+stadium6.seatingCapacity);
System.out.println("Stadium Type: "+stadium6.stadiumType);
System.out.println("Flood Lights: "+stadium6.floodLights);
System.out.println("Parking Available: "+stadium6.parkingAvailable);
System.out.println("VIP Lounge: "+stadium6.vipLounge);
System.out.println("Media Room: "+stadium6.mediaRoom);
System.out.println("Locker Rooms: "+stadium6.lockerRooms);
System.out.println("Security System: "+stadium6.securitySystem);
System.out.println("Food Stalls: "+stadium6.foodStalls);
System.out.println("Ticket Counter: "+stadium6.ticketCounter);
System.out.println("Online Booking: "+stadium6.onlineBooking);
System.out.println("Practice Ground: "+stadium6.practiceGround);
System.out.println("Scoreboard: "+stadium6.scoreboard);
System.out.println("First Aid: "+stadium6.firstAid);
System.out.println("CCTV Available: "+stadium6.cctvAvailable);
System.out.println("Public Transport Access: "+stadium6.publicTransportAccess);
System.out.println("Restroom Available: "+stadium6.restroomAvailable);
System.out.println("Opening Time: "+stadium6.openingTime);
System.out.println("Closing Time: "+stadium6.closingTime);
System.out.println("Ticket Price: "+stadium6.ticketPrice);

stadium6.name = "Salt Lake Stadium";
stadium6.location = "Salt Lake";
stadium6.city = "Kolkata";
stadium6.state = "West Bengal";
stadium6.country = "India";
stadium6.seatingCapacity = 85000;
stadium6.stadiumType = "Football";
stadium6.floodLights = true;
stadium6.parkingAvailable = true;
stadium6.vipLounge = true;
stadium6.mediaRoom = true;
stadium6.lockerRooms = true;
stadium6.securitySystem = true;
stadium6.foodStalls = true;
stadium6.ticketCounter = true;
stadium6.onlineBooking = true;
stadium6.practiceGround = true;
stadium6.scoreboard = true;
stadium6.firstAid = true;
stadium6.cctvAvailable = true;
stadium6.publicTransportAccess = true;
stadium6.restroomAvailable = true;
stadium6.openingTime = "8:00 AM";
stadium6.closingTime = "10:00 PM";
stadium6.ticketPrice = 500;


System.out.println("Stadium name: "+stadium6.name);
System.out.println("Location: "+stadium6.location);
System.out.println("City: "+stadium6.city);
System.out.println("State: "+stadium6.state);
System.out.println("Country: "+stadium6.country);
System.out.println("Seating Capacity: "+stadium6.seatingCapacity);
System.out.println("Stadium Type: "+stadium6.stadiumType);
System.out.println("Flood Lights: "+stadium6.floodLights);
System.out.println("Parking Available: "+stadium6.parkingAvailable);
System.out.println("VIP Lounge: "+stadium6.vipLounge);
System.out.println("Media Room: "+stadium6.mediaRoom);
System.out.println("Locker Rooms: "+stadium6.lockerRooms);
System.out.println("Security System: "+stadium6.securitySystem);
System.out.println("Food Stalls: "+stadium6.foodStalls);
System.out.println("Ticket Counter: "+stadium6.ticketCounter);
System.out.println("Online Booking: "+stadium6.onlineBooking);
System.out.println("Practice Ground: "+stadium6.practiceGround);
System.out.println("Scoreboard: "+stadium6.scoreboard);
System.out.println("First Aid: "+stadium6.firstAid);
System.out.println("CCTV Available: "+stadium6.cctvAvailable);
System.out.println("Public Transport Access: "+stadium6.publicTransportAccess);
System.out.println("Restroom Available: "+stadium6.restroomAvailable);
System.out.println("Opening Time: "+stadium6.openingTime);
System.out.println("Closing Time: "+stadium6.closingTime);
System.out.println("Ticket Price: "+stadium6.ticketPrice);

Stadium stadium7 = new Stadium();

System.out.println("Stadium name: "+stadium7.name);
System.out.println("Location: "+stadium7.location);
System.out.println("City: "+stadium7.city);
System.out.println("State: "+stadium7.state);
System.out.println("Country: "+stadium7.country);
System.out.println("Seating Capacity: "+stadium7.seatingCapacity);
System.out.println("Stadium Type: "+stadium7.stadiumType);
System.out.println("Flood Lights: "+stadium7.floodLights);
System.out.println("Parking Available: "+stadium7.parkingAvailable);
System.out.println("VIP Lounge: "+stadium7.vipLounge);
System.out.println("Media Room: "+stadium7.mediaRoom);
System.out.println("Locker Rooms: "+stadium7.lockerRooms);
System.out.println("Security System: "+stadium7.securitySystem);
System.out.println("Food Stalls: "+stadium7.foodStalls);
System.out.println("Ticket Counter: "+stadium7.ticketCounter);
System.out.println("Online Booking: "+stadium7.onlineBooking);
System.out.println("Practice Ground: "+stadium7.practiceGround);
System.out.println("Scoreboard: "+stadium7.scoreboard);
System.out.println("First Aid: "+stadium7.firstAid);
System.out.println("CCTV Available: "+stadium7.cctvAvailable);
System.out.println("Public Transport Access: "+stadium7.publicTransportAccess);
System.out.println("Restroom Available: "+stadium7.restroomAvailable);
System.out.println("Opening Time: "+stadium7.openingTime);
System.out.println("Closing Time: "+stadium7.closingTime);
System.out.println("Ticket Price: "+stadium7.ticketPrice);

stadium7.name = "Eden Gardens";
stadium7.location = "Maidan";
stadium7.city = "Kolkata";
stadium7.state = "West Bengal";
stadium7.country = "India";
stadium7.seatingCapacity = 66000;
stadium7.stadiumType = "Cricket";
stadium7.floodLights = true;
stadium7.parkingAvailable = true;
stadium7.vipLounge = true;
stadium7.mediaRoom = true;
stadium7.lockerRooms = true;
stadium7.securitySystem = true;
stadium7.foodStalls = true;
stadium7.ticketCounter = true;
stadium7.onlineBooking = true;
stadium7.practiceGround = true;
stadium7.scoreboard = true;
stadium7.firstAid = true;
stadium7.cctvAvailable = true;
stadium7.publicTransportAccess = true;
stadium7.restroomAvailable = true;
stadium7.openingTime = "9:00 AM";
stadium7.closingTime = "11:00 PM";
stadium7.ticketPrice = 700;
System.out.println("Stadium name: "+stadium7.name);
System.out.println("Location: "+stadium7.location);
System.out.println("City: "+stadium7.city);
System.out.println("State: "+stadium7.state);
System.out.println("Country: "+stadium7.country);
System.out.println("Seating Capacity: "+stadium7.seatingCapacity);
System.out.println("Stadium Type: "+stadium7.stadiumType);
System.out.println("Flood Lights: "+stadium7.floodLights);
System.out.println("Parking Available: "+stadium7.parkingAvailable);
System.out.println("VIP Lounge: "+stadium7.vipLounge);
System.out.println("Media Room: "+stadium7.mediaRoom);
System.out.println("Locker Rooms: "+stadium7.lockerRooms);
System.out.println("Security System: "+stadium7.securitySystem);
System.out.println("Food Stalls: "+stadium7.foodStalls);
System.out.println("Ticket Counter: "+stadium7.ticketCounter);
System.out.println("Online Booking: "+stadium7.onlineBooking);
System.out.println("Practice Ground: "+stadium7.practiceGround);
System.out.println("Scoreboard: "+stadium7.scoreboard);
System.out.println("First Aid: "+stadium7.firstAid);
System.out.println("CCTV Available: "+stadium7.cctvAvailable);
System.out.println("Public Transport Access: "+stadium7.publicTransportAccess);
System.out.println("Restroom Available: "+stadium7.restroomAvailable);
System.out.println("Opening Time: "+stadium7.openingTime);
System.out.println("Closing Time: "+stadium7.closingTime);
System.out.println("Ticket Price: "+stadium7.ticketPrice);


Stadium stadium8 = new Stadium();

System.out.println("Stadium name: "+stadium8.name);
System.out.println("Location: "+stadium8.location);
System.out.println("City: "+stadium8.city);
System.out.println("State: "+stadium8.state);
System.out.println("Country: "+stadium8.country);
System.out.println("Seating Capacity: "+stadium8.seatingCapacity);
System.out.println("Stadium Type: "+stadium8.stadiumType);
System.out.println("Flood Lights: "+stadium8.floodLights);
System.out.println("Parking Available: "+stadium8.parkingAvailable);
System.out.println("VIP Lounge: "+stadium8.vipLounge);
System.out.println("Media Room: "+stadium8.mediaRoom);
System.out.println("Locker Rooms: "+stadium8.lockerRooms);
System.out.println("Security System: "+stadium8.securitySystem);
System.out.println("Food Stalls: "+stadium8.foodStalls);
System.out.println("Ticket Counter: "+stadium8.ticketCounter);
System.out.println("Online Booking: "+stadium8.onlineBooking);
System.out.println("Practice Ground: "+stadium8.practiceGround);
System.out.println("Scoreboard: "+stadium8.scoreboard);
System.out.println("First Aid: "+stadium8.firstAid);
System.out.println("CCTV Available: "+stadium8.cctvAvailable);
System.out.println("Public Transport Access: "+stadium8.publicTransportAccess);
System.out.println("Restroom Available: "+stadium8.restroomAvailable);
System.out.println("Opening Time: "+stadium8.openingTime);
System.out.println("Closing Time: "+stadium8.closingTime);
System.out.println("Ticket Price: "+stadium8.ticketPrice);

stadium8.name = "Greenfield Stadium";
stadium8.location = "Karyavattom";
stadium8.city = "Thiruvananthapuram";
stadium8.state = "Kerala";
stadium8.country = "India";
stadium8.seatingCapacity = 55000;
stadium8.stadiumType = "Multi Purpose";
stadium8.floodLights = true;
stadium8.parkingAvailable = true;
stadium8.vipLounge = true;
stadium8.mediaRoom = true;
stadium8.lockerRooms = true;
stadium8.securitySystem = true;
stadium8.foodStalls = true;
stadium8.ticketCounter = true;
stadium8.onlineBooking = true;
stadium8.practiceGround = true;
stadium8.scoreboard = true;
stadium8.firstAid = true;
stadium8.cctvAvailable = true;
stadium8.publicTransportAccess = true;
stadium8.restroomAvailable = true;
stadium8.openingTime = "8:30 AM";
stadium8.closingTime = "10:30 PM";
stadium8.ticketPrice = 450;

System.out.println("Stadium name: "+stadium8.name);
System.out.println("Location: "+stadium8.location);
System.out.println("City: "+stadium8.city);
System.out.println("State: "+stadium8.state);
System.out.println("Country: "+stadium8.country);
System.out.println("Seating Capacity: "+stadium8.seatingCapacity);
System.out.println("Stadium Type: "+stadium8.stadiumType);
System.out.println("Flood Lights: "+stadium8.floodLights);
System.out.println("Parking Available: "+stadium8.parkingAvailable);
System.out.println("VIP Lounge: "+stadium8.vipLounge);
System.out.println("Media Room: "+stadium8.mediaRoom);
System.out.println("Locker Rooms: "+stadium8.lockerRooms);
System.out.println("Security System: "+stadium8.securitySystem);
System.out.println("Food Stalls: "+stadium8.foodStalls);
System.out.println("Ticket Counter: "+stadium8.ticketCounter);
System.out.println("Online Booking: "+stadium8.onlineBooking);
System.out.println("Practice Ground: "+stadium8.practiceGround);
System.out.println("Scoreboard: "+stadium8.scoreboard);
System.out.println("First Aid: "+stadium8.firstAid);
System.out.println("CCTV Available: "+stadium8.cctvAvailable);
System.out.println("Public Transport Access: "+stadium8.publicTransportAccess);
System.out.println("Restroom Available: "+stadium8.restroomAvailable);
System.out.println("Opening Time: "+stadium8.openingTime);
System.out.println("Closing Time: "+stadium8.closingTime);
System.out.println("Ticket Price: "+stadium8.ticketPrice);



Stadium stadium9 = new Stadium();

System.out.println("Stadium name: "+stadium9.name);
System.out.println("Location: "+stadium9.location);
System.out.println("City: "+stadium9.city);
System.out.println("State: "+stadium9.state);
System.out.println("Country: "+stadium9.country);
System.out.println("Seating Capacity: "+stadium9.seatingCapacity);
System.out.println("Stadium Type: "+stadium9.stadiumType);
System.out.println("Flood Lights: "+stadium9.floodLights);
System.out.println("Parking Available: "+stadium9.parkingAvailable);
System.out.println("VIP Lounge: "+stadium9.vipLounge);
System.out.println("Media Room: "+stadium9.mediaRoom);
System.out.println("Locker Rooms: "+stadium9.lockerRooms);
System.out.println("Security System: "+stadium9.securitySystem);
System.out.println("Food Stalls: "+stadium9.foodStalls);
System.out.println("Ticket Counter: "+stadium9.ticketCounter);
System.out.println("Online Booking: "+stadium9.onlineBooking);
System.out.println("Practice Ground: "+stadium9.practiceGround);
System.out.println("Scoreboard: "+stadium9.scoreboard);
System.out.println("First Aid: "+stadium9.firstAid);
System.out.println("CCTV Available: "+stadium9.cctvAvailable);
System.out.println("Public Transport Access: "+stadium9.publicTransportAccess);
System.out.println("Restroom Available: "+stadium9.restroomAvailable);
System.out.println("Opening Time: "+stadium9.openingTime);
System.out.println("Closing Time: "+stadium9.closingTime);
System.out.println("Ticket Price: "+stadium9.ticketPrice);


stadium9.name = "DY Patil Stadium";
stadium9.location = "Nerul";
stadium9.city = "Mumbai";
stadium9.state = "Maharashtra";
stadium9.country = "India";
stadium9.seatingCapacity = 55000;
stadium9.stadiumType = "Cricket";
stadium9.floodLights = true;
stadium9.parkingAvailable = true;
stadium9.vipLounge = true;
stadium9.mediaRoom = true;
stadium9.lockerRooms = true;
stadium9.securitySystem = true;
stadium9.foodStalls = true;
stadium9.ticketCounter = true;
stadium9.onlineBooking = true;
stadium9.practiceGround = true;
stadium9.scoreboard = true;
stadium9.firstAid = true;
stadium9.cctvAvailable = true;
stadium9.publicTransportAccess = true;
stadium9.restroomAvailable = true;
stadium9.openingTime = "9:00 AM";
stadium9.closingTime = "11:00 PM";
stadium9.ticketPrice = 600;

System.out.println("Stadium name: "+stadium9.name);
System.out.println("Location: "+stadium9.location);
System.out.println("City: "+stadium9.city);
System.out.println("State: "+stadium9.state);
System.out.println("Country: "+stadium9.country);
System.out.println("Seating Capacity: "+stadium9.seatingCapacity);
System.out.println("Stadium Type: "+stadium9.stadiumType);
System.out.println("Flood Lights: "+stadium9.floodLights);
System.out.println("Parking Available: "+stadium9.parkingAvailable);
System.out.println("VIP Lounge: "+stadium9.vipLounge);
System.out.println("Media Room: "+stadium9.mediaRoom);
System.out.println("Locker Rooms: "+stadium9.lockerRooms);
System.out.println("Security System: "+stadium9.securitySystem);
System.out.println("Food Stalls: "+stadium9.foodStalls);
System.out.println("Ticket Counter: "+stadium9.ticketCounter);
System.out.println("Online Booking: "+stadium9.onlineBooking);
System.out.println("Practice Ground: "+stadium9.practiceGround);
System.out.println("Scoreboard: "+stadium9.scoreboard);
System.out.println("First Aid: "+stadium9.firstAid);
System.out.println("CCTV Available: "+stadium9.cctvAvailable);
System.out.println("Public Transport Access: "+stadium9.publicTransportAccess);
System.out.println("Restroom Available: "+stadium9.restroomAvailable);
System.out.println("Opening Time: "+stadium9.openingTime);
System.out.println("Closing Time: "+stadium9.closingTime);
System.out.println("Ticket Price: "+stadium9.ticketPrice);


Stadium stadium10 = new Stadium();

System.out.println("Stadium name: "+stadium10.name);
System.out.println("Location: "+stadium10.location);
System.out.println("City: "+stadium10.city);
System.out.println("State: "+stadium10.state);
System.out.println("Country: "+stadium10.country);
System.out.println("Seating Capacity: "+stadium10.seatingCapacity);
System.out.println("Stadium Type: "+stadium10.stadiumType);
System.out.println("Flood Lights: "+stadium10.floodLights);
System.out.println("Parking Available: "+stadium10.parkingAvailable);
System.out.println("VIP Lounge: "+stadium10.vipLounge);
System.out.println("Media Room: "+stadium10.mediaRoom);
System.out.println("Locker Rooms: "+stadium10.lockerRooms);
System.out.println("Security System: "+stadium10.securitySystem);
System.out.println("Food Stalls: "+stadium10.foodStalls);
System.out.println("Ticket Counter: "+stadium10.ticketCounter);
System.out.println("Online Booking: "+stadium10.onlineBooking);
System.out.println("Practice Ground: "+stadium10.practiceGround);
System.out.println("Scoreboard: "+stadium10.scoreboard);
System.out.println("First Aid: "+stadium10.firstAid);
System.out.println("CCTV Available: "+stadium10.cctvAvailable);
System.out.println("Public Transport Access: "+stadium10.publicTransportAccess);
System.out.println("Restroom Available: "+stadium10.restroomAvailable);
System.out.println("Opening Time: "+stadium10.openingTime);
System.out.println("Closing Time: "+stadium10.closingTime);
System.out.println("Ticket Price: "+stadium10.ticketPrice);


stadium10.name = "Wankhede Stadium";
stadium10.location = "Churchgate";
stadium10.city = "Mumbai";
stadium10.state = "Maharashtra";
stadium10.country = "India";
stadium10.seatingCapacity = 33000;
stadium10.stadiumType = "Cricket";
stadium10.floodLights = true;
stadium10.parkingAvailable = true;
stadium10.vipLounge = true;
stadium10.mediaRoom = true;
stadium10.lockerRooms = true;
stadium10.securitySystem = true;
stadium10.foodStalls = true;
stadium10.ticketCounter = true;
stadium10.onlineBooking = true;
stadium10.practiceGround = true;
stadium10.scoreboard = true;
stadium10.firstAid = true;
stadium10.cctvAvailable = true;
stadium10.publicTransportAccess = true;
stadium10.restroomAvailable = true;
stadium10.openingTime = "9:00 AM";
stadium10.closingTime = "11:30 PM";
stadium10.ticketPrice = 800;

System.out.println("Stadium name: "+stadium10.name);
System.out.println("Location: "+stadium10.location);
System.out.println("City: "+stadium10.city);
System.out.println("State: "+stadium10.state);
System.out.println("Country: "+stadium10.country);
System.out.println("Seating Capacity: "+stadium10.seatingCapacity);
System.out.println("Stadium Type: "+stadium10.stadiumType);
System.out.println("Flood Lights: "+stadium10.floodLights);
System.out.println("Parking Available: "+stadium10.parkingAvailable);
System.out.println("VIP Lounge: "+stadium10.vipLounge);
System.out.println("Media Room: "+stadium10.mediaRoom);
System.out.println("Locker Rooms: "+stadium10.lockerRooms);
System.out.println("Security System: "+stadium10.securitySystem);
System.out.println("Food Stalls: "+stadium10.foodStalls);
System.out.println("Ticket Counter: "+stadium10.ticketCounter);
System.out.println("Online Booking: "+stadium10.onlineBooking);
System.out.println("Practice Ground: "+stadium10.practiceGround);
System.out.println("Scoreboard: "+stadium10.scoreboard);
System.out.println("First Aid: "+stadium10.firstAid);
System.out.println("CCTV Available: "+stadium10.cctvAvailable);
System.out.println("Public Transport Access: "+stadium10.publicTransportAccess);
System.out.println("Restroom Available: "+stadium10.restroomAvailable);
System.out.println("Opening Time: "+stadium10.openingTime);
System.out.println("Closing Time: "+stadium10.closingTime);
System.out.println("Ticket Price: "+stadium10.ticketPrice);


}

}