class Swiggy {
    public static double search(String foodName) {
        if(foodName.equals("HyderabadiBiryani")) return 200;
        else if(foodName.equals("AndhraMeals")) return 150;
        else if(foodName.equals("NorthIndianThali")) return 180;
        else if(foodName.equals("SouthIndianThali")) return 160;
        else if(foodName.equals("FishCurry")) return 190;
        else if(foodName.equals("PrawnMasala")) return 240;
        else if(foodName.equals("EggCurry")) return 130;
        else if(foodName.equals("ChickenTikka")) return 210;
        else if(foodName.equals("TandooriChicken")) return 230;
        else if(foodName.equals("MalaiKofta")) return 170;
        else if(foodName.equals("KadaiPaneer")) return 165;
        else if(foodName.equals("VegKolhapuri")) return 150;
        else if(foodName.equals("MushroomMasala")) return 155;
        else if(foodName.equals("JeeraRice")) return 90;
        else if(foodName.equals("GheeRice")) return 100;
        else if(foodName.equals("ChickenFriedRice")) return 150;
        else if(foodName.equals("SchezwanNoodles")) return 140;
        else if(foodName.equals("ChilliChicken")) return 180;
        else if(foodName.equals("ChilliPaneer")) return 160;
        else if(foodName.equals("HotAndSourSoup")) return 95;
        else if(foodName.equals("SweetCornSoup")) return 85;
        else if(foodName.equals("MasalaPapad")) return 35;
        else if(foodName.equals("DahiPuri")) return 60;
        else if(foodName.equals("BhelPuri")) return 50;
        else if(foodName.equals("SevPuri")) return 55;
        else if(foodName.equals("PaniPuri")) return 40;
        else if(foodName.equals("Khichdi")) return 80;
        else if(foodName.equals("VegetablePulao")) return 120;
        else if(foodName.equals("MethiParatha")) return 75;
        else if(foodName.equals("LachhaParatha")) return 60;
        else if(foodName.equals("RumaliRoti")) return 35;
        else if(foodName.equals("ChickenShawarma")) return 130;
        else if(foodName.equals("VegShawarma")) return 110;
        else if(foodName.equals("FalafelWrap")) return 120;
        else if(foodName.equals("HummusPlatter")) return 150;
        else if(foodName.equals("Taco")) return 140;
        else if(foodName.equals("Nachos")) return 130;
        else if(foodName.equals("PastaAlfredo")) return 170;
        else if(foodName.equals("PastaArrabiata")) return 160;
        else if(foodName.equals("MacAndCheese")) return 150;
        else if(foodName.equals("ChocolateBrownie")) return 120;
        else if(foodName.equals("IceCreamSundae")) return 110;
        else if(foodName.equals("VanillaIceCream")) return 80;
        else if(foodName.equals("FruitSalad")) return 90;
        else if(foodName.equals("BlueberryShake")) return 120;
        else if(foodName.equals("OreoShake")) return 130;
        else if(foodName.equals("MochaCoffee")) return 100;
        else if(foodName.equals("Cappuccino")) return 110;
        else if(foodName.equals("Espresso")) return 90;
        else if(foodName.equals("GreenTea")) return 60;
        else if(foodName.equals("MasalaChai")) return 30;
        else if(foodName.equals("HerbalTea")) return 70;
        else if(foodName.equals("FreshLimeSoda")) return 50;
        else if(foodName.equals("OrangeJuice")) return 80;
        else if(foodName.equals("WatermelonJuice")) return 90;
        return 0;
    }
}
