class TempleRunner{

public static void main(String[] templess){

Temple temple1 = new Temple();

System.out.println("Before initialization : ");
System.out.println("Temple name : " + temple1.name);
System.out.println("Temple location : " + temple1.location);
System.out.println("Temple city : " + temple1.city);
System.out.println("Temple state : " + temple1.state);
System.out.println("Temple country : " + temple1.country);
System.out.println("Temple deity : " + temple1.deity);
System.out.println("Temple establishedYear : " + temple1.establishedYear);
System.out.println("Temple founder : " + temple1.founder);
System.out.println("Temple architectureStyle : " + temple1.architectureStyle);
System.out.println("Temple numberOfPriests : " + temple1.numberOfPriests);
System.out.println("Temple dailyVisitors : " + temple1.dailyVisitors);
System.out.println("Temple prasadamAvailable : " + temple1.prasadamAvailable);
System.out.println("Temple parkingAvailable : " + temple1.parkingAvailable);
System.out.println("Temple photographyAllowed : " + temple1.photographyAllowed);
System.out.println("Temple accommodationAvailable : " + temple1.accommodationAvailable);
System.out.println("Temple onlineBooking : " + temple1.onlineBooking);
System.out.println("Temple specialPooja : " + temple1.specialPooja);
System.out.println("Temple festivalCelebration : " + temple1.festivalCelebration);
System.out.println("Temple donationFacility : " + temple1.donationFacility);
System.out.println("Temple wheelchairAccess : " + temple1.wheelchairAccess);
System.out.println("Temple securitySystem : " + temple1.securitySystem);
System.out.println("Temple famousFestival : " + temple1.famousFestival);
System.out.println("Temple openingTime : " + temple1.openingTime);
System.out.println("Temple closingTime : " + temple1.closingTime);
System.out.println("Temple templeType : " + temple1.templeType);



temple1.name="Tirupati Balaji Temple";
temple1.location="Tirumala";
temple1.city="Tirupati";
temple1.state="Andhra Pradesh";
temple1.country="India";
temple1.deity="Lord Venkateshwara";
temple1.establishedYear=300;
temple1.founder="King Thondaiman";
temple1.architectureStyle="Dravidian";
temple1.numberOfPriests=200;
temple1.dailyVisitors=70000;
temple1.prasadamAvailable=true;
temple1.parkingAvailable=true;
temple1.photographyAllowed=false;
temple1.accommodationAvailable=true;
temple1.onlineBooking=true;
temple1.specialPooja=true;
temple1.festivalCelebration=true;
temple1.donationFacility=true;
temple1.wheelchairAccess=true;
temple1.securitySystem=true;
temple1.famousFestival="Brahmotsavam";
temple1.openingTime="3:00 AM";
temple1.closingTime="11:00 PM";
temple1.templeType="Hindu";


System.out.println("After initialization : ");
System.out.println("Temple name : " + temple1.name);
System.out.println("Temple location : " + temple1.location);
System.out.println("Temple city : " + temple1.city);
System.out.println("Temple state : " + temple1.state);
System.out.println("Temple country : " + temple1.country);
System.out.println("Temple deity : " + temple1.deity);
System.out.println("Temple establishedYear : " + temple1.establishedYear);
System.out.println("Temple founder : " + temple1.founder);
System.out.println("Temple architectureStyle : " + temple1.architectureStyle);
System.out.println("Temple numberOfPriests : " + temple1.numberOfPriests);
System.out.println("Temple dailyVisitors : " + temple1.dailyVisitors);
System.out.println("Temple prasadamAvailable : " + temple1.prasadamAvailable);
System.out.println("Temple parkingAvailable : " + temple1.parkingAvailable);
System.out.println("Temple photographyAllowed : " + temple1.photographyAllowed);
System.out.println("Temple accommodationAvailable : " + temple1.accommodationAvailable);
System.out.println("Temple onlineBooking : " + temple1.onlineBooking);
System.out.println("Temple specialPooja : " + temple1.specialPooja);
System.out.println("Temple festivalCelebration : " + temple1.festivalCelebration);
System.out.println("Temple donationFacility : " + temple1.donationFacility);
System.out.println("Temple wheelchairAccess : " + temple1.wheelchairAccess);
System.out.println("Temple securitySystem : " + temple1.securitySystem);
System.out.println("Temple famousFestival : " + temple1.famousFestival);
System.out.println("Temple openingTime : " + temple1.openingTime);
System.out.println("Temple closingTime : " + temple1.closingTime);
System.out.println("Temple templeType : " + temple1.templeType);



Temple temple2 = new Temple();

System.out.println("Temple name: "+temple2.name);
System.out.println("Temple location: "+temple2.location);
System.out.println("Temple city: "+temple2.city);
System.out.println("Temple state: "+temple2.state);
System.out.println("Temple country: "+temple2.country);
System.out.println("Temple deity: "+temple2.deity);
System.out.println("Temple established year: "+temple2.establishedYear);
System.out.println("Temple founder: "+temple2.founder);
System.out.println("Temple architecture style: "+temple2.architectureStyle);
System.out.println("Temple number of priests: "+temple2.numberOfPriests);
System.out.println("Temple daily visitors: "+temple2.dailyVisitors);
System.out.println("Temple prasadam available: "+temple2.prasadamAvailable);
System.out.println("Temple parking available: "+temple2.parkingAvailable);
System.out.println("Temple photography allowed: "+temple2.photographyAllowed);
System.out.println("Temple accommodation available: "+temple2.accommodationAvailable);
System.out.println("Temple online booking: "+temple2.onlineBooking);
System.out.println("Temple special pooja: "+temple2.specialPooja);
System.out.println("Temple festival celebration: "+temple2.festivalCelebration);
System.out.println("Temple donation facility: "+temple2.donationFacility);
System.out.println("Temple wheelchair access: "+temple2.wheelchairAccess);
System.out.println("Temple security system: "+temple2.securitySystem);
System.out.println("Temple famous festival: "+temple2.famousFestival);
System.out.println("Temple opening time: "+temple2.openingTime);
System.out.println("Temple closing time: "+temple2.closingTime);
System.out.println("Temple type: "+temple2.templeType);

temple2.name="Golden Temple";
temple2.location="Amritsar";
temple2.city="Amritsar";
temple2.state="Punjab";
temple2.country="India";
temple2.deity="Guru Granth Sahib";
temple2.establishedYear=1604;
temple2.founder="Guru Arjan";
temple2.architectureStyle="Sikh";
temple2.numberOfPriests=150;
temple2.dailyVisitors=50000;
temple2.prasadamAvailable=true;
temple2.parkingAvailable=true;
temple2.photographyAllowed=true;
temple2.accommodationAvailable=true;
temple2.onlineBooking=true;
temple2.specialPooja=true;
temple2.festivalCelebration=true;
temple2.donationFacility=true;
temple2.wheelchairAccess=true;
temple2.securitySystem=true;
temple2.famousFestival="Guru Nanak Jayanti";
temple2.openingTime="4:00 AM";
temple2.closingTime="10:00 PM";
temple2.templeType="Sikh";

System.out.println("Temple name: "+temple2.name);
System.out.println("Temple location: "+temple2.location);
System.out.println("Temple city: "+temple2.city);
System.out.println("Temple state: "+temple2.state);
System.out.println("Temple country: "+temple2.country);
System.out.println("Temple deity: "+temple2.deity);
System.out.println("Temple established year: "+temple2.establishedYear);
System.out.println("Temple founder: "+temple2.founder);
System.out.println("Temple architecture style: "+temple2.architectureStyle);
System.out.println("Temple number of priests: "+temple2.numberOfPriests);
System.out.println("Temple daily visitors: "+temple2.dailyVisitors);
System.out.println("Temple prasadam available: "+temple2.prasadamAvailable);
System.out.println("Temple parking available: "+temple2.parkingAvailable);
System.out.println("Temple photography allowed: "+temple2.photographyAllowed);
System.out.println("Temple accommodation available: "+temple2.accommodationAvailable);
System.out.println("Temple online booking: "+temple2.onlineBooking);
System.out.println("Temple special pooja: "+temple2.specialPooja);
System.out.println("Temple festival celebration: "+temple2.festivalCelebration);
System.out.println("Temple donation facility: "+temple2.donationFacility);
System.out.println("Temple wheelchair access: "+temple2.wheelchairAccess);
System.out.println("Temple security system: "+temple2.securitySystem);
System.out.println("Temple famous festival: "+temple2.famousFestival);
System.out.println("Temple opening time: "+temple2.openingTime);
System.out.println("Temple closing time: "+temple2.closingTime);
System.out.println("Temple type: "+temple2.templeType);



Temple temple3 = new Temple();

System.out.println("Temple name: "+temple3.name);
System.out.println("Temple location: "+temple3.location);
System.out.println("Temple city: "+temple3.city);
System.out.println("Temple state: "+temple3.state);
System.out.println("Temple country: "+temple3.country);
System.out.println("Temple deity: "+temple3.deity);
System.out.println("Temple established year: "+temple3.establishedYear);
System.out.println("Temple founder: "+temple3.founder);
System.out.println("Temple architecture style: "+temple3.architectureStyle);
System.out.println("Temple number of priests: "+temple3.numberOfPriests);
System.out.println("Temple daily visitors: "+temple3.dailyVisitors);
System.out.println("Temple prasadam available: "+temple3.prasadamAvailable);
System.out.println("Temple parking available: "+temple3.parkingAvailable);
System.out.println("Temple photography allowed: "+temple3.photographyAllowed);
System.out.println("Temple accommodation available: "+temple3.accommodationAvailable);
System.out.println("Temple online booking: "+temple3.onlineBooking);
System.out.println("Temple special pooja: "+temple3.specialPooja);
System.out.println("Temple festival celebration: "+temple3.festivalCelebration);
System.out.println("Temple donation facility: "+temple3.donationFacility);
System.out.println("Temple wheelchair access: "+temple3.wheelchairAccess);
System.out.println("Temple security system: "+temple3.securitySystem);
System.out.println("Temple famous festival: "+temple3.famousFestival);
System.out.println("Temple opening time: "+temple3.openingTime);
System.out.println("Temple closing time: "+temple3.closingTime);
System.out.println("Temple type: "+temple3.templeType);




temple3.name="Meenakshi Temple";
temple3.location="Madurai";
temple3.city="Madurai";
temple3.state="Tamil Nadu";
temple3.country="India";
temple3.deity="Goddess Meenakshi";
temple3.establishedYear=1600;
temple3.founder="Pandya Kings";
temple3.architectureStyle="Dravidian";
temple3.numberOfPriests=120;
temple3.dailyVisitors=30000;
temple3.prasadamAvailable=true;
temple3.parkingAvailable=true;
temple3.photographyAllowed=false;
temple3.accommodationAvailable=true;
temple3.onlineBooking=false;
temple3.specialPooja=true;
temple3.festivalCelebration=true;
temple3.donationFacility=true;
temple3.wheelchairAccess=false;
temple3.securitySystem=true;
temple3.famousFestival="Chithirai Festival";
temple3.openingTime="5:00 AM";
temple3.closingTime="9:30 PM";
temple3.templeType="Hindu";

System.out.println("Temple name: "+temple3.name);
System.out.println("Temple location: "+temple3.location);
System.out.println("Temple city: "+temple3.city);
System.out.println("Temple state: "+temple3.state);
System.out.println("Temple country: "+temple3.country);
System.out.println("Temple deity: "+temple3.deity);
System.out.println("Temple established year: "+temple3.establishedYear);
System.out.println("Temple founder: "+temple3.founder);
System.out.println("Temple architecture style: "+temple3.architectureStyle);
System.out.println("Temple number of priests: "+temple3.numberOfPriests);
System.out.println("Temple daily visitors: "+temple3.dailyVisitors);
System.out.println("Temple prasadam available: "+temple3.prasadamAvailable);
System.out.println("Temple parking available: "+temple3.parkingAvailable);
System.out.println("Temple photography allowed: "+temple3.photographyAllowed);
System.out.println("Temple accommodation available: "+temple3.accommodationAvailable);
System.out.println("Temple online booking: "+temple3.onlineBooking);
System.out.println("Temple special pooja: "+temple3.specialPooja);
System.out.println("Temple festival celebration: "+temple3.festivalCelebration);
System.out.println("Temple donation facility: "+temple3.donationFacility);
System.out.println("Temple wheelchair access: "+temple3.wheelchairAccess);
System.out.println("Temple security system: "+temple3.securitySystem);
System.out.println("Temple famous festival: "+temple3.famousFestival);
System.out.println("Temple opening time: "+temple3.openingTime);
System.out.println("Temple closing time: "+temple3.closingTime);
System.out.println("Temple type: "+temple3.templeType);

Temple temple4 = new Temple();


System.out.println("Temple name: "+temple4.name);
System.out.println("Temple location: "+temple4.location);
System.out.println("Temple city: "+temple4.city);
System.out.println("Temple state: "+temple4.state);
System.out.println("Temple country: "+temple4.country);
System.out.println("Temple deity: "+temple4.deity);
System.out.println("Temple established year: "+temple4.establishedYear);
System.out.println("Temple founder: "+temple4.founder);
System.out.println("Temple architecture style: "+temple4.architectureStyle);
System.out.println("Temple number of priests: "+temple4.numberOfPriests);
System.out.println("Temple daily visitors: "+temple4.dailyVisitors);
System.out.println("Temple prasadam available: "+temple4.prasadamAvailable);
System.out.println("Temple parking available: "+temple4.parkingAvailable);
System.out.println("Temple photography allowed: "+temple4.photographyAllowed);
System.out.println("Temple accommodation available: "+temple4.accommodationAvailable);
System.out.println("Temple online booking: "+temple4.onlineBooking);
System.out.println("Temple special pooja: "+temple4.specialPooja);
System.out.println("Temple festival celebration: "+temple4.festivalCelebration);
System.out.println("Temple donation facility: "+temple4.donationFacility);
System.out.println("Temple wheelchair access: "+temple4.wheelchairAccess);
System.out.println("Temple security system: "+temple4.securitySystem);
System.out.println("Temple famous festival: "+temple4.famousFestival);
System.out.println("Temple opening time: "+temple4.openingTime);
System.out.println("Temple closing time: "+temple4.closingTime);
System.out.println("Temple type: "+temple4.templeType);

temple4.name="Somnath Temple";
temple4.location="Somnath";
temple4.city="Veraval";
temple4.state="Gujarat";
temple4.country="India";
temple4.deity="Lord Shiva";
temple4.establishedYear=1951;
temple4.founder="Sardar Patel";
temple4.architectureStyle="Chalukya";
temple4.numberOfPriests=90;
temple4.dailyVisitors=20000;
temple4.prasadamAvailable=true;
temple4.parkingAvailable=true;
temple4.photographyAllowed=false;
temple4.accommodationAvailable=true;
temple4.onlineBooking=true;
temple4.specialPooja=true;
temple4.festivalCelebration=true;
temple4.donationFacility=true;
temple4.wheelchairAccess=true;
temple4.securitySystem=true;
temple4.famousFestival="Mahashivratri";
temple4.openingTime="6:00 AM";
temple4.closingTime="9:00 PM";
temple4.templeType="Hindu";

System.out.println("Temple name: "+temple4.name);
System.out.println("Temple location: "+temple4.location);
System.out.println("Temple city: "+temple4.city);
System.out.println("Temple state: "+temple4.state);
System.out.println("Temple country: "+temple4.country);
System.out.println("Temple deity: "+temple4.deity);
System.out.println("Temple established year: "+temple4.establishedYear);
System.out.println("Temple founder: "+temple4.founder);
System.out.println("Temple architecture style: "+temple4.architectureStyle);
System.out.println("Temple number of priests: "+temple4.numberOfPriests);
System.out.println("Temple daily visitors: "+temple4.dailyVisitors);
System.out.println("Temple prasadam available: "+temple4.prasadamAvailable);
System.out.println("Temple parking available: "+temple4.parkingAvailable);
System.out.println("Temple photography allowed: "+temple4.photographyAllowed);
System.out.println("Temple accommodation available: "+temple4.accommodationAvailable);
System.out.println("Temple online booking: "+temple4.onlineBooking);
System.out.println("Temple special pooja: "+temple4.specialPooja);
System.out.println("Temple festival celebration: "+temple4.festivalCelebration);
System.out.println("Temple donation facility: "+temple4.donationFacility);
System.out.println("Temple wheelchair access: "+temple4.wheelchairAccess);
System.out.println("Temple security system: "+temple4.securitySystem);
System.out.println("Temple famous festival: "+temple4.famousFestival);
System.out.println("Temple opening time: "+temple4.openingTime);
System.out.println("Temple closing time: "+temple4.closingTime);
System.out.println("Temple type: "+temple4.templeType);

Temple temple5 = new Temple();

System.out.println("Temple name: "+temple5.name);
System.out.println("Temple location: "+temple5.location);
System.out.println("Temple city: "+temple5.city);
System.out.println("Temple state: "+temple5.state);
System.out.println("Temple country: "+temple5.country);
System.out.println("Temple deity: "+temple5.deity);
System.out.println("Temple established year: "+temple5.establishedYear);
System.out.println("Temple founder: "+temple5.founder);
System.out.println("Temple architecture style: "+temple5.architectureStyle);
System.out.println("Temple number of priests: "+temple5.numberOfPriests);
System.out.println("Temple daily visitors: "+temple5.dailyVisitors);
System.out.println("Temple prasadam available: "+temple5.prasadamAvailable);
System.out.println("Temple parking available: "+temple5.parkingAvailable);
System.out.println("Temple photography allowed: "+temple5.photographyAllowed);
System.out.println("Temple accommodation available: "+temple5.accommodationAvailable);
System.out.println("Temple online booking: "+temple5.onlineBooking);
System.out.println("Temple special pooja: "+temple5.specialPooja);
System.out.println("Temple festival celebration: "+temple5.festivalCelebration);
System.out.println("Temple donation facility: "+temple5.donationFacility);
System.out.println("Temple wheelchair access: "+temple5.wheelchairAccess);
System.out.println("Temple security system: "+temple5.securitySystem);
System.out.println("Temple famous festival: "+temple5.famousFestival);
System.out.println("Temple opening time: "+temple5.openingTime);
System.out.println("Temple closing time: "+temple5.closingTime);
System.out.println("Temple type: "+temple5.templeType);

temple5.name="Kedarnath Temple";
temple5.location="Kedarnath";
temple5.city="Rudraprayag";
temple5.state="Uttarakhand";
temple5.country="India";
temple5.deity="Lord Shiva";
temple5.establishedYear=800;
temple5.founder="Adi Shankaracharya";
temple5.architectureStyle="Himalayan";
temple5.numberOfPriests=70;
temple5.dailyVisitors=15000;
temple5.prasadamAvailable=true;
temple5.parkingAvailable=false;
temple5.photographyAllowed=false;
temple5.accommodationAvailable=true;
temple5.onlineBooking=true;
temple5.specialPooja=true;
temple5.festivalCelebration=true;
temple5.donationFacility=true;
temple5.wheelchairAccess=false;
temple5.securitySystem=true;
temple5.famousFestival="Mahashivratri";
temple5.openingTime="4:00 AM";
temple5.closingTime="8:00 PM";
temple5.templeType="Hindu";

System.out.println("Temple name: "+temple5.name);
System.out.println("Temple location: "+temple5.location);
System.out.println("Temple city: "+temple5.city);
System.out.println("Temple state: "+temple5.state);
System.out.println("Temple country: "+temple5.country);
System.out.println("Temple deity: "+temple5.deity);
System.out.println("Temple established year: "+temple5.establishedYear);
System.out.println("Temple founder: "+temple5.founder);
System.out.println("Temple architecture style: "+temple5.architectureStyle);
System.out.println("Temple number of priests: "+temple5.numberOfPriests);
System.out.println("Temple daily visitors: "+temple5.dailyVisitors);
System.out.println("Temple prasadam available: "+temple5.prasadamAvailable);
System.out.println("Temple parking available: "+temple5.parkingAvailable);
System.out.println("Temple photography allowed: "+temple5.photographyAllowed);
System.out.println("Temple accommodation available: "+temple5.accommodationAvailable);
System.out.println("Temple online booking: "+temple5.onlineBooking);
System.out.println("Temple special pooja: "+temple5.specialPooja);
System.out.println("Temple festival celebration: "+temple5.festivalCelebration);
System.out.println("Temple donation facility: "+temple5.donationFacility);
System.out.println("Temple wheelchair access: "+temple5.wheelchairAccess);
System.out.println("Temple security system: "+temple5.securitySystem);
System.out.println("Temple famous festival: "+temple5.famousFestival);
System.out.println("Temple opening time: "+temple5.openingTime);
System.out.println("Temple closing time: "+temple5.closingTime);
System.out.println("Temple type: "+temple5.templeType);


Temple temple6 = new Temple();

System.out.println("Temple name: "+temple6.name);
System.out.println("Temple location: "+temple6.location);
System.out.println("Temple city: "+temple6.city);
System.out.println("Temple state: "+temple6.state);
System.out.println("Temple country: "+temple6.country);
System.out.println("Temple deity: "+temple6.deity);
System.out.println("Temple established year: "+temple6.establishedYear);
System.out.println("Temple founder: "+temple6.founder);
System.out.println("Temple architecture style: "+temple6.architectureStyle);
System.out.println("Temple number of priests: "+temple6.numberOfPriests);
System.out.println("Temple daily visitors: "+temple6.dailyVisitors);
System.out.println("Temple prasadam available: "+temple6.prasadamAvailable);
System.out.println("Temple parking available: "+temple6.parkingAvailable);
System.out.println("Temple photography allowed: "+temple6.photographyAllowed);
System.out.println("Temple accommodation available: "+temple6.accommodationAvailable);
System.out.println("Temple online booking: "+temple6.onlineBooking);
System.out.println("Temple special pooja: "+temple6.specialPooja);
System.out.println("Temple festival celebration: "+temple6.festivalCelebration);
System.out.println("Temple donation facility: "+temple6.donationFacility);
System.out.println("Temple wheelchair access: "+temple6.wheelchairAccess);
System.out.println("Temple security system: "+temple6.securitySystem);
System.out.println("Temple famous festival: "+temple6.famousFestival);
System.out.println("Temple opening time: "+temple6.openingTime);
System.out.println("Temple closing time: "+temple6.closingTime);
System.out.println("Temple type: "+temple6.templeType);


temple6.name="Badrinath Temple";
temple6.location="Badrinath";
temple6.city="Chamoli";
temple6.state="Uttarakhand";
temple6.country="India";
temple6.deity="Lord Vishnu";
temple6.establishedYear=900;
temple6.founder="Adi Shankaracharya";
temple6.architectureStyle="North Indian";
temple6.numberOfPriests=80;
temple6.dailyVisitors=18000;
temple6.prasadamAvailable=true;
temple6.parkingAvailable=false;
temple6.photographyAllowed=false;
temple6.accommodationAvailable=true;
temple6.onlineBooking=true;
temple6.specialPooja=true;
temple6.festivalCelebration=true;
temple6.donationFacility=true;
temple6.wheelchairAccess=false;
temple6.securitySystem=true;
temple6.famousFestival="Badri Kedar Festival";
temple6.openingTime="4:30 AM";
temple6.closingTime="9:00 PM";
temple6.templeType="Hindu";

System.out.println("Temple name: "+temple6.name);
System.out.println("Temple location: "+temple6.location);
System.out.println("Temple city: "+temple6.city);
System.out.println("Temple state: "+temple6.state);
System.out.println("Temple country: "+temple6.country);
System.out.println("Temple deity: "+temple6.deity);
System.out.println("Temple established year: "+temple6.establishedYear);
System.out.println("Temple founder: "+temple6.founder);
System.out.println("Temple architecture style: "+temple6.architectureStyle);
System.out.println("Temple number of priests: "+temple6.numberOfPriests);
System.out.println("Temple daily visitors: "+temple6.dailyVisitors);
System.out.println("Temple prasadam available: "+temple6.prasadamAvailable);
System.out.println("Temple parking available: "+temple6.parkingAvailable);
System.out.println("Temple photography allowed: "+temple6.photographyAllowed);
System.out.println("Temple accommodation available: "+temple6.accommodationAvailable);
System.out.println("Temple online booking: "+temple6.onlineBooking);
System.out.println("Temple special pooja: "+temple6.specialPooja);
System.out.println("Temple festival celebration: "+temple6.festivalCelebration);
System.out.println("Temple donation facility: "+temple6.donationFacility);
System.out.println("Temple wheelchair access: "+temple6.wheelchairAccess);
System.out.println("Temple security system: "+temple6.securitySystem);
System.out.println("Temple famous festival: "+temple6.famousFestival);
System.out.println("Temple opening time: "+temple6.openingTime);
System.out.println("Temple closing time: "+temple6.closingTime);
System.out.println("Temple type: "+temple6.templeType);

Temple temple7 = new Temple();

System.out.println("Temple name: "+temple7.name);
System.out.println("Temple location: "+temple7.location);
System.out.println("Temple city: "+temple7.city);
System.out.println("Temple state: "+temple7.state);
System.out.println("Temple country: "+temple7.country);
System.out.println("Temple deity: "+temple7.deity);
System.out.println("Temple established year: "+temple7.establishedYear);
System.out.println("Temple founder: "+temple7.founder);
System.out.println("Temple architecture style: "+temple7.architectureStyle);
System.out.println("Temple number of priests: "+temple7.numberOfPriests);
System.out.println("Temple daily visitors: "+temple7.dailyVisitors);
System.out.println("Temple prasadam available: "+temple7.prasadamAvailable);
System.out.println("Temple parking available: "+temple7.parkingAvailable);
System.out.println("Temple photography allowed: "+temple7.photographyAllowed);
System.out.println("Temple accommodation available: "+temple7.accommodationAvailable);
System.out.println("Temple online booking: "+temple7.onlineBooking);
System.out.println("Temple special pooja: "+temple7.specialPooja);
System.out.println("Temple festival celebration: "+temple7.festivalCelebration);
System.out.println("Temple donation facility: "+temple7.donationFacility);
System.out.println("Temple wheelchair access: "+temple7.wheelchairAccess);
System.out.println("Temple security system: "+temple7.securitySystem);
System.out.println("Temple famous festival: "+temple7.famousFestival);
System.out.println("Temple opening time: "+temple7.openingTime);
System.out.println("Temple closing time: "+temple7.closingTime);
System.out.println("Temple type: "+temple7.templeType);

temple7.name="Jagannath Temple";
temple7.location="Puri";
temple7.city="Puri";
temple7.state="Odisha";
temple7.country="India";
temple7.deity="Lord Jagannath";
temple7.establishedYear=1161;
temple7.founder="King Anantavarman";
temple7.architectureStyle="Kalinga";
temple7.numberOfPriests=150;
temple7.dailyVisitors=40000;
temple7.prasadamAvailable=true;
temple7.parkingAvailable=true;
temple7.photographyAllowed=false;
temple7.accommodationAvailable=true;
temple7.onlineBooking=true;
temple7.specialPooja=true;
temple7.festivalCelebration=true;
temple7.donationFacility=true;
temple7.wheelchairAccess=true;
temple7.securitySystem=true;
temple7.famousFestival="Rath Yatra";
temple7.openingTime="5:00 AM";
temple7.closingTime="10:00 PM";
temple7.templeType="Hindu";

System.out.println("Temple name: "+temple7.name);
System.out.println("Temple location: "+temple7.location);
System.out.println("Temple city: "+temple7.city);
System.out.println("Temple state: "+temple7.state);
System.out.println("Temple country: "+temple7.country);
System.out.println("Temple deity: "+temple7.deity);
System.out.println("Temple established year: "+temple7.establishedYear);
System.out.println("Temple founder: "+temple7.founder);
System.out.println("Temple architecture style: "+temple7.architectureStyle);
System.out.println("Temple number of priests: "+temple7.numberOfPriests);
System.out.println("Temple daily visitors: "+temple7.dailyVisitors);
System.out.println("Temple prasadam available: "+temple7.prasadamAvailable);
System.out.println("Temple parking available: "+temple7.parkingAvailable);
System.out.println("Temple photography allowed: "+temple7.photographyAllowed);
System.out.println("Temple accommodation available: "+temple7.accommodationAvailable);
System.out.println("Temple online booking: "+temple7.onlineBooking);
System.out.println("Temple special pooja: "+temple7.specialPooja);
System.out.println("Temple festival celebration: "+temple7.festivalCelebration);
System.out.println("Temple donation facility: "+temple7.donationFacility);
System.out.println("Temple wheelchair access: "+temple7.wheelchairAccess);
System.out.println("Temple security system: "+temple7.securitySystem);
System.out.println("Temple famous festival: "+temple7.famousFestival);
System.out.println("Temple opening time: "+temple7.openingTime);
System.out.println("Temple closing time: "+temple7.closingTime);
System.out.println("Temple type: "+temple7.templeType);


Temple temple8 = new Temple();

System.out.println("Temple name: "+temple8.name);
System.out.println("Temple location: "+temple8.location);
System.out.println("Temple city: "+temple8.city);
System.out.println("Temple state: "+temple8.state);
System.out.println("Temple country: "+temple8.country);
System.out.println("Temple deity: "+temple8.deity);
System.out.println("Temple established year: "+temple8.establishedYear);
System.out.println("Temple founder: "+temple8.founder);
System.out.println("Temple architecture style: "+temple8.architectureStyle);
System.out.println("Temple number of priests: "+temple8.numberOfPriests);
System.out.println("Temple daily visitors: "+temple8.dailyVisitors);
System.out.println("Temple prasadam available: "+temple8.prasadamAvailable);
System.out.println("Temple parking available: "+temple8.parkingAvailable);
System.out.println("Temple photography allowed: "+temple8.photographyAllowed);
System.out.println("Temple accommodation available: "+temple8.accommodationAvailable);
System.out.println("Temple online booking: "+temple8.onlineBooking);
System.out.println("Temple special pooja: "+temple8.specialPooja);
System.out.println("Temple festival celebration: "+temple8.festivalCelebration);
System.out.println("Temple donation facility: "+temple8.donationFacility);
System.out.println("Temple wheelchair access: "+temple8.wheelchairAccess);
System.out.println("Temple security system: "+temple8.securitySystem);
System.out.println("Temple famous festival: "+temple8.famousFestival);
System.out.println("Temple opening time: "+temple8.openingTime);
System.out.println("Temple closing time: "+temple8.closingTime);
System.out.println("Temple type: "+temple8.templeType);

temple8.name="Rameshwaram Temple";
temple8.location="Rameshwaram";
temple8.city="Ramanathapuram";
temple8.state="Tamil Nadu";
temple8.country="India";
temple8.deity="Lord Shiva";
temple8.establishedYear=1200;
temple8.founder="Pandya Dynasty";
temple8.architectureStyle="Dravidian";
temple8.numberOfPriests=100;
temple8.dailyVisitors=25000;
temple8.prasadamAvailable=true;
temple8.parkingAvailable=true;
temple8.photographyAllowed=false;
temple8.accommodationAvailable=true;
temple8.onlineBooking=true;
temple8.specialPooja=true;
temple8.festivalCelebration=true;
temple8.donationFacility=true;
temple8.wheelchairAccess=true;
temple8.securitySystem=true;
temple8.famousFestival="Mahashivratri";
temple8.openingTime="5:00 AM";
temple8.closingTime="9:00 PM";
temple8.templeType="Hindu";

System.out.println("Temple name: "+temple8.name);
System.out.println("Temple location: "+temple8.location);
System.out.println("Temple city: "+temple8.city);
System.out.println("Temple state: "+temple8.state);
System.out.println("Temple country: "+temple8.country);
System.out.println("Temple deity: "+temple8.deity);
System.out.println("Temple established year: "+temple8.establishedYear);
System.out.println("Temple founder: "+temple8.founder);
System.out.println("Temple architecture style: "+temple8.architectureStyle);
System.out.println("Temple number of priests: "+temple8.numberOfPriests);
System.out.println("Temple daily visitors: "+temple8.dailyVisitors);
System.out.println("Temple prasadam available: "+temple8.prasadamAvailable);
System.out.println("Temple parking available: "+temple8.parkingAvailable);
System.out.println("Temple photography allowed: "+temple8.photographyAllowed);
System.out.println("Temple accommodation available: "+temple8.accommodationAvailable);
System.out.println("Temple online booking: "+temple8.onlineBooking);
System.out.println("Temple special pooja: "+temple8.specialPooja);
System.out.println("Temple festival celebration: "+temple8.festivalCelebration);
System.out.println("Temple donation facility: "+temple8.donationFacility);
System.out.println("Temple wheelchair access: "+temple8.wheelchairAccess);
System.out.println("Temple security system: "+temple8.securitySystem);
System.out.println("Temple famous festival: "+temple8.famousFestival);
System.out.println("Temple opening time: "+temple8.openingTime);
System.out.println("Temple closing time: "+temple8.closingTime);
System.out.println("Temple type: "+temple8.templeType);


Temple temple9 = new Temple();

System.out.println("Temple name: "+temple9.name);
System.out.println("Temple location: "+temple9.location);
System.out.println("Temple city: "+temple9.city);
System.out.println("Temple state: "+temple9.state);
System.out.println("Temple country: "+temple9.country);
System.out.println("Temple deity: "+temple9.deity);
System.out.println("Temple established year: "+temple9.establishedYear);
System.out.println("Temple founder: "+temple9.founder);
System.out.println("Temple architecture style: "+temple9.architectureStyle);
System.out.println("Temple number of priests: "+temple9.numberOfPriests);
System.out.println("Temple daily visitors: "+temple9.dailyVisitors);
System.out.println("Temple prasadam available: "+temple9.prasadamAvailable);
System.out.println("Temple parking available: "+temple9.parkingAvailable);
System.out.println("Temple photography allowed: "+temple9.photographyAllowed);
System.out.println("Temple accommodation available: "+temple9.accommodationAvailable);
System.out.println("Temple online booking: "+temple9.onlineBooking);
System.out.println("Temple special pooja: "+temple9.specialPooja);
System.out.println("Temple festival celebration: "+temple9.festivalCelebration);
System.out.println("Temple donation facility: "+temple9.donationFacility);
System.out.println("Temple wheelchair access: "+temple9.wheelchairAccess);
System.out.println("Temple security system: "+temple9.securitySystem);
System.out.println("Temple famous festival: "+temple9.famousFestival);
System.out.println("Temple opening time: "+temple9.openingTime);
System.out.println("Temple closing time: "+temple9.closingTime);
System.out.println("Temple type: "+temple9.templeType);

temple9.name="Vaishno Devi Temple";
temple9.location="Katra";
temple9.city="Reasi";
temple9.state="Jammu and Kashmir";
temple9.country="India";
temple9.deity="Goddess Vaishno Devi";
temple9.establishedYear=700;
temple9.founder="Pandit Sridhar";
temple9.architectureStyle="North Indian";
temple9.numberOfPriests=120;
temple9.dailyVisitors=35000;
temple9.prasadamAvailable=true;
temple9.parkingAvailable=true;
temple9.photographyAllowed=false;
temple9.accommodationAvailable=true;
temple9.onlineBooking=true;
temple9.specialPooja=true;
temple9.festivalCelebration=true;
temple9.donationFacility=true;
temple9.wheelchairAccess=false;
temple9.securitySystem=true;
temple9.famousFestival="Navratri";
temple9.openingTime="4:00 AM";
temple9.closingTime="10:00 PM";
temple9.templeType="Hindu";

System.out.println("Temple name: "+temple9.name);
System.out.println("Temple location: "+temple9.location);
System.out.println("Temple city: "+temple9.city);
System.out.println("Temple state: "+temple9.state);
System.out.println("Temple country: "+temple9.country);
System.out.println("Temple deity: "+temple9.deity);
System.out.println("Temple established year: "+temple9.establishedYear);
System.out.println("Temple founder: "+temple9.founder);
System.out.println("Temple architecture style: "+temple9.architectureStyle);
System.out.println("Temple number of priests: "+temple9.numberOfPriests);
System.out.println("Temple daily visitors: "+temple9.dailyVisitors);
System.out.println("Temple prasadam available: "+temple9.prasadamAvailable);
System.out.println("Temple parking available: "+temple9.parkingAvailable);
System.out.println("Temple photography allowed: "+temple9.photographyAllowed);
System.out.println("Temple accommodation available: "+temple9.accommodationAvailable);
System.out.println("Temple online booking: "+temple9.onlineBooking);
System.out.println("Temple special pooja: "+temple9.specialPooja);
System.out.println("Temple festival celebration: "+temple9.festivalCelebration);
System.out.println("Temple donation facility: "+temple9.donationFacility);
System.out.println("Temple wheelchair access: "+temple9.wheelchairAccess);
System.out.println("Temple security system: "+temple9.securitySystem);
System.out.println("Temple famous festival: "+temple9.famousFestival);
System.out.println("Temple opening time: "+temple9.openingTime);
System.out.println("Temple closing time: "+temple9.closingTime);
System.out.println("Temple type: "+temple9.templeType);


Temple temple10 = new Temple();

System.out.println("Temple name: "+temple10.name);
System.out.println("Temple location: "+temple10.location);
System.out.println("Temple city: "+temple10.city);
System.out.println("Temple state: "+temple10.state);
System.out.println("Temple country: "+temple10.country);
System.out.println("Temple deity: "+temple10.deity);
System.out.println("Temple established year: "+temple10.establishedYear);
System.out.println("Temple founder: "+temple10.founder);
System.out.println("Temple architecture style: "+temple10.architectureStyle);
System.out.println("Temple number of priests: "+temple10.numberOfPriests);
System.out.println("Temple daily visitors: "+temple10.dailyVisitors);
System.out.println("Temple prasadam available: "+temple10.prasadamAvailable);
System.out.println("Temple parking available: "+temple10.parkingAvailable);
System.out.println("Temple photography allowed: "+temple10.photographyAllowed);
System.out.println("Temple accommodation available: "+temple10.accommodationAvailable);
System.out.println("Temple online booking: "+temple10.onlineBooking);
System.out.println("Temple special pooja: "+temple10.specialPooja);
System.out.println("Temple festival celebration: "+temple10.festivalCelebration);
System.out.println("Temple donation facility: "+temple10.donationFacility);
System.out.println("Temple wheelchair access: "+temple10.wheelchairAccess);
System.out.println("Temple security system: "+temple10.securitySystem);
System.out.println("Temple famous festival: "+temple10.famousFestival);
System.out.println("Temple opening time: "+temple10.openingTime);
System.out.println("Temple closing time: "+temple10.closingTime);
System.out.println("Temple type: "+temple10.templeType);

temple10.name="Akshardham Temple";
temple10.location="Delhi";
temple10.city="New Delhi";
temple10.state="Delhi";
temple10.country="India";
temple10.deity="Swaminarayan";
temple10.establishedYear=2005;
temple10.founder="BAPS Organization";
temple10.architectureStyle="Modern Hindu";
temple10.numberOfPriests=80;
temple10.dailyVisitors=20000;
temple10.prasadamAvailable=true;
temple10.parkingAvailable=true;
temple10.photographyAllowed=false;
temple10.accommodationAvailable=false;
temple10.onlineBooking=true;
temple10.specialPooja=true;
temple10.festivalCelebration=true;
temple10.donationFacility=true;
temple10.wheelchairAccess=true;
temple10.securitySystem=true;
temple10.famousFestival="Diwali";
temple10.openingTime="9:30 AM";
temple10.closingTime="6:30 PM";
temple10.templeType="Hindu";

System.out.println("Temple name: "+temple10.name);
System.out.println("Temple location: "+temple10.location);
System.out.println("Temple city: "+temple10.city);
System.out.println("Temple state: "+temple10.state);
System.out.println("Temple country: "+temple10.country);
System.out.println("Temple deity: "+temple10.deity);
System.out.println("Temple established year: "+temple10.establishedYear);
System.out.println("Temple founder: "+temple10.founder);
System.out.println("Temple architecture style: "+temple10.architectureStyle);
System.out.println("Temple number of priests: "+temple10.numberOfPriests);
System.out.println("Temple daily visitors: "+temple10.dailyVisitors);
System.out.println("Temple prasadam available: "+temple10.prasadamAvailable);
System.out.println("Temple parking available: "+temple10.parkingAvailable);
System.out.println("Temple photography allowed: "+temple10.photographyAllowed);
System.out.println("Temple accommodation available: "+temple10.accommodationAvailable);
System.out.println("Temple online booking: "+temple10.onlineBooking);
System.out.println("Temple special pooja: "+temple10.specialPooja);
System.out.println("Temple festival celebration: "+temple10.festivalCelebration);
System.out.println("Temple donation facility: "+temple10.donationFacility);
System.out.println("Temple wheelchair access: "+temple10.wheelchairAccess);
System.out.println("Temple security system: "+temple10.securitySystem);
System.out.println("Temple famous festival: "+temple10.famousFestival);
System.out.println("Temple opening time: "+temple10.openingTime);
System.out.println("Temple closing time: "+temple10.closingTime);
System.out.println("Temple type: "+temple10.templeType);


/*Temple temple11 = new Temple();

temple11.name="ISKCON Temple";
temple11.location="Bangalore";
temple11.city="Bengaluru";
temple11.state="Karnataka";
temple11.country="India";
temple11.deity="Lord Krishna";
temple11.establishedYear=1997;
temple11.founder="ISKCON Society";
temple11.architectureStyle="Modern";
temple11.numberOfPriests=60;
temple11.dailyVisitors=15000;
temple11.prasadamAvailable=true;
temple11.parkingAvailable=true;
temple11.photographyAllowed=false;
temple11.accommodationAvailable=true;
temple11.onlineBooking=true;
temple11.specialPooja=true;
temple11.festivalCelebration=true;
temple11.donationFacility=true;
temple11.wheelchairAccess=true;
temple11.securitySystem=true;
temple11.famousFestival="Janmashtami";
temple11.openingTime="4:30 AM";
temple11.closingTime="8:30 PM";
temple11.templeType="Hindu";

Temple temple12 = new Temple();
temple12.name="Kashi Vishwanath Temple";
temple12.location="Varanasi";
temple12.city="Varanasi";
temple12.state="Uttar Pradesh";
temple12.country="India";
temple12.deity="Lord Shiva";
temple12.establishedYear=1780;
temple12.founder="Ahilyabai Holkar";
temple12.architectureStyle="North Indian";
temple12.numberOfPriests=100;
temple12.dailyVisitors=30000;
temple12.prasadamAvailable=true;
temple12.parkingAvailable=true;
temple12.photographyAllowed=false;
temple12.accommodationAvailable=true;
temple12.onlineBooking=true;
temple12.specialPooja=true;
temple12.festivalCelebration=true;
temple12.donationFacility=true;
temple12.wheelchairAccess=true;
temple12.securitySystem=true;
temple12.famousFestival="Mahashivratri";
temple12.openingTime="3:00 AM";
temple12.closingTime="11:00 PM";
temple12.templeType="Hindu";



Temple temple13 = new Temple();

temple13.name="Shirdi Sai Baba Temple";
temple13.location="Shirdi";
temple13.city="Ahmednagar";
temple13.state="Maharashtra";
temple13.country="India";
temple13.deity="Sai Baba";
temple13.establishedYear=1922;
temple13.founder="Sai Baba Devotees";
temple13.architectureStyle="Modern";
temple13.numberOfPriests=70;
temple13.dailyVisitors=25000;
temple13.prasadamAvailable=true;
temple13.parkingAvailable=true;
temple13.photographyAllowed=false;
temple13.accommodationAvailable=true;
temple13.onlineBooking=true;
temple13.specialPooja=true;
temple13.festivalCelebration=true;
temple13.donationFacility=true;
temple13.wheelchairAccess=true;
temple13.securitySystem=true;
temple13.famousFestival="Ram Navami";
temple13.openingTime="4:00 AM";
temple13.closingTime="10:30 PM";
temple13.templeType="Hindu";


Temple temple14 = new Temple();

temple14.name="Murudeshwar Temple";
temple14.location="Murudeshwar";
temple14.city="Bhatkal";
temple14.state="Karnataka";
temple14.country="India";
temple14.deity="Lord Shiva";
temple14.establishedYear=2008;
temple14.founder="R N Shetty";
temple14.architectureStyle="Modern";
temple14.numberOfPriests=50;
temple14.dailyVisitors=12000;
temple14.prasadamAvailable=true;
temple14.parkingAvailable=true;
temple14.photographyAllowed=true;
temple14.accommodationAvailable=true;
temple14.onlineBooking=false;
temple14.specialPooja=true;
temple14.festivalCelebration=true;
temple14.donationFacility=true;
temple14.wheelchairAccess=true;
temple14.securitySystem=true;
temple14.famousFestival="Mahashivratri";
temple14.openingTime="6:00 AM";
temple14.closingTime="8:30 PM";
temple14.templeType="Hindu";


Temple temple15 = new Temple();

temple15.name="Dharmasthala Temple";
temple15.location="Dharmasthala";
temple15.city="Dakshina Kannada";
temple15.state="Karnataka";
temple15.country="India";
temple15.deity="Lord Manjunatha";
temple15.establishedYear=800;
temple15.founder="Pergade Family";
temple15.architectureStyle="Dravidian";
temple15.numberOfPriests=90;
temple15.dailyVisitors=20000;
temple15.prasadamAvailable=true;
temple15.parkingAvailable=true;
temple15.photographyAllowed=false;
temple15.accommodationAvailable=true;
temple15.onlineBooking=true;
temple15.specialPooja=true;
temple15.festivalCelebration=true;
temple15.donationFacility=true;
temple15.wheelchairAccess=true;
temple15.securitySystem=true;
temple15.famousFestival="Laksha Deepotsava";
temple15.openingTime="6:00 AM";
temple15.closingTime="9:00 PM";
temple15.templeType="Hindu";


Temple temple16 = new Temple();

temple16.name="Udupi Krishna Temple";
temple16.location="Udupi";
temple16.city="Udupi";
temple16.state="Karnataka";
temple16.country="India";
temple16.deity="Lord Krishna";
temple16.establishedYear=1200;
temple16.founder="Madhvacharya";
temple16.architectureStyle="Traditional";
temple16.numberOfPriests=60;
temple16.dailyVisitors=15000;
temple16.prasadamAvailable=true;
temple16.parkingAvailable=true;
temple16.photographyAllowed=false;
temple16.accommodationAvailable=true;
temple16.onlineBooking=true;
temple16.specialPooja=true;
temple16.festivalCelebration=true;
temple16.donationFacility=true;
temple16.wheelchairAccess=true;
temple16.securitySystem=true;
temple16.famousFestival="Krishna Janmashtami";
temple16.openingTime="5:00 AM";
temple16.closingTime="9:00 PM";
temple16.templeType="Hindu";



Temple temple17 = new Temple();

temple17.name="Sabarimala Temple";
temple17.location="Sabarimala";
temple17.city="Pathanamthitta";
temple17.state="Kerala";
temple17.country="India";
temple17.deity="Lord Ayyappa";
temple17.establishedYear=1000;
temple17.founder="Pandalam Kings";
temple17.architectureStyle="Kerala";
temple17.numberOfPriests=80;
temple17.dailyVisitors=50000;
temple17.prasadamAvailable=true;
temple17.parkingAvailable=false;
temple17.photographyAllowed=false;
temple17.accommodationAvailable=true;
temple17.onlineBooking=true;
temple17.specialPooja=true;
temple17.festivalCelebration=true;
temple17.donationFacility=true;
temple17.wheelchairAccess=false;
temple17.securitySystem=true;
temple17.famousFestival="Mandala Pooja";
temple17.openingTime="4:00 AM";
temple17.closingTime="10:00 PM";
temple17.templeType="Hindu";



Temple temple18 = new Temple();

temple18.name="Konark Sun Temple";
temple18.location="Konark";
temple18.city="Puri";
temple18.state="Odisha";
temple18.country="India";
temple18.deity="Sun God";
temple18.establishedYear=1250;
temple18.founder="King Narasimhadeva";
temple18.architectureStyle="Kalinga";
temple18.numberOfPriests=40;
temple18.dailyVisitors=10000;
temple18.prasadamAvailable=false;
temple18.parkingAvailable=true;
temple18.photographyAllowed=true;
temple18.accommodationAvailable=false;
temple18.onlineBooking=false;
temple18.specialPooja=false;
temple18.festivalCelebration=true;
temple18.donationFacility=true;
temple18.wheelchairAccess=true;
temple18.securitySystem=true;
temple18.famousFestival="Konark Festival";
temple18.openingTime="6:00 AM";
temple18.closingTime="6:00 PM";
temple18.templeType="Historic";

Temple temple19 = new Temple();

temple19.name="Chidambaram Temple";
temple19.location="Chidambaram";
temple19.city="Cuddalore";
temple19.state="Tamil Nadu";
temple19.country="India";
temple19.deity="Lord Nataraja";
temple19.establishedYear=900;
temple19.founder="Chola Kings";
temple19.architectureStyle="Dravidian";
temple19.numberOfPriests=70;
temple19.dailyVisitors=12000;
temple19.prasadamAvailable=true;
temple19.parkingAvailable=true;
temple19.photographyAllowed=false;
temple19.accommodationAvailable=true;
temple19.onlineBooking=false;
temple19.specialPooja=true;
temple19.festivalCelebration=true;
temple19.donationFacility=true;
temple19.wheelchairAccess=true;
temple19.securitySystem=true;
temple19.famousFestival="Natyanjali";
temple19.openingTime="6:00 AM";
temple19.closingTime="9:00 PM";
temple19.templeType="Hindu";



Temple temple20 = new Temple();

temple20.name="Lingaraj Temple";
temple20.location="Bhubaneswar";
temple20.city="Bhubaneswar";
temple20.state="Odisha";
temple20.country="India";
temple20.deity="Lord Shiva";
temple20.establishedYear=1100;
temple20.founder="Somavamsi Dynasty";
temple20.architectureStyle="Kalinga";
temple20.numberOfPriests=90;
temple20.dailyVisitors=18000;
temple20.prasadamAvailable=true;
temple20.parkingAvailable=true;
temple20.photographyAllowed=false;
temple20.accommodationAvailable=true;
temple20.onlineBooking=false;
temple20.specialPooja=true;
temple20.festivalCelebration=true;
temple20.donationFacility=true;
temple20.wheelchairAccess=true;
temple20.securitySystem=true;
temple20.famousFestival="Shivaratri";
temple20.openingTime="5:00 AM";
temple20.closingTime="9:30 PM";
temple20.templeType="Hindu";
*/


}
}