class UberEats {
    public static double search(String foodName) {
        if(foodName.equals("BBQChickenPizza")) return 320;
        else if(foodName.equals("VegSupremePizza")) return 280;
        else if(foodName.equals("ChickenLasagna")) return 260;
        else if(foodName.equals("VegLasagna")) return 240;
        else if(foodName.equals("SpaghettiBolognese")) return 300;
        else if(foodName.equals("SpaghettiAglioOlio")) return 220;
        else if(foodName.equals("GrilledChickenSteak")) return 350;
        else if(foodName.equals("VegSteak")) return 270;
        else if(foodName.equals("PeriPeriFries")) return 140;
        else if(foodName.equals("LoadedNachos")) return 180;
        else if(foodName.equals("ChickenQuesadilla")) return 210;
        else if(foodName.equals("VegQuesadilla")) return 190;
        else if(foodName.equals("MexicanRiceBowl")) return 230;
        else if(foodName.equals("TeriyakiChicken")) return 340;
        else if(foodName.equals("SushiPlatter")) return 400;
        else if(foodName.equals("TempuraPrawns")) return 380;
        else if(foodName.equals("RamenBowl")) return 260;
        else if(foodName.equals("PhoSoup")) return 240;
        else if(foodName.equals("KoreanFriedChicken")) return 360;
        else if(foodName.equals("Bibimbap")) return 280;
        else if(foodName.equals("GreekSalad")) return 200;
        else if(foodName.equals("CaesarSalad")) return 220;
        else if(foodName.equals("AvocadoToast")) return 180;
        else if(foodName.equals("Pancakes")) return 150;
        else if(foodName.equals("Waffles")) return 170;
        else if(foodName.equals("FrenchToast")) return 160;
        else if(foodName.equals("ClubSandwich")) return 210;
        else if(foodName.equals("BLTSandwich")) return 230;
        else if(foodName.equals("ChickenPopcorn")) return 190;
        else if(foodName.equals("VegCutlet")) return 90;
        else if(foodName.equals("MuttonRoganJosh")) return 370;
        else if(foodName.equals("ChickenKorma")) return 300;
        else if(foodName.equals("PaneerLababdar")) return 260;
        else if(foodName.equals("DalMakhani")) return 210;
        else if(foodName.equals("StuffedCapsicum")) return 200;
        else if(foodName.equals("CornCheeseBalls")) return 150;
        else if(foodName.equals("GarlicBread")) return 120;
        else if(foodName.equals("CheeseGarlicBread")) return 150;
        else if(foodName.equals("Tiramisu")) return 250;
        else if(foodName.equals("RedVelvetCake")) return 240;
        else if(foodName.equals("Cheesecake")) return 260;
        else if(foodName.equals("BananaSmoothie")) return 120;
        else if(foodName.equals("ProteinShake")) return 180;
        else if(foodName.equals("IcedTea")) return 100;
        else if(foodName.equals("VirginMojito")) return 130;
        else if(foodName.equals("MintLemonade")) return 110;
        else if(foodName.equals("HotChocolate")) return 140;
        else if(foodName.equals("CaramelLatte")) return 150;
        else if(foodName.equals("HazelnutCoffee")) return 160;
        else if(foodName.equals("StrawberryCheesecakeShake")) return 190;
        else if(foodName.equals("ChocoLavaCake")) return 170;
        else if(foodName.equals("ButterScotchIceCream")) return 100;
        else if(foodName.equals("KulfiFalooda")) return 130;
        else if(foodName.equals("KesarPistaMilk")) return 120;
        else if(foodName.equals("BadamMilk")) return 110;
        return 0;
    }
}
