class Zomato {
    public static double search(String foodName) {
        if(foodName.equals("MasalaDosa")) return 90;
        else if(foodName.equals("IdliSambar")) return 50;
        else if(foodName.equals("VadaSambar")) return 45;
        else if(foodName.equals("Pongal")) return 60;
        else if(foodName.equals("PooriBhaji")) return 70;
        else if(foodName.equals("Upma")) return 40;
        else if(foodName.equals("RavaDosa")) return 85;
        else if(foodName.equals("OnionUttapam")) return 95;
        else if(foodName.equals("TomatoRice")) return 80;
        else if(foodName.equals("LemonRice")) return 75;
        else if(foodName.equals("CurdRice")) return 65;
        else if(foodName.equals("Bisibelebath")) return 100;
        else if(foodName.equals("VegBiryani")) return 130;
        else if(foodName.equals("ChickenBiryani")) return 180;
        else if(foodName.equals("MuttonBiryani")) return 220;
        else if(foodName.equals("PaneerButterMasala")) return 160;
        else if(foodName.equals("ButterNaan")) return 40;
        else if(foodName.equals("GarlicNaan")) return 50;
        else if(foodName.equals("TandooriRoti")) return 30;
        else if(foodName.equals("PalakPaneer")) return 150;
        else if(foodName.equals("CholeBhature")) return 120;
        else if(foodName.equals("RajmaChawal")) return 110;
        else if(foodName.equals("DalTadka")) return 100;
        else if(foodName.equals("FriedRice")) return 120;
        else if(foodName.equals("GobiManchurian")) return 140;
        else if(foodName.equals("HakkaNoodles")) return 115;
        else if(foodName.equals("VegManchowSoup")) return 90;
        else if(foodName.equals("SpringRoll")) return 95;
        else if(foodName.equals("PavBhaji")) return 85;
        else if(foodName.equals("VadaPav")) return 25;
        else if(foodName.equals("Samosa")) return 20;
        else if(foodName.equals("Kachori")) return 25;
        else if(foodName.equals("AlooParatha")) return 70;
        else if(foodName.equals("PaneerParatha")) return 90;
        else if(foodName.equals("EggParatha")) return 80;
        else if(foodName.equals("ChickenRoll")) return 110;
        else if(foodName.equals("VegBurger")) return 90;
        else if(foodName.equals("ChickenBurger")) return 120;
        else if(foodName.equals("MargheritaPizza")) return 199;
        else if(foodName.equals("FarmhousePizza")) return 299;
        else if(foodName.equals("PepperoniPizza")) return 349;
        else if(foodName.equals("CheeseSandwich")) return 70;
        else if(foodName.equals("GrilledSandwich")) return 90;
        else if(foodName.equals("MysorePak")) return 60;
        else if(foodName.equals("GulabJamun")) return 50;
        else if(foodName.equals("Rasgulla")) return 45;
        else if(foodName.equals("Jalebi")) return 40;
        else if(foodName.equals("ChocolateCake")) return 120;
        else if(foodName.equals("BlackForestCake")) return 150;
        else if(foodName.equals("StrawberryMilkshake")) return 100;
        else if(foodName.equals("MangoMilkshake")) return 110;
        else if(foodName.equals("ColdCoffee")) return 90;
        else if(foodName.equals("Lassi")) return 60;
        else if(foodName.equals("Buttermilk")) return 30;
        else if(foodName.equals("TenderCoconut")) return 40;
        return 0;
    }
}
